I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('state_to_state_migrations_table_2009.xls')

In [3]:
df.shape

(78, 115)

In [4]:
df.columns

Index(['Dataset: 2007-2009 American Community Survey 3-Year Estimates',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109',
       'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..9',
       'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,Dataset: 2007-2009 American Community Survey 3-Year Estimates,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..9",Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,579815,18712.400933,982,787.647232,1183,831.978082,373,310.150125,4447,...,1899.65142,991,356.04029,215,215.308758,Alabama,1026,622.138043,258,248.900514

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Dataset: 2007-2009 American Community Survey 3-Year Estimates',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109',
       'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..9',
       'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

In [7]:
df.head(20)

,Dataset: 2007-2009 American Community Survey 3-Year Estimates,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..9",Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,579815,18712.400933,982,787.647232,1183,831.978082,373,310.150125,4447,...,1899.65142,991,356.04029,215,215.308758,Alabama,1026,622.138043,258,248.900514
9,Alaska,1390,1676.700576,107051,7517.989701,1285,551.937582,209,253.933605,3780,...,217.645374,3620,1512.597671,0,244,Alaska,1048,945.841456,470,811.649651
10,Arizona,392,343.453191,2249,1200.924924,1055904,32273.726078,1818,940.811008,46921,...,1412.181099,11148,2587.901091,781,725.532933,Arizona,3795,1486.736039,1260,861.211389
11,Arkansas,443,320.686833,968,1088.884387,1365,842.076046,416745,17032.841644,4837,...,171.485628,520,591.058824,29,56.614056,Arkansas,459,393.024032,115,139.515009
12,California,2889,1476.395427,5332,2553.474664,34040,5056.485826,3539,1668.206212,5238440,...,3449.049968,33408,4711.160156,835,627.759244,California,6958,2525.644363,1114,685.405294
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Colorado,1774,1152.918233,1215,707.613151,9378,2408.339749,2463,1157.0399,21223,...,2097.737901,4325,1492.397817,468,582.64091,Colorado,2982,1256.931464,5630,2795.754062
15,Connecticut,1963,2175.873686,504,496.091064,629,661.62945,14,21.589646,5041,...,1427.717666,1163,574.205152,0,277,Connecticut,74,99.368076,205,331.85913
16,Delaware,365,326.625924,143,225.493441,494,518.271211,0,263,575,...,2537.671341,14,22.307801,47,65.888359,Delaware,0,263,0,263
17,District of Columbia,203,167.538223,240,279.343814,32,54.042694,106,126.777643,2980,...,1517.567199,190,187.172883,207,296.950979,District of Columbia,344,307.378275,54,89.541507
18,Florida,9179,2237.912952,5863,2472.21916,6104,2396.81685,2211,1119.824673,22213,...,2809.996564,8343,2672.150476,4312,1982.433583,Florida,6214,1727.93626,423,391.079852
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Georgia,18302,3493.360882,2137,1324.37861,1747,734.821887,1720,1296.593445,16980,...,3521.358752,3134,1233.556533,710,542.602695,Georgia,962,559.203711,997,1297.646132
21,Hawaii,1163,1561.300169,1245,741.28809,1153,561.309821,281,338.55223,11820,...,1401.085959,4758,1457.410122,71,117.703745,Hawaii,65,104.40762,48,79.837597
22,Idaho,74,130.646041,710,433.54536,4727,1933.558569,586,684.388802,10088,...,708.140784,11906,2740.467013,0,263,Idaho,796,800.590083,1284,820.834726
23,Illinois,1959,1056.333263,572,363.384745,5238,1981.566208,2061,814.43234,12828,...,1616.972914,2659,1157.284449,724,483.481564,Illinois,12412,1985.190028,241,187.071654

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,Dataset: 2007-2009 American Community Survey 3-Year Estimates,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..9",Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
8,Alabama,579815,18712.400933,982,787.647232,1183,831.978082,373,310.150125,4447,...,1899.65142,991,356.04029,215,215.308758,Alabama,1026,622.138043,258,248.900514
9,Alaska,1390,1676.700576,107051,7517.989701,1285,551.937582,209,253.933605,3780,...,217.645374,3620,1512.597671,0,244,Alaska,1048,945.841456,470,811.649651
10,Arizona,392,343.453191,2249,1200.924924,1055904,32273.726078,1818,940.811008,46921,...,1412.181099,11148,2587.901091,781,725.532933,Arizona,3795,1486.736039,1260,861.211389
11,Arkansas,443,320.686833,968,1088.884387,1365,842.076046,416745,17032.841644,4837,...,171.485628,520,591.058824,29,56.614056,Arkansas,459,393.024032,115,139.515009
12,California,2889,1476.395427,5332,2553.474664,34040,5056.485826,3539,1668.206212,5238440,...,3449.049968,33408,4711.160156,835,627.759244,California,6958,2525.644363,1114,685.405294
14,Colorado,1774,1152.918233,1215,707.613151,9378,2408.339749,2463,1157.0399,21223,...,2097.737901,4325,1492.397817,468,582.64091,Colorado,2982,1256.931464,5630,2795.754062
15,Connecticut,1963,2175.873686,504,496.091064,629,661.62945,14,21.589646,5041,...,1427.717666,1163,574.205152,0,277,Connecticut,74,99.368076,205,331.85913
16,Delaware,365,326.625924,143,225.493441,494,518.271211,0,263,575,...,2537.671341,14,22.307801,47,65.888359,Delaware,0,263,0,263
17,District of Columbia,203,167.538223,240,279.343814,32,54.042694,106,126.777643,2980,...,1517.567199,190,187.172883,207,296.950979,District of Columbia,344,307.378275,54,89.541507
18,Florida,9179,2237.912952,5863,2472.21916,6104,2396.81685,2211,1119.824673,22213,...,2809.996564,8343,2672.150476,4312,1982.433583,Florida,6214,1727.93626,423,391.079852
20,Georgia,18302,3493.360882,2137,1324.37861,1747,734.821887,1720,1296.593445,16980,...,3521.358752,3134,1233.556533,710,542.602695,Georgia,962,559.203711,997,1297.646132
21,Hawaii,1163,1561.300169,1245,741.28809,1153,561.309821,281,338.55223,11820,...,1401.085959,4758,1457.410122,71,117.703745,Hawaii,65,104.40762,48,79.837597
22,Idaho,74,130.646041,710,433.54536,4727,1933.558569,586,684.388802,10088,...,708.140784,11906,2740.467013,0,263,Idaho,796,800.590083,1284,820.834726
23,Illinois,1959,1056.333263,572,363.384745,5238,1981.566208,2061,814.43234,12828,...,1616.972914,2659,1157.284449,724,483.481564,Illinois,12412,1985.190028,241,187.071654
24,Indiana,2729,1480.20972,201,248.231808,3790,1297.595144,873,649.618706,5806,...,929.206903,1010,730.024979,1100,903.394851,Indiana,2906,1100.766104,570,494.687905
26,Iowa,261,404.386372,440,401.010548,2142,1062.637087,590,434.163308,3510,...,404.056505,1836,975.494154,0,228,Iowa,3573,1116.609715,713,1128.372998
27,Kansas,1323,848.9499,947,971.383852,2689,1338.332866,1292,743.274915,6776,...,608.93103,568,297.176888,0,244,Kansas,237,212.28819,422,375.04539

Rename columns to be clearer, including manually renaming certain columns and stripping 'Unnamed: ' from the rest

In [9]:
print(df.columns.tolist())

['Dataset: 2007-2009 American Community Survey 3-Year Estimates', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..1', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..2', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..3', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..4', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..5', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..6', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..7', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..8', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..9', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114']

In [10]:
#for the first column

df.rename(columns={'Dataset: 2007-2009 American Community Survey 3-Year Estimates': '0'}, inplace=True)

#renaming all of these weird long composite names at the sart of every group of 11

df.rename(columns= {'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.': '11'}, inplace=True)
for i in range(1, 10):
    number = (i * 11) + 11
    df.rename(columns={f'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..{i}':f'{number}'}, inplace=True)

#for the rest of the columns, just trimming:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

print(df.columns.tolist())

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114']

In [11]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [12]:
df.iloc[3:] = df.iloc[3:].fillna('0')

In [13]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,104,105,106,107,108,109,111,112,113,114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,Virginia,NaN,Washington,NaN,West Virginia,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,579815,18712.400933,982,787.647232,1183,831.978082,373,310.150125,4447,...,5821,1899.65142,991,356.04029,215,215.308758,1026,622.138043,258,248.900514
9,Alaska,1390,1676.700576,107051,7517.989701,1285,551.937582,209,253.933605,3780,...,264,217.645374,3620,1512.597671,0,244,1048,945.841456,470,811.649651

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [14]:
#For the rest of the columns:
#first, fill in blanks

df_filledin = df.ffill(axis=1)

df_filledin.head()

,0,1,2,3,4,5,6,7,8,9,...,104,105,106,107,108,109,111,112,113,114
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,579815,18712.400933,982,787.647232,1183,831.978082,373,310.150125,4447,...,5821,1899.65142,991,356.04029,215,215.308758,1026,622.138043,258,248.900514
9,Alaska,1390,1676.700576,107051,7517.989701,1285,551.937582,209,253.933605,3780,...,264,217.645374,3620,1512.597671,0,244,1048,945.841456,470,811.649651

In [15]:
#then pull the info I need to name each column

for i in range(1, 105):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

In [16]:
df_filledin.head()

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,579815,18712.400933,982,787.647232,1183,831.978082,373,310.150125,4447,...,5821,1899.65142,991,356.04029,215,215.308758,1026,622.138043,258,248.900514
9,Alaska,1390,1676.700576,107051,7517.989701,1285,551.937582,209,253.933605,3780,...,264,217.645374,3620,1512.597671,0,244,1048,945.841456,470,811.649651

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [17]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
54,Ohio,2326,1197.333791,1311,792.732139,3845,1656.321289,930,763.412936,7763,...,7827,1948.829042,1620,1414.086961,5679,1533.907283,1157,837.835094,136,189.131724
55,Oklahoma,1313,950.086551,765,587.699935,4401,1594.693833,7671,2134.115027,9264,...,2351,1315.112943,1989,1315.040615,115,175.164695,393,297.803614,846,834.240711
56,Oregon,1178,551.221803,4826,2608.494011,4833,1771.711547,457,391.278906,32088,...,1115,806.605416,23557,3643.695497,901,1405.361635,769,799.215509,1392,829.272955
57,Pennsylvania,705,373.019302,1185,921.422562,2493,939.361043,798,739.18739,9955,...,11607,2195.852667,1491,730.726053,4074,1686.109112,2252,1215.401546,151,155.562998
58,Puerto Rico,0,289,0,289,774,915.9013,60,103.908805,668,...,697,818.441973,226,366.301093,0,289,68,110.703734,123,157.732684
60,Rhode Island,0,287,2076,1988.773127,446,336.304751,0,287,2045,...,2855,1699.37517,330,518.969474,0,287,44,73.079484,0,287
61,South Carolina,2447,1160.275011,241,182.433392,1378,588.08589,555,341.203495,5290,...,8035,2222.679448,1841,799.067195,617,514.427429,850,468.934942,527,828.06006
62,South Dakota,180,236.243421,15,25.981107,361,298.930041,56,89.390275,2390,...,299,348.696932,891,742.816594,0,223,674,517.611477,666,426.625604
63,Tennessee,9479,3376.727847,1101,1006.848653,3644,1665.155831,5854,2403.886123,7555,...,7904,1952.261161,2278,1362.180837,537,461.787716,1316,554.977997,452,440.478662
64,Texas,8538,2628.750173,9457,3475.579926,21263,4362.821803,10856,3027.100131,61270,...,17223,3831.380126,9996,1924.905169,906,567.747151,2915,1091.833356,1369,1039.251583
66,Utah,336,280.122055,783,451.213035,10309,3264.727545,92,149.084109,15623,...,1047,615.194482,5817,2335.809292,96,156.853575,656,404.232769,1297,618.601479
67,Vermont,64,113.204808,0,211,46,53.478947,46,76.587073,793,...,254,266.283279,167,155.830651,0,211,173,215.107889,240,417.371707
68,Virginia,2890,1110.452069,1983,1198.861283,5651,2695.174697,602,509.169221,17162,...,929239,24834.055464,4090,1726.232855,4710,1724.882946,1469,926.971512,1149,836.482338
69,Washington,1179,748.913147,3199,1210.109956,9507,3294.307574,708,680.867368,42693,...,3938,1489.7312,888519,25236.960213,917,828.809379,1518,723.123552,1517,854.45471
70,West Virginia,988,719.960988,1272,1029.921678,931,766.797036,321,514.429927,181,...,6307,1655.263421,37,61.385176,169720,11670.392492,42,61.08357,0,269
72,Wisconsin,574,505.026922,603,402.239334,2323,895.591089,365,266.984818,4361,...,1710,846.811585,1642,926.665602,195,288.466592,699209,19237.757929,222,257.278473
73,Wyoming,0,265,454,521.644518,759,474.231418,300,470.671124,1581,...,367,555.442965,1770,960.332769,0,265,286,441.463112,56319,5487.157153
74,Footnotes:,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75,*Incudes Puerto Rico and the District of Columbia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
76,MOE - Margin of error based on 90% confidence ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [18]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence interval
0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Alabama (Estimate),579815,1390,392,443,2889,1774,1963,365,203,9179,...,336,64,2890,1179,988,574,0,0,0,0
Residence 1 year ago in --: Alabama (MOE),18712.400933,1676.700576,343.453191,320.686833,1476.395427,1152.918233,2175.873686,326.625924,167.538223,2237.912952,...,280.122055,113.204808,1110.452069,748.913147,719.960988,505.026922,265,0,0,0
Residence 1 year ago in --: Alaska (Estimate),982,107051,2249,968,5332,1215,504,143,240,5863,...,783,0,1983,3199,1272,603,454,0,0,0
Residence 1 year ago in --: Alaska (MOE),787.647232,7517.989701,1200.924924,1088.884387,2553.474664,707.613151,496.091064,225.493441,279.343814,2472.21916,...,451.213035,211,1198.861283,1210.109956,1029.921678,402.239334,521.644518,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),215.308758,244,725.532933,56.614056,627.759244,582.64091,277,65.888359,296.950979,1982.433583,...,156.853575,211,1724.882946,828.809379,11670.392492,288.466592,265,0,0,0
Residence 1 year ago in --: Wisconsin (Estimate),1026,1048,3795,459,6958,2982,74,0,344,6214,...,656,173,1469,1518,42,699209,286,0,0,0
Residence 1 year ago in --: Wisconsin (MOE),622.138043,945.841456,1486.736039,393.024032,2525.644363,1256.931464,99.368076,263,307.378275,1727.93626,...,404.232769,215.107889,926.971512,723.123552,61.08357,19237.757929,441.463112,0,0,0
Residence 1 year ago in --: Wyoming (Estimate),258,470,1260,115,1114,5630,205,0,54,423,...,1297,240,1149,1517,0,222,56319,0,0,0
Residence 1 year ago in --: Wyoming (MOE),248.900514,811.649651,861.211389,139.515009,685.405294,2795.754062,331.85913,263,89.541507,391.079852,...,618.601479,417.371707,836.482338,854.45471,269,257.278473,5487.157153,0,0,0

In [19]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [20]:

df = df.iloc[1:]

In [21]:
df

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence interval
Residence 1 year ago in --: Alabama (Estimate),579815,1390,392,443,2889,1774,1963,365,203,9179,...,336,64,2890,1179,988,574,0,0,0,0
Residence 1 year ago in --: Alabama (MOE),18712.400933,1676.700576,343.453191,320.686833,1476.395427,1152.918233,2175.873686,326.625924,167.538223,2237.912952,...,280.122055,113.204808,1110.452069,748.913147,719.960988,505.026922,265,0,0,0
Residence 1 year ago in --: Alaska (Estimate),982,107051,2249,968,5332,1215,504,143,240,5863,...,783,0,1983,3199,1272,603,454,0,0,0
Residence 1 year ago in --: Alaska (MOE),787.647232,7517.989701,1200.924924,1088.884387,2553.474664,707.613151,496.091064,225.493441,279.343814,2472.21916,...,451.213035,211,1198.861283,1210.109956,1029.921678,402.239334,521.644518,0,0,0
Residence 1 year ago in --: Arizona (Estimate),1183,1285,1055904,1365,34040,9378,629,494,32,6104,...,10309,46,5651,9507,931,2323,759,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),215.308758,244,725.532933,56.614056,627.759244,582.64091,277,65.888359,296.950979,1982.433583,...,156.853575,211,1724.882946,828.809379,11670.392492,288.466592,265,0,0,0
Residence 1 year ago in --: Wisconsin (Estimate),1026,1048,3795,459,6958,2982,74,0,344,6214,...,656,173,1469,1518,42,699209,286,0,0,0
Residence 1 year ago in --: Wisconsin (MOE),622.138043,945.841456,1486.736039,393.024032,2525.644363,1256.931464,99.368076,263,307.378275,1727.93626,...,404.232769,215.107889,926.971512,723.123552,61.08357,19237.757929,441.463112,0,0,0
Residence 1 year ago in --: Wyoming (Estimate),258,470,1260,115,1114,5630,205,0,54,423,...,1297,240,1149,1517,0,222,56319,0,0,0
Residence 1 year ago in --: Wyoming (MOE),248.900514,811.649651,861.211389,139.515009,685.405294,2795.754062,331.85913,263,89.541507,391.079852,...,618.601479,417.371707,836.482338,854.45471,269,257.278473,5487.157153,0,0,0

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [22]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [23]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [24]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Residence 1 year ago in --: Alabama (Estimate)                       203
Residence 1 year ago in --: Alaska (Estimate)                        240
Residence 1 year ago in --: Arizona (Estimate)                        32
Residence 1 year ago in --: Arkansas (Estimate)                      106
Residence 1 year ago in --: California (Estimate)                   2980
Residence 1 year ago in --: Colorado (Estimate)                      505
Residence 1 year ago in --: Connecticut (Estimate)                   288
Residence 1 year ago in --: Delaware (Estimate)                      571
Residence 1 year ago in --: District of Columbi...                 47156
Residence 1 year ago in --: Florida (Estimate)                      2275
Residence 1 year ago in --: Georgia (Estimate)                       900
Residence 1 year ago in --: Hawaii (Estimate)                        145
Residence 1 year ago in --: Idaho (Estimate)                           0
Residence 1 year ago in --: Illinois (Estimate)                     1370
Residence 1 year ago in --: Indiana (Estimate)                         0
Residence 1 year ago in --: Iowa (Estimate)                           33
Residence 1 year ago in --: Kansas (Estimate)                         95
Residence 1 year ago in --: Kentucky (Estimate)                      114
Residence 1 year ago in --: Louisiana (Estimate)                       0
Residence 1 year ago in --: Maine (Estimate)                         390
Residence 1 year ago in --: Maryland (Estimate)                     9960
Residence 1 year ago in --: Massachusetts (Esti...                  1084
Residence 1 year ago in --: Michigan (Estimate)                      259
Residence 1 year ago in --: Minnesota (Estimate)                     194
Residence 1 year ago in --: Mississippi (Estimate)                     0
Residence 1 year ago in --: Missouri (Estimate)                      102
Residence 1 year ago in --: Montana (Estimate)                        66
Residence 1 year ago in --: Nebraska (Estimate)                       57
Residence 1 year ago in --: Nevada (Estimate)                        147
Residence 1 year ago in --: New Hampshire (Esti...                    72
Residence 1 year ago in --: New Jersey (Estimate)                   1232
Residence 1 year ago in --: New Mexico (Estimate)                      0
Residence 1 year ago in --: New York (Estimate)                     3647
Residence 1 year ago in --: North Carolina (Est...                  1276
Residence 1 year ago in --: North Dakota (Estim...                     0
Residence 1 year ago in --: Ohio (Estimate)                          373
Residence 1 year ago in --: Oklahoma (Estimate)                       57
Residence 1 year ago in --: Oregon (Estimate)                        285
Residence 1 year ago in --: Pennsylvania (Estim...                  1705
Residence 1 year ago in --: Puerto Rico (Estimate)                   147
Residence 1 year ago in --: Rhode Island (Estim...                    68
Residence 1 year ago in --: South Carolina (Est...                   345
Residence 1 year ago in --: South Dakota (Estim...                    58
Residence 1 year ago in --: Tennessee (Estimate)                      89
Residence 1 year ago in --: Texas (Estimate)                         819
Residence 1 year ago in --: Utah (Estimate)                           76
Residence 1 year ago in --: Vermont (Estimate)                       161
Residence 1 year ago in --: Virginia (Estimate)                     5586
Residence 1 year ago in --: Washington (Estimate)                    190
Residence 1 year ago in --: West Virginia (Esti...                   207
Residence 1 year ago in --: Wisconsin (Estimate)                     344
Residence 1 year ago in --: Wyoming (Estimate)                        54

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [25]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

For 2021 and 2017, we needed to cut off the top columns that arent for specific states, but that's not relevent here because of different structure for 2009 and 2005

In [26]:

# df_estimates = df_estimates[4:]
# df_moes = df_moes[4:]

In [27]:
df_moes.head()

0          District of Columbia
0
Alabama               167.538223
Alaska                279.343814
Arizona                54.042694
Arkansas              126.777643
California            909.759736

In [28]:
df_estimates.head()

0          District of Columbia
0
Alabama                      203
Alaska                       240
Arizona                       32
Arkansas                     106
California                  2980

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [29]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Now I'm adding a state polulation column to my newly formatted table

In [30]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [31]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [32]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [33]:
df

0                    pop_migrated      MOE +/- state_population
0
Alabama                       203   167.538223          5024279
Alaska                        240   279.343814           733391
Arizona                        32    54.042694          7151502
Arkansas                      106   126.777643          3011524
California                   2980   909.759736         39538223
Colorado                      505   508.123432          5773714
Connecticut                   288   283.733651          3605944
Delaware                      571   530.941684           989948
District of Columbia        47156  5403.420082           689545
Florida                      2275  1048.698338         21538187
Georgia                       900   542.662537         10711908
Hawaii                        145   169.997837          1455271
Idaho                           0          296          1839106
Illinois                     1370   515.900692         12812508
Indiana                         0          296          6785528
Iowa                           33    55.794365          3190369
Kansas                         95   114.222716          2937880
Kentucky                      114   192.053662          4505836
Louisiana                       0          296          4657757
Maine                         390    475.57445          1362359
Maryland                     9960  2471.428532          6177224
Massachusetts                1084     476.7802          7029917
Michigan                      259   268.477658         10077331
Minnesota                     194   177.058481          5706494
Mississippi                     0          296          2961279
Missouri                      102   114.679627          6154913
Montana                        66    89.439453          1084225
Nebraska                       57    94.296675          1961504
Nevada                        147   150.257041          3104614
New Hampshire                  72    99.348331          1377529
New Jersey                   1232   806.814143          9288994
New Mexico                      0          296          2117522
New York                     3647  1011.675134         20201249
North Carolina               1276   847.399521         10439388
North Dakota                    0          296           779094
Ohio                          373   288.891929         11799448
Oklahoma                       57    93.579393          3959353
Oregon                        285   252.775006          4237256
Pennsylvania                 1705   704.236393         13002700
Puerto Rico                   147   168.121897          3285874
Rhode Island                   68   112.193342          1097379
South Carolina                345   385.515147          5118425
South Dakota                   58     95.99389           886667
Tennessee                      89   142.806466          6910840
Texas                         819   571.018219         29145505
Utah                           76   125.954804          3271616
Vermont                       161   152.643237           643077
Virginia                     5586  1517.567199          8631393
Washington                    190   187.172883          7705281
West Virginia                 207   296.950979          1793716
Wisconsin                     344   307.378275          5893718
Wyoming                        54    89.541507           576851

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [34]:
df['state_pop_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [35]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Need to manually drop DC here because its input differently than in the other years -- here, the D.C. figure for folks that lived in D.C. both this year and last year is not n/a or 0, but rather a substantial number that represents the number of folks that did NOT move since last year's census

In [36]:
df = df.drop(['District of Columbia'])

Looking at states with most people coming to DC

In [37]:
df.sort_values(by='state_pop_adjusted', ascending=False).head(10)

0,pop_migrated,MOE +/-,state_population,state_pop_adjusted,moe_adjusted
0,,,,,
Maryland,9960,2471.428532,6177224,0.001612,0.000400
Virginia,5586,1517.567199,8631393,0.000647,0.000176
Delaware,571,530.941684,989948,0.000577,0.000536
Alaska,240,279.343814,733391,0.000327,0.000381
Maine,390,475.57445,1362359,0.000286,0.000349
Vermont,161,152.643237,643077,0.000250,0.000237
New York,3647,1011.675134,20201249,0.000181,0.000050
Massachusetts,1084,476.7802,7029917,0.000154,0.000068
New Jersey,1232,806.814143,9288994,0.000133,0.000087
Pennsylvania,1705,704.236393,13002700,0.000131,0.000054

To export, want to make a slice excluding all DMV states -- Maryland, Virginia

In [38]:
df_tochart = df.drop(['Maryland'])

df_tochart = df_tochart.drop(['Virginia'])

df_tochart

0,pop_migrated,MOE +/-,state_population,state_pop_adjusted,moe_adjusted
0,,,,,
Alabama,203,167.538223,5024279,0.000040,0.000033
Alaska,240,279.343814,733391,0.000327,0.000381
Arizona,32,54.042694,7151502,0.000004,0.000008
Arkansas,106,126.777643,3011524,0.000035,0.000042
California,2980,909.759736,39538223,0.000075,0.000023
Colorado,505,508.123432,5773714,0.000087,0.000088
Connecticut,288,283.733651,3605944,0.000080,0.000079
Delaware,571,530.941684,989948,0.000577,0.000536
Florida,2275,1048.698338,21538187,0.000106,0.000049
Georgia,900,542.662537,10711908,0.000084,0.000051
Hawaii,145,169.997837,1455271,0.000100,0.000117
Idaho,0,296,1839106,0.000000,0.000161
Illinois,1370,515.900692,12812508,0.000107,0.000040
Indiana,0,296,6785528,0.000000,0.000044
Iowa,33,55.794365,3190369,0.000010,0.000017
Kansas,95,114.222716,2937880,0.000032,0.000039
Kentucky,114,192.053662,4505836,0.000025,0.000043
Louisiana,0,296,4657757,0.000000,0.000064
Maine,390,475.57445,1362359,0.000286,0.000349
Massachusetts,1084,476.7802,7029917,0.000154,0.000068
Michigan,259,268.477658,10077331,0.000026,0.000027
Minnesota,194,177.058481,5706494,0.000034,0.000031
Mississippi,0,296,2961279,0.000000,0.000100
Missouri,102,114.679627,6154913,0.000017,0.000019
Montana,66,89.439453,1084225,0.000061,0.000082
Nebraska,57,94.296675,1961504,0.000029,0.000048
Nevada,147,150.257041,3104614,0.000047,0.000048
New Hampshire,72,99.348331,1377529,0.000052,0.000072
New Jersey,1232,806.814143,9288994,0.000133,0.000087
New Mexico,0,296,2117522,0.000000,0.000140
New York,3647,1011.675134,20201249,0.000181,0.000050
North Carolina,1276,847.399521,10439388,0.000122,0.000081
North Dakota,0,296,779094,0.000000,0.000380
Ohio,373,288.891929,11799448,0.000032,0.000024
Oklahoma,57,93.579393,3959353,0.000014,0.000024
Oregon,285,252.775006,4237256,0.000067,0.000060
Pennsylvania,1705,704.236393,13002700,0.000131,0.000054
Puerto Rico,147,168.121897,3285874,0.000045,0.000051
Rhode Island,68,112.193342,1097379,0.000062,0.000102
South Carolina,345,385.515147,5118425,0.000067,0.000075
South Dakota,58,95.99389,886667,0.000065,0.000108
Tennessee,89,142.806466,6910840,0.000013,0.000021
Texas,819,571.018219,29145505,0.000028,0.000020
Utah,76,125.954804,3271616,0.000023,0.000038
Vermont,161,152.643237,643077,0.000250,0.000237
Washington,190,187.172883,7705281,0.000025,0.000024
West Virginia,207,296.950979,1793716,0.000115,0.000166
Wisconsin,344,307.378275,5893718,0.000058,0.000052
Wyoming,54,89.541507,576851,0.000094,0.000155

Save as csv file

In [40]:
df_tochart.to_csv('DC-migration-2009.csv')