I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [ ]:
df = pd.read_excel('state_to_state_migrations_table_2009.xls')

In [3]:
df.shape

(84, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,312432820,28736,265461391,215531,37860849,181528,7207333,70975,97219,...,4294,United States1,1903247,36322,73846,9838,18416,3666,1810985,33055

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,312432820,28736,265461391,215531,37860849,181528,7207333,70975,97219,...,4294,United States1,1903247,36322,73846,9838,18416,3666,1810985,33055
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4781296,3371,4067683,20967,594583,19882,104102,7789,NaN,...,272,Alabama,14928,3443,312,330,156,163,14460,3423
11,Alaska,725193,1551,583799,9191,99953,8006,34360,4808,572,...,193,Alaska,7081,1794,184,202,25,39,6872,1748
12,Arizona,6543362,4567,5321158,29468,941347,27201,236146,10894,2140,...,909,Arizona,44711,4328,376,194,386,348,43949,4314
13,Arkansas,2923642,3216,2475807,16481,367837,13479,70621,8082,0,...,193,Arkansas,9377,2360,8,30,187,189,9182,2361
14,California,37873189,9076,32197933,60116,4898331,56784,485477,17797,2958,...,722,California,291448,14033,3179,2894,1646,1319,286623,13590
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5206012,3835,4186643,26465,778520,23616,206543,11855,2926,...,1254,Colorado,34306,4249,686,603,507,474,33113,4211
17,Connecticut,3562959,2829,3127421,14790,325895,12696,88351,6859,337,...,220,Connecticut,21292,3176,2761,1418,0,190,18531,2644
18,Delaware,914025,1666,791278,8053,81363,6755,36790,3896,0,...,193,Delaware,4594,1249,0,225,0,190,4594,1249
19,District of Columbia,636535,1515,509958,6417,68917,5785,46571,3601,316,...,9,District of Columbia,11089,2078,62,107,0,190,11027,2087
20,Florida,19345059,7799,16199361,50810,2442119,43961,529406,20819,10281,...,398,Florida,174173,11757,21245,7079,2688,1863,150240,9384
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,9870319,5843,8256209,33041,1279601,32070,278972,14820,18739,...,459,Georgia,55537,7076,3763,1815,820,647,50954,6558
23,Hawaii,1387361,1759,1177733,11169,135860,10399,58083,6288,593,...,193,Hawaii,15685,2833,327,418,905,556,14453,2825

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,312432820,28736,265461391,215531,37860849,181528,7207333,70975,97219,...,4294,United States1,1903247,36322,73846,9838,18416,3666,1810985,33055
10,Alabama,4781296,3371,4067683,20967,594583,19882,104102,7789,NaN,...,272,Alabama,14928,3443,312,330,156,163,14460,3423
11,Alaska,725193,1551,583799,9191,99953,8006,34360,4808,572,...,193,Alaska,7081,1794,184,202,25,39,6872,1748
12,Arizona,6543362,4567,5321158,29468,941347,27201,236146,10894,2140,...,909,Arizona,44711,4328,376,194,386,348,43949,4314
13,Arkansas,2923642,3216,2475807,16481,367837,13479,70621,8082,0,...,193,Arkansas,9377,2360,8,30,187,189,9182,2361
14,California,37873189,9076,32197933,60116,4898331,56784,485477,17797,2958,...,722,California,291448,14033,3179,2894,1646,1319,286623,13590
16,Colorado,5206012,3835,4186643,26465,778520,23616,206543,11855,2926,...,1254,Colorado,34306,4249,686,603,507,474,33113,4211
17,Connecticut,3562959,2829,3127421,14790,325895,12696,88351,6859,337,...,220,Connecticut,21292,3176,2761,1418,0,190,18531,2644
18,Delaware,914025,1666,791278,8053,81363,6755,36790,3896,0,...,193,Delaware,4594,1249,0,225,0,190,4594,1249
19,District of Columbia,636535,1515,509958,6417,68917,5785,46571,3601,316,...,9,District of Columbia,11089,2078,62,107,0,190,11027,2087
20,Florida,19345059,7799,16199361,50810,2442119,43961,529406,20819,10281,...,398,Florida,174173,11757,21245,7079,2688,1863,150240,9384
22,Georgia,9870319,5843,8256209,33041,1279601,32070,278972,14820,18739,...,459,Georgia,55537,7076,3763,1815,820,647,50954,6558
23,Hawaii,1387361,1759,1177733,11169,135860,10399,58083,6288,593,...,193,Hawaii,15685,2833,327,418,905,556,14453,2825
24,Idaho,1592596,2295,1317235,16033,205418,14233,61592,6754,72,...,838,Idaho,8351,1735,0,225,195,189,8156,1682
25,Illinois,12740816,5630,11036387,35854,1411859,33540,223605,12110,2044,...,269,Illinois,68965,5972,1005,635,538,522,67422,6071
26,Indiana,6492306,4236,5499346,22908,835689,22877,133508,10617,1235,...,22,Indiana,23763,2905,145,188,0,190,23618,2875
28,Iowa,3053635,2290,2585189,13974,380270,13622,75650,5854,180,...,503,Iowa,12526,2778,0,225,0,190,12526,2778

Rename columns to be clearer numbers

In [9]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '120', '121', '122', '123', '124', '125', '126', '127', '128', '129'],
      dtype='str', length=130)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [10]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

df

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,312432820,28736,265461391,215531,37860849,181528,7207333,70975,97219,...,28150,4294,1903247,36322,73846,9838,18416,3666,1810985,33055
10,Alabama,4781296,3371,4067683,20967,594583,19882,104102,7789,NaN,...,282,272,14928,3443,312,330,156,163,14460,3423
11,Alaska,725193,1551,583799,9191,99953,8006,34360,4808,572,...,0,193,7081,1794,184,202,25,39,6872,1748
12,Arizona,6543362,4567,5321158,29468,941347,27201,236146,10894,2140,...,1838,909,44711,4328,376,194,386,348,43949,4314
13,Arkansas,2923642,3216,2475807,16481,367837,13479,70621,8082,0,...,0,193,9377,2360,8,30,187,189,9182,2361
14,California,37873189,9076,32197933,60116,4898331,56784,485477,17797,2958,...,1030,722,291448,14033,3179,2894,1646,1319,286623,13590
16,Colorado,5206012,3835,4186643,26465,778520,23616,206543,11855,2926,...,4307,1254,34306,4249,686,603,507,474,33113,4211
17,Connecticut,3562959,2829,3127421,14790,325895,12696,88351,6859,337,...,132,220,21292,3176,2761,1418,0,190,18531,2644
18,Delaware,914025,1666,791278,8053,81363,6755,36790,3896,0,...,0,193,4594,1249,0,225,0,190,4594,1249
19,District of Columbia,636535,1515,509958,6417,68917,5785,46571,3601,316,...,3,9,11089,2078,62,107,0,190,11027,2087
20,Florida,19345059,7799,16199361,50810,2442119,43961,529406,20819,10281,...,341,398,174173,11757,21245,7079,2688,1863,150240,9384
22,Georgia,9870319,5843,8256209,33041,1279601,32070,278972,14820,18739,...,562,459,55537,7076,3763,1815,820,647,50954,6558
23,Hawaii,1387361,1759,1177733,11169,135860,10399,58083,6288,593,...,0,193,15685,2833,327,418,905,556,14453,2825
24,Idaho,1592596,2295,1317235,16033,205418,14233,61592,6754,72,...,1508,838,8351,1735,0,225,195,189,8156,1682
25,Illinois,12740816,5630,11036387,35854,1411859,33540,223605,12110,2044,...,202,269,68965,5972,1005,635,538,522,67422,6071
26,Indiana,6492306,4236,5499346,22908,835689,22877,133508,10617,1235,...,13,22,23763,2905,145,188,0,190,23618,2875
28,Iowa,3053635,2290,2585189,13974,380270,13622,75650,5854,180,...,423,503,12526,2778,0,225,0,190,12526,2778
29,Kansas,2854869,2630,2386028,13627,363906,13865,89735,7639,1074,...,181,300,15200,2576,401,500,31,53,14768,2454
30,Kentucky,4345186,3568,3665604,20740,558412,20510,103207,7831,1418,...,231,387,17963,2935,887,840,0,190,17076,2639
31,Louisiana,4568320,3499,3941211,19715,519010,19311,91889,7792,2683,...,0,193,16210,2847,785,516,0,190,15425,2808
32,Maine,1315753,1637,1128262,10088,146334,7289,36780,5886,13,...,70,119,4377,1354,120,199,109,123,4148,1354
34,Maryland,5857213,3983,5078020,22291,572131,19949,161525,8927,1918,...,313,284,45537,5911,1057,771,1328,1687,43152,5655
35,Massachusetts,6619999,3581,5724592,21615,700613,19699,135150,7947,409,...,92,116,59644,5947,2005,873,319,273,57320,5762
36,Michigan,9784094,4423,8296283,28574,1294706,27760,144091,9108,2517,...,154,174,49014,5406,891,891,300,220,47823,5370
37,Minnesota,5353441,3604,4585137,18773,636274,16853,104825,7533,493,...,213,195,27205,3508,922,1011,60,100,26223,3362
38,Mississippi,2957797,3020,2531410,17190,350982,17037,68588,7223,7077,...,0,193,6817,1697,79,119,114,153,6624,1718
40,Missouri,5973448,3901,5015609,20692,779132,19774,159936,8247,1004,...,59,100,18771,2528,262,406,483,359,18026,2483
41,Montana,1003013,1606,827494,8870,130187,8740,40035,4850,21,...,987,475,5297,1529,0,225,96,184,5201,1523
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
45,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1842900,1874,1546788,11720,241707,10381,45854,4131,294,...,496,291,8551,2187,418,674,0,190,8133,2139
48,Nevada,2757365,2854,2166730,21632,447480,18504,126583,10558,491,...,887,651,16572,2988,740,1232,680,451,15152,2621
49,New Hampshire,1310978,1470,1128583,9242,131200,8765,44867,3945,123,...,0,193,6328,1628,209,289,148,277,5971,1681
50,New Jersey,8803679,4536,7941559,23812,667248,20440,136907,7795,853,...,0,193,57965,5844,4072,1719,59,69,53834,5785
51,New Mexico,2059689,2429,1764969,11546,224508,10230,56808,5205,63,...,273,357,13404,2734,0,225,68,102,13336,2718
53,New York,19431954,5997,17297785,33907,1715158,32741,272066,11081,1648,...,309,332,146945,8788,4536,1114,313,277,142096,8647
54,North Carolina,9737365,5593,8233641,32920,1176351,28011,275922,11861,3268,...,35,56,51451,5768,1526,959,1073,709,48852,5497
55,North Dakota,714804,1226,593677,6918,78944,6064,38908,4434,0,...,857,750,3275,1041,0,225,120,205,3155,1014
56,Ohio,11439593,5197,9748676,32878,1458505,30005,185749,11791,1318,...,151,149,46663,5344,3130,1778,353,298,43180,4828
57,Oklahoma,3801521,2431,3131192,15909,545546,16100,109255,7388,1024,...,561,396,15528,2852,509,437,547,474,14472,2761
59,Oregon,3888216,3139,3154813,21706,571472,19031,143841,11050,704,...,1022,792,18090,2679,94,147,206,205,17790,2663
60,Pennsylvania,12639493,5012,11113742,26981,1240573,25055,224280,10969,720,...,515,681,60898,5797,8640,3713,422,325,51836,4857
61,Rhode Island,1040986,1700,905093,9118,94129,7465,34108,3955,279,...,0,193,7656,1818,345,268,0,190,7311,1824
62,South Carolina,4720602,3292,4000306,23018,537062,21454,166047,11725,1715,...,86,142,17187,3089,844,397,479,748,15864,2916
63,South Dakota,832703,1252,691659,7143,108713,6320,30042,3368,84,...,981,580,2289,740,0,225,0,190,2289,740
65,Tennessee,6419226,4130,5429144,23649,779329,22585,186525,10529,8500,...,126,193,24228,3633,405,350,223,361,23600,3648
66,Texas,26087349,7700,21658382,58836,3695565,53762,548034,19346,8404,...,4640,2083,185368,11019,3656,1365,1782,1037,179930,11077
67,Utah,2854667,2542,2361079,14278,377528,12802,97869,8768,574,...,3700,1700,18191,2341,424,416,0,190,17767,2286
68,Vermont,621256,831,542002,5677,53684,4844,23180,2623,27,...,68,79,2390,740,0,225,0,190,2390,740
69,Virginia,8163664,5516,6874626,28924,962359,28924,266348,12779,4894,...,59,87,60331,5456,1792,1102,530,325,58009,5255
71,Washington,6888552,4605,5700703,29511,927367,25300,208215,12437,686,...,400,325,52267,5312,16,32,366,498,51885,5270
72,West Virginia,1837863,1643,1621269,9601,161679,7576,51957,4368,196,...,0,193,2958,858,257,365,16,35,2685,795
73,Wisconsin,5681024,3027,4872672,19472,688588,20478,100846,7050,294,...,43,39,18918,3020,678,638,138,172,18102,2917
74,Wyoming,575933,1244,469511,7193,76905,6557,27584,3195,40,...,NaN,NaN,1933,779,93,163,0,190,1840,744
76,Puerto Rico,3579220,2941,3329074,12018,221047,10899,24652,3657,293,...,0,193,4447,1092,N/A2,N/A2,0,190,4447,1092

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [11]:
df.iloc[3:] = df.iloc[3:].fillna('0')

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#first, dealing with columns B-G/1-6)

column_1_name = f'{df.iloc[0, 1]} ({df.iloc[2, 1]})'
column_2_name = f'{df.iloc[0, 1]} ({df.iloc[2, 2]})'

column_3_name = f'{df.iloc[0, 3]} ({df.iloc[2, 3]})'
column_4_name = f'{df.iloc[0, 3]} ({df.iloc[2, 4]})'

column_5_name = f'{df.iloc[0, 5]} ({df.iloc[2, 5]})'
column_6_name = f'{df.iloc[0, 5]} ({df.iloc[2, 6]})'

df_clean = df.rename(columns ={
    '1': column_1_name,
    '2': column_2_name,
    '3': column_3_name,
    '4': column_4_name,
    '5': column_5_name,
    '6': column_6_name})

#next, for the rest of the columns:
#first, fill in blanks

df_filledin = df_clean.ffill(axis=1)

#then pull the info I need to name each column

for i in range(7, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [13]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Population 1 year and over (Estimate),Population 1 year and over (MOE),Same house 1 year ago (Estimate),Same house 1 year ago (MOE),Same state of residence 1 year ago (Estimate),Same state of residence 1 year ago (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (Estimate),Different state of residence 1 year ago (cont.): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
53,New York,19431954,5997,17297785,33907,1715158,32741,272066,11081,1648,...,309,332,146945,8788,4536,1114,313,277,142096,8647
54,North Carolina,9737365,5593,8233641,32920,1176351,28011,275922,11861,3268,...,35,56,51451,5768,1526,959,1073,709,48852,5497
55,North Dakota,714804,1226,593677,6918,78944,6064,38908,4434,0,...,857,750,3275,1041,0,225,120,205,3155,1014
56,Ohio,11439593,5197,9748676,32878,1458505,30005,185749,11791,1318,...,151,149,46663,5344,3130,1778,353,298,43180,4828
57,Oklahoma,3801521,2431,3131192,15909,545546,16100,109255,7388,1024,...,561,396,15528,2852,509,437,547,474,14472,2761
59,Oregon,3888216,3139,3154813,21706,571472,19031,143841,11050,704,...,1022,792,18090,2679,94,147,206,205,17790,2663
60,Pennsylvania,12639493,5012,11113742,26981,1240573,25055,224280,10969,720,...,515,681,60898,5797,8640,3713,422,325,51836,4857
61,Rhode Island,1040986,1700,905093,9118,94129,7465,34108,3955,279,...,0,193,7656,1818,345,268,0,190,7311,1824
62,South Carolina,4720602,3292,4000306,23018,537062,21454,166047,11725,1715,...,86,142,17187,3089,844,397,479,748,15864,2916
63,South Dakota,832703,1252,691659,7143,108713,6320,30042,3368,84,...,981,580,2289,740,0,225,0,190,2289,740
65,Tennessee,6419226,4130,5429144,23649,779329,22585,186525,10529,8500,...,126,193,24228,3633,405,350,223,361,23600,3648
66,Texas,26087349,7700,21658382,58836,3695565,53762,548034,19346,8404,...,4640,2083,185368,11019,3656,1365,1782,1037,179930,11077
67,Utah,2854667,2542,2361079,14278,377528,12802,97869,8768,574,...,3700,1700,18191,2341,424,416,0,190,17767,2286
68,Vermont,621256,831,542002,5677,53684,4844,23180,2623,27,...,68,79,2390,740,0,225,0,190,2390,740
69,Virginia,8163664,5516,6874626,28924,962359,28924,266348,12779,4894,...,59,87,60331,5456,1792,1102,530,325,58009,5255
71,Washington,6888552,4605,5700703,29511,927367,25300,208215,12437,686,...,400,325,52267,5312,16,32,366,498,51885,5270
72,West Virginia,1837863,1643,1621269,9601,161679,7576,51957,4368,196,...,0,193,2958,858,257,365,16,35,2685,795
73,Wisconsin,5681024,3027,4872672,19472,688588,20478,100846,7050,294,...,43,39,18918,3020,678,638,138,172,18102,2917
74,Wyoming,575933,1244,469511,7193,76905,6557,27584,3195,40,...,0,0,1933,779,93,163,0,190,1840,744
76,Puerto Rico,3579220,2941,3329074,12018,221047,10899,24652,3657,293,...,0,193,4447,1092,N/A2,N/A2,0,190,4447,1092


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [14]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,United States1,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,United States1,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),312432820,4781296,725193,6543362,2923642,37873189,5206012,3562959,914025,636535,...,6419226,26087349,2854667,621256,8163664,6888552,1837863,5681024,575933,3579220
Population 1 year and over (MOE),28736,3371,1551,4567,3216,9076,3835,2829,1666,1515,...,4130,7700,2542,831,5516,4605,1643,3027,1244,2941
Same house 1 year ago (Estimate),265461391,4067683,583799,5321158,2475807,32197933,4186643,3127421,791278,509958,...,5429144,21658382,2361079,542002,6874626,5700703,1621269,4872672,469511,3329074
Same house 1 year ago (MOE),215531,20967,9191,29468,16481,60116,26465,14790,8053,6417,...,23649,58836,14278,5677,28924,29511,9601,19472,7193,12018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),9838,330,202,194,30,2894,603,1418,225,107,...,350,1365,416,225,1102,32,365,638,163,N/A2
Abroad 1 year ago--: U.S. Island Area (Estimate),18416,156,25,386,187,1646,507,0,0,0,...,223,1782,0,0,530,366,16,138,0,0
Abroad 1 year ago--: U.S. Island Area (MOE),3666,163,39,348,189,1319,474,190,190,190,...,361,1037,190,190,325,498,35,172,190,190
Abroad 1 year ago--: Foreign Country (Estimate),1810985,14460,6872,43949,9182,286623,33113,18531,4594,11027,...,23600,179930,17767,2390,58009,51885,2685,18102,1840,4447
Abroad 1 year ago--: Foreign Country (MOE),33055,3423,1748,4314,2361,13590,4211,2644,1249,2087,...,3648,11077,2286,740,5255,5270,795,2917,744,1092

In [15]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [16]:

df = df.iloc[1:]

In [17]:
df

0,United States1,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),312432820,4781296,725193,6543362,2923642,37873189,5206012,3562959,914025,636535,...,6419226,26087349,2854667,621256,8163664,6888552,1837863,5681024,575933,3579220
Population 1 year and over (MOE),28736,3371,1551,4567,3216,9076,3835,2829,1666,1515,...,4130,7700,2542,831,5516,4605,1643,3027,1244,2941
Same house 1 year ago (Estimate),265461391,4067683,583799,5321158,2475807,32197933,4186643,3127421,791278,509958,...,5429144,21658382,2361079,542002,6874626,5700703,1621269,4872672,469511,3329074
Same house 1 year ago (MOE),215531,20967,9191,29468,16481,60116,26465,14790,8053,6417,...,23649,58836,14278,5677,28924,29511,9601,19472,7193,12018
Same state of residence 1 year ago (Estimate),37860849,594583,99953,941347,367837,4898331,778520,325895,81363,68917,...,779329,3695565,377528,53684,962359,927367,161679,688588,76905,221047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),9838,330,202,194,30,2894,603,1418,225,107,...,350,1365,416,225,1102,32,365,638,163,N/A2
Abroad 1 year ago--: U.S. Island Area (Estimate),18416,156,25,386,187,1646,507,0,0,0,...,223,1782,0,0,530,366,16,138,0,0
Abroad 1 year ago--: U.S. Island Area (MOE),3666,163,39,348,189,1319,474,190,190,190,...,361,1037,190,190,325,498,35,172,190,190
Abroad 1 year ago--: Foreign Country (Estimate),1810985,14460,6872,43949,9182,286623,33113,18531,4594,11027,...,23600,179930,17767,2390,58009,51885,2685,18102,1840,4447
Abroad 1 year ago--: Foreign Country (MOE),33055,3423,1748,4314,2361,13590,4211,2644,1249,2087,...,3648,11077,2286,740,5255,5270,795,2917,744,1092

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [18]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [19]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [20]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Population 1 year and over (Estimate)                             636535
Same house 1 year ago (Estimate)                                  509958
Same state of residence 1 year ago (Estimate)                      68917
Different state of residence 1 year ago: Total ...                 46571
Different state of residence 1 year ago: Alabam...                   316
Different state of residence 1 year ago (cont.)...                   579
Different state of residence 1 year ago (cont.)...                    79
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                  2427
Different state of residence 1 year ago (cont.)...                   337
Different state of residence 1 year ago (cont.)...                  1597
Different state of residence 1 year ago (cont.)...                   336
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                  1307
Different state of residence 1 year ago (cont.)...                  1497
Different state of residence 1 year ago (cont.)...                   339
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   753
Different state of residence 1 year ago (cont.)...                   215
Different state of residence 1 year ago (cont.)...                    27
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                    46
Different state of residence 1 year ago (cont.)...                   858
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                  9237
Different state of residence 1 year ago (cont.)...                  1557
Different state of residence 1 year ago (cont.)...                   622
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   278
Different state of residence 1 year ago (cont.)...                    44
Different state of residence 1 year ago (cont.)...                    22
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   108
Different state of residence 1 year ago (cont.)...                  2173
Different state of residence 1 year ago (cont.)...                   411
Different state of residence 1 year ago (cont.)...                  4770
Different state of residence 1 year ago (cont.)...                  1253
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   315
Different state of residence 1 year ago (cont.)...                   155
Different state of residence 1 year ago (cont.)...                   194
Different state of residence 1 year ago (cont.)...                  2177
Different state of residence 1 year ago (cont.)...                  1150
Different state of residence 1 year ago (cont.)...                   506
Different state of residence 1 year ago (cont.)...                   203
Different state of residence 1 year ago (cont.)...                   560
Different state of residence 1 year ago (cont.)...                  1625
Different state of residence 1 year ago (cont.)...                   126
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                  7814
Different state of residence 1 year ago (cont.)...                   159
Different state of residence 1 year ago (cont.)...                   391
Different state of residence 1 year ago (cont.)...                     5
Different state of residence 1 year ago (cont.)...                     3
Abroad 1 year ago--: Total (Estimate)                              11089
Abroad 1 year ago--: Puerto Rico (Estimate)                           62
Abroad 1 year ago--: U.S. Island Area (Estimate)                       0
Abroad 1 year ago--: Foreign Country (Estimate)                    11027

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [21]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

Cut off the top columns that arent for specific states

In [22]:

df_estimates = df_estimates[4:]
df_moes = df_moes[4:]

In [23]:
df_moes.head()

0          District of Columbia
0
Alabama                      217
Alaska                       658
Arizona                      130
Arkansas                     192
California                   847

In [24]:
df_estimates.head()

0          District of Columbia
0
Alabama                      316
Alaska                       579
Arizona                       79
Arkansas                       0
California                  2427

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [25]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Also need to cut out one "total" column that is the total amount of "Abroad One Year Ago" incl PR, US Island Area, and Foreign Country

In [26]:
df = df.drop('Total')

df

0                    District of Columbia  MOE +/-
0
Alabama                                316     217
Alaska                                 579     658
Arizona                                 79     130
Arkansas                                 0     192
California                            2427     847
Colorado                               337     242
Connecticut                           1597     631
Delaware                               336     254
District of Columbia                     0       0
Florida                               1307     640
Georgia                               1497     599
Hawaii                                 339     526
Idaho                                    0     193
Illinois                               753     398
Indiana                                215     199
Iowa                                    27      46
Kansas                                   0     170
Kentucky                                46      71
Louisiana                              858     475
Maine                                    0     165
Maryland                              9237    1988
Massachusetts                         1557     616
Michigan                               622     325
Minnesota                                0     145
Mississippi                              0     208
Missouri                               278     219
Montana                                 44      75
Nebraska                                22      38
Nevada                                   0     206
New Hampshire                          108     139
New Jersey                            2173     949
New Mexico                             411     481
New York                              4770    1660
North Carolina                        1253     452
North Dakota                             0     149
Ohio                                   315     262
Oklahoma                               155     193
Oregon                                 194     259
Pennsylvania                          2177     791
Rhode Island                          1150     864
South Carolina                         506     316
South Dakota                           203     246
Tennessee                              560     408
Texas                                 1625     716
Utah                                   126     158
Vermont                                  0     151
Virginia                              7814    1263
Washington                             159     152
West Virginia                          391     245
Wisconsin                                5      12
Wyoming                                  3       9
Puerto Rico                             62     107
U.S. Island Area                         0     190
Foreign Country                      11027    2087

also need to drop out the last two columns US Island Area and Foreign Country because those dont exist in the pop df and I don't need for this analysis

In [27]:
df = df.drop('U.S. Island Area')
df = df.drop('Foreign Country')

also need to drop the top row of pops df to get the dataframes to have the same row indices

In [28]:
df_pops = df_pops.drop('Label (Grouping)')

Now I'm adding a state polulation column to my newly formatted table

In [29]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [30]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [31]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [32]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       316     217          5024279
Alaska                        579     658           733391
Arizona                        79     130          7151502
Arkansas                        0     192          3011524
California                   2427     847         39538223
Colorado                      337     242          5773714
Connecticut                  1597     631          3605944
Delaware                      336     254           989948
District of Columbia            0       0           689545
Florida                      1307     640         21538187
Georgia                      1497     599         10711908
Hawaii                        339     526          1455271
Idaho                           0     193          1839106
Illinois                      753     398         12812508
Indiana                       215     199          6785528
Iowa                           27      46          3190369
Kansas                          0     170          2937880
Kentucky                       46      71          4505836
Louisiana                     858     475          4657757
Maine                           0     165          1362359
Maryland                     9237    1988          6177224
Massachusetts                1557     616          7029917
Michigan                      622     325         10077331
Minnesota                       0     145          5706494
Mississippi                     0     208          2961279
Missouri                      278     219          6154913
Montana                        44      75          1084225
Nebraska                       22      38          1961504
Nevada                          0     206          3104614
New Hampshire                 108     139          1377529
New Jersey                   2173     949          9288994
New Mexico                    411     481          2117522
New York                     4770    1660         20201249
North Carolina               1253     452         10439388
North Dakota                    0     149           779094
Ohio                          315     262         11799448
Oklahoma                      155     193          3959353
Oregon                        194     259          4237256
Pennsylvania                 2177     791         13002700
Rhode Island                 1150     864          1097379
South Carolina                506     316          5118425
South Dakota                  203     246           886667
Tennessee                     560     408          6910840
Texas                        1625     716         29145505
Utah                          126     158          3271616
Vermont                         0     151           643077
Virginia                     7814    1263          8631393
Washington                    159     152          7705281
West Virginia                 391     245          1793716
Wisconsin                       5      12          5893718
Wyoming                         3       9           576851
Puerto Rico                    62     107          3285874

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [33]:
df['state_pop_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Starting a new dataframe that I can build on for comparing across years

In [34]:
df_tochart = df['state_pop_adjusted'].sort_values(ascending=False)

df_tochart.head(10)

0
Maryland        0.001495
Rhode Island    0.001048
Virginia        0.000905
Alaska          0.000789
Connecticut     0.000443
Delaware        0.000339
New York        0.000236
New Jersey      0.000234
Hawaii          0.000233
South Dakota    0.000229
Name: state_pop_adjusted, dtype: float64

Also want to make a slice excluding all DMV states -- Maryland, Virginia

In [35]:
df_withoutdmv = df_tochart.drop(['Maryland'])

df_withoutdmv = df_withoutdmv.drop(['Virginia'])

df_withoutdmv

0
Rhode Island            1.047952e-03
Alaska                  7.894834e-04
Connecticut             4.428799e-04
Delaware                3.394118e-04
New York                2.361240e-04
New Jersey              2.339328e-04
Hawaii                  2.329463e-04
South Dakota            2.289473e-04
Massachusetts           2.214820e-04
West Virginia           2.179832e-04
New Mexico              1.940948e-04
Louisiana               1.842088e-04
Pennsylvania            1.674268e-04
Georgia                 1.397510e-04
North Carolina          1.200262e-04
South Carolina          9.885854e-05
Tennessee               8.103212e-05
New Hampshire           7.840125e-05
Alabama                 6.289460e-05
Michigan                6.172269e-05
California              6.138364e-05
Florida                 6.068292e-05
Illinois                5.877070e-05
Colorado                5.836798e-05
Texas                   5.575474e-05
Oregon                  4.578435e-05
Missouri                4.516717e-05
Montana                 4.058198e-05
Oklahoma                3.914781e-05
Utah                    3.851308e-05
Indiana                 3.168508e-05
Ohio                    2.669616e-05
Washington              2.063520e-05
Puerto Rico             1.886865e-05
Nebraska                1.121588e-05
Arizona                 1.104663e-05
Kentucky                1.020898e-05
Iowa                    8.462971e-06
Wyoming                 5.200650e-06
Wisconsin               8.483609e-07
North Dakota            0.000000e+00
Maine                   0.000000e+00
Kansas                  0.000000e+00
Idaho                   0.000000e+00
District of Columbia    0.000000e+00
Minnesota               0.000000e+00
Vermont                 0.000000e+00
Arkansas                0.000000e+00
Mississippi             0.000000e+00
Nevada                  0.000000e+00
Name: state_pop_adjusted, dtype: float64