I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2005.xls')

In [3]:
df.shape

(77, 115)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112',
       'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,580353,22382,608,432,574,542,3168,1655,3025,...,1142,1324,817,432,467,Alabama,303,230,436,507

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112',
       'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,580353,22382,608,432,574,542,3168,1655,3025,...,1142,1324,817,432,467,Alabama,303,230,436,507
9,Alaska,152,176,84150,6528,883,530,54,83,3898,...,537,5711,2516,0,233,Alaska,765,465,222,353
10,Arizona,1427,784,1836,1443,917186,26917,1845,948,94296,...,2459,10335,2314,527,468,Arizona,7798,2272,1458,811
11,Arkansas,1894,1228,660,504,1266,617,390364,17198,6167,...,997,1062,1260,59,77,Arkansas,1542,1232,41,71
12,California,4375,3603,5274,1769,28156,4098,2481,1232,4904586,...,3684,29727,5382,329,280,California,3958,1599,1425,1003
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Colorado,1495,1016,2392,1240,7018,1957,1218,795,25350,...,1481,3650,1515,539,743,Colorado,3498,1160,5690,2494
15,Connecticut,520,502,310,320,49,82,0,274,3979,...,766,634,502,140,179,Connecticut,50,85,0,274
16,Delaware,546,921,337,381,216,254,344,563,933,...,588,0,274,254,326,Delaware,0,274,0,274
17,District of Columbia,0,286,0,286,490,573,0,286,2348,...,1586,443,354,389,376,District of Columbia,49,82,0,286
18,Florida,10559,2597,2932,1390,5962,2466,3300,1985,29152,...,4434,5337,2529,3771,1782,Florida,9295,3054,873,685
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Georgia,22111,5035,2570,1265,3395,1828,1178,797,20673,...,2603,7117,5307,881,606,Georgia,3597,1840,0,297
21,Hawaii,1464,1370,125,156,1409,1144,207,266,15261,...,1065,2074,985,0,264,Hawaii,168,214,113,141
22,Idaho,185,212,1650,970,2259,943,0,256,15663,...,308,10696,2449,0,256,Idaho,366,409,1177,1103
23,Illinois,1551,788,2879,2320,5050,1456,2549,1624,18821,...,1276,2007,936,1405,1341,Illinois,11072,2278,78,130

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
8,Alabama,580353,22382,608,432,574,542,3168,1655,3025,...,1142,1324,817,432,467,Alabama,303,230,436,507
9,Alaska,152,176,84150,6528,883,530,54,83,3898,...,537,5711,2516,0,233,Alaska,765,465,222,353
10,Arizona,1427,784,1836,1443,917186,26917,1845,948,94296,...,2459,10335,2314,527,468,Arizona,7798,2272,1458,811
11,Arkansas,1894,1228,660,504,1266,617,390364,17198,6167,...,997,1062,1260,59,77,Arkansas,1542,1232,41,71
12,California,4375,3603,5274,1769,28156,4098,2481,1232,4904586,...,3684,29727,5382,329,280,California,3958,1599,1425,1003
14,Colorado,1495,1016,2392,1240,7018,1957,1218,795,25350,...,1481,3650,1515,539,743,Colorado,3498,1160,5690,2494
15,Connecticut,520,502,310,320,49,82,0,274,3979,...,766,634,502,140,179,Connecticut,50,85,0,274
16,Delaware,546,921,337,381,216,254,344,563,933,...,588,0,274,254,326,Delaware,0,274,0,274
17,District of Columbia,0,286,0,286,490,573,0,286,2348,...,1586,443,354,389,376,District of Columbia,49,82,0,286
18,Florida,10559,2597,2932,1390,5962,2466,3300,1985,29152,...,4434,5337,2529,3771,1782,Florida,9295,3054,873,685
20,Georgia,22111,5035,2570,1265,3395,1828,1178,797,20673,...,2603,7117,5307,881,606,Georgia,3597,1840,0,297
21,Hawaii,1464,1370,125,156,1409,1144,207,266,15261,...,1065,2074,985,0,264,Hawaii,168,214,113,141
22,Idaho,185,212,1650,970,2259,943,0,256,15663,...,308,10696,2449,0,256,Idaho,366,409,1177,1103
23,Illinois,1551,788,2879,2320,5050,1456,2549,1624,18821,...,1276,2007,936,1405,1341,Illinois,11072,2278,78,130
24,Indiana,664,505,240,277,2393,927,226,234,7181,...,2083,1040,801,528,357,Indiana,3350,1660,139,211
26,Iowa,343,402,201,237,2010,850,812,589,4962,...,405,1480,1064,196,330,Iowa,4081,1453,879,542
27,Kansas,1048,915,0,240,2101,990,1404,1008,6823,...,511,754,519,222,298,Kansas,459,440,1009,723

Rename columns to be clearer, including manually renaming certain columns and stripping 'Unnamed: ' from the rest

In [9]:
print(df.columns.tolist())

['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114']

In [10]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.': '0'}, inplace=True)

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

print(df.columns.tolist())

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114']

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [11]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#For the rest of the columns:
#first, fill in blanks

df_filledin = df.ffill(axis=1)

df_filledin.head()

,0,1,2,3,4,5,6,7,8,9,...,104,105,106,107,108,109,111,112,113,114
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,580353,22382,608,432,574,542,3168,1655,3025,...,2572,1142,1324,817,432,467,303,230,436,507
9,Alaska,152,176,84150,6528,883,530,54,83,3898,...,618,537,5711,2516,0,233,765,465,222,353

In [13]:
#then pull the info I need to name each column

for i in range(1, 105):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

In [14]:
df_filledin.head()

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,580353,22382,608,432,574,542,3168,1655,3025,...,2572,1142,1324,817,432,467,303,230,436,507
9,Alaska,152,176,84150,6528,883,530,54,83,3898,...,618,537,5711,2516,0,233,765,465,222,353

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [15]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
54,Ohio,2469,1533,212,160,3310,1058,639,445,11049,...,5088,2322,2059,1213,8291,2179,2250,1428,311,314
55,Oklahoma,877,652,360,311,2945,1160,6745,2329,8520,...,1751,969,1557,849,0,247,135,158,2114,1163
56,Oregon,1223,1136,2137,1000,5775,1790,1422,1287,56379,...,2269,1891,23320,4570,50,65,903,633,228,285
57,Pennsylvania,950,567,934,480,2957,1416,735,525,11802,...,11232,2720,1250,680,4083,1685,545,361,218,245
58,Puerto Rico,88,100,0,280,85,149,0,280,1296,...,353,281,0,280,0,280,161,270,0,280
60,Rhode Island,88,147,87,146,438,507,0,284,1856,...,1224,982,306,337,89,146,0,284,98,160
61,South Carolina,2254,1256,203,202,1279,868,199,188,3554,...,6522,2600,2314,1549,326,269,497,377,287,356
62,South Dakota,0,219,303,372,612,380,0,219,1055,...,61,85,918,1011,202,315,440,379,964,919
63,Tennessee,8546,2232,595,553,874,529,5197,2099,12254,...,7697,1944,1978,1121,1603,683,2681,1597,453,436
64,Texas,7042,2767,3656,1868,12180,3015,9653,2551,74777,...,11987,3968,10823,3399,684,571,5054,1984,1600,765
66,Utah,0,258,500,420,6222,2057,77,127,17879,...,788,436,3773,1550,362,381,764,1237,746,526
67,Vermont,0,211,15,25,92,151,0,211,290,...,409,365,215,232,98,115,0,211,19,35
68,Virginia,2150,917,1911,1066,2251,976,387,286,16065,...,865315,23781,4554,1739,7597,2235,1131,656,193,292
69,Washington,184,165,7156,2267,12125,3711,681,554,47720,...,3655,1247,953030,27327,398,452,2176,1105,442,394
70,West Virginia,347,399,1164,1367,399,359,56,99,369,...,5535,1795,0,266,159425,9930,276,405,57,99
72,Wisconsin,2275,2656,136,137,2197,942,992,762,6743,...,1576,958,2390,1532,242,278,672491,19133,536,560
73,Wyoming,268,274,146,210,1229,1144,178,295,3353,...,445,514,781,561,49,83,35,66,61851,6023
74,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,...,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:
75,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...
76,"Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...",...,"Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm...","Source: U.S. Census Bureau, 2005 American Comm..."


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [16]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,MOE - Margin of error based on 90% confidence interval,"Source: U.S. Census Bureau, 2005 American Community Survey"
0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Alabama (Estimate),580353,152,1427,1894,4375,1495,520,546,0,10559,...,0,0,2150,184,347,2275,268,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Alabama (MOE),22382,176,784,1228,3603,1016,502,921,286,2597,...,258,211,917,165,399,2656,274,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Alaska (Estimate),608,84150,1836,660,5274,2392,310,337,0,2932,...,500,15,1911,7156,1164,136,146,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Alaska (MOE),432,6528,1443,504,1769,1240,320,381,286,1390,...,420,25,1066,2267,1367,137,210,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),467,233,468,77,280,743,179,326,376,1782,...,381,115,2235,452,9930,278,83,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Wisconsin (Estimate),303,765,7798,1542,3958,3498,50,0,49,9295,...,764,0,1131,2176,276,672491,35,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Wisconsin (MOE),230,465,2272,1232,1599,1160,85,274,82,3054,...,1237,211,656,1105,405,19133,66,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Wyoming (Estimate),436,222,1458,41,1425,5690,0,0,0,873,...,746,19,193,442,57,536,61851,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Wyoming (MOE),507,353,811,71,1003,2494,274,274,286,685,...,526,35,292,394,99,560,6023,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."

In [17]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [18]:

df = df.iloc[1:]

In [19]:
df

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,MOE - Margin of error based on 90% confidence interval,"Source: U.S. Census Bureau, 2005 American Community Survey"
Residence 1 year ago in --: Alabama (Estimate),580353,152,1427,1894,4375,1495,520,546,0,10559,...,0,0,2150,184,347,2275,268,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Alabama (MOE),22382,176,784,1228,3603,1016,502,921,286,2597,...,258,211,917,165,399,2656,274,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Alaska (Estimate),608,84150,1836,660,5274,2392,310,337,0,2932,...,500,15,1911,7156,1164,136,146,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Alaska (MOE),432,6528,1443,504,1769,1240,320,381,286,1390,...,420,25,1066,2267,1367,137,210,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Arizona (Estimate),574,883,917186,1266,28156,7018,49,216,490,5962,...,6222,92,2251,12125,399,2197,1229,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),467,233,468,77,280,743,179,326,376,1782,...,381,115,2235,452,9930,278,83,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Wisconsin (Estimate),303,765,7798,1542,3958,3498,50,0,49,9295,...,764,0,1131,2176,276,672491,35,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Wisconsin (MOE),230,465,2272,1232,1599,1160,85,274,82,3054,...,1237,211,656,1105,405,19133,66,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Wyoming (Estimate),436,222,1458,41,1425,5690,0,0,0,873,...,746,19,193,442,57,536,61851,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."
Residence 1 year ago in --: Wyoming (MOE),507,353,811,71,1003,2494,274,274,286,685,...,526,35,292,394,99,560,6023,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2005 American Comm..."

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [20]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [21]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [22]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Residence 1 year ago in --: Alabama (Estimate)                         0
Residence 1 year ago in --: Alaska (Estimate)                          0
Residence 1 year ago in --: Arizona (Estimate)                       490
Residence 1 year ago in --: Arkansas (Estimate)                        0
Residence 1 year ago in --: California (Estimate)                   2348
Residence 1 year ago in --: Colorado (Estimate)                      269
Residence 1 year ago in --: Connecticut (Estimate)                   261
Residence 1 year ago in --: Delaware (Estimate)                      357
Residence 1 year ago in --: District of Columbi...                 50118
Residence 1 year ago in --: Florida (Estimate)                      1103
Residence 1 year ago in --: Georgia (Estimate)                       319
Residence 1 year ago in --: Hawaii (Estimate)                         56
Residence 1 year ago in --: Idaho (Estimate)                           0
Residence 1 year ago in --: Illinois (Estimate)                     1519
Residence 1 year ago in --: Indiana (Estimate)                       192
Residence 1 year ago in --: Iowa (Estimate)                            0
Residence 1 year ago in --: Kansas (Estimate)                          0
Residence 1 year ago in --: Kentucky (Estimate)                       32
Residence 1 year ago in --: Louisiana (Estimate)                     271
Residence 1 year ago in --: Maine (Estimate)                         174
Residence 1 year ago in --: Maryland (Estimate)                    10087
Residence 1 year ago in --: Massachusetts (Esti...                  2579
Residence 1 year ago in --: Michigan (Estimate)                      122
Residence 1 year ago in --: Minnesota (Estimate)                     363
Residence 1 year ago in --: Mississippi (Estimate)                     0
Residence 1 year ago in --: Missouri (Estimate)                       68
Residence 1 year ago in --: Montana (Estimate)                         0
Residence 1 year ago in --: Nebraska (Estimate)                      186
Residence 1 year ago in --: Nevada (Estimate)                          0
Residence 1 year ago in --: New Hampshire (Esti...                    66
Residence 1 year ago in --: New Jersey (Estimate)                    954
Residence 1 year ago in --: New Mexico (Estimate)                    212
Residence 1 year ago in --: New York (Estimate)                     2801
Residence 1 year ago in --: North Carolina (Est...                  2156
Residence 1 year ago in --: North Dakota (Estim...                     0
Residence 1 year ago in --: Ohio (Estimate)                          216
Residence 1 year ago in --: Oklahoma (Estimate)                      127
Residence 1 year ago in --: Oregon (Estimate)                        176
Residence 1 year ago in --: Pennsylvania (Estim...                   898
Residence 1 year ago in --: Puerto Rico (Estimate)                   179
Residence 1 year ago in --: Rhode Island (Estim...                    55
Residence 1 year ago in --: South Carolina (Est...                   397
Residence 1 year ago in --: South Dakota (Estim...                     0
Residence 1 year ago in --: Tennessee (Estimate)                     367
Residence 1 year ago in --: Texas (Estimate)                         730
Residence 1 year ago in --: Utah (Estimate)                          796
Residence 1 year ago in --: Vermont (Estimate)                        27
Residence 1 year ago in --: Virginia (Estimate)                     5654
Residence 1 year ago in --: Washington (Estimate)                    443
Residence 1 year ago in --: West Virginia (Esti...                   389
Residence 1 year ago in --: Wisconsin (Estimate)                      49
Residence 1 year ago in --: Wyoming (Estimate)                         0

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [23]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

For 2021 and 2017, we needed to cut off the top columns that arent for specific states, but that's not relevent here because of different structure for 2009 and 2005

In [24]:

# df_estimates = df_estimates[4:]
# df_moes = df_moes[4:]

In [25]:
df_moes.head()

0          District of Columbia
0
Alabama                      286
Alaska                       286
Arizona                      573
Arkansas                     286
California                  1010

In [26]:
df_estimates.head()

0          District of Columbia
0
Alabama                        0
Alaska                         0
Arizona                      490
Arkansas                       0
California                  2348

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [27]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Now I'm adding a state polulation column to my newly formatted table

In [28]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [29]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [30]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [31]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                         0     286          5024279
Alaska                          0     286           733391
Arizona                       490     573          7151502
Arkansas                        0     286          3011524
California                   2348    1010         39538223
Colorado                      269     250          5773714
Connecticut                   261     209          3605944
Delaware                      357     346           989948
District of Columbia        50118    5594           689545
Florida                      1103     461         21538187
Georgia                       319     209         10711908
Hawaii                         56      92          1455271
Idaho                           0     286          1839106
Illinois                     1519     812         12812508
Indiana                       192     141          6785528
Iowa                            0     286          3190369
Kansas                          0     286          2937880
Kentucky                       32      55          4505836
Louisiana                     271     330          4657757
Maine                         174     206          1362359
Maryland                    10087    3063          6177224
Massachusetts                2579    1021          7029917
Michigan                      122     123         10077331
Minnesota                     363     257          5706494
Mississippi                     0     286          2961279
Missouri                       68     113          6154913
Montana                         0     286          1084225
Nebraska                      186     191          1961504
Nevada                          0     286          3104614
New Hampshire                  66     112          1377529
New Jersey                    954     551          9288994
New Mexico                    212     248          2117522
New York                     2801    1081         20201249
North Carolina               2156    1278         10439388
North Dakota                    0     286           779094
Ohio                          216     204         11799448
Oklahoma                      127     152          3959353
Oregon                        176     174          4237256
Pennsylvania                  898     517         13002700
Puerto Rico                   179     232          3285874
Rhode Island                   55      92          1097379
South Carolina                397     442          5118425
South Dakota                    0     286           886667
Tennessee                     367     388          6910840
Texas                         730     503         29145505
Utah                          796    1029          3271616
Vermont                        27      46           643077
Virginia                     5654    1586          8631393
Washington                    443     354          7705281
West Virginia                 389     376          1793716
Wisconsin                      49      82          5893718
Wyoming                         0     286           576851

Adding columns representing the top and bottom of the margins of error

In [36]:
df['pop_migrated_upper'] = pd.to_numeric(df['pop_migrated']) + pd.to_numeric(df['MOE +/-']) 

df['pop_migrated_lower'] = pd.to_numeric(df['pop_migrated']) - pd.to_numeric(df['MOE +/-']) 

df

0,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower
0,,,,,
Alabama,0,286,5024279,286,-286
Alaska,0,286,733391,286,-286
Arizona,490,573,7151502,1063,-83
Arkansas,0,286,3011524,286,-286
California,2348,1010,39538223,3358,1338
Colorado,269,250,5773714,519,19
Connecticut,261,209,3605944,470,52
Delaware,357,346,989948,703,11
District of Columbia,50118,5594,689545,55712,44524
Florida,1103,461,21538187,1564,642
Georgia,319,209,10711908,528,110
Hawaii,56,92,1455271,148,-36
Idaho,0,286,1839106,286,-286
Illinois,1519,812,12812508,2331,707
Indiana,192,141,6785528,333,51
Iowa,0,286,3190369,286,-286
Kansas,0,286,2937880,286,-286
Kentucky,32,55,4505836,87,-23
Louisiana,271,330,4657757,601,-59
Maine,174,206,1362359,380,-32
Maryland,10087,3063,6177224,13150,7024
Massachusetts,2579,1021,7029917,3600,1558
Michigan,122,123,10077331,245,-1
Minnesota,363,257,5706494,620,106
Mississippi,0,286,2961279,286,-286
Missouri,68,113,6154913,181,-45
Montana,0,286,1084225,286,-286
Nebraska,186,191,1961504,377,-5
Nevada,0,286,3104614,286,-286
New Hampshire,66,112,1377529,178,-46
New Jersey,954,551,9288994,1505,403
New Mexico,212,248,2117522,460,-36
New York,2801,1081,20201249,3882,1720
North Carolina,2156,1278,10439388,3434,878
North Dakota,0,286,779094,286,-286
Ohio,216,204,11799448,420,12
Oklahoma,127,152,3959353,279,-25
Oregon,176,174,4237256,350,2
Pennsylvania,898,517,13002700,1415,381
Puerto Rico,179,232,3285874,411,-53
Rhode Island,55,92,1097379,147,-37
South Carolina,397,442,5118425,839,-45
South Dakota,0,286,886667,286,-286
Tennessee,367,388,6910840,755,-21
Texas,730,503,29145505,1233,227
Utah,796,1029,3271616,1825,-233
Vermont,27,46,643077,73,-19
Virginia,5654,1586,8631393,7240,4068
Washington,443,354,7705281,797,89
West Virginia,389,376,1793716,765,13
Wisconsin,49,82,5893718,131,-33
Wyoming,0,286,576851,286,-286

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [37]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

df['migrated_adjusted_upper'] = (
    pd.to_numeric(df['pop_migrated_upper'])
    / pd.to_numeric(df['state_population'])

)

df['migrated_adjusted_lower'] = (
    pd.to_numeric(df['pop_migrated_lower'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [38]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Need to manually drop DC here because its input differently than in the other years -- here, the D.C. figure for folks that lived in D.C. both this year and last year is not n/a or 0, but rather a substantial number that represents the number of folks that did NOT move since last year's census

In [39]:
df = df.drop(['District of Columbia'])

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [40]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)

df.head()

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted
0,Alabama,0,286,5024279,286,-286,0.000000,0.000057,-0.000057,0.000057
1,Alaska,0,286,733391,286,-286,0.000000,0.000390,-0.000390,0.000390
2,Arizona,490,573,7151502,1063,-83,0.000069,0.000149,-0.000012,0.000080
3,Arkansas,0,286,3011524,286,-286,0.000000,0.000095,-0.000095,0.000095
4,California,2348,1010,39538223,3358,1338,0.000059,0.000085,0.000034,0.000026

Looking at states with most people coming to DC

In [41]:

df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted
19,Maryland,10087,3063,6177224,13150,7024,0.001633,0.002129,0.001137,0.000496
46,Virginia,5654,1586,8631393,7240,4068,0.000655,0.000839,0.000471,0.000184
20,Massachusetts,2579,1021,7029917,3600,1558,0.000367,0.000512,0.000222,0.000145
7,Delaware,357,346,989948,703,11,0.000361,0.000710,0.000011,0.000350
44,Utah,796,1029,3271616,1825,-233,0.000243,0.000558,-0.000071,0.000315
48,West Virginia,389,376,1793716,765,13,0.000217,0.000426,0.000007,0.000210
32,North Carolina,2156,1278,10439388,3434,878,0.000207,0.000329,0.000084,0.000122
31,New York,2801,1081,20201249,3882,1720,0.000139,0.000192,0.000085,0.000054
18,Maine,174,206,1362359,380,-32,0.000128,0.000279,-0.000023,0.000151
12,Illinois,1519,812,12812508,2331,707,0.000119,0.000182,0.000055,0.000063

To export, want to make a slice excluding all DMV states -- Maryland, Virginia

In [42]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]

Now need to reset the index again to make numbers consecutive now that I've removed ceratin rows.

In [43]:
df = df.reset_index(drop=True)

Now add in 2004 election winners for each state

First, read in file

In [44]:
df_2004_election_winners = pd.read_csv('pres-election-results-2004.csv')

df_2004_election_winners.shape

(48, 5)

Next, add winning party and percent of votes columns

In [45]:
df_2004_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

Reset index to match the other df

In [46]:
df_2004_election_winners = df_2004_election_winners.reset_index(drop=True)

In [47]:
df_2004_election_winners.head()

df_2004_election_winners.index

RangeIndex(start=0, stop=48, step=1)

In [48]:

df['winning_party'] = df_2004_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2004_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,0,286,5024279,286,-286,0.000000,0.000057,-0.000057,0.000057,REPUBLICAN,0.624607
1,Alaska,0,286,733391,286,-286,0.000000,0.000390,-0.000390,0.000390,REPUBLICAN,0.610653
2,Arizona,490,573,7151502,1063,-83,0.000069,0.000149,-0.000012,0.000080,REPUBLICAN,0.548694
3,Arkansas,0,286,3011524,286,-286,0.000000,0.000095,-0.000095,0.000095,REPUBLICAN,0.543060
4,California,2348,1010,39538223,3358,1338,0.000059,0.000085,0.000034,0.000026,DEMOCRAT,0.543056

Save as csv file

In [49]:
df.to_csv('DC-migration-2005.csv')