I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('State_to_State_Migrations_Table_2021.xls')

In [3]:
df.shape

(86, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.tail(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
57,Oklahoma,3943443,2733,3347420,19615,475441,17079,108288,7791,914,...,27,Oklahoma,12294,2508,705,766,46,77,11543,2532
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Oregon,4207387,3683,3600937,18211,458434,18455,133935,9142,487,...,731,Oregon,14081,2915,33,55,582,456,13466,2932
60,Pennsylvania,12842522,5067,11452320,31938,1078336,27367,261831,13241,585,...,290,Pennsylvania,50035,7559,6249,2423,232,220,43554,6723
61,Rhode Island,1085539,1975,959140,9449,77691,8236,43266,4692,0,...,232,Rhode Island,5442,1407,275,270,44,61,5123,1366
62,South Carolina,5142137,4196,4444195,25549,484535,19587,196200,11924,1472,...,226,South Carolina,17207,3327,648,491,1321,1275,15238,3087
63,South Dakota,884616,1584,759943,7867,95407,7171,27528,3650,30,...,1041,South Dakota,1738,643,255,320,0,170,1483,590
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Tennessee,6899165,4617,5955858,27272,701333,22674,220591,14903,9869,...,588,Tennessee,21383,4515,899,654,382,442,20102,4599
66,Texas,29170380,12760,25086829,71104,3315313,62222,591395,26127,9389,...,2403,Texas,176843,15137,4180,1912,1618,1339,171045,15106
67,Utah,3295561,3308,2817208,17954,359628,15733,101051,8401,436,...,1035,Utah,17674,3338,63,92,1325,1371,16286,2959
68,Vermont,641007,929,564684,5468,42454,4180,31809,3854,94,...,69,Vermont,2060,719,45,78,0,165,2015,724
69,Virginia,8557020,4817,7384723,29614,855269,26354,272693,12741,1878,...,320,Virginia,44335,6304,2912,1593,279,273,41144,5997
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Washington,7657350,4731,6474967,29847,909338,26736,225306,12843,1064,...,2952,Washington,47739,6640,1205,1340,1932,910,44602,6132
72,West Virginia,1767792,1989,1584041,12269,137757,9831,43801,6531,506,...,216,West Virginia,2193,1049,0,216,0,216,2193,1049
73,Wisconsin,5838954,3227,5123397,18301,578787,17247,122742,7724,331,...,181,Wisconsin,14028,2331,533,440,66,110,13429,2325
74,Wyoming,573476,1211,481018,7250,63128,6111,27281,4320,0,...,NaN,Wyoming,2049,1147,0,208,0,208,2049,1147
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Puerto Rico,3248011,2728,3040178,12763,177594,12122,27380,3989,47,...,240,Puerto Rico,2859,1312,NaN,NaN,0,254,2859,1312

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,328464538,34090,286552923,190336,32577121,167671,7859837,75123,104481,...,6515,United States2,1474657,34636,54669,7470,19587,4066,1400401,33711
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4989797,4341,4392571,25089,468964,23356,115641,10300,NaN,...,216,Alabama,12621,2388,534,436,29,47,12058,2400
11,Alaska,723949,1517,625088,8315,63611,6501,31378,3888,517,...,114,Alaska,3872,1532,205,202,0,184,3667,1527
12,Arizona,7202745,5156,6144045,29885,759450,24263,264948,14419,1485,...,1242,Arizona,34302,5615,857,764,57,96,33388,5544
13,Arkansas,2990311,2937,2595527,18138,312848,15129,76108,8024,950,...,783,Arkansas,5828,1634,0,213,0,213,5828,1634
14,California,38833197,12214,34461724,53862,3749371,49440,433402,16802,2710,...,704,California,188700,12292,968,597,1921,860,185811,12087
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5757628,4091,4794481,26077,686892,20293,250031,17084,2192,...,1986,Colorado,26224,4163,491,430,291,297,25442,4129
17,Connecticut,3571470,3191,3168509,15301,279328,13726,106618,8523,0,...,217,Connecticut,17015,3252,1664,1063,165,192,15186,3170
18,Delaware,994669,1764,889174,6362,58180,5692,42551,4342,0,...,210,Delaware,4764,1768,319,372,0,210,4445,1723
19,District of Columbia,661026,1835,527167,8611,68606,7109,57746,5874,342,...,93,District of Columbia,7507,1477,568,434,0,236,6939,1433
20,Florida,21590684,8058,18571567,47265,2206566,41666,674740,25002,15159,...,958,Florida,137811,11410,13795,4714,2274,1557,121742,9765
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,10688429,6334,9243299,38980,1107180,34938,302512,17711,22228,...,34,Georgia,35438,5067,1805,708,742,579,32891,4832
23,Hawaii,1426298,2455,1230761,11560,110790,9317,71626,8474,2192,...,200,Hawaii,13121,3194,0,200,1626,1486,11495,2781

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,328464538,34090,286552923,190336,32577121,167671,7859837,75123,104481,...,6515,United States2,1474657,34636,54669,7470,19587,4066,1400401,33711
10,Alabama,4989797,4341,4392571,25089,468964,23356,115641,10300,NaN,...,216,Alabama,12621,2388,534,436,29,47,12058,2400
11,Alaska,723949,1517,625088,8315,63611,6501,31378,3888,517,...,114,Alaska,3872,1532,205,202,0,184,3667,1527
12,Arizona,7202745,5156,6144045,29885,759450,24263,264948,14419,1485,...,1242,Arizona,34302,5615,857,764,57,96,33388,5544
13,Arkansas,2990311,2937,2595527,18138,312848,15129,76108,8024,950,...,783,Arkansas,5828,1634,0,213,0,213,5828,1634
14,California,38833197,12214,34461724,53862,3749371,49440,433402,16802,2710,...,704,California,188700,12292,968,597,1921,860,185811,12087
16,Colorado,5757628,4091,4794481,26077,686892,20293,250031,17084,2192,...,1986,Colorado,26224,4163,491,430,291,297,25442,4129
17,Connecticut,3571470,3191,3168509,15301,279328,13726,106618,8523,0,...,217,Connecticut,17015,3252,1664,1063,165,192,15186,3170
18,Delaware,994669,1764,889174,6362,58180,5692,42551,4342,0,...,210,Delaware,4764,1768,319,372,0,210,4445,1723
19,District of Columbia,661026,1835,527167,8611,68606,7109,57746,5874,342,...,93,District of Columbia,7507,1477,568,434,0,236,6939,1433
20,Florida,21590684,8058,18571567,47265,2206566,41666,674740,25002,15159,...,958,Florida,137811,11410,13795,4714,2274,1557,121742,9765
22,Georgia,10688429,6334,9243299,38980,1107180,34938,302512,17711,22228,...,34,Georgia,35438,5067,1805,708,742,579,32891,4832
23,Hawaii,1426298,2455,1230761,11560,110790,9317,71626,8474,2192,...,200,Hawaii,13121,3194,0,200,1626,1486,11495,2781
24,Idaho,1879719,2400,1601568,15804,176458,11576,96388,9806,350,...,1117,Idaho,5305,1504,115,183,140,185,5050,1478
25,Illinois,12544435,5532,11095785,30825,1200753,28559,195177,9929,614,...,863,Illinois,52720,6604,879,724,233,380,51608,6671
26,Indiana,6729771,4323,5835956,27793,714384,23581,156417,11930,1906,...,865,Indiana,23014,4886,1372,1768,0,208,21642,4590
28,Iowa,3159672,2419,2725417,14379,347372,13477,77245,6177,478,...,10,Iowa,9638,2625,615,876,345,275,8678,2296

Rename columns to be clearer numbers

In [9]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '120', '121', '122', '123', '124', '125', '126', '127', '128', '129'],
      dtype='str', length=130)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [10]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

df

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,328464538,34090,286552923,190336,32577121,167671,7859837,75123,104481,...,35164,6515,1474657,34636,54669,7470,19587,4066,1400401,33711
10,Alabama,4989797,4341,4392571,25089,468964,23356,115641,10300,NaN,...,0,216,12621,2388,534,436,29,47,12058,2400
11,Alaska,723949,1517,625088,8315,63611,6501,31378,3888,517,...,89,114,3872,1532,205,202,0,184,3667,1527
12,Arizona,7202745,5156,6144045,29885,759450,24263,264948,14419,1485,...,1580,1242,34302,5615,857,764,57,96,33388,5544
13,Arkansas,2990311,2937,2595527,18138,312848,15129,76108,8024,950,...,643,783,5828,1634,0,213,0,213,5828,1634
14,California,38833197,12214,34461724,53862,3749371,49440,433402,16802,2710,...,1338,704,188700,12292,968,597,1921,860,185811,12087
16,Colorado,5757628,4091,4794481,26077,686892,20293,250031,17084,2192,...,3413,1986,26224,4163,491,430,291,297,25442,4129
17,Connecticut,3571470,3191,3168509,15301,279328,13726,106618,8523,0,...,0,217,17015,3252,1664,1063,165,192,15186,3170
18,Delaware,994669,1764,889174,6362,58180,5692,42551,4342,0,...,0,210,4764,1768,319,372,0,210,4445,1723
19,District of Columbia,661026,1835,527167,8611,68606,7109,57746,5874,342,...,56,93,7507,1477,568,434,0,236,6939,1433
20,Florida,21590684,8058,18571567,47265,2206566,41666,674740,25002,15159,...,1758,958,137811,11410,13795,4714,2274,1557,121742,9765
22,Georgia,10688429,6334,9243299,38980,1107180,34938,302512,17711,22228,...,20,34,35438,5067,1805,708,742,579,32891,4832
23,Hawaii,1426298,2455,1230761,11560,110790,9317,71626,8474,2192,...,0,200,13121,3194,0,200,1626,1486,11495,2781
24,Idaho,1879719,2400,1601568,15804,176458,11576,96388,9806,350,...,1516,1117,5305,1504,115,183,140,185,5050,1478
25,Illinois,12544435,5532,11095785,30825,1200753,28559,195177,9929,614,...,639,863,52720,6604,879,724,233,380,51608,6671
26,Indiana,6729771,4323,5835956,27793,714384,23581,156417,11930,1906,...,742,865,23014,4886,1372,1768,0,208,21642,4590
28,Iowa,3159672,2419,2725417,14379,347372,13477,77245,6177,478,...,6,10,9638,2625,615,876,345,275,8678,2296
29,Kansas,2900594,2687,2461533,17436,323036,14539,102319,9863,967,...,209,342,13706,2890,190,381,63,107,13453,2864
30,Kentucky,4460646,2878,3878219,19555,463451,18318,107693,6224,2407,...,56,99,11283,2868,31,52,509,655,10743,2742
31,Louisiana,4571302,4582,3987402,19669,483769,18398,81944,8435,3717,...,283,465,18187,3480,191,213,264,216,17732,3475
32,Maine,1360264,1424,1203199,8547,111418,7447,43492,4855,20,...,337,415,2155,853,0,182,0,182,2155,853
34,Maryland,6099715,4217,5387234,27596,519574,25291,160016,10653,906,...,684,783,32891,4509,1000,634,193,207,31698,4597
35,Massachusetts,6916314,4173,6043959,21629,663154,18384,158311,7554,1056,...,35,50,50890,5007,1791,954,176,192,48923,4814
36,Michigan,9950336,4442,8827083,27764,950370,25147,143042,9088,2032,...,504,395,29841,3227,811,521,32,38,28998,3056
37,Minnesota,5645866,3318,4930664,19720,606582,17333,93286,6975,104,...,405,325,15334,2586,116,143,205,158,15013,2584
38,Mississippi,2919574,3069,2608484,17207,241171,15519,59759,6266,3795,...,1801,2759,10160,4031,413,627,145,176,9602,3959
40,Missouri,6102443,4216,5282198,20691,635797,21055,165921,9843,1362,...,415,331,18527,3709,526,600,563,583,17438,3589
41,Montana,1093888,1329,944443,9690,100380,7474,44531,5330,370,...,1947,1227,4534,2602,0,184,0,184,4534,2602
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
45,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1939700,1981,1677312,10187,208977,8549,43287,5163,134,...,1751,850,10124,2264,629,641,0,170,9495,1953
48,Nevada,3111722,3366,2661617,23083,305571,18198,132648,11663,492,...,1060,721,11886,3080,0,221,702,858,11184,2836
49,New Hampshire,1377638,1710,1223839,9920,97263,8285,53245,5800,370,...,0,198,3291,1252,280,237,113,158,2898,1218
50,New Jersey,9174117,4777,8199595,28594,723937,24913,195828,12159,246,...,39,63,54757,7106,2264,1127,0,222,52493,6958
51,New Mexico,2092251,2945,1828971,15156,188495,12055,68019,7525,484,...,884,620,6766,2347,90,112,26,57,6650,2347
53,New York,19626300,8200,17583476,37829,1666707,37802,287249,11439,1930,...,0,217,88868,6675,2189,1269,95,148,86584,6576
54,North Carolina,10446881,5346,9034306,35163,1032016,31433,336681,16849,3276,...,110,169,43878,5344,941,661,781,934,42156,5050
55,North Dakota,764638,1475,641023,8415,83572,7158,37844,5480,377,...,494,383,2199,969,373,423,0,170,1826,803
56,Ohio,11660200,5489,10209047,26190,1228277,27914,184477,11210,2258,...,16,34,38399,5751,645,443,70,114,37684,5691
57,Oklahoma,3943443,2733,3347420,19615,475441,17079,108288,7791,914,...,17,27,12294,2508,705,766,46,77,11543,2532
59,Oregon,4207387,3683,3600937,18211,458434,18455,133935,9142,487,...,1020,731,14081,2915,33,55,582,456,13466,2932
60,Pennsylvania,12842522,5067,11452320,31938,1078336,27367,261831,13241,585,...,229,290,50035,7559,6249,2423,232,220,43554,6723
61,Rhode Island,1085539,1975,959140,9449,77691,8236,43266,4692,0,...,0,232,5442,1407,275,270,44,61,5123,1366
62,South Carolina,5142137,4196,4444195,25549,484535,19587,196200,11924,1472,...,0,226,17207,3327,648,491,1321,1275,15238,3087
63,South Dakota,884616,1584,759943,7867,95407,7171,27528,3650,30,...,1395,1041,1738,643,255,320,0,170,1483,590
65,Tennessee,6899165,4617,5955858,27272,701333,22674,220591,14903,9869,...,550,588,21383,4515,899,654,382,442,20102,4599
66,Texas,29170380,12760,25086829,71104,3315313,62222,591395,26127,9389,...,4424,2403,176843,15137,4180,1912,1618,1339,171045,15106
67,Utah,3295561,3308,2817208,17954,359628,15733,101051,8401,436,...,1991,1035,17674,3338,63,92,1325,1371,16286,2959
68,Vermont,641007,929,564684,5468,42454,4180,31809,3854,94,...,39,69,2060,719,45,78,0,165,2015,724
69,Virginia,8557020,4817,7384723,29614,855269,26354,272693,12741,1878,...,444,320,44335,6304,2912,1593,279,273,41144,5997
71,Washington,7657350,4731,6474967,29847,909338,26736,225306,12843,1064,...,1995,2952,47739,6640,1205,1340,1932,910,44602,6132
72,West Virginia,1767792,1989,1584041,12269,137757,9831,43801,6531,506,...,0,216,2193,1049,0,216,0,216,2193,1049
73,Wisconsin,5838954,3227,5123397,18301,578787,17247,122742,7724,331,...,230,181,14028,2331,533,440,66,110,13429,2325
74,Wyoming,573476,1211,481018,7250,63128,6111,27281,4320,0,...,NaN,NaN,2049,1147,0,208,0,208,2049,1147
76,Puerto Rico,3248011,2728,3040178,12763,177594,12122,27380,3989,47,...,147,240,2859,1312,NaN,NaN,0,254,2859,1312

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [11]:
df.iloc[3:] = df.iloc[3:].fillna('0')

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#first, dealing with columns B-G/1-6)

column_1_name = f'{df.iloc[0, 1]} ({df.iloc[2, 1]})'
column_2_name = f'{df.iloc[0, 1]} ({df.iloc[2, 2]})'

column_3_name = f'{df.iloc[0, 3]} ({df.iloc[2, 3]})'
column_4_name = f'{df.iloc[0, 3]} ({df.iloc[2, 4]})'

column_5_name = f'{df.iloc[0, 5]} ({df.iloc[2, 5]})'
column_6_name = f'{df.iloc[0, 5]} ({df.iloc[2, 6]})'

df_clean = df.rename(columns ={
    '1': column_1_name,
    '2': column_2_name,
    '3': column_3_name,
    '4': column_4_name,
    '5': column_5_name,
    '6': column_6_name})

#next, for the rest of the columns:
#first, fill in blanks

df_filledin = df_clean.ffill(axis=1)

#then pull the info I need to name each column

for i in range(7, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [13]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Population 1 year and over (Estimate),Population 1 year and over (MOE),Same house 1 year ago (Estimate),Same house 1 year ago (MOE),Same state of residence 1 year ago (Estimate),Same state of residence 1 year ago (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (continued): Wyoming (Estimate),Different state of residence 1 year ago (continued): Wyoming (MOE),Abroad 1 year ago: Total (Estimate),Abroad 1 year ago: Total (MOE),Abroad 1 year ago: Puerto Rico (Estimate),Abroad 1 year ago: Puerto Rico (MOE),Abroad 1 year ago: U.S. Island Area (Estimate),Abroad 1 year ago: U.S. Island Area (MOE),Abroad 1 year ago: Foreign Country (Estimate),Abroad 1 year ago: Foreign Country (MOE)
53,New York,19626300,8200,17583476,37829,1666707,37802,287249,11439,1930,...,0,217,88868,6675,2189,1269,95,148,86584,6576
54,North Carolina,10446881,5346,9034306,35163,1032016,31433,336681,16849,3276,...,110,169,43878,5344,941,661,781,934,42156,5050
55,North Dakota,764638,1475,641023,8415,83572,7158,37844,5480,377,...,494,383,2199,969,373,423,0,170,1826,803
56,Ohio,11660200,5489,10209047,26190,1228277,27914,184477,11210,2258,...,16,34,38399,5751,645,443,70,114,37684,5691
57,Oklahoma,3943443,2733,3347420,19615,475441,17079,108288,7791,914,...,17,27,12294,2508,705,766,46,77,11543,2532
59,Oregon,4207387,3683,3600937,18211,458434,18455,133935,9142,487,...,1020,731,14081,2915,33,55,582,456,13466,2932
60,Pennsylvania,12842522,5067,11452320,31938,1078336,27367,261831,13241,585,...,229,290,50035,7559,6249,2423,232,220,43554,6723
61,Rhode Island,1085539,1975,959140,9449,77691,8236,43266,4692,0,...,0,232,5442,1407,275,270,44,61,5123,1366
62,South Carolina,5142137,4196,4444195,25549,484535,19587,196200,11924,1472,...,0,226,17207,3327,648,491,1321,1275,15238,3087
63,South Dakota,884616,1584,759943,7867,95407,7171,27528,3650,30,...,1395,1041,1738,643,255,320,0,170,1483,590
65,Tennessee,6899165,4617,5955858,27272,701333,22674,220591,14903,9869,...,550,588,21383,4515,899,654,382,442,20102,4599
66,Texas,29170380,12760,25086829,71104,3315313,62222,591395,26127,9389,...,4424,2403,176843,15137,4180,1912,1618,1339,171045,15106
67,Utah,3295561,3308,2817208,17954,359628,15733,101051,8401,436,...,1991,1035,17674,3338,63,92,1325,1371,16286,2959
68,Vermont,641007,929,564684,5468,42454,4180,31809,3854,94,...,39,69,2060,719,45,78,0,165,2015,724
69,Virginia,8557020,4817,7384723,29614,855269,26354,272693,12741,1878,...,444,320,44335,6304,2912,1593,279,273,41144,5997
71,Washington,7657350,4731,6474967,29847,909338,26736,225306,12843,1064,...,1995,2952,47739,6640,1205,1340,1932,910,44602,6132
72,West Virginia,1767792,1989,1584041,12269,137757,9831,43801,6531,506,...,0,216,2193,1049,0,216,0,216,2193,1049
73,Wisconsin,5838954,3227,5123397,18301,578787,17247,122742,7724,331,...,230,181,14028,2331,533,440,66,110,13429,2325
74,Wyoming,573476,1211,481018,7250,63128,6111,27281,4320,0,...,0,0,2049,1147,0,208,0,208,2049,1147
76,Puerto Rico,3248011,2728,3040178,12763,177594,12122,27380,3989,47,...,147,240,2859,1312,0,0,0,254,2859,1312


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [ ]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),328464538,4989797,723949,7202745,2990311,38833197,5757628,3571470,994669,661026,...,6899165,29170380,3295561,641007,8557020,7657350,1767792,5838954,573476,3248011
Population 1 year and over (MOE),34090,4341,1517,5156,2937,12214,4091,3191,1764,1835,...,4617,12760,3308,929,4817,4731,1989,3227,1211,2728
Same house 1 year ago (Estimate),286552923,4392571,625088,6144045,2595527,34461724,4794481,3168509,889174,527167,...,5955858,25086829,2817208,564684,7384723,6474967,1584041,5123397,481018,3040178
Same house 1 year ago (MOE),190336,25089,8315,29885,18138,53862,26077,15301,6362,8611,...,27272,71104,17954,5468,29614,29847,12269,18301,7250,12763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago: Puerto Rico (MOE),7470,436,202,764,213,597,430,1063,372,434,...,654,1912,92,78,1593,1340,216,440,208,0
Abroad 1 year ago: U.S. Island Area (Estimate),19587,29,0,57,0,1921,291,165,0,0,...,382,1618,1325,0,279,1932,0,66,0,0
Abroad 1 year ago: U.S. Island Area (MOE),4066,47,184,96,213,860,297,192,210,236,...,442,1339,1371,165,273,910,216,110,208,254
Abroad 1 year ago: Foreign Country (Estimate),1400401,12058,3667,33388,5828,185811,25442,15186,4445,6939,...,20102,171045,16286,2015,41144,44602,2193,13429,2049,2859
Abroad 1 year ago: Foreign Country (MOE),33711,2400,1527,5544,1634,12087,4129,3170,1723,1433,...,4599,15106,2959,724,5997,6132,1049,2325,1147,1312

In [17]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [18]:

df = df.iloc[1:]

In [19]:
df

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),328464538,4989797,723949,7202745,2990311,38833197,5757628,3571470,994669,661026,...,6899165,29170380,3295561,641007,8557020,7657350,1767792,5838954,573476,3248011
Population 1 year and over (MOE),34090,4341,1517,5156,2937,12214,4091,3191,1764,1835,...,4617,12760,3308,929,4817,4731,1989,3227,1211,2728
Same house 1 year ago (Estimate),286552923,4392571,625088,6144045,2595527,34461724,4794481,3168509,889174,527167,...,5955858,25086829,2817208,564684,7384723,6474967,1584041,5123397,481018,3040178
Same house 1 year ago (MOE),190336,25089,8315,29885,18138,53862,26077,15301,6362,8611,...,27272,71104,17954,5468,29614,29847,12269,18301,7250,12763
Same state of residence 1 year ago (Estimate),32577121,468964,63611,759450,312848,3749371,686892,279328,58180,68606,...,701333,3315313,359628,42454,855269,909338,137757,578787,63128,177594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago: Puerto Rico (MOE),7470,436,202,764,213,597,430,1063,372,434,...,654,1912,92,78,1593,1340,216,440,208,0
Abroad 1 year ago: U.S. Island Area (Estimate),19587,29,0,57,0,1921,291,165,0,0,...,382,1618,1325,0,279,1932,0,66,0,0
Abroad 1 year ago: U.S. Island Area (MOE),4066,47,184,96,213,860,297,192,210,236,...,442,1339,1371,165,273,910,216,110,208,254
Abroad 1 year ago: Foreign Country (Estimate),1400401,12058,3667,33388,5828,185811,25442,15186,4445,6939,...,20102,171045,16286,2015,41144,44602,2193,13429,2049,2859
Abroad 1 year ago: Foreign Country (MOE),33711,2400,1527,5544,1634,12087,4129,3170,1723,1433,...,4599,15106,2959,724,5997,6132,1049,2325,1147,1312

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [20]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [21]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [22]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Population 1 year and over (Estimate)                             661026
Same house 1 year ago (Estimate)                                  527167
Same state of residence 1 year ago (Estimate)                      68606
Different state of residence 1 year ago: Total ...                 57746
Different state of residence 1 year ago: Alabam...                   342
Different state of residence 1 year ago (contin...                   196
Different state of residence 1 year ago (contin...                   674
Different state of residence 1 year ago (contin...                    37
Different state of residence 1 year ago (contin...                  3945
Different state of residence 1 year ago (contin...                   261
Different state of residence 1 year ago (contin...                  1102
Different state of residence 1 year ago (contin...                  3560
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  2581
Different state of residence 1 year ago (contin...                  1662
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                    93
Different state of residence 1 year ago (contin...                  1736
Different state of residence 1 year ago (contin...                   159
Different state of residence 1 year ago (contin...                   145
Different state of residence 1 year ago (contin...                   503
Different state of residence 1 year ago (contin...                   202
Different state of residence 1 year ago (contin...                   324
Different state of residence 1 year ago (contin...                  1028
Different state of residence 1 year ago (contin...                  7754
Different state of residence 1 year ago (contin...                  2389
Different state of residence 1 year ago (contin...                   607
Different state of residence 1 year ago (contin...                   726
Different state of residence 1 year ago (contin...                    29
Different state of residence 1 year ago (contin...                    87
Different state of residence 1 year ago (contin...                    65
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   431
Different state of residence 1 year ago (contin...                   266
Different state of residence 1 year ago (contin...                  2709
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  3658
Different state of residence 1 year ago (contin...                  1330
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  1610
Different state of residence 1 year ago (contin...                   374
Different state of residence 1 year ago (contin...                   426
Different state of residence 1 year ago (contin...                  2237
Different state of residence 1 year ago (contin...                   366
Different state of residence 1 year ago (contin...                   196
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   663
Different state of residence 1 year ago (contin...                  1498
Different state of residence 1 year ago (contin...                    24
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  9003
Different state of residence 1 year ago (contin...                  1817
Different state of residence 1 year ago (contin...                   568
Different state of residence 1 year ago (contin...                   307
Different state of residence 1 year ago (contin...                    56
Abroad 1 year ago: Total (Estimate)                                 7507
Abroad 1 year ago: Puerto Rico (Estimate)                            568
Abroad 1 year ago: U.S. Island Area (Estimate)                         0
Abroad 1 year ago: Foreign Country (Estimate)                       6939

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [23]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

Cut off the top columns that arent for specific states

In [24]:

df_estimates = df_estimates[4:]
df_moes = df_moes[4:]

In [25]:
df_moes.head()

0          District of Columbia
0
Alabama                      369
Alaska                       179
Arizona                      632
Arkansas                      75
California                  1308

In [26]:
df_estimates.head()

0          District of Columbia
0
Alabama                      342
Alaska                       196
Arizona                      674
Arkansas                      37
California                  3945

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [27]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Also need to cut out one "total" column that is the total amount of "Abroad One Year Ago" incl PR, US Island Area, and Foreign Country

In [28]:
df = df.drop('Total')

df

0                    District of Columbia  MOE +/-
0
Alabama                                342     369
Alaska                                 196     179
Arizona                                674     632
Arkansas                                37      75
California                            3945    1308
Colorado                               261     258
Connecticut                           1102     562
Delaware                              3560    1052
District of Columbia                     0       0
Florida                               2581    1114
Georgia                               1662     836
Hawaii                                   0     236
Idaho                                   93     116
Illinois                              1736     928
Indiana                                159     263
Iowa                                   145     167
Kansas                                 503     668
Kentucky                               202     205
Louisiana                              324     341
Maine                                 1028     573
Maryland                              7754    1798
Massachusetts                         2389     870
Michigan                               607     418
Minnesota                              726     504
Mississippi                             29      67
Missouri                                87     108
Montana                                 65      78
Nebraska                                 0     236
Nevada                                 431     412
New Hampshire                          266     329
New Jersey                            2709    1162
New Mexico                               0     236
New York                              3658    1245
North Carolina                        1330     807
North Dakota                             0     236
Ohio                                  1610    1744
Oklahoma                               374     397
Oregon                                 426     250
Pennsylvania                          2237    1095
Rhode Island                           366     348
South Carolina                         196     272
South Dakota                             0     236
Tennessee                              663     363
Texas                                 1498    1002
Utah                                    24      37
Vermont                                  0     236
Virginia                              9003    2140
Washington                            1817     849
West Virginia                          568     437
Wisconsin                              307     304
Wyoming                                 56      93
Puerto Rico                            568     434
U.S. Island Area                         0     236
Foreign Country                       6939    1433

also need to drop out the last two columns US Island Area and Foreign Country because those dont exist in the pop df and I don't need for this analysis

In [29]:
df = df.drop('U.S. Island Area')
df = df.drop('Foreign Country')

also need to drop the top row of pops df to get the dataframes to have the same row indices

In [30]:
df_pops = df_pops.drop('Label (Grouping)')

Now I'm adding a state polulation column to my newly formatted table

In [31]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [32]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [33]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [34]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       342     369          5024279
Alaska                        196     179           733391
Arizona                       674     632          7151502
Arkansas                       37      75          3011524
California                   3945    1308         39538223
Colorado                      261     258          5773714
Connecticut                  1102     562          3605944
Delaware                     3560    1052           989948
District of Columbia            0       0           689545
Florida                      2581    1114         21538187
Georgia                      1662     836         10711908
Hawaii                          0     236          1455271
Idaho                          93     116          1839106
Illinois                     1736     928         12812508
Indiana                       159     263          6785528
Iowa                          145     167          3190369
Kansas                        503     668          2937880
Kentucky                      202     205          4505836
Louisiana                     324     341          4657757
Maine                        1028     573          1362359
Maryland                     7754    1798          6177224
Massachusetts                2389     870          7029917
Michigan                      607     418         10077331
Minnesota                     726     504          5706494
Mississippi                    29      67          2961279
Missouri                       87     108          6154913
Montana                        65      78          1084225
Nebraska                        0     236          1961504
Nevada                        431     412          3104614
New Hampshire                 266     329          1377529
New Jersey                   2709    1162          9288994
New Mexico                      0     236          2117522
New York                     3658    1245         20201249
North Carolina               1330     807         10439388
North Dakota                    0     236           779094
Ohio                         1610    1744         11799448
Oklahoma                      374     397          3959353
Oregon                        426     250          4237256
Pennsylvania                 2237    1095         13002700
Rhode Island                  366     348          1097379
South Carolina                196     272          5118425
South Dakota                    0     236           886667
Tennessee                     663     363          6910840
Texas                        1498    1002         29145505
Utah                           24      37          3271616
Vermont                         0     236           643077
Virginia                     9003    2140          8631393
Washington                   1817     849          7705281
West Virginia                 568     437          1793716
Wisconsin                     307     304          5893718
Wyoming                        56      93           576851
Puerto Rico                   568     434          3285874

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [35]:
df['state_pop_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Starting a new dataframe that I can build on for comparing across years

In [ ]:
df_tochart = df['state_pop_adjusted'].sort_values(ascending=False)

df_tochart.head(10)

0
Delaware         0.003596
Maryland         0.001255
Virginia         0.001043
Maine            0.000755
Massachusetts    0.000340
Rhode Island     0.000334
West Virginia    0.000317
Connecticut      0.000306
New Jersey       0.000292
Alaska           0.000267
Name: state_pop_adjusted, dtype: float64

Also want to make a slice excluding all DMV states -- Maryland, Virginia

In [44]:
df_withoutdmv = df_tochart.drop(['Maryland'])

df_withoutdmv = df_withoutdmv.drop(['Virginia'])

df_withoutdmv

0
Delaware                0.003596
Maine                   0.000755
Massachusetts           0.000340
Rhode Island            0.000334
West Virginia           0.000317
Connecticut             0.000306
New Jersey              0.000292
Alaska                  0.000267
Washington              0.000236
New Hampshire           0.000193
New York                0.000181
Puerto Rico             0.000173
Pennsylvania            0.000172
Kansas                  0.000171
Georgia                 0.000155
Nevada                  0.000139
Ohio                    0.000136
Illinois                0.000135
North Carolina          0.000127
Minnesota               0.000127
Florida                 0.000120
Oregon                  0.000101
California              0.000100
Wyoming                 0.000097
Tennessee               0.000096
Oklahoma                0.000094
Arizona                 0.000094
Louisiana               0.000070
Alabama                 0.000068
Michigan                0.000060
Montana                 0.000060
Wisconsin               0.000052
Texas                   0.000051
Idaho                   0.000051
Iowa                    0.000045
Colorado                0.000045
Kentucky                0.000045
South Carolina          0.000038
Indiana                 0.000023
Missouri                0.000014
Arkansas                0.000012
Mississippi             0.000010
Utah                    0.000007
District of Columbia    0.000000
New Mexico              0.000000
Hawaii                  0.000000
Vermont                 0.000000
Nebraska                0.000000
North Dakota            0.000000
South Dakota            0.000000
Name: state_pop_adjusted, dtype: float64