Going to try with matplot lib

I used chatgpt to help me generate some of this initial code

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.colors as mcolors
import plotly.express as px

Read in dataframes, and then make a list of dataframes so I can run through them all

In [2]:
#following election years
df_2005 = pd.read_csv('DC-migration-2005.csv')
df_2009 = pd.read_csv('DC-migration-2009.csv')
df_2013 = pd.read_csv('DC-migration-2013.csv')
df_2017 = pd.read_csv('DC-migration-2017.csv')
df_2021 = pd.read_csv('DC-migration-2021.csv')


#pre-election years for comparison

df_2006 = pd.read_csv('DC-migration-2006.csv')
df_2007 = pd.read_csv('DC-migration-2007.csv')
df_2008 = pd.read_csv('DC-migration-2008.csv')

df_2010 = pd.read_csv('DC-migration-2010.csv')
df_2011 = pd.read_csv('DC-migration-2011.csv')
df_2012 = pd.read_csv('DC-migration-2012.csv')

df_2014 = pd.read_csv('DC-migration-2013.csv')
df_2015 = pd.read_csv('DC-migration-2015.csv')
df_2016 = pd.read_csv('DC-migration-2016.csv')

df_2018 = pd.read_csv('DC-migration-2018.csv')
df_2019 = pd.read_csv('DC-migration-2019.csv')

Drop the initial columns that were carried over from the indexes and messing up this data.

In [3]:
df_2005 = df_2005.drop(columns=["Unnamed: 0"])
df_2006 = df_2006.drop(columns=["Unnamed: 0"])
df_2007 = df_2007.drop(columns=["Unnamed: 0"])
df_2008 = df_2008.drop(columns=["Unnamed: 0"])
df_2009 = df_2009.drop(columns=["Unnamed: 0"])
df_2010 = df_2010.drop(columns=["Unnamed: 0"])
df_2011 = df_2011.drop(columns=["Unnamed: 0"])
df_2012 = df_2012.drop(columns=["Unnamed: 0"])
df_2013 = df_2013.drop(columns=["Unnamed: 0"])
df_2014 = df_2014.drop(columns=["Unnamed: 0"])
df_2015 = df_2015.drop(columns=["Unnamed: 0"])
df_2016 = df_2016.drop(columns=["Unnamed: 0"])
df_2017 = df_2017.drop(columns=["Unnamed: 0"])
df_2018 = df_2018.drop(columns=["Unnamed: 0"])
df_2019 = df_2019.drop(columns=["Unnamed: 0"])
df_2021 = df_2021.drop(columns=["Unnamed: 0"])

In [4]:
df_2005.tail()

df_2015.tail()

,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
43,Vermont,117,143,643077,0.000182,0.000222,DEMOCRAT,0.665706
44,Washington,134,164,7705281,0.000017,0.000021,DEMOCRAT,0.561634
45,West Virginia,478,432,1793716,0.000266,0.000241,REPUBLICAN,0.622958
46,Wisconsin,514,421,5893718,0.000087,0.000071,DEMOCRAT,0.527762
47,Wyoming,0,200,576851,0.000000,0.000347,REPUBLICAN,0.681936

Add in a state year column so in order to be able to loop through the dataframes

In [5]:
df_2005['year'] = 2005
df_2006['year'] = 2006
df_2007['year'] = 2007
df_2008['year'] = 2008
df_2009['year'] = 2009
df_2010['year'] = 2010
df_2011['year'] = 2011
df_2012['year'] = 2012
df_2013['year'] = 2013
df_2014['year'] = 2014
df_2015['year'] = 2015
df_2016['year'] = 2016
df_2017['year'] = 2017
df_2018['year'] = 2018
df_2019['year'] = 2019
df_2021['year'] = 2021

Forming a new dataframe to compare other years with 2017. Starting with 2015, 2016, 2017 data

In [6]:
df_17_compare = pd.DataFrame()

df_17_compare['state'] = df_2017['state'].copy()
df_17_compare['pop_migrated_2015'] = df_2015['pop_migrated'].copy()
df_17_compare['pop_migrated_2016'] = df_2016['pop_migrated'].copy()
df_17_compare['pop_migrated_2017'] = df_2017['pop_migrated'].copy()

Make a new column averaging the non election years -- i.e. 2015 and 2016 (since census is early in year before election)

In [7]:
df_17_compare['15_16_avg'] = (df_17_compare['pop_migrated_2015'] + df_17_compare['pop_migrated_2016']) / 2

In [8]:
df_17_compare.head(30)

,state,pop_migrated_2015,pop_migrated_2016,pop_migrated_2017,15_16_avg
0,Alabama,359,140,494,249.5
1,Alaska,235,77,0,156.0
2,Arizona,367,744,549,555.5
3,Arkansas,203,0,105,101.5
4,California,4119,3908,3763,4013.5
5,Colorado,433,531,1109,482.0
6,Connecticut,1292,1225,1149,1258.5
7,Delaware,252,278,375,265.0
8,Florida,2731,2717,1182,2724.0
9,Georgia,1013,1105,1507,1059.0
10,Hawaii,52,103,29,77.5
11,Idaho,5,0,161,2.5
12,Illinois,785,2418,2726,1601.5
13,Indiana,748,957,710,852.5
14,Iowa,135,218,17,176.5
15,Kansas,33,0,0,16.5
16,Kentucky,275,233,285,254.0
17,Louisiana,392,197,461,294.5
18,Maine,258,118,122,188.0
19,Massachusetts,2876,1974,2669,2425.0
20,Michigan,1308,922,808,1115.0
21,Minnesota,545,542,436,543.5
22,Mississippi,338,224,157,281.0
23,Missouri,141,566,466,353.5
24,Montana,0,17,0,8.5
25,Nebraska,674,190,0,432.0
26,Nevada,68,356,128,212.0
27,New Hampshire,47,168,88,107.5
28,New Jersey,1804,1494,2590,1649.0
29,New Mexico,40,1,206,20.5

Make a new column with the percent change between 2016 and 2017 years

In [9]:
df_17_compare['pct_change_pre_post_election'] = (
    df_17_compare['pop_migrated_2017'] - df_17_compare['15_16_avg']
) / df_17_compare["15_16_avg"] * 100

df_17_compare.head()

,state,pop_migrated_2015,pop_migrated_2016,pop_migrated_2017,15_16_avg,pct_change_pre_post_election
0,Alabama,359,140,494,249.5,97.995992
1,Alaska,235,77,0,156.0,-100.000000
2,Arizona,367,744,549,555.5,-1.170117
3,Arkansas,203,0,105,101.5,3.448276
4,California,4119,3908,3763,4013.5,-6.241435

Add back in the party info

In [10]:
df_17_compare['winning_party'] = df_2017['winning_party'] 
df_17_compare['winner_percent_of_votes'] = df_2017['winner_percent_of_votes'] 

df_17_compare.head()

,state,pop_migrated_2015,pop_migrated_2016,pop_migrated_2017,15_16_avg,pct_change_pre_post_election,winning_party,winner_percent_of_votes
0,Alabama,359,140,494,249.5,97.995992,REPUBLICAN,0.620831
1,Alaska,235,77,0,156.0,-100.000000,REPUBLICAN,0.512815
2,Arizona,367,744,549,555.5,-1.170117,REPUBLICAN,0.486716
3,Arkansas,203,0,105,101.5,3.448276,REPUBLICAN,0.605741
4,California,4119,3908,3763,4013.5,-6.241435,DEMOCRAT,0.617264

Add a total column, so that I can see tota numbers migrating into D.C. in an election year and not in an election year.

In [11]:
df_17_compare.loc["Total"] = df_17_compare.sum(numeric_only=True)

df_17_compare.head()

,state,pop_migrated_2015,pop_migrated_2016,pop_migrated_2017,15_16_avg,pct_change_pre_post_election,winning_party,winner_percent_of_votes
0,Alabama,359.0,140.0,494.0,249.5,97.995992,REPUBLICAN,0.620831
1,Alaska,235.0,77.0,0.0,156.0,-100.000000,REPUBLICAN,0.512815
2,Arizona,367.0,744.0,549.0,555.5,-1.170117,REPUBLICAN,0.486716
3,Arkansas,203.0,0.0,105.0,101.5,3.448276,REPUBLICAN,0.605741
4,California,4119.0,3908.0,3763.0,4013.5,-6.241435,DEMOCRAT,0.617264

In [12]:
df_17_compare.sort_values('pct_change_pre_post_election', ascending=False)

,state,pop_migrated_2015,pop_migrated_2016,pop_migrated_2017,15_16_avg,pct_change_pre_post_election,winning_party,winner_percent_of_votes
Total,NaN,37151.0,35529.0,37887.0,36340.0,7259.628037,NaN,26.348198
11,Idaho,5.0,0.0,161.0,2.5,6340.000000,REPUBLICAN,0.592614
29,New Mexico,40.0,1.0,206.0,20.5,904.878049,DEMOCRAT,0.482556
43,Vermont,117.0,0.0,447.0,58.5,664.102564,DEMOCRAT,0.557227
5,Colorado,433.0,531.0,1109.0,482.0,130.082988,DEMOCRAT,0.481570
0,Alabama,359.0,140.0,494.0,249.5,97.995992,REPUBLICAN,0.620831
42,Utah,177.0,249.0,384.0,213.0,80.281690,REPUBLICAN,0.455408
12,Illinois,785.0,2418.0,2726.0,1601.5,70.215423,DEMOCRAT,0.558254
41,Texas,1314.0,2213.0,2858.0,1763.5,62.064077,REPUBLICAN,0.522347
40,Tennessee,873.0,452.0,1057.0,662.5,59.547170,REPUBLICAN,0.607220
28,New Jersey,1804.0,1494.0,2590.0,1649.0,57.064888,DEMOCRAT,0.554531
17,Louisiana,392.0,197.0,461.0,294.5,56.536503,REPUBLICAN,0.580887
9,Georgia,1013.0,1105.0,1507.0,1059.0,42.304060,REPUBLICAN,0.507713
7,Delaware,252.0,278.0,375.0,265.0,41.509434,DEMOCRAT,0.533533
23,Missouri,141.0,566.0,466.0,353.5,31.824611,REPUBLICAN,0.567723
31,North Carolina,1501.0,1367.0,1867.0,1434.0,30.195258,REPUBLICAN,0.498281
33,Ohio,1027.0,659.0,1026.0,843.0,21.708185,REPUBLICAN,0.516877
37,Rhode Island,234.0,268.0,296.0,251.0,17.928287,DEMOCRAT,0.544066
16,Kentucky,275.0,233.0,285.0,254.0,12.204724,REPUBLICAN,0.625196
19,Massachusetts,2876.0,1974.0,2669.0,2425.0,10.061856,DEMOCRAT,0.590501
30,New York,5133.0,4762.0,5238.0,4947.5,5.871652,DEMOCRAT,0.561361
3,Arkansas,203.0,0.0,105.0,101.5,3.448276,REPUBLICAN,0.605741
2,Arizona,367.0,744.0,549.0,555.5,-1.170117,REPUBLICAN,0.486716
4,California,4119.0,3908.0,3763.0,4013.5,-6.241435,DEMOCRAT,0.617264
6,Connecticut,1292.0,1225.0,1149.0,1258.5,-8.700834,DEMOCRAT,0.545663
13,Indiana,748.0,957.0,710.0,852.5,-16.715543,REPUBLICAN,0.569400
27,New Hampshire,47.0,168.0,88.0,107.5,-18.139535,DEMOCRAT,0.468263
36,Pennsylvania,1999.0,2468.0,1824.0,2233.5,-18.334453,REPUBLICAN,0.485779
21,Minnesota,545.0,542.0,436.0,543.5,-19.779209,DEMOCRAT,0.464450
44,Washington,134.0,418.0,206.0,276.0,-25.362319,DEMOCRAT,0.525387
20,Michigan,1308.0,922.0,808.0,1115.0,-27.533632,REPUBLICAN,0.474976
18,Maine,258.0,118.0,122.0,188.0,-35.106383,DEMOCRAT,0.463452
26,Nevada,68.0,356.0,128.0,212.0,-39.622642,DEMOCRAT,0.479178
22,Mississippi,338.0,224.0,157.0,281.0,-44.128114,REPUBLICAN,0.579410
8,Florida,2731.0,2717.0,1182.0,2724.0,-56.607930,REPUBLICAN,0.490219
10,Hawaii,52.0,103.0,29.0,77.5,-62.580645,DEMOCRAT,0.609808
46,Wisconsin,514.0,242.0,115.0,378.0,-69.576720,REPUBLICAN,0.472182
35,Oregon,157.0,125.0,37.0,141.0,-73.758865,DEMOCRAT,0.500719
38,South Carolina,1806.0,382.0,235.0,1094.0,-78.519196,REPUBLICAN,0.549393
32,North Dakota,0.0,83.0,5.0,41.5,-87.951807,REPUBLICAN,0.629556
14,Iowa,135.0,218.0,17.0,176.5,-90.368272,REPUBLICAN,0.511621
34,Oklahoma,150.0,122.0,0.0,136.0,-100.000000,REPUBLICAN,0.653229
25,Nebraska,674.0,190.0,0.0,432.0,-100.000000,REPUBLICAN,0.587474
39,South Dakota,9.0,0.0,0.0,4.5,-100.000000,REPUBLICAN,0.615308
15,Kansas,33.0,0.0,0.0,16.5,-100.000000,REPUBLICAN,0.566546
1,Alaska,235.0,77.0,0.0,156.0,-100.000000,REPUBLICAN,0.512815
45,West Virginia,478.0,296.0,0.0,387.0,-100.000000,REPUBLICAN,0.686306
24,Montana,0.0,17.0,0.0,8.5,-100.000000,REPUBLICAN,0.564662
47,Wyoming,0.0,0.0,0.0,0.0,NaN,REPUBLICAN,0.673984

Forming a new dataframe to compare things with 2021. Will start with 2018 and 2019, and 2021 data (there is no 2018 instead of 2020 because no data in 2020 because of covid)

In [13]:
df_21_compare = pd.DataFrame()

df_21_compare['state'] = df_2019['state'].copy()
df_21_compare['pop_migrated_2018'] = df_2018['pop_migrated'].copy()
df_21_compare['pop_migrated_2019'] = df_2019['pop_migrated'].copy()
df_21_compare['pop_migrated_2021'] = df_2021['pop_migrated'].copy()

Make a column averaging 2018 and 2019

In [14]:
df_21_compare['18-19_avg'] = (df_21_compare['pop_migrated_2018'] + df_21_compare['pop_migrated_2019']) / 2

Add back in the party info

In [15]:
df_21_compare['winning_party'] = df_2021['winning_party'] 
df_21_compare['winner_percent_of_votes'] = df_2021['winner_percent_of_votes'] 

df_21_compare.head()

,state,pop_migrated_2018,pop_migrated_2019,pop_migrated_2021,18-19_avg,winning_party,winner_percent_of_votes
0,Alabama,174,462,342,318.0,REPUBLICAN,0.620316
1,Alaska,0,338,196,169.0,REPUBLICAN,0.528331
2,Arizona,204,291,674,247.5,DEMOCRAT,0.493647
3,Arkansas,0,0,37,0.0,REPUBLICAN,0.623957
4,California,3803,3437,3945,3620.0,DEMOCRAT,0.634839

Percent change 2019 vs 2021 of migrants to DC from each state

In [16]:
df_21_compare['pct_change_pre_post_election'] = (
    df_21_compare['pop_migrated_2021'] - df_21_compare['18-19_avg']
) / df_21_compare["18-19_avg"] * 100

df_21_compare.head()

,state,pop_migrated_2018,pop_migrated_2019,pop_migrated_2021,18-19_avg,winning_party,winner_percent_of_votes,pct_change_pre_post_election
0,Alabama,174,462,342,318.0,REPUBLICAN,0.620316,7.547170
1,Alaska,0,338,196,169.0,REPUBLICAN,0.528331,15.976331
2,Arizona,204,291,674,247.5,DEMOCRAT,0.493647,172.323232
3,Arkansas,0,0,37,0.0,REPUBLICAN,0.623957,inf
4,California,3803,3437,3945,3620.0,DEMOCRAT,0.634839,8.977901

Add in a total column so that I can see tota numbers migrating into D.C. in an election year and not in an election year.

In [17]:
df_21_compare.loc["Total"] = df_21_compare.sum(numeric_only=True)

df_21_compare.head()

,state,pop_migrated_2018,pop_migrated_2019,pop_migrated_2021,18-19_avg,winning_party,winner_percent_of_votes,pct_change_pre_post_election
0,Alabama,174.0,462.0,342.0,318.0,REPUBLICAN,0.620316,7.547170
1,Alaska,0.0,338.0,196.0,169.0,REPUBLICAN,0.528331,15.976331
2,Arizona,204.0,291.0,674.0,247.5,DEMOCRAT,0.493647,172.323232
3,Arkansas,0.0,0.0,37.0,0.0,REPUBLICAN,0.623957,inf
4,California,3803.0,3437.0,3945.0,3620.0,DEMOCRAT,0.634839,8.977901

In [18]:
df_21_compare.sort_values('pct_change_pre_post_election', ascending=False)

,state,pop_migrated_2018,pop_migrated_2019,pop_migrated_2021,18-19_avg,winning_party,winner_percent_of_votes,pct_change_pre_post_election
Total,NaN,27047.0,34552.0,40989.0,30799.5,NaN,27.582650,inf
3,Arkansas,0.0,0.0,37.0,0.0,REPUBLICAN,0.623957,inf
7,Delaware,182.0,0.0,3560.0,91.0,DEMOCRAT,0.587430,3812.087912
15,Kansas,0.0,41.0,503.0,20.5,REPUBLICAN,0.562125,2353.658537
26,Nevada,36.0,0.0,431.0,18.0,DEMOCRAT,0.500568,2294.444444
11,Idaho,0.0,28.0,93.0,14.0,REPUBLICAN,0.638376,564.285714
34,Oklahoma,0.0,185.0,374.0,92.5,REPUBLICAN,0.653733,304.324324
18,Maine,61.0,448.0,1028.0,254.5,DEMOCRAT,0.525256,303.929273
21,Minnesota,143.0,278.0,726.0,210.5,DEMOCRAT,0.523951,244.893112
35,Oregon,80.0,172.0,426.0,126.0,DEMOCRAT,0.564533,238.095238
37,Rhode Island,87.0,138.0,366.0,112.5,DEMOCRAT,0.594762,225.333333
27,New Hampshire,130.0,49.0,266.0,89.5,DEMOCRAT,0.527078,197.206704
44,Washington,387.0,852.0,1817.0,619.5,DEMOCRAT,0.579703,193.301049
2,Arizona,204.0,291.0,674.0,247.5,DEMOCRAT,0.493647,172.323232
45,West Virginia,294.0,324.0,568.0,309.0,REPUBLICAN,0.686316,83.818770
9,Georgia,647.0,1190.0,1662.0,918.5,DEMOCRAT,0.494731,80.947197
16,Kentucky,110.0,131.0,202.0,120.5,REPUBLICAN,0.620866,67.634855
47,Wyoming,68.0,0.0,56.0,34.0,REPUBLICAN,0.694998,64.705882
8,Florida,1789.0,1496.0,2581.0,1642.5,REPUBLICAN,0.512198,57.138508
17,Louisiana,0.0,452.0,324.0,226.0,REPUBLICAN,0.584609,43.362832
12,Illinois,1066.0,1361.0,1736.0,1213.5,DEMOCRAT,0.575416,43.057272
6,Connecticut,262.0,1298.0,1102.0,780.0,DEMOCRAT,0.592607,41.282051
33,Ohio,1592.0,755.0,1610.0,1173.5,REPUBLICAN,0.532713,37.196421
24,Montana,92.0,4.0,65.0,48.0,REPUBLICAN,0.569185,35.416667
36,Pennsylvania,1617.0,1718.0,2237.0,1667.5,DEMOCRAT,0.500085,34.152924
14,Iowa,162.0,59.0,145.0,110.5,REPUBLICAN,0.528002,31.221719
19,Massachusetts,1664.0,2383.0,2389.0,2023.5,DEMOCRAT,0.651230,18.062763
1,Alaska,0.0,338.0,196.0,169.0,REPUBLICAN,0.528331,15.976331
4,California,3803.0,3437.0,3945.0,3620.0,DEMOCRAT,0.634839,8.977901
0,Alabama,174.0,462.0,342.0,318.0,REPUBLICAN,0.620316,7.547170
31,North Carolina,1026.0,1481.0,1330.0,1253.5,REPUBLICAN,0.499343,6.102912
28,New Jersey,2382.0,2758.0,2709.0,2570.0,DEMOCRAT,0.573342,5.408560
20,Michigan,486.0,758.0,607.0,622.0,DEMOCRAT,0.506208,-2.411576
41,Texas,1036.0,2073.0,1498.0,1554.5,REPUBLICAN,0.520576,-3.634609
46,Wisconsin,346.0,362.0,307.0,354.0,DEMOCRAT,0.494495,-13.276836
30,New York,4642.0,4314.0,3658.0,4478.0,DEMOCRAT,0.603919,-18.311746
40,Tennessee,690.0,991.0,663.0,840.5,REPUBLICAN,0.606603,-21.118382
13,Indiana,146.0,427.0,159.0,286.5,REPUBLICAN,0.570212,-44.502618
5,Colorado,336.0,870.0,261.0,603.0,DEMOCRAT,0.550111,-56.716418
38,South Carolina,408.0,568.0,196.0,488.0,REPUBLICAN,0.550935,-59.836066
42,Utah,215.0,0.0,24.0,107.5,REPUBLICAN,0.581298,-77.674419
23,Missouri,201.0,976.0,87.0,588.5,REPUBLICAN,0.567997,-85.216653
22,Mississippi,146.0,265.0,29.0,205.5,REPUBLICAN,0.576030,-85.888078
39,South Dakota,0.0,250.0,0.0,125.0,REPUBLICAN,0.617694,-100.000000
25,Nebraska,0.0,49.0,0.0,24.5,REPUBLICAN,0.582242,-100.000000
43,Vermont,213.0,54.0,0.0,133.5,DEMOCRAT,0.654558,-100.000000
10,Hawaii,124.0,0.0,0.0,62.0,DEMOCRAT,0.631494,-100.000000
29,New Mexico,0.0,466.0,0.0,233.0,DEMOCRAT,0.542893,-100.000000
32,North Dakota,0.0,0.0,0.0,0.0,REPUBLICAN,0.651140,NaN

In [19]:
df_21_compare.head()

,state,pop_migrated_2018,pop_migrated_2019,pop_migrated_2021,18-19_avg,winning_party,winner_percent_of_votes,pct_change_pre_post_election
0,Alabama,174.0,462.0,342.0,318.0,REPUBLICAN,0.620316,7.547170
1,Alaska,0.0,338.0,196.0,169.0,REPUBLICAN,0.528331,15.976331
2,Arizona,204.0,291.0,674.0,247.5,DEMOCRAT,0.493647,172.323232
3,Arkansas,0.0,0.0,37.0,0.0,REPUBLICAN,0.623957,inf
4,California,3803.0,3437.0,3945.0,3620.0,DEMOCRAT,0.634839,8.977901

Now going to make a dataframe to compare other years with 2009

In [20]:
df_09_compare = pd.DataFrame()

#creating column with state name

df_09_compare['state'] = df_2009['state'].copy()

#column with the 2009 migration numbers

df_09_compare['pop_migrated_2021'] = df_2009['pop_migrated'].copy()

copying over the election information

In [21]:
df_09_compare['winning_party'] = df_2009['winning_party'] 

df_09_compare['winner_percent_of_votes'] = df_2009['winner_percent_of_votes'] 

df_09_compare.head()

        state  pop_migrated_2021 winning_party  winner_percent_of_votes
0     Alabama                203    REPUBLICAN                 0.603169
1      Alaska                240    REPUBLICAN                 0.594245
2     Arizona                 32    REPUBLICAN                 0.536352
3    Arkansas                106    REPUBLICAN                 0.587159
4  California               2980      DEMOCRAT                 0.610126

New method to see anomolies.

Going to compare each year (all the states) to the average of all other years.

2017

In [22]:
#average people from each state to DC in all years except 2017 

df_17_compare['avg_all years'] = (df_2005['pop_migrated'] + df_2006['pop_migrated'] + df_2007['pop_migrated'] + df_2008['pop_migrated'] + df_2009['pop_migrated'] + df_2010['pop_migrated'] + df_2011['pop_migrated'] + df_2012['pop_migrated'] + df_2013['pop_migrated'] + df_2014['pop_migrated'] + df_2015['pop_migrated'] + df_2016['pop_migrated'] + df_2018['pop_migrated'] + df_2019['pop_migrated'] + df_2021['pop_migrated']) / 15

#compare to 2017
df_17_compare['anomaly'] = df_17_compare['pop_migrated_2017'] / df_17_compare['avg_all years']

2021

In [23]:
#average people from each state to DC in all years except 2021

df_21_compare['avg_all years'] = (df_2005['pop_migrated'] + df_2006['pop_migrated'] + df_2007['pop_migrated'] + df_2008['pop_migrated'] + df_2009['pop_migrated'] + df_2010['pop_migrated'] + df_2011['pop_migrated'] + df_2012['pop_migrated'] + df_2013['pop_migrated'] + df_2014['pop_migrated'] + df_2015['pop_migrated'] + df_2016['pop_migrated'] + df_2017['pop_migrated'] + df_2018['pop_migrated'] + df_2019['pop_migrated']) / 15

#compare to 2021

df_21_compare['anomaly'] = df_21_compare['pop_migrated_2021'] / df_21_compare['avg_all years']

2009

In [24]:
#average people from each state to DC in all years except 2009

df_09_compare['avg_all years'] = (df_2005['pop_migrated'] + df_2006['pop_migrated'] + df_2007['pop_migrated'] + df_2008['pop_migrated'] + df_2010['pop_migrated'] + df_2011['pop_migrated'] + df_2012['pop_migrated'] + df_2013['pop_migrated'] + df_2014['pop_migrated'] + df_2015['pop_migrated'] + df_2016['pop_migrated'] + df_2017['pop_migrated'] + df_2018['pop_migrated'] + df_2019['pop_migrated'] + df_2021['pop_migrated']) / 15

#compare to 2009

df_09_compare['anomaly'] = df_09_compare['pop_migrated_2021'] / df_09_compare['avg_all years']

Look at anomalies

In [25]:
df_09_compare.sort_values('anomaly', ascending=False)

,state,pop_migrated_2021,winning_party,winner_percent_of_votes,avg_all years,anomaly
47,Wyoming,54,REPUBLICAN,0.647138,23.000000,2.347826
18,Maine,390,DEMOCRAT,0.577057,176.333333,2.211720
24,Montana,66,REPUBLICAN,0.495325,34.333333,1.922330
26,Nevada,147,DEMOCRAT,0.551467,93.400000,1.573876
8,Florida,2275,DEMOCRAT,0.510333,1674.733333,1.358425
35,Oregon,285,DEMOCRAT,0.567488,222.400000,1.281475
43,Vermont,161,DEMOCRAT,0.674557,129.400000,1.244204
3,Arkansas,106,REPUBLICAN,0.587159,93.266667,1.136526
46,Wisconsin,344,DEMOCRAT,0.562178,311.333333,1.104925
39,South Dakota,58,REPUBLICAN,0.531590,54.800000,1.058394
5,Colorado,505,DEMOCRAT,0.536602,483.466667,1.044539
12,Illinois,1370,DEMOCRAT,0.619181,1322.400000,1.035995
10,Hawaii,145,DEMOCRAT,0.714529,145.466667,0.996792
15,Kansas,95,REPUBLICAN,0.566123,103.533333,0.917579
31,North Carolina,1276,DEMOCRAT,0.497037,1431.066667,0.891643
36,Pennsylvania,1705,DEMOCRAT,0.544855,1918.666667,0.888638
30,New York,3647,DEMOCRAT,0.601570,4126.266667,0.883850
7,Delaware,571,DEMOCRAT,0.619427,653.866667,0.873267
4,California,2980,DEMOCRAT,0.610126,3447.733333,0.864336
0,Alabama,203,REPUBLICAN,0.603169,240.733333,0.843257
9,Georgia,900,REPUBLICAN,0.522045,1078.733333,0.834312
1,Alaska,240,REPUBLICAN,0.594245,299.666667,0.800890
38,South Carolina,345,REPUBLICAN,0.538736,473.600000,0.728463
28,New Jersey,1232,DEMOCRAT,0.572721,1744.600000,0.706179
21,Minnesota,194,DEMOCRAT,0.540603,286.000000,0.678322
16,Kentucky,114,REPUBLICAN,0.573990,173.400000,0.657439
45,West Virginia,207,REPUBLICAN,0.557103,346.400000,0.597575
19,Massachusetts,1084,DEMOCRAT,0.613632,1902.200000,0.569866
34,Oklahoma,57,REPUBLICAN,0.656451,102.066667,0.558459
25,Nebraska,57,REPUBLICAN,0.565319,103.866667,0.548780
41,Texas,819,REPUBLICAN,0.554524,1493.466667,0.548389
27,New Hampshire,72,DEMOCRAT,0.541269,140.800000,0.511364
42,Utah,76,REPUBLICAN,0.625839,165.933333,0.458015
33,Ohio,373,DEMOCRAT,0.515043,829.133333,0.449867
44,Washington,190,DEMOCRAT,0.576529,477.466667,0.397934
20,Michigan,259,DEMOCRAT,0.574332,697.733333,0.371202
23,Missouri,102,REPUBLICAN,0.494261,306.133333,0.333188
6,Connecticut,288,DEMOCRAT,0.605888,1046.533333,0.275194
14,Iowa,33,DEMOCRAT,0.539280,128.200000,0.257410
37,Rhode Island,68,DEMOCRAT,0.628640,374.533333,0.181559
40,Tennessee,89,REPUBLICAN,0.568970,534.066667,0.166646
2,Arizona,32,REPUBLICAN,0.536352,407.600000,0.078508
22,Mississippi,0,REPUBLICAN,0.561762,121.133333,0.000000
17,Louisiana,0,REPUBLICAN,0.585627,330.000000,0.000000
29,New Mexico,0,DEMOCRAT,0.569075,150.866667,0.000000
13,Indiana,0,DEMOCRAT,0.499459,397.666667,0.000000
32,North Dakota,0,REPUBLICAN,0.532501,31.400000,0.000000
11,Idaho,0,REPUBLICAN,0.615171,43.800000,0.000000

In [26]:
df_17_compare.sort_values('anomaly', ascending=False)

,state,pop_migrated_2015,pop_migrated_2016,pop_migrated_2017,15_16_avg,pct_change_pre_post_election,winning_party,winner_percent_of_votes,avg_all years,anomaly
11,Idaho,5.0,0.0,161.0,2.5,6340.000000,REPUBLICAN,0.592614,33.066667,4.868952
43,Vermont,117.0,0.0,447.0,58.5,664.102564,DEMOCRAT,0.557227,110.333333,4.051360
42,Utah,177.0,249.0,384.0,213.0,80.281690,REPUBLICAN,0.455408,145.400000,2.640990
5,Colorado,433.0,531.0,1109.0,482.0,130.082988,DEMOCRAT,0.481570,443.200000,2.502256
40,Tennessee,873.0,452.0,1057.0,662.5,59.547170,REPUBLICAN,0.607220,469.533333,2.251171
0,Alabama,359.0,140.0,494.0,249.5,97.995992,REPUBLICAN,0.620831,221.333333,2.231928
12,Illinois,785.0,2418.0,2726.0,1601.5,70.215423,DEMOCRAT,0.558254,1232.000000,2.212662
41,Texas,1314.0,2213.0,2858.0,1763.5,62.064077,REPUBLICAN,0.522347,1357.533333,2.105289
13,Indiana,748.0,957.0,710.0,852.5,-16.715543,REPUBLICAN,0.569400,350.333333,2.026641
16,Kentucky,275.0,233.0,285.0,254.0,12.204724,REPUBLICAN,0.625196,162.000000,1.759259
23,Missouri,141.0,566.0,466.0,353.5,31.824611,REPUBLICAN,0.567723,281.866667,1.653264
21,Minnesota,545.0,542.0,436.0,543.5,-19.779209,DEMOCRAT,0.464450,269.866667,1.615613
28,New Jersey,1804.0,1494.0,2590.0,1649.0,57.064888,DEMOCRAT,0.554531,1654.066667,1.565838
17,Louisiana,392.0,197.0,461.0,294.5,56.536503,REPUBLICAN,0.580887,299.266667,1.540432
29,New Mexico,40.0,1.0,206.0,20.5,904.878049,DEMOCRAT,0.482556,137.133333,1.502188
19,Massachusetts,2876.0,1974.0,2669.0,2425.0,10.061856,DEMOCRAT,0.590501,1796.533333,1.485639
2,Arizona,367.0,744.0,549.0,555.5,-1.170117,REPUBLICAN,0.486716,373.133333,1.471324
9,Georgia,1013.0,1105.0,1507.0,1059.0,42.304060,REPUBLICAN,0.507713,1038.266667,1.451458
22,Mississippi,338.0,224.0,157.0,281.0,-44.128114,REPUBLICAN,0.579410,110.666667,1.418675
26,Nevada,68.0,356.0,128.0,212.0,-39.622642,DEMOCRAT,0.479178,94.666667,1.352113
31,North Carolina,1501.0,1367.0,1867.0,1434.0,30.195258,REPUBLICAN,0.498281,1391.666667,1.341557
33,Ohio,1027.0,659.0,1026.0,843.0,21.708185,REPUBLICAN,0.516877,785.600000,1.306008
30,New York,5133.0,4762.0,5238.0,4947.5,5.871652,DEMOCRAT,0.561361,4020.200000,1.302920
20,Michigan,1308.0,922.0,808.0,1115.0,-27.533632,REPUBLICAN,0.474976,661.133333,1.222144
6,Connecticut,1292.0,1225.0,1149.0,1258.5,-8.700834,DEMOCRAT,0.545663,989.133333,1.161623
3,Arkansas,203.0,0.0,105.0,101.5,3.448276,REPUBLICAN,0.605741,93.333333,1.125000
4,California,4119.0,3908.0,3763.0,4013.5,-6.241435,DEMOCRAT,0.617264,3395.533333,1.108221
36,Pennsylvania,1999.0,2468.0,1824.0,2233.5,-18.334453,REPUBLICAN,0.485779,1910.733333,0.954607
37,Rhode Island,234.0,268.0,296.0,251.0,17.928287,DEMOCRAT,0.544066,359.333333,0.823748
8,Florida,2731.0,2717.0,1182.0,2724.0,-56.607930,REPUBLICAN,0.490219,1747.600000,0.676356
27,New Hampshire,47.0,168.0,88.0,107.5,-18.139535,DEMOCRAT,0.468263,139.733333,0.629771
18,Maine,258.0,118.0,122.0,188.0,-35.106383,DEMOCRAT,0.463452,194.200000,0.628218
7,Delaware,252.0,278.0,375.0,265.0,41.509434,DEMOCRAT,0.533533,666.933333,0.562275
38,South Carolina,1806.0,382.0,235.0,1094.0,-78.519196,REPUBLICAN,0.549393,480.933333,0.488633
44,Washington,134.0,418.0,206.0,276.0,-25.362319,DEMOCRAT,0.525387,476.400000,0.432410
46,Wisconsin,514.0,242.0,115.0,378.0,-69.576720,REPUBLICAN,0.472182,326.600000,0.352113
10,Hawaii,52.0,103.0,29.0,77.5,-62.580645,DEMOCRAT,0.609808,153.200000,0.189295
32,North Dakota,0.0,83.0,5.0,41.5,-87.951807,REPUBLICAN,0.629556,31.066667,0.160944
35,Oregon,157.0,125.0,37.0,141.0,-73.758865,DEMOCRAT,0.500719,238.933333,0.154855
14,Iowa,135.0,218.0,17.0,176.5,-90.368272,REPUBLICAN,0.511621,129.266667,0.131511
45,West Virginia,478.0,296.0,0.0,387.0,-100.000000,REPUBLICAN,0.686306,360.200000,0.000000
24,Montana,0.0,17.0,0.0,8.5,-100.000000,REPUBLICAN,0.564662,38.733333,0.000000
39,South Dakota,9.0,0.0,0.0,4.5,-100.000000,REPUBLICAN,0.615308,58.666667,0.000000
34,Oklahoma,150.0,122.0,0.0,136.0,-100.000000,REPUBLICAN,0.653229,105.866667,0.000000
25,Nebraska,674.0,190.0,0.0,432.0,-100.000000,REPUBLICAN,0.587474,107.666667,0.000000
1,Alaska,235.0,77.0,0.0,156.0,-100.000000,REPUBLICAN,0.512815,315.666667,0.000000
15,Kansas,33.0,0.0,0.0,16.5,-100.000000,REPUBLICAN,0.566546,109.866667,0.000000
47,Wyoming,0.0,0.0,0.0,0.0,NaN,REPUBLICAN,0.673984,26.600000,0.000000
Total,NaN,37151.0,35529.0,37887.0,36340.0,7259.628037,NaN,26.348198,NaN,NaN

Export

In [27]:
df_17_compare.to_csv('df_17_compare.csv')
df_21_compare.to_csv('df_21_compare.csv')
df_09_compare.to_csv('df_09_compare.csv')

Build condensed versions of just the anomolies for datawrapper charts -- all I want is the anomaly for 2009, for 2017, and for 2021 with the state names as irst column

In [28]:
df_anomaly_compare_2017 = pd.DataFrame()
df_anomaly_compare_2021 = pd.DataFrame()
df_anomaly_compare_2009 = pd.DataFrame()


df_anomaly_compare_2017['state'] = df_17_compare['state']
df_anomaly_compare_2017['2017_anomaly'] = df_17_compare['anomaly']
df_anomaly_compare_2017['winning_party'] = df_17_compare['winning_party']

df_anomaly_compare_2021['state'] = df_21_compare['state']
df_anomaly_compare_2021['2021_anomaly'] = df_21_compare['anomaly']
df_anomaly_compare_2021['winning_party'] = df_21_compare['winning_party']

df_anomaly_compare_2009['state'] = df_09_compare['state']
df_anomaly_compare_2009['2009_anomaly'] = df_09_compare['anomaly']
df_anomaly_compare_2009['winning_party'] = df_09_compare['winning_party']

In [29]:
df_anomaly_compare_2017.sort_values('2017_anomaly', ascending=False).head(15)

         state  2017_anomaly winning_party
11       Idaho      4.868952    REPUBLICAN
43     Vermont      4.051360      DEMOCRAT
42        Utah      2.640990    REPUBLICAN
5     Colorado      2.502256      DEMOCRAT
40   Tennessee      2.251171    REPUBLICAN
0      Alabama      2.231928    REPUBLICAN
12    Illinois      2.212662      DEMOCRAT
41       Texas      2.105289    REPUBLICAN
13     Indiana      2.026641    REPUBLICAN
16    Kentucky      1.759259    REPUBLICAN
23    Missouri      1.653264    REPUBLICAN
21   Minnesota      1.615613      DEMOCRAT
28  New Jersey      1.565838      DEMOCRAT
17   Louisiana      1.540432    REPUBLICAN
29  New Mexico      1.502188      DEMOCRAT

In [30]:
df_anomaly_compare_2017.sort_values('2017_anomaly', ascending=False).head(15)

         state  2017_anomaly winning_party
11       Idaho      4.868952    REPUBLICAN
43     Vermont      4.051360      DEMOCRAT
42        Utah      2.640990    REPUBLICAN
5     Colorado      2.502256      DEMOCRAT
40   Tennessee      2.251171    REPUBLICAN
0      Alabama      2.231928    REPUBLICAN
12    Illinois      2.212662      DEMOCRAT
41       Texas      2.105289    REPUBLICAN
13     Indiana      2.026641    REPUBLICAN
16    Kentucky      1.759259    REPUBLICAN
23    Missouri      1.653264    REPUBLICAN
21   Minnesota      1.615613      DEMOCRAT
28  New Jersey      1.565838      DEMOCRAT
17   Louisiana      1.540432    REPUBLICAN
29  New Mexico      1.502188      DEMOCRAT

Only save top 15

In [33]:

df_anomaly_compare_2017 = df_anomaly_compare_2017.sort_values('2017_anomaly', ascending=False).head(15) # all rows over 1.5x the avg
df_anomaly_compare_2021 = df_anomaly_compare_2021.sort_values('2021_anomaly', ascending=False).head(15) # all rows over 1.5x the avg
df_anomaly_compare_2009 = df_anomaly_compare_2009.sort_values('2009_anomaly', ascending=False).head(9) # all rows over 1.1x the avg

df_anomaly_compare_2009

        state  2009_anomaly winning_party
47    Wyoming      2.347826    REPUBLICAN
18      Maine      2.211720      DEMOCRAT
24    Montana      1.922330    REPUBLICAN
26     Nevada      1.573876      DEMOCRAT
8     Florida      1.358425      DEMOCRAT
35     Oregon      1.281475      DEMOCRAT
43    Vermont      1.244204      DEMOCRAT
3    Arkansas      1.136526    REPUBLICAN
46  Wisconsin      1.104925      DEMOCRAT

And export

In [34]:
df_anomaly_compare_2017.to_csv('df_anomaly_compare_2017.csv')
df_anomaly_compare_2021.to_csv('df_anomaly_compare_2021.csv')
df_anomaly_compare_2009.to_csv('df_anomaly_compare_2009.csv')

Make some maps of the anomolies for 2017 and 2021

In [ ]:
import numpy as np
import matplotlib.colors as mcolors

cleaning for mapping

In [ ]:
df_2017_formap = df_17_compare.sort_values('anomaly', ascending=False).head(10) # all rows over 1.5x the avg
df_2021_formap = df_21_compare.sort_values('anomaly', ascending=False).head(10) # all rows over 1.5x the avg
df_2009_formap = df_09_compare.sort_values('anomaly', ascending=False).head(10) # all rows over 1.1x the avg

In [ ]:
us_state_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC"
}

for i in range(len(df_2017_formap)):
    df_2017_formap["state_code"] = df_2017_formap["state"].map(us_state_abbrev)
for i in range(len(df_2021_formap)):
    df_2021_formap["state_code"] = df_2021_formap["state"].map(us_state_abbrev)
for i in range(len(df_2009_formap)):
    df_2009_formap["state_code"] = df_2009_formap["state"].map(us_state_abbrev)

Making new column for shading on map

In [ ]:
for i in range(len(df_2017_formap)):
    df_2017_formap["percent_won_and_party"] = np.where(
        df_2017_formap["winning_party"] == "DEMOCRAT",
        df_2017_formap["winner_percent_of_votes"],    # keep as-is (positive)
        df_2017_formap["winner_percent_of_votes"] * -1    # flip sign to negative
    )

for i in range(len(df_2021_formap)):
    df_2021_formap["percent_won_and_party"] = np.where(
        df_2021_formap["winning_party"] == "DEMOCRAT",
        df_2021_formap["winner_percent_of_votes"],    # keep as-is (positive)
        df_2021_formap["winner_percent_of_votes"] * -1   # flip sign to negative
    )

for i in range(len(df_2009_formap)):
    df_2009_formap["percent_won_and_party"] = np.where(
        df_2009_formap["winning_party"] == "DEMOCRAT",
        df_2009_formap["winner_percent_of_votes"],    # keep as-is (positive)
        df_2009_formap["winner_percent_of_votes"] * -1   # flip sign to negative
    )

In [ ]:
df_2021_formap.head(5)

df_2017_formap.head(5)

df_2009_formap.head(5)

In [ ]:
fig_2021_anomaly = px.choropleth(
    df_2021_formap,
    locations="state_code",
    locationmode="USA-states",
    color="percent_won_and_party",
    scope="usa",
    color_continuous_scale=["#AA0000", '#C88FE4',"#0645B4"],
    range_color=[-0.8, 0.8]
)

fig_2021_anomaly.show()

In [ ]:
fig_2017_anomaly = px.choropleth(
    df_2017_formap,
    locations="state_code",
    locationmode="USA-states",
    color="percent_won_and_party",
    scope="usa",
    color_continuous_scale=["#AA0000", '#C88FE4',"#0645B4"],
    range_color=[-0.8, 0.8]
)

fig_2017_anomaly.show()

In [ ]:
fig_2009_anomaly = px.choropleth(
    df_2009_formap,
    locations="state_code",
    locationmode="USA-states",
    color="percent_won_and_party",
    scope="usa",
    color_continuous_scale=["#AA0000", '#C88FE4',"#0645B4"],
    range_color=[-0.8, 0.8]
)

fig_2009_anomaly.show()

Save new maps

In [ ]:
fig_2017_anomaly.write_image("2017_anomaly_map.svg", engine="kaleido")
fig_2021_anomaly.write_image("2021_anomaly_map.svg", engine="kaleido")

In [ ]:
fig_2009_anomaly.write_image("2009_anomaly_map.svg", engine="kaleido")

Save new anomaly lists