I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2010.xls')

In [3]:
df.shape

(84, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,NaN,...,52,Alabama,13166,2247,228,265,181,160,12757,2241
11,Alaska,702974,1600,565031,7596,95878,7984,36326,3708,477,...,131,Alaska,5739,1602,19,30,1374,1188,4346,1205
12,Arizona,6332786,4439,5069002,35057,1001991,32027,222725,11873,416,...,393,Arizona,39068,6046,599,771,223,286,38246,5951
13,Arkansas,2888304,2453,2387806,18627,412997,17485,79127,7901,1405,...,513,Arkansas,8374,2099,87,146,0,273,8287,2123
14,California,36907897,10889,30790221,71574,5413287,66460,444749,18415,3364,...,664,California,259640,13144,1223,1128,5123,2453,253294,13154
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,4988190,3936,4042039,25546,725413,23003,186366,9897,954,...,1439,Colorado,34372,4253,874,880,125,181,33373,4235
17,Connecticut,3541146,2779,3100742,16358,342904,15404,77333,6651,896,...,78,Connecticut,20167,2860,2027,1233,0,281,18140,2685
18,Delaware,889812,1573,764640,9145,90001,8498,30759,4030,128,...,265,Delaware,4412,1791,954,1095,431,400,3027,1274
19,District of Columbia,596747,1124,474676,8281,63766,6163,51244,4828,360,...,292,District of Columbia,7061,1472,0,292,62,103,6999,1448
20,Florida,18647600,7733,15554008,45602,2459530,38387,482889,22701,15830,...,258,Florida,151173,10799,12968,4149,1131,800,137074,9549
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,9587237,5924,8015409,37393,1278548,36794,249459,15858,13840,...,118,Georgia,43821,5631,1010,742,376,365,42435,5734
23,Hawaii,1346274,1690,1140572,10422,134315,9295,53581,6065,749,...,33,Hawaii,17806,4654,0,275,805,581,17001,4673

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,NaN,...,52,Alabama,13166,2247,228,265,181,160,12757,2241
11,Alaska,702974,1600,565031,7596,95878,7984,36326,3708,477,...,131,Alaska,5739,1602,19,30,1374,1188,4346,1205
12,Arizona,6332786,4439,5069002,35057,1001991,32027,222725,11873,416,...,393,Arizona,39068,6046,599,771,223,286,38246,5951
13,Arkansas,2888304,2453,2387806,18627,412997,17485,79127,7901,1405,...,513,Arkansas,8374,2099,87,146,0,273,8287,2123
14,California,36907897,10889,30790221,71574,5413287,66460,444749,18415,3364,...,664,California,259640,13144,1223,1128,5123,2453,253294,13154
16,Colorado,4988190,3936,4042039,25546,725413,23003,186366,9897,954,...,1439,Colorado,34372,4253,874,880,125,181,33373,4235
17,Connecticut,3541146,2779,3100742,16358,342904,15404,77333,6651,896,...,78,Connecticut,20167,2860,2027,1233,0,281,18140,2685
18,Delaware,889812,1573,764640,9145,90001,8498,30759,4030,128,...,265,Delaware,4412,1791,954,1095,431,400,3027,1274
19,District of Columbia,596747,1124,474676,8281,63766,6163,51244,4828,360,...,292,District of Columbia,7061,1472,0,292,62,103,6999,1448
20,Florida,18647600,7733,15554008,45602,2459530,38387,482889,22701,15830,...,258,Florida,151173,10799,12968,4149,1131,800,137074,9549
22,Georgia,9587237,5924,8015409,37393,1278548,36794,249459,15858,13840,...,118,Georgia,43821,5631,1010,742,376,365,42435,5734
23,Hawaii,1346274,1690,1140572,10422,134315,9295,53581,6065,749,...,33,Hawaii,17806,4654,0,275,805,581,17001,4673
24,Idaho,1550967,1954,1279856,12606,209272,10887,55638,6079,376,...,723,Idaho,6201,1618,233,374,36,62,5932,1578
25,Illinois,12680126,5467,11009852,32636,1404525,28126,203959,11573,1397,...,432,Illinois,61790,4951,2055,820,0,267,59735,4897
26,Indiana,6414862,4257,5431015,24897,833086,22796,127353,8463,1502,...,403,Indiana,23408,3198,572,457,75,124,22761,3113
28,Iowa,3013053,2381,2553210,15158,375650,12448,72557,5707,330,...,119,Iowa,11636,2469,149,176,0,228,11487,2434

Rename columns to be clearer, including manually renaming certain columns and stripping 'Unnamed: ' from the rest

In [9]:
print(df.columns.tolist())

['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129']

In [10]:
#for the first column

df.rename(columns={'Dataset: 2007-2009 American Community Survey 3-Year Estimates': '0'}, inplace=True)

#renaming all of these weird long composite names at the sart of every group of 11

df.rename(columns= {'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 47.': '11'}, inplace=True)
for i in range(1, 10):
    number = (i * 11) + 11
    df.rename(columns={f'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48..{i}':f'{number}'}, inplace=True)

#for the rest of the columns, just trimming:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

print(df.columns.tolist())

['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129']

In [11]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [12]:
df.iloc[3:] = df.iloc[3:].fillna('0')

In [13]:
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",1,2,3,4,5,6,7,8,9,...,120,121,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,0,...,52,Alabama,13166,2247,228,265,181,160,12757,2241

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [14]:
#For the rest of the columns:
#first, fill in blanks

df_filledin = df.ffill(axis=1)

df_filledin.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",1,2,3,4,5,6,7,8,9,...,120,121,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,Population 1 year and over,Same house 1 year ago,Same house 1 year ago,Same state of residence 1 year ago,Same state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,...,Different state of residence 1 year ago (cont.),Current residence in --,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,Total,Alabama,...,Wyoming,Wyoming,Total,Total,Puerto Rico,Puerto Rico,U.S. Island Area,U.S. Island Area,Foreign Country,Foreign Country
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,0,...,52,Alabama,13166,2247,228,265,181,160,12757,2241

In [15]:
#then pull the info I need to name each column

for i in range(1, 105):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

In [16]:
df_filledin.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Population 1 year and over: nan (Estimate),Population 1 year and over: nan (MOE),Same house 1 year ago: nan (Estimate),Same house 1 year ago: nan (MOE),Same state of residence 1 year ago: nan (Estimate),Same state of residence 1 year ago: nan (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,120,121,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,Population 1 year and over,Same house 1 year ago,Same house 1 year ago,Same state of residence 1 year ago,Same state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,...,Different state of residence 1 year ago (cont.),Current residence in --,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,Total,Alabama,...,Wyoming,Wyoming,Total,Total,Puerto Rico,Puerto Rico,U.S. Island Area,U.S. Island Area,Foreign Country,Foreign Country
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,0,...,52,Alabama,13166,2247,228,265,181,160,12757,2241

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [17]:
df = df_filledin.iloc[3:]

df.tail(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Population 1 year and over: nan (Estimate),Population 1 year and over: nan (MOE),Same house 1 year ago: nan (Estimate),Same house 1 year ago: nan (MOE),Same state of residence 1 year ago: nan (Estimate),Same state of residence 1 year ago: nan (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,120,121,122,123,124,125,126,127,128,129
53,New York,19171916,7371,16976205,41292,1779540,36331,269427,14924,1310,...,148,New York,146744,10086,6740,2049,199,187,139805,10405
54,North Carolina,9443000,5070,7982017,29580,1141001,25307,263256,13976,3044,...,819,North Carolina,56726,6204,1950,1463,424,371,54352,5718
55,North Dakota,665654,1209,556222,6833,75720,5430,30100,3890,109,...,206,North Dakota,3612,1401,0,211,44,78,3568,1401
56,Ohio,11405101,4931,9745227,23258,1453401,23324,172633,10673,1289,...,187,Ohio,33840,3757,2140,1360,159,176,31541,3544
57,Oklahoma,3716264,3181,3065497,21363,528824,18463,106511,8108,1612,...,1012,Oklahoma,15432,3309,209,222,364,373,14859,3345
59,Oregon,3794008,3282,3110896,20156,545841,17758,116700,7898,400,...,336,Oregon,20571,3300,821,847,0,277,19750,3228
60,Pennsylvania,12577555,4619,11053022,29699,1239199,26490,235580,12249,369,...,936,Pennsylvania,49754,5788,6275,2169,147,176,43332,5190
61,Rhode Island,1042240,1435,900283,9035,99603,7344,32059,4070,136,...,291,Rhode Island,10295,3236,276,353,0,291,10019,3178
62,South Carolina,4577399,3786,3870879,23788,537961,21768,152441,10548,1741,...,524,South Carolina,16118,2669,269,229,28,47,15821,2663
63,South Dakota,805616,1372,680993,6027,96805,5853,25777,3187,325,...,549,South Dakota,2041,830,0,223,0,223,2041,830
65,Tennessee,6282706,4009,5299496,24505,801355,21988,159778,11597,8897,...,287,Tennessee,22077,2865,0,287,0,287,22077,2865
66,Texas,24899075,8102,20500156,52416,3740344,51566,486558,20955,8636,...,1022,Texas,172017,11236,4180,2074,843,622,166994,10904
67,Utah,2724064,2775,2240636,18397,388410,17535,77780,6769,93,...,1168,Utah,17238,3167,383,446,108,129,16747,3143
68,Vermont,619363,779,534975,5691,59032,4857,22529,2945,0,...,86,Vermont,2827,845,0,211,0,211,2827,845
69,Virginia,7930773,4735,6752310,28251,870491,21599,259507,12319,2671,...,429,Virginia,48465,5536,1306,872,217,207,46942,5312
71,Washington,6661321,4568,5464985,26926,946923,24983,191784,12094,1322,...,524,Washington,57629,6310,0,277,2715,1276,54914,5988
72,West Virginia,1833535,1890,1625125,9824,166168,9198,39609,4590,41,...,269,West Virginia,2633,899,182,232,0,269,2451,855
73,Wisconsin,5623196,3124,4824045,20412,691592,17462,93065,6949,552,...,104,Wisconsin,14494,2323,521,478,0,218,13973,2235
74,Wyoming,556954,1133,444614,8794,82255,8679,28046,4226,172,...,0,Wyoming,2039,774,0,269,0,269,2039,774
76,Puerto Rico,3676493,2933,3392179,13112,247593,12844,31732,4381,629,...,285,Puerto Rico,4989,1988,N/A2,N/A2,102,109,4887,1974


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [18]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

KeyError: '0'

In [ ]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [ ]:

df = df.iloc[1:]

In [ ]:
df

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence interval
Residence 1 year ago in --: Alabama (Estimate),579815,1390,392,443,2889,1774,1963,365,203,9179,...,336,64,2890,1179,988,574,0,0,0,0
Residence 1 year ago in --: Alabama (MOE),18712.400933,1676.700576,343.453191,320.686833,1476.395427,1152.918233,2175.873686,326.625924,167.538223,2237.912952,...,280.122055,113.204808,1110.452069,748.913147,719.960988,505.026922,265,0,0,0
Residence 1 year ago in --: Alaska (Estimate),982,107051,2249,968,5332,1215,504,143,240,5863,...,783,0,1983,3199,1272,603,454,0,0,0
Residence 1 year ago in --: Alaska (MOE),787.647232,7517.989701,1200.924924,1088.884387,2553.474664,707.613151,496.091064,225.493441,279.343814,2472.21916,...,451.213035,211,1198.861283,1210.109956,1029.921678,402.239334,521.644518,0,0,0
Residence 1 year ago in --: Arizona (Estimate),1183,1285,1055904,1365,34040,9378,629,494,32,6104,...,10309,46,5651,9507,931,2323,759,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),215.308758,244,725.532933,56.614056,627.759244,582.64091,277,65.888359,296.950979,1982.433583,...,156.853575,211,1724.882946,828.809379,11670.392492,288.466592,265,0,0,0
Residence 1 year ago in --: Wisconsin (Estimate),1026,1048,3795,459,6958,2982,74,0,344,6214,...,656,173,1469,1518,42,699209,286,0,0,0
Residence 1 year ago in --: Wisconsin (MOE),622.138043,945.841456,1486.736039,393.024032,2525.644363,1256.931464,99.368076,263,307.378275,1727.93626,...,404.232769,215.107889,926.971512,723.123552,61.08357,19237.757929,441.463112,0,0,0
Residence 1 year ago in --: Wyoming (Estimate),258,470,1260,115,1114,5630,205,0,54,423,...,1297,240,1149,1517,0,222,56319,0,0,0
Residence 1 year ago in --: Wyoming (MOE),248.900514,811.649651,861.211389,139.515009,685.405294,2795.754062,331.85913,263,89.541507,391.079852,...,618.601479,417.371707,836.482338,854.45471,269,257.278473,5487.157153,0,0,0

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [ ]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [ ]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [ ]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Residence 1 year ago in --: Alabama (Estimate)                       203
Residence 1 year ago in --: Alaska (Estimate)                        240
Residence 1 year ago in --: Arizona (Estimate)                        32
Residence 1 year ago in --: Arkansas (Estimate)                      106
Residence 1 year ago in --: California (Estimate)                   2980
Residence 1 year ago in --: Colorado (Estimate)                      505
Residence 1 year ago in --: Connecticut (Estimate)                   288
Residence 1 year ago in --: Delaware (Estimate)                      571
Residence 1 year ago in --: District of Columbi...                 47156
Residence 1 year ago in --: Florida (Estimate)                      2275
Residence 1 year ago in --: Georgia (Estimate)                       900
Residence 1 year ago in --: Hawaii (Estimate)                        145
Residence 1 year ago in --: Idaho (Estimate)                           0
Residence 1 year ago in --: Illinois (Estimate)                     1370
Residence 1 year ago in --: Indiana (Estimate)                         0
Residence 1 year ago in --: Iowa (Estimate)                           33
Residence 1 year ago in --: Kansas (Estimate)                         95
Residence 1 year ago in --: Kentucky (Estimate)                      114
Residence 1 year ago in --: Louisiana (Estimate)                       0
Residence 1 year ago in --: Maine (Estimate)                         390
Residence 1 year ago in --: Maryland (Estimate)                     9960
Residence 1 year ago in --: Massachusetts (Esti...                  1084
Residence 1 year ago in --: Michigan (Estimate)                      259
Residence 1 year ago in --: Minnesota (Estimate)                     194
Residence 1 year ago in --: Mississippi (Estimate)                     0
Residence 1 year ago in --: Missouri (Estimate)                      102
Residence 1 year ago in --: Montana (Estimate)                        66
Residence 1 year ago in --: Nebraska (Estimate)                       57
Residence 1 year ago in --: Nevada (Estimate)                        147
Residence 1 year ago in --: New Hampshire (Esti...                    72
Residence 1 year ago in --: New Jersey (Estimate)                   1232
Residence 1 year ago in --: New Mexico (Estimate)                      0
Residence 1 year ago in --: New York (Estimate)                     3647
Residence 1 year ago in --: North Carolina (Est...                  1276
Residence 1 year ago in --: North Dakota (Estim...                     0
Residence 1 year ago in --: Ohio (Estimate)                          373
Residence 1 year ago in --: Oklahoma (Estimate)                       57
Residence 1 year ago in --: Oregon (Estimate)                        285
Residence 1 year ago in --: Pennsylvania (Estim...                  1705
Residence 1 year ago in --: Puerto Rico (Estimate)                   147
Residence 1 year ago in --: Rhode Island (Estim...                    68
Residence 1 year ago in --: South Carolina (Est...                   345
Residence 1 year ago in --: South Dakota (Estim...                    58
Residence 1 year ago in --: Tennessee (Estimate)                      89
Residence 1 year ago in --: Texas (Estimate)                         819
Residence 1 year ago in --: Utah (Estimate)                           76
Residence 1 year ago in --: Vermont (Estimate)                       161
Residence 1 year ago in --: Virginia (Estimate)                     5586
Residence 1 year ago in --: Washington (Estimate)                    190
Residence 1 year ago in --: West Virginia (Esti...                   207
Residence 1 year ago in --: Wisconsin (Estimate)                     344
Residence 1 year ago in --: Wyoming (Estimate)                        54

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [ ]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

For 2021 and 2017, we needed to cut off the top columns that arent for specific states, but that's not relevent here because of different structure for 2009 and 2005

In [ ]:

# df_estimates = df_estimates[4:]
# df_moes = df_moes[4:]

In [ ]:
df_moes.head()

0          District of Columbia
0
Alabama               167.538223
Alaska                279.343814
Arizona                54.042694
Arkansas              126.777643
California            909.759736

In [ ]:
df_estimates.head()

0          District of Columbia
0
Alabama                      203
Alaska                       240
Arizona                       32
Arkansas                     106
California                  2980

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [ ]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Now I'm adding a state polulation column to my newly formatted table

In [ ]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [ ]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [ ]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [ ]:
df

0                    pop_migrated      MOE +/- state_population
0
Alabama                       203   167.538223          5024279
Alaska                        240   279.343814           733391
Arizona                        32    54.042694          7151502
Arkansas                      106   126.777643          3011524
California                   2980   909.759736         39538223
Colorado                      505   508.123432          5773714
Connecticut                   288   283.733651          3605944
Delaware                      571   530.941684           989948
District of Columbia        47156  5403.420082           689545
Florida                      2275  1048.698338         21538187
Georgia                       900   542.662537         10711908
Hawaii                        145   169.997837          1455271
Idaho                           0          296          1839106
Illinois                     1370   515.900692         12812508
Indiana                         0          296          6785528
Iowa                           33    55.794365          3190369
Kansas                         95   114.222716          2937880
Kentucky                      114   192.053662          4505836
Louisiana                       0          296          4657757
Maine                         390    475.57445          1362359
Maryland                     9960  2471.428532          6177224
Massachusetts                1084     476.7802          7029917
Michigan                      259   268.477658         10077331
Minnesota                     194   177.058481          5706494
Mississippi                     0          296          2961279
Missouri                      102   114.679627          6154913
Montana                        66    89.439453          1084225
Nebraska                       57    94.296675          1961504
Nevada                        147   150.257041          3104614
New Hampshire                  72    99.348331          1377529
New Jersey                   1232   806.814143          9288994
New Mexico                      0          296          2117522
New York                     3647  1011.675134         20201249
North Carolina               1276   847.399521         10439388
North Dakota                    0          296           779094
Ohio                          373   288.891929         11799448
Oklahoma                       57    93.579393          3959353
Oregon                        285   252.775006          4237256
Pennsylvania                 1705   704.236393         13002700
Puerto Rico                   147   168.121897          3285874
Rhode Island                   68   112.193342          1097379
South Carolina                345   385.515147          5118425
South Dakota                   58     95.99389           886667
Tennessee                      89   142.806466          6910840
Texas                         819   571.018219         29145505
Utah                           76   125.954804          3271616
Vermont                       161   152.643237           643077
Virginia                     5586  1517.567199          8631393
Washington                    190   187.172883          7705281
West Virginia                 207   296.950979          1793716
Wisconsin                     344   307.378275          5893718
Wyoming                        54    89.541507           576851

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [ ]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [ ]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Need to manually drop DC here because its input differently than in the other years -- here, the D.C. figure for folks that lived in D.C. both this year and last year is not n/a or 0, but rather a substantial number that represents the number of folks that did NOT move since last year's census

In [ ]:
df = df.drop(['District of Columbia'])

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [ ]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,203,167.538223,5024279,0.000040,0.000033
1,Alaska,240,279.343814,733391,0.000327,0.000381
2,Arizona,32,54.042694,7151502,0.000004,0.000008
3,Arkansas,106,126.777643,3011524,0.000035,0.000042
4,California,2980,909.759736,39538223,0.000075,0.000023

Looking at states with most people coming to DC

In [ ]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
19,Maryland,9960,2471.428532,6177224,0.001612,0.000400
46,Virginia,5586,1517.567199,8631393,0.000647,0.000176
7,Delaware,571,530.941684,989948,0.000577,0.000536
1,Alaska,240,279.343814,733391,0.000327,0.000381
18,Maine,390,475.57445,1362359,0.000286,0.000349
45,Vermont,161,152.643237,643077,0.000250,0.000237
31,New York,3647,1011.675134,20201249,0.000181,0.000050
20,Massachusetts,1084,476.7802,7029917,0.000154,0.000068
29,New Jersey,1232,806.814143,9288994,0.000133,0.000087
37,Pennsylvania,1705,704.236393,13002700,0.000131,0.000054

To export, want to make a slice excluding all DMV states -- Maryland, Virginia

In [ ]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]

Now need to reset the index again to make numbers consecutive now that I've removed ceratin rows.

In [ ]:
df = df.reset_index(drop=True)

Now add in 2008 election winners for each state

First, read in file

In [ ]:
df_2008_election_winners = pd.read_csv('pres-election-results-2008.csv')

type(df_2008_election_winners)

pandas.DataFrame

Next, add winning party and percent of votes columns

In [ ]:
df_2008_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

df_2008_election_winners.head()

        state  year party_detailed  percent_total_votes
0     Alabama  2008     REPUBLICAN             0.603169
1      Alaska  2008     REPUBLICAN             0.594245
2     Arizona  2008     REPUBLICAN             0.536352
3    Arkansas  2008     REPUBLICAN             0.587159
4  California  2008       DEMOCRAT             0.610126

In [ ]:

df['winning_party'] = df_2008_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2008_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,203,167.538223,5024279,0.000040,0.000033,REPUBLICAN,0.603169
1,Alaska,240,279.343814,733391,0.000327,0.000381,REPUBLICAN,0.594245
2,Arizona,32,54.042694,7151502,0.000004,0.000008,REPUBLICAN,0.536352
3,Arkansas,106,126.777643,3011524,0.000035,0.000042,REPUBLICAN,0.587159
4,California,2980,909.759736,39538223,0.000075,0.000023,DEMOCRAT,0.610126

Check that indexes match

In [ ]:
df.index

RangeIndex(start=0, stop=48, step=1)

In [ ]:
df_2008_election_winners.index

RangeIndex(start=0, stop=48, step=1)

Save as csv file

In [ ]:
df.to_csv('DC-migration-2010.csv')

NameError: name 'df' is not defined