I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [2]:
import pandas as pd
import numpy as np

Read in the file

In [3]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2008.xls')

In [4]:
df.shape

(78, 115)

In [5]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112',
       'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [6]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,573316,20492,2912,1554,896,624,341,304,4962,...,1689,1750,968,119,142,Alabama,1399,1137,91,158

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [7]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112',
       'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

In [8]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,573316,20492,2912,1554,896,624,341,304,4962,...,1689,1750,968,119,142,Alabama,1399,1137,91,158
9,Alaska,1392,991,110205,8212,1904,1086,332,468,4951,...,712,3805,1404,34,59,Alaska,397,380,195,228
10,Arizona,1028,661,2983,1147,948400,31246,1289,730,51020,...,1298,11891,2803,356,274,Arizona,2792,1148,1701,955
11,Arkansas,1009,784,95,114,2872,1451,414632,17258,6451,...,1355,970,914,458,503,Arkansas,1468,820,154,189
12,California,2868,1167,5905,2598,37873,5688,4504,2438,4834704,...,3015,29680,4801,1372,970,California,4705,1437,1585,798
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Colorado,1243,1446,3330,1808,12096,3181,966,638,28890,...,1143,4926,1946,455,453,Colorado,3492,1465,5234,1627
15,Connecticut,139,161,1870,1338,977,817,0,275,2970,...,1585,1127,1107,85,76,Connecticut,1342,834,411,367
16,Delaware,89,155,235,286,180,185,0,263,1294,...,1274,550,584,92,145,Delaware,144,235,109,179
17,District of Columbia,103,140,230,272,509,476,35,60,1688,...,1362,296,302,424,233,District of Columbia,197,165,0,296
18,Florida,13116,3282,10734,4124,4501,1310,4368,1971,18241,...,4110,6198,2807,2179,822,Florida,5633,1987,495,429
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Georgia,20484,4348,2734,1543,4337,1984,2193,1229,14254,...,2631,2626,1268,1460,1521,Georgia,2623,1273,550,525
21,Hawaii,502,572,1050,1127,2669,2393,1322,1153,12820,...,2124,4254,1766,42,71,Hawaii,748,759,503,803
22,Idaho,80,136,1390,882,2109,1025,751,749,10492,...,317,9480,2038,0,259,Idaho,547,427,1960,1221
23,Illinois,2029,1207,1694,985,4746,1562,2131,829,20722,...,1964,3383,1445,578,338,Illinois,16722,3677,67,118

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [9]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
8,Alabama,573316,20492,2912,1554,896,624,341,304,4962,...,1689,1750,968,119,142,Alabama,1399,1137,91,158
9,Alaska,1392,991,110205,8212,1904,1086,332,468,4951,...,712,3805,1404,34,59,Alaska,397,380,195,228
10,Arizona,1028,661,2983,1147,948400,31246,1289,730,51020,...,1298,11891,2803,356,274,Arizona,2792,1148,1701,955
11,Arkansas,1009,784,95,114,2872,1451,414632,17258,6451,...,1355,970,914,458,503,Arkansas,1468,820,154,189
12,California,2868,1167,5905,2598,37873,5688,4504,2438,4834704,...,3015,29680,4801,1372,970,California,4705,1437,1585,798
14,Colorado,1243,1446,3330,1808,12096,3181,966,638,28890,...,1143,4926,1946,455,453,Colorado,3492,1465,5234,1627
15,Connecticut,139,161,1870,1338,977,817,0,275,2970,...,1585,1127,1107,85,76,Connecticut,1342,834,411,367
16,Delaware,89,155,235,286,180,185,0,263,1294,...,1274,550,584,92,145,Delaware,144,235,109,179
17,District of Columbia,103,140,230,272,509,476,35,60,1688,...,1362,296,302,424,233,District of Columbia,197,165,0,296
18,Florida,13116,3282,10734,4124,4501,1310,4368,1971,18241,...,4110,6198,2807,2179,822,Florida,5633,1987,495,429
20,Georgia,20484,4348,2734,1543,4337,1984,2193,1229,14254,...,2631,2626,1268,1460,1521,Georgia,2623,1273,550,525
21,Hawaii,502,572,1050,1127,2669,2393,1322,1153,12820,...,2124,4254,1766,42,71,Hawaii,748,759,503,803
22,Idaho,80,136,1390,882,2109,1025,751,749,10492,...,317,9480,2038,0,259,Idaho,547,427,1960,1221
23,Illinois,2029,1207,1694,985,4746,1562,2131,829,20722,...,1964,3383,1445,578,338,Illinois,16722,3677,67,118
24,Indiana,713,352,509,507,4590,1928,935,715,7951,...,1050,1644,802,1255,594,Indiana,3637,1391,0,265
26,Iowa,219,255,578,311,1749,852,3309,2503,3019,...,692,533,380,0,226,Iowa,2816,883,235,256
27,Kansas,1704,1502,283,291,2831,1665,1873,978,6118,...,1767,1966,928,205,278,Kansas,1210,619,380,459

Rename columns to be clearer, including manually renaming certain columns and stripping 'Unnamed: ' from the rest

In [10]:
print(df.columns.tolist())

['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114']

In [11]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.': '0'}, inplace=True)

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

print(df.columns.tolist())

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114']

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [12]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [13]:
#For the rest of the columns:
#first, fill in blanks

df_filledin = df.ffill(axis=1)

df_filledin.head()

,0,1,2,3,4,5,6,7,8,9,...,104,105,106,107,108,109,111,112,113,114
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,573316,20492,2912,1554,896,624,341,304,4962,...,2944,1689,1750,968,119,142,1399,1137,91,158
9,Alaska,1392,991,110205,8212,1904,1086,332,468,4951,...,862,712,3805,1404,34,59,397,380,195,228

In [14]:
#then pull the info I need to name each column

for i in range(1, 105):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

In [15]:
df_filledin.head()

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,573316,20492,2912,1554,896,624,341,304,4962,...,2944,1689,1750,968,119,142,1399,1137,91,158
9,Alaska,1392,991,110205,8212,1904,1086,332,468,4951,...,862,712,3805,1404,34,59,397,380,195,228

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [16]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
54,Ohio,2564,1300,2788,1663,3142,1195,416,403,6921,...,5764,2037,4055,2125,5581,1569,1239,650,126,152
55,Oklahoma,1732,1245,1485,917,3632,1600,7784,1957,8167,...,1364,656,2236,1123,737,773,446,377,855,637
56,Oregon,707,608,3003,1360,3344,1193,452,469,33497,...,1997,1060,18315,2633,104,173,1660,927,632,504
57,Pennsylvania,971,578,1426,833,2264,999,308,284,9368,...,11481,2154,1625,705,4188,1886,1071,711,109,140
58,Puerto Rico,200,319,0,289,0,289,0,289,779,...,407,348,354,563,0,289,633,497,0,289
60,Rhode Island,0,287,177,292,139,182,233,387,1478,...,1333,925,285,265,322,464,63,106,179,292
61,South Carolina,1837,692,679,558,759,403,860,638,4143,...,9358,2481,1349,929,411,329,920,489,0,287
62,South Dakota,267,317,66,102,1046,708,22,38,1051,...,224,203,742,469,51,83,583,539,185,144
63,Tennessee,6780,1882,1970,1865,1353,797,5096,1631,9008,...,7424,1843,822,569,2457,1813,2779,1682,261,277
64,Texas,6086,1718,7173,2388,16278,3086,13341,3083,73993,...,15143,3255,9796,2740,1895,1653,7548,2181,3167,2061
66,Utah,695,584,2160,1090,9075,3370,450,406,18607,...,1501,795,2930,1063,70,120,2574,1699,4524,1986
67,Vermont,0,211,252,180,200,293,0,211,1062,...,775,371,176,136,51,67,0,211,27,45
68,Virginia,4171,1539,866,749,4286,1904,1030,741,14469,...,925353,25033,5253,2174,8624,2608,2131,1138,375,443
69,Washington,1845,1227,5334,1916,10009,3271,830,589,41082,...,5699,1993,895624,22404,543,379,1895,1368,262,292
70,West Virginia,282,476,812,774,59,100,0,265,968,...,8166,2087,258,286,170344,9533,51,87,33,55
72,Wisconsin,432,297,1645,971,1328,768,1373,1946,4618,...,1381,655,1657,941,217,214,682608,20672,47,76
73,Wyoming,459,486,72,93,724,542,557,562,1709,...,0,261,526,389,0,261,179,158,65556,5755
74,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,...,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:
75,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,...,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia,*Incudes Puerto Rico and the District of Columbia
76,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [17]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence interval
0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Alabama (Estimate),573316,1392,1028,1009,2868,1243,139,89,103,13116,...,695,0,4171,1845,282,432,459,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Alabama (MOE),20492,991,661,784,1167,1446,161,155,140,3282,...,584,211,1539,1227,476,297,486,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Alaska (Estimate),2912,110205,2983,95,5905,3330,1870,235,230,10734,...,2160,252,866,5334,812,1645,72,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Alaska (MOE),1554,8212,1147,114,2598,1808,1338,286,272,4124,...,1090,180,749,1916,774,971,93,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),142,59,274,503,970,453,76,145,233,822,...,120,67,2608,379,9533,214,261,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Wisconsin (Estimate),1399,397,2792,1468,4705,3492,1342,144,197,5633,...,2574,0,2131,1895,51,682608,179,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Wisconsin (MOE),1137,380,1148,820,1437,1465,834,235,165,1987,...,1699,211,1138,1368,87,20672,158,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Wyoming (Estimate),91,195,1701,154,1585,5234,411,109,0,495,...,4524,27,375,262,33,47,65556,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Wyoming (MOE),158,228,955,189,798,1627,367,179,296,429,...,1986,45,443,292,55,76,5755,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...

In [18]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [19]:

df = df.iloc[1:]

In [20]:
df

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence interval
Residence 1 year ago in --: Alabama (Estimate),573316,1392,1028,1009,2868,1243,139,89,103,13116,...,695,0,4171,1845,282,432,459,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Alabama (MOE),20492,991,661,784,1167,1446,161,155,140,3282,...,584,211,1539,1227,476,297,486,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Alaska (Estimate),2912,110205,2983,95,5905,3330,1870,235,230,10734,...,2160,252,866,5334,812,1645,72,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Alaska (MOE),1554,8212,1147,114,2598,1808,1338,286,272,4124,...,1090,180,749,1916,774,971,93,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Arizona (Estimate),896,1904,948400,2872,37873,12096,977,180,509,4501,...,9075,200,4286,10009,59,1328,724,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),142,59,274,503,970,453,76,145,233,822,...,120,67,2608,379,9533,214,261,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Wisconsin (Estimate),1399,397,2792,1468,4705,3492,1342,144,197,5633,...,2574,0,2131,1895,51,682608,179,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Wisconsin (MOE),1137,380,1148,820,1437,1465,834,235,165,1987,...,1699,211,1138,1368,87,20672,158,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Wyoming (Estimate),91,195,1701,154,1585,5234,411,109,0,495,...,4524,27,375,262,33,47,65556,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...
Residence 1 year ago in --: Wyoming (MOE),158,228,955,189,798,1627,367,179,296,429,...,1986,45,443,292,55,76,5755,Footnotes:,*Incudes Puerto Rico and the District of Columbia,MOE - Margin of error based on 90% confidence ...

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [21]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [22]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [23]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Residence 1 year ago in --: Alabama (Estimate)                       103
Residence 1 year ago in --: Alaska (Estimate)                        230
Residence 1 year ago in --: Arizona (Estimate)                       509
Residence 1 year ago in --: Arkansas (Estimate)                       35
Residence 1 year ago in --: California (Estimate)                   1688
Residence 1 year ago in --: Colorado (Estimate)                      360
Residence 1 year ago in --: Connecticut (Estimate)                   919
Residence 1 year ago in --: Delaware (Estimate)                      981
Residence 1 year ago in --: District of Columbi...                 63313
Residence 1 year ago in --: Florida (Estimate)                      1650
Residence 1 year ago in --: Georgia (Estimate)                       709
Residence 1 year ago in --: Hawaii (Estimate)                        355
Residence 1 year ago in --: Idaho (Estimate)                          79
Residence 1 year ago in --: Illinois (Estimate)                      877
Residence 1 year ago in --: Indiana (Estimate)                       137
Residence 1 year ago in --: Iowa (Estimate)                          139
Residence 1 year ago in --: Kansas (Estimate)                        364
Residence 1 year ago in --: Kentucky (Estimate)                        0
Residence 1 year ago in --: Louisiana (Estimate)                     484
Residence 1 year ago in --: Maine (Estimate)                           0
Residence 1 year ago in --: Maryland (Estimate)                    12275
Residence 1 year ago in --: Massachusetts (Esti...                  1523
Residence 1 year ago in --: Michigan (Estimate)                      895
Residence 1 year ago in --: Minnesota (Estimate)                     300
Residence 1 year ago in --: Mississippi (Estimate)                    91
Residence 1 year ago in --: Missouri (Estimate)                      179
Residence 1 year ago in --: Montana (Estimate)                        65
Residence 1 year ago in --: Nebraska (Estimate)                        0
Residence 1 year ago in --: Nevada (Estimate)                          0
Residence 1 year ago in --: New Hampshire (Esti...                   230
Residence 1 year ago in --: New Jersey (Estimate)                   1160
Residence 1 year ago in --: New Mexico (Estimate)                     51
Residence 1 year ago in --: New York (Estimate)                     3974
Residence 1 year ago in --: North Carolina (Est...                  1370
Residence 1 year ago in --: North Dakota (Estim...                     0
Residence 1 year ago in --: Ohio (Estimate)                          966
Residence 1 year ago in --: Oklahoma (Estimate)                      109
Residence 1 year ago in --: Oregon (Estimate)                        412
Residence 1 year ago in --: Pennsylvania (Estim...                  1880
Residence 1 year ago in --: Puerto Rico (Estimate)                   165
Residence 1 year ago in --: Rhode Island (Estim...                   336
Residence 1 year ago in --: South Carolina (Est...                   608
Residence 1 year ago in --: South Dakota (Estim...                     0
Residence 1 year ago in --: Tennessee (Estimate)                      35
Residence 1 year ago in --: Texas (Estimate)                         711
Residence 1 year ago in --: Utah (Estimate)                            0
Residence 1 year ago in --: Vermont (Estimate)                         0
Residence 1 year ago in --: Virginia (Estimate)                     6828
Residence 1 year ago in --: Washington (Estimate)                    296
Residence 1 year ago in --: West Virginia (Esti...                   424
Residence 1 year ago in --: Wisconsin (Estimate)                     197
Residence 1 year ago in --: Wyoming (Estimate)                         0

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [24]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

For 2021 and 2017, we needed to cut off the top columns that arent for specific states, but that's not relevent here because of different structure for 2009 and 2005

In [25]:

# df_estimates = df_estimates[4:]
# df_moes = df_moes[4:]

In [26]:
df_moes.head()

0          District of Columbia
0
Alabama                      140
Alaska                       272
Arizona                      476
Arkansas                      60
California                   646

In [27]:
df_estimates.head()

0          District of Columbia
0
Alabama                      103
Alaska                       230
Arizona                      509
Arkansas                      35
California                  1688

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [28]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Now I'm adding a state polulation column to my newly formatted table

In [29]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [30]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [31]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [32]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       103     140          5024279
Alaska                        230     272           733391
Arizona                       509     476          7151502
Arkansas                       35      60          3011524
California                   1688     646         39538223
Colorado                      360     306          5773714
Connecticut                   919     634          3605944
Delaware                      981     721           989948
District of Columbia        63313    5969           689545
Florida                      1650     708         21538187
Georgia                       709     437         10711908
Hawaii                        355     521          1455271
Idaho                          79     135          1839106
Illinois                      877     451         12812508
Indiana                       137     137          6785528
Iowa                          139     173          3190369
Kansas                        364     360          2937880
Kentucky                        0     296          4505836
Louisiana                     484     679          4657757
Maine                           0     296          1362359
Maryland                    12275    2507          6177224
Massachusetts                1523     665          7029917
Michigan                      895     778         10077331
Minnesota                     300     277          5706494
Mississippi                    91     114          2961279
Missouri                      179     229          6154913
Montana                        65     108          1084225
Nebraska                        0     296          1961504
Nevada                          0     296          3104614
New Hampshire                 230     191          1377529
New Jersey                   1160     628          9288994
New Mexico                     51      84          2117522
New York                     3974    1310         20201249
North Carolina               1370     428         10439388
North Dakota                    0     296           779094
Ohio                          966     514         11799448
Oklahoma                      109     122          3959353
Oregon                        412     340          4237256
Pennsylvania                 1880     795         13002700
Puerto Rico                   165     135          3285874
Rhode Island                  336     249          1097379
South Carolina                608     391          5118425
South Dakota                    0     296           886667
Tennessee                      35      59          6910840
Texas                         711     430         29145505
Utah                            0     296          3271616
Vermont                         0     296           643077
Virginia                     6828    1362          8631393
Washington                    296     302          7705281
West Virginia                 424     233          1793716
Wisconsin                     197     165          5893718
Wyoming                         0     296           576851

Adding columns representing the top and bottom of the margins of error

In [33]:
df['pop_migrated_upper'] = pd.to_numeric(df['pop_migrated']) + pd.to_numeric(df['MOE +/-']) 

df['pop_migrated_lower'] = pd.to_numeric(df['pop_migrated']) - pd.to_numeric(df['MOE +/-']) 

df

0,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower
0,,,,,
Alabama,103,140,5024279,243,-37
Alaska,230,272,733391,502,-42
Arizona,509,476,7151502,985,33
Arkansas,35,60,3011524,95,-25
California,1688,646,39538223,2334,1042
Colorado,360,306,5773714,666,54
Connecticut,919,634,3605944,1553,285
Delaware,981,721,989948,1702,260
District of Columbia,63313,5969,689545,69282,57344
Florida,1650,708,21538187,2358,942
Georgia,709,437,10711908,1146,272
Hawaii,355,521,1455271,876,-166
Idaho,79,135,1839106,214,-56
Illinois,877,451,12812508,1328,426
Indiana,137,137,6785528,274,0
Iowa,139,173,3190369,312,-34
Kansas,364,360,2937880,724,4
Kentucky,0,296,4505836,296,-296
Louisiana,484,679,4657757,1163,-195
Maine,0,296,1362359,296,-296
Maryland,12275,2507,6177224,14782,9768
Massachusetts,1523,665,7029917,2188,858
Michigan,895,778,10077331,1673,117
Minnesota,300,277,5706494,577,23
Mississippi,91,114,2961279,205,-23
Missouri,179,229,6154913,408,-50
Montana,65,108,1084225,173,-43
Nebraska,0,296,1961504,296,-296
Nevada,0,296,3104614,296,-296
New Hampshire,230,191,1377529,421,39
New Jersey,1160,628,9288994,1788,532
New Mexico,51,84,2117522,135,-33
New York,3974,1310,20201249,5284,2664
North Carolina,1370,428,10439388,1798,942
North Dakota,0,296,779094,296,-296
Ohio,966,514,11799448,1480,452
Oklahoma,109,122,3959353,231,-13
Oregon,412,340,4237256,752,72
Pennsylvania,1880,795,13002700,2675,1085
Puerto Rico,165,135,3285874,300,30
Rhode Island,336,249,1097379,585,87
South Carolina,608,391,5118425,999,217
South Dakota,0,296,886667,296,-296
Tennessee,35,59,6910840,94,-24
Texas,711,430,29145505,1141,281
Utah,0,296,3271616,296,-296
Vermont,0,296,643077,296,-296
Virginia,6828,1362,8631393,8190,5466
Washington,296,302,7705281,598,-6
West Virginia,424,233,1793716,657,191
Wisconsin,197,165,5893718,362,32
Wyoming,0,296,576851,296,-296

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [34]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

df['migrated_adjusted_upper'] = (
    pd.to_numeric(df['pop_migrated_upper'])
    / pd.to_numeric(df['state_population'])

)

df['migrated_adjusted_lower'] = (
    pd.to_numeric(df['pop_migrated_lower'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [35]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Need to manually drop DC here because its input differently than in the other years -- here, the D.C. figure for folks that lived in D.C. both this year and last year is not n/a or 0, but rather a substantial number that represents the number of folks that did NOT move since last year's census

In [36]:
df = df.drop(['District of Columbia'])

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [37]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)

df.head()

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted
0,Alabama,103,140,5024279,243,-37,0.000021,0.000048,-0.000007,0.000028
1,Alaska,230,272,733391,502,-42,0.000314,0.000684,-0.000057,0.000371
2,Arizona,509,476,7151502,985,33,0.000071,0.000138,0.000005,0.000067
3,Arkansas,35,60,3011524,95,-25,0.000012,0.000032,-0.000008,0.000020
4,California,1688,646,39538223,2334,1042,0.000043,0.000059,0.000026,0.000016

Looking at states with most people coming to DC

In [38]:

df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted
19,Maryland,12275,2507,6177224,14782,9768,0.001987,0.002393,0.001581,0.000406
7,Delaware,981,721,989948,1702,260,0.000991,0.001719,0.000263,0.000728
46,Virginia,6828,1362,8631393,8190,5466,0.000791,0.000949,0.000633,0.000158
1,Alaska,230,272,733391,502,-42,0.000314,0.000684,-0.000057,0.000371
39,Rhode Island,336,249,1097379,585,87,0.000306,0.000533,0.000079,0.000227
6,Connecticut,919,634,3605944,1553,285,0.000255,0.000431,0.000079,0.000176
10,Hawaii,355,521,1455271,876,-166,0.000244,0.000602,-0.000114,0.000358
48,West Virginia,424,233,1793716,657,191,0.000236,0.000366,0.000106,0.000130
20,Massachusetts,1523,665,7029917,2188,858,0.000217,0.000311,0.000122,0.000095
31,New York,3974,1310,20201249,5284,2664,0.000197,0.000262,0.000132,0.000065

To export, want to make a slice excluding all DMV states -- Maryland, Virginia

In [39]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]

Now need to reset the index again to make numbers consecutive now that I've removed ceratin rows.

In [40]:
df = df.reset_index(drop=True)

Now add in 2004 election winners for each state

First, read in file

In [41]:
df_2004_election_winners = pd.read_csv('pres-election-results-2004.csv')

df_2004_election_winners.shape

(48, 5)

Next, add winning party and percent of votes columns

In [42]:
df_2004_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

Reset index to match the other df

In [43]:
df_2004_election_winners = df_2004_election_winners.reset_index(drop=True)

In [44]:
df_2004_election_winners.head()

df_2004_election_winners.index

RangeIndex(start=0, stop=48, step=1)

In [45]:

df['winning_party'] = df_2004_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2004_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,103,140,5024279,243,-37,0.000021,0.000048,-0.000007,0.000028,REPUBLICAN,0.624607
1,Alaska,230,272,733391,502,-42,0.000314,0.000684,-0.000057,0.000371,REPUBLICAN,0.610653
2,Arizona,509,476,7151502,985,33,0.000071,0.000138,0.000005,0.000067,REPUBLICAN,0.548694
3,Arkansas,35,60,3011524,95,-25,0.000012,0.000032,-0.000008,0.000020,REPUBLICAN,0.543060
4,California,1688,646,39538223,2334,1042,0.000043,0.000059,0.000026,0.000016,DEMOCRAT,0.543056

Save as csv file

In [46]:
df.to_csv('DC-migration-2008.csv')