I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA State_to_State_Migrations_Table_2018.xls')

In [3]:
df.shape

(86, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.tail(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
57,Oklahoma,3895983,2671,3226343,19150,548493,16807,106943,7091,541,...,585,Oklahoma,14204,2621,1221,583,56,95,12927,2612
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Oregon,4152756,2818,3438653,21057,554097,19988,140627,8621,315,...,885,Oregon,19379,2985,0,207,20,31,19359,2984
60,Pennsylvania,12674699,5544,11119060,29386,1239854,27201,253520,11151,1202,...,158,Pennsylvania,62265,6309,11188,3271,813,462,50264,5417
61,Rhode Island,1047975,1870,928114,8740,78525,6998,32841,3919,183,...,220,Rhode Island,8495,2974,662,822,165,273,7668,2872
62,South Carolina,5029034,4100,4309043,19661,511153,17925,186505,10214,4636,...,444,South Carolina,22333,4693,3505,2884,450,456,18378,3654
63,South Dakota,871271,1414,740970,7483,100177,7064,26775,3764,84,...,494,South Dakota,3349,1373,262,443,61,94,3026,1230
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Tennessee,6692936,4573,5706212,25189,748791,24332,209377,12422,8547,...,132,Tennessee,28556,4119,1615,1100,147,139,26794,4127
66,Texas,28333482,10498,23992374,61744,3575604,57916,563945,24840,5945,...,1220,Texas,201559,15023,11057,3135,823,613,189679,14038
67,Utah,3114717,3345,2583764,17461,408033,13986,100824,7505,315,...,875,Utah,22096,4992,0,193,0,193,22096,4992
68,Vermont,621681,937,542177,5046,50818,4088,26306,3523,124,...,53,Vermont,2380,890,5,11,0,157,2375,888
69,Virginia,8424340,5001,7142767,30604,947475,29018,274003,13094,3426,...,227,Virginia,60095,6045,2328,1038,1245,1003,56522,6064
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Washington,7453439,4565,6101533,28433,1028654,26957,260906,14324,495,...,692,Washington,62346,6857,1477,1065,696,527,60173,6871
72,West Virginia,1787630,2061,1585832,8806,156420,8563,43841,4205,83,...,201,West Virginia,1537,579,220,261,0,201,1317,533
73,Wisconsin,5751525,3027,4960260,19314,659159,17572,114613,6968,572,...,182,Wisconsin,17493,2722,2285,1343,0,151,15208,2299
74,Wyoming,570867,1239,479561,7122,62957,6074,25734,3856,639,...,NaN,Wyoming,2615,1269,119,189,0,203,2496,1254
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Puerto Rico,3173956,2199,2915696,14840,234174,14034,20900,4606,0,...,228,Puerto Rico,3186,975,NaN,NaN,250,244,2936,941

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,323531965,28863,278079469,191887,35921585,160760,7571282,77765,98194,...,3941,United States2,1959629,39920,133451,10797,24689,4667,1801489,38285
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4832358,3328,4173026,19530,534914,18557,109301,9827,NaN,...,122,Alabama,15117,3039,957,731,893,649,13267,2944
11,Alaska,727164,1214,608707,7474,81229,5883,32099,4643,518,...,158,Alaska,5129,1871,344,375,267,327,4518,1795
12,Arizona,7090137,4507,5887700,28309,888452,25934,273714,15128,2801,...,578,Arizona,40271,5472,1289,1053,1449,1238,37533,5516
13,Arkansas,2975961,3093,2539294,19535,354774,17489,73179,7023,438,...,201,Arkansas,8714,2518,1693,1440,0,201,7021,1711
14,California,39114889,11156,34232867,55636,4092388,50349,501023,17029,4591,...,833,California,288611,13254,1250,636,3712,2675,283649,13452
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5633029,3632,4626834,24416,728730,20205,239153,15015,3597,...,956,Colorado,38312,4607,1104,1016,126,209,37082,4439
17,Connecticut,3538203,3043,3102312,17295,320248,14157,84718,7195,1054,...,207,Connecticut,30925,5302,4485,1952,699,477,25741,4487
18,Delaware,958770,1413,853523,7519,67984,6209,34451,4392,39,...,200,Delaware,2812,957,185,225,50,83,2577,965
19,District of Columbia,693798,1873,568201,6930,68603,5579,47555,4011,174,...,113,District of Columbia,9439,1788,183,230,0,213,9256,1780
20,Florida,21092877,8313,17863603,57744,2420485,51354,587261,22336,12870,...,736,Florida,221528,12275,44710,7633,3860,2338,172958,9699
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,10410462,5598,8909803,34965,1174523,34817,274273,15590,15589,...,1677,Georgia,51863,6993,1382,787,2712,1563,47769,6696
23,Hawaii,1403653,1798,1211015,10611,125172,9102,54074,5497,484,...,134,Hawaii,13392,3033,68,129,388,373,12936,3076

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,323531965,28863,278079469,191887,35921585,160760,7571282,77765,98194,...,3941,United States2,1959629,39920,133451,10797,24689,4667,1801489,38285
10,Alabama,4832358,3328,4173026,19530,534914,18557,109301,9827,NaN,...,122,Alabama,15117,3039,957,731,893,649,13267,2944
11,Alaska,727164,1214,608707,7474,81229,5883,32099,4643,518,...,158,Alaska,5129,1871,344,375,267,327,4518,1795
12,Arizona,7090137,4507,5887700,28309,888452,25934,273714,15128,2801,...,578,Arizona,40271,5472,1289,1053,1449,1238,37533,5516
13,Arkansas,2975961,3093,2539294,19535,354774,17489,73179,7023,438,...,201,Arkansas,8714,2518,1693,1440,0,201,7021,1711
14,California,39114889,11156,34232867,55636,4092388,50349,501023,17029,4591,...,833,California,288611,13254,1250,636,3712,2675,283649,13452
16,Colorado,5633029,3632,4626834,24416,728730,20205,239153,15015,3597,...,956,Colorado,38312,4607,1104,1016,126,209,37082,4439
17,Connecticut,3538203,3043,3102312,17295,320248,14157,84718,7195,1054,...,207,Connecticut,30925,5302,4485,1952,699,477,25741,4487
18,Delaware,958770,1413,853523,7519,67984,6209,34451,4392,39,...,200,Delaware,2812,957,185,225,50,83,2577,965
19,District of Columbia,693798,1873,568201,6930,68603,5579,47555,4011,174,...,113,District of Columbia,9439,1788,183,230,0,213,9256,1780
20,Florida,21092877,8313,17863603,57744,2420485,51354,587261,22336,12870,...,736,Florida,221528,12275,44710,7633,3860,2338,172958,9699
22,Georgia,10410462,5598,8909803,34965,1174523,34817,274273,15590,15589,...,1677,Georgia,51863,6993,1382,787,2712,1563,47769,6696
23,Hawaii,1403653,1798,1211015,10611,125172,9102,54074,5497,484,...,134,Hawaii,13392,3033,68,129,388,373,12936,3076
24,Idaho,1734756,1843,1438727,13783,209540,11848,79765,7651,84,...,601,Idaho,6724,2141,703,945,134,158,5887,1832
25,Illinois,12599244,4929,11029483,28667,1295596,27638,206620,12209,1280,...,114,Illinois,67545,6353,2677,1184,260,220,64608,6311
26,Indiana,6612948,4582,5614432,25211,821113,19953,145256,9569,966,...,979,Indiana,32147,5376,2561,1249,64,93,29522,5080
28,Iowa,3119306,2428,2662849,14455,371285,12931,74199,4846,148,...,183,Iowa,10973,2506,633,717,0,163,10340,2342

Rename columns to be clearer numbers

In [9]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '120', '121', '122', '123', '124', '125', '126', '127', '128', '129'],
      dtype='str', length=130)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [10]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

df

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,323531965,28863,278079469,191887,35921585,160760,7571282,77765,98194,...,26078,3941,1959629,39920,133451,10797,24689,4667,1801489,38285
10,Alabama,4832358,3328,4173026,19530,534914,18557,109301,9827,NaN,...,74,122,15117,3039,957,731,893,649,13267,2944
11,Alaska,727164,1214,608707,7474,81229,5883,32099,4643,518,...,192,158,5129,1871,344,375,267,327,4518,1795
12,Arizona,7090137,4507,5887700,28309,888452,25934,273714,15128,2801,...,929,578,40271,5472,1289,1053,1449,1238,37533,5516
13,Arkansas,2975961,3093,2539294,19535,354774,17489,73179,7023,438,...,0,201,8714,2518,1693,1440,0,201,7021,1711
14,California,39114889,11156,34232867,55636,4092388,50349,501023,17029,4591,...,1526,833,288611,13254,1250,636,3712,2675,283649,13452
16,Colorado,5633029,3632,4626834,24416,728730,20205,239153,15015,3597,...,1951,956,38312,4607,1104,1016,126,209,37082,4439
17,Connecticut,3538203,3043,3102312,17295,320248,14157,84718,7195,1054,...,0,207,30925,5302,4485,1952,699,477,25741,4487
18,Delaware,958770,1413,853523,7519,67984,6209,34451,4392,39,...,0,200,2812,957,185,225,50,83,2577,965
19,District of Columbia,693798,1873,568201,6930,68603,5579,47555,4011,174,...,68,113,9439,1788,183,230,0,213,9256,1780
20,Florida,21092877,8313,17863603,57744,2420485,51354,587261,22336,12870,...,744,736,221528,12275,44710,7633,3860,2338,172958,9699
22,Georgia,10410462,5598,8909803,34965,1174523,34817,274273,15590,15589,...,1339,1677,51863,6993,1382,787,2712,1563,47769,6696
23,Hawaii,1403653,1798,1211015,10611,125172,9102,54074,5497,484,...,178,134,13392,3033,68,129,388,373,12936,3076
24,Idaho,1734756,1843,1438727,13783,209540,11848,79765,7651,84,...,856,601,6724,2141,703,945,134,158,5887,1832
25,Illinois,12599244,4929,11029483,28667,1295596,27638,206620,12209,1280,...,93,114,67545,6353,2677,1184,260,220,64608,6311
26,Indiana,6612948,4582,5614432,25211,821113,19953,145256,9569,966,...,1008,979,32147,5376,2561,1249,64,93,29522,5080
28,Iowa,3119306,2428,2662849,14455,371285,12931,74199,4846,148,...,240,183,10973,2506,633,717,0,163,10340,2342
29,Kansas,2874208,2798,2392841,17716,371025,16909,95748,7841,476,...,606,375,14594,2669,152,178,82,117,14360,2671
30,Kentucky,4414714,3279,3744188,18273,547535,17640,110456,8385,2055,...,0,197,12535,2534,1122,927,188,212,11225,2396
31,Louisiana,4603081,3921,4033845,20655,474843,19702,81355,7131,1462,...,97,166,13038,2659,238,285,30,50,12770,2619
32,Maine,1324095,1563,1143612,8051,142453,7284,34706,3872,0,...,0,170,3324,899,0,170,0,170,3324,899
34,Maryland,5974521,4649,5133916,25668,630955,20758,163216,10535,647,...,147,238,46434,5298,1962,1166,941,556,43531,5086
35,Massachusetts,6834364,3940,5970065,27037,653940,24452,144042,7468,483,...,44,72,66317,6542,5677,1887,186,250,60454,5948
36,Michigan,9891083,5094,8562101,27627,1144840,25036,139276,9581,537,...,101,148,44866,5380,397,326,90,153,44379,5395
37,Minnesota,5543490,3354,4781432,18432,635928,16956,100270,6150,976,...,424,557,25860,2968,100,124,47,78,25713,2963
38,Mississippi,2955717,2710,2582347,16553,297788,14562,68000,7708,8401,...,747,364,7582,2152,303,341,334,236,6945,2037
40,Missouri,6053109,4138,5161553,20177,720626,18922,152326,8935,2378,...,610,460,18604,3207,777,617,106,132,17721,3217
41,Montana,1051757,1381,891554,8487,113693,6464,43375,4560,540,...,1949,767,3135,1247,131,224,364,541,2640,1130
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
45,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1905843,2229,1602056,12636,239853,10425,54579,5668,268,...,960,627,9355,2326,40,70,10,19,9305,2324
48,Nevada,3003761,2581,2495398,19156,366629,16899,127362,9279,397,...,791,660,14372,2825,564,440,911,558,12897,2519
49,New Hampshire,1344750,1556,1170412,9723,119936,8415,48367,4520,158,...,0,192,6035,1599,1041,916,0,192,4994,1431
50,New Jersey,8815804,5090,7870909,27774,722620,23628,159846,11726,147,...,0,210,62429,6193,5863,2370,32,48,56534,5436
51,New Mexico,2072546,2647,1797834,15105,204099,13898,60068,6617,1099,...,248,279,10545,2691,725,1012,245,225,9575,2441
53,New York,19329704,7489,17327068,36048,1614505,32857,254447,9994,1395,...,18,34,133684,8451,9431,2872,582,318,123671,7226
54,North Carolina,10274540,4937,8723401,36579,1178884,32327,318681,14755,3287,...,1046,920,53574,5403,2393,1366,819,657,50362,5138
55,North Dakota,749825,1391,623183,7019,89228,6522,33735,4338,4,...,290,302,3679,1446,119,137,279,376,3281,1235
56,Ohio,11555163,5668,9892715,29438,1426959,27610,198026,10200,1744,...,75,120,37463,4801,2248,1377,353,383,34862,4598
57,Oklahoma,3895983,2671,3226343,19150,548493,16807,106943,7091,541,...,641,585,14204,2621,1221,583,56,95,12927,2612
59,Oregon,4152756,2818,3438653,21057,554097,19988,140627,8621,315,...,1277,885,19379,2985,0,207,20,31,19359,2984
60,Pennsylvania,12674699,5544,11119060,29386,1239854,27201,253520,11151,1202,...,156,158,62265,6309,11188,3271,813,462,50264,5417
61,Rhode Island,1047975,1870,928114,8740,78525,6998,32841,3919,183,...,0,220,8495,2974,662,822,165,273,7668,2872
62,South Carolina,5029034,4100,4309043,19661,511153,17925,186505,10214,4636,...,266,444,22333,4693,3505,2884,450,456,18378,3654
63,South Dakota,871271,1414,740970,7483,100177,7064,26775,3764,84,...,651,494,3349,1373,262,443,61,94,3026,1230
65,Tennessee,6692936,4573,5706212,25189,748791,24332,209377,12422,8547,...,121,132,28556,4119,1615,1100,147,139,26794,4127
66,Texas,28333482,10498,23992374,61744,3575604,57916,563945,24840,5945,...,2327,1220,201559,15023,11057,3135,823,613,189679,14038
67,Utah,3114717,3345,2583764,17461,408033,13986,100824,7505,315,...,1534,875,22096,4992,0,193,0,193,22096,4992
68,Vermont,621681,937,542177,5046,50818,4088,26306,3523,124,...,45,53,2380,890,5,11,0,157,2375,888
69,Virginia,8424340,5001,7142767,30604,947475,29018,274003,13094,3426,...,266,227,60095,6045,2328,1038,1245,1003,56522,6064
71,Washington,7453439,4565,6101533,28433,1028654,26957,260906,14324,495,...,1237,692,62346,6857,1477,1065,696,527,60173,6871
72,West Virginia,1787630,2061,1585832,8806,156420,8563,43841,4205,83,...,0,201,1537,579,220,261,0,201,1317,533
73,Wisconsin,5751525,3027,4960260,19314,659159,17572,114613,6968,572,...,206,182,17493,2722,2285,1343,0,151,15208,2299
74,Wyoming,570867,1239,479561,7122,62957,6074,25734,3856,639,...,NaN,NaN,2615,1269,119,189,0,203,2496,1254
76,Puerto Rico,3173956,2199,2915696,14840,234174,14034,20900,4606,0,...,0,228,3186,975,NaN,NaN,250,244,2936,941

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [11]:
df.iloc[3:] = df.iloc[3:].fillna('0')

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#first, dealing with columns B-G/1-6)

column_1_name = f'{df.iloc[0, 1]} ({df.iloc[2, 1]})'
column_2_name = f'{df.iloc[0, 1]} ({df.iloc[2, 2]})'

column_3_name = f'{df.iloc[0, 3]} ({df.iloc[2, 3]})'
column_4_name = f'{df.iloc[0, 3]} ({df.iloc[2, 4]})'

column_5_name = f'{df.iloc[0, 5]} ({df.iloc[2, 5]})'
column_6_name = f'{df.iloc[0, 5]} ({df.iloc[2, 6]})'

df_clean = df.rename(columns ={
    '1': column_1_name,
    '2': column_2_name,
    '3': column_3_name,
    '4': column_4_name,
    '5': column_5_name,
    '6': column_6_name})

#next, for the rest of the columns:
#first, fill in blanks

df_filledin = df_clean.ffill(axis=1)

#then pull the info I need to name each column

for i in range(7, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [13]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Population 1 year and over (Estimate),Population 1 year and over (MOE),Same house 1 year ago (Estimate),Same house 1 year ago (MOE),Same state of residence 1 year ago (Estimate),Same state of residence 1 year ago (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (continued): Wyoming (Estimate),Different state of residence 1 year ago (continued): Wyoming (MOE),Abroad 1 year ago: Total (Estimate),Abroad 1 year ago: Total (MOE),Abroad 1 year ago: Puerto Rico (Estimate),Abroad 1 year ago: Puerto Rico (MOE),Abroad 1 year ago: U.S. Island Area (Estimate),Abroad 1 year ago: U.S. Island Area (MOE),Abroad 1 year ago: Foreign Country (Estimate),Abroad 1 year ago: Foreign Country (MOE)
53,New York,19329704,7489,17327068,36048,1614505,32857,254447,9994,1395,...,18,34,133684,8451,9431,2872,582,318,123671,7226
54,North Carolina,10274540,4937,8723401,36579,1178884,32327,318681,14755,3287,...,1046,920,53574,5403,2393,1366,819,657,50362,5138
55,North Dakota,749825,1391,623183,7019,89228,6522,33735,4338,4,...,290,302,3679,1446,119,137,279,376,3281,1235
56,Ohio,11555163,5668,9892715,29438,1426959,27610,198026,10200,1744,...,75,120,37463,4801,2248,1377,353,383,34862,4598
57,Oklahoma,3895983,2671,3226343,19150,548493,16807,106943,7091,541,...,641,585,14204,2621,1221,583,56,95,12927,2612
59,Oregon,4152756,2818,3438653,21057,554097,19988,140627,8621,315,...,1277,885,19379,2985,0,207,20,31,19359,2984
60,Pennsylvania,12674699,5544,11119060,29386,1239854,27201,253520,11151,1202,...,156,158,62265,6309,11188,3271,813,462,50264,5417
61,Rhode Island,1047975,1870,928114,8740,78525,6998,32841,3919,183,...,0,220,8495,2974,662,822,165,273,7668,2872
62,South Carolina,5029034,4100,4309043,19661,511153,17925,186505,10214,4636,...,266,444,22333,4693,3505,2884,450,456,18378,3654
63,South Dakota,871271,1414,740970,7483,100177,7064,26775,3764,84,...,651,494,3349,1373,262,443,61,94,3026,1230
65,Tennessee,6692936,4573,5706212,25189,748791,24332,209377,12422,8547,...,121,132,28556,4119,1615,1100,147,139,26794,4127
66,Texas,28333482,10498,23992374,61744,3575604,57916,563945,24840,5945,...,2327,1220,201559,15023,11057,3135,823,613,189679,14038
67,Utah,3114717,3345,2583764,17461,408033,13986,100824,7505,315,...,1534,875,22096,4992,0,193,0,193,22096,4992
68,Vermont,621681,937,542177,5046,50818,4088,26306,3523,124,...,45,53,2380,890,5,11,0,157,2375,888
69,Virginia,8424340,5001,7142767,30604,947475,29018,274003,13094,3426,...,266,227,60095,6045,2328,1038,1245,1003,56522,6064
71,Washington,7453439,4565,6101533,28433,1028654,26957,260906,14324,495,...,1237,692,62346,6857,1477,1065,696,527,60173,6871
72,West Virginia,1787630,2061,1585832,8806,156420,8563,43841,4205,83,...,0,201,1537,579,220,261,0,201,1317,533
73,Wisconsin,5751525,3027,4960260,19314,659159,17572,114613,6968,572,...,206,182,17493,2722,2285,1343,0,151,15208,2299
74,Wyoming,570867,1239,479561,7122,62957,6074,25734,3856,639,...,0,0,2615,1269,119,189,0,203,2496,1254
76,Puerto Rico,3173956,2199,2915696,14840,234174,14034,20900,4606,0,...,0,228,3186,975,0,0,250,244,2936,941


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [14]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),323531965,4832358,727164,7090137,2975961,39114889,5633029,3538203,958770,693798,...,6692936,28333482,3114717,621681,8424340,7453439,1787630,5751525,570867,3173956
Population 1 year and over (MOE),28863,3328,1214,4507,3093,11156,3632,3043,1413,1873,...,4573,10498,3345,937,5001,4565,2061,3027,1239,2199
Same house 1 year ago (Estimate),278079469,4173026,608707,5887700,2539294,34232867,4626834,3102312,853523,568201,...,5706212,23992374,2583764,542177,7142767,6101533,1585832,4960260,479561,2915696
Same house 1 year ago (MOE),191887,19530,7474,28309,19535,55636,24416,17295,7519,6930,...,25189,61744,17461,5046,30604,28433,8806,19314,7122,14840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago: Puerto Rico (MOE),10797,731,375,1053,1440,636,1016,1952,225,230,...,1100,3135,193,11,1038,1065,261,1343,189,0
Abroad 1 year ago: U.S. Island Area (Estimate),24689,893,267,1449,0,3712,126,699,50,0,...,147,823,0,0,1245,696,0,0,0,250
Abroad 1 year ago: U.S. Island Area (MOE),4667,649,327,1238,201,2675,209,477,83,213,...,139,613,193,157,1003,527,201,151,203,244
Abroad 1 year ago: Foreign Country (Estimate),1801489,13267,4518,37533,7021,283649,37082,25741,2577,9256,...,26794,189679,22096,2375,56522,60173,1317,15208,2496,2936
Abroad 1 year ago: Foreign Country (MOE),38285,2944,1795,5516,1711,13452,4439,4487,965,1780,...,4127,14038,4992,888,6064,6871,533,2299,1254,941

In [15]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [16]:

df = df.iloc[1:]

In [17]:
df

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),323531965,4832358,727164,7090137,2975961,39114889,5633029,3538203,958770,693798,...,6692936,28333482,3114717,621681,8424340,7453439,1787630,5751525,570867,3173956
Population 1 year and over (MOE),28863,3328,1214,4507,3093,11156,3632,3043,1413,1873,...,4573,10498,3345,937,5001,4565,2061,3027,1239,2199
Same house 1 year ago (Estimate),278079469,4173026,608707,5887700,2539294,34232867,4626834,3102312,853523,568201,...,5706212,23992374,2583764,542177,7142767,6101533,1585832,4960260,479561,2915696
Same house 1 year ago (MOE),191887,19530,7474,28309,19535,55636,24416,17295,7519,6930,...,25189,61744,17461,5046,30604,28433,8806,19314,7122,14840
Same state of residence 1 year ago (Estimate),35921585,534914,81229,888452,354774,4092388,728730,320248,67984,68603,...,748791,3575604,408033,50818,947475,1028654,156420,659159,62957,234174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago: Puerto Rico (MOE),10797,731,375,1053,1440,636,1016,1952,225,230,...,1100,3135,193,11,1038,1065,261,1343,189,0
Abroad 1 year ago: U.S. Island Area (Estimate),24689,893,267,1449,0,3712,126,699,50,0,...,147,823,0,0,1245,696,0,0,0,250
Abroad 1 year ago: U.S. Island Area (MOE),4667,649,327,1238,201,2675,209,477,83,213,...,139,613,193,157,1003,527,201,151,203,244
Abroad 1 year ago: Foreign Country (Estimate),1801489,13267,4518,37533,7021,283649,37082,25741,2577,9256,...,26794,189679,22096,2375,56522,60173,1317,15208,2496,2936
Abroad 1 year ago: Foreign Country (MOE),38285,2944,1795,5516,1711,13452,4439,4487,965,1780,...,4127,14038,4992,888,6064,6871,533,2299,1254,941

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [18]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [19]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [20]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Population 1 year and over (Estimate)                             693798
Same house 1 year ago (Estimate)                                  568201
Same state of residence 1 year ago (Estimate)                      68603
Different state of residence 1 year ago: Total ...                 47555
Different state of residence 1 year ago: Alabam...                   174
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   204
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  3803
Different state of residence 1 year ago (contin...                   336
Different state of residence 1 year ago (contin...                   262
Different state of residence 1 year ago (contin...                   182
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  1789
Different state of residence 1 year ago (contin...                   647
Different state of residence 1 year ago (contin...                   124
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  1066
Different state of residence 1 year ago (contin...                   146
Different state of residence 1 year ago (contin...                   162
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   110
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                    61
Different state of residence 1 year ago (contin...                 12735
Different state of residence 1 year ago (contin...                  1664
Different state of residence 1 year ago (contin...                   486
Different state of residence 1 year ago (contin...                   143
Different state of residence 1 year ago (contin...                   146
Different state of residence 1 year ago (contin...                   201
Different state of residence 1 year ago (contin...                    92
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                    36
Different state of residence 1 year ago (contin...                   130
Different state of residence 1 year ago (contin...                  2382
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  4642
Different state of residence 1 year ago (contin...                  1026
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  1592
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                    80
Different state of residence 1 year ago (contin...                  1617
Different state of residence 1 year ago (contin...                    87
Different state of residence 1 year ago (contin...                   408
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   690
Different state of residence 1 year ago (contin...                  1036
Different state of residence 1 year ago (contin...                   215
Different state of residence 1 year ago (contin...                   213
Different state of residence 1 year ago (contin...                  7773
Different state of residence 1 year ago (contin...                   387
Different state of residence 1 year ago (contin...                   294
Different state of residence 1 year ago (contin...                   346
Different state of residence 1 year ago (contin...                    68
Abroad 1 year ago: Total (Estimate)                                 9439
Abroad 1 year ago: Puerto Rico (Estimate)                            183
Abroad 1 year ago: U.S. Island Area (Estimate)                         0
Abroad 1 year ago: Foreign Country (Estimate)                       9256

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [21]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

Cut off the top columns that arent for specific states

In [22]:

df_estimates = df_estimates[4:]
df_moes = df_moes[4:]

In [23]:
df_moes.head()

0          District of Columbia
0
Alabama                      225
Alaska                       213
Arizona                      220
Arkansas                     213
California                  1151

In [24]:
df_estimates.head()

0          District of Columbia
0
Alabama                      174
Alaska                         0
Arizona                      204
Arkansas                       0
California                  3803

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [25]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Also need to cut out one "total" column that is the total amount of "Abroad One Year Ago" incl PR, US Island Area, and Foreign Country

In [26]:
df = df.drop('Total')

df

0                    District of Columbia  MOE +/-
0
Alabama                                174     225
Alaska                                   0     213
Arizona                                204     220
Arkansas                                 0     213
California                            3803    1151
Colorado                               336     289
Connecticut                            262     190
Delaware                               182     215
District of Columbia                     0       0
Florida                               1789     842
Georgia                                647     392
Hawaii                                 124     213
Idaho                                    0     213
Illinois                              1066     655
Indiana                                146     163
Iowa                                   162     160
Kansas                                   0     213
Kentucky                               110     108
Louisiana                                0     213
Maine                                   61     103
Maryland                             12735    2757
Massachusetts                         1664     441
Michigan                               486     319
Minnesota                              143     138
Mississippi                            146     263
Missouri                               201     182
Montana                                 92      77
Nebraska                                 0     213
Nevada                                  36      83
New Hampshire                          130     225
New Jersey                            2382     894
New Mexico                               0     213
New York                              4642    1361
North Carolina                        1026     569
North Dakota                             0     213
Ohio                                  1592     805
Oklahoma                                 0     213
Oregon                                  80     134
Pennsylvania                          1617     591
Rhode Island                            87      96
South Carolina                         408     253
South Dakota                             0     213
Tennessee                              690     478
Texas                                 1036     648
Utah                                   215     187
Vermont                                213     345
Virginia                              7773    1392
Washington                             387     331
West Virginia                          294     401
Wisconsin                              346     377
Wyoming                                 68     113
Puerto Rico                            183     230
U.S. Island Area                         0     213
Foreign Country                       9256    1780

also need to drop out the last two columns US Island Area and Foreign Country because those dont exist in the pop df and I don't need for this analysis

In [27]:
df = df.drop('U.S. Island Area')
df = df.drop('Foreign Country')

also need to drop the top row of pops df to get the dataframes to have the same row indices

In [28]:
df_pops = df_pops.drop('Label (Grouping)')

Now I'm adding a state polulation column to my newly formatted table

In [29]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [30]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [31]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [32]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       174     225          5024279
Alaska                          0     213           733391
Arizona                       204     220          7151502
Arkansas                        0     213          3011524
California                   3803    1151         39538223
Colorado                      336     289          5773714
Connecticut                   262     190          3605944
Delaware                      182     215           989948
District of Columbia            0       0           689545
Florida                      1789     842         21538187
Georgia                       647     392         10711908
Hawaii                        124     213          1455271
Idaho                           0     213          1839106
Illinois                     1066     655         12812508
Indiana                       146     163          6785528
Iowa                          162     160          3190369
Kansas                          0     213          2937880
Kentucky                      110     108          4505836
Louisiana                       0     213          4657757
Maine                          61     103          1362359
Maryland                    12735    2757          6177224
Massachusetts                1664     441          7029917
Michigan                      486     319         10077331
Minnesota                     143     138          5706494
Mississippi                   146     263          2961279
Missouri                      201     182          6154913
Montana                        92      77          1084225
Nebraska                        0     213          1961504
Nevada                         36      83          3104614
New Hampshire                 130     225          1377529
New Jersey                   2382     894          9288994
New Mexico                      0     213          2117522
New York                     4642    1361         20201249
North Carolina               1026     569         10439388
North Dakota                    0     213           779094
Ohio                         1592     805         11799448
Oklahoma                        0     213          3959353
Oregon                         80     134          4237256
Pennsylvania                 1617     591         13002700
Rhode Island                   87      96          1097379
South Carolina                408     253          5118425
South Dakota                    0     213           886667
Tennessee                     690     478          6910840
Texas                        1036     648         29145505
Utah                          215     187          3271616
Vermont                       213     345           643077
Virginia                     7773    1392          8631393
Washington                    387     331          7705281
West Virginia                 294     401          1793716
Wisconsin                     346     377          5893718
Wyoming                        68     113           576851
Puerto Rico                   183     230          3285874

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [33]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [34]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Looking at states with most people coming to DC

In [35]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,,,,,
Maryland,12735,2757,6177224,0.002062,0.000446
Virginia,7773,1392,8631393,0.000901,0.000161
Vermont,213,345,643077,0.000331,0.000536
New Jersey,2382,894,9288994,0.000256,0.000096
Massachusetts,1664,441,7029917,0.000237,0.000063
New York,4642,1361,20201249,0.000230,0.000067
Delaware,182,215,989948,0.000184,0.000217
West Virginia,294,401,1793716,0.000164,0.000224
Ohio,1592,805,11799448,0.000135,0.000068
Pennsylvania,1617,591,13002700,0.000124,0.000045

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [36]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,174,225,5024279,0.000035,0.000045
1,Alaska,0,213,733391,0.000000,0.000290
2,Arizona,204,220,7151502,0.000029,0.000031
3,Arkansas,0,213,3011524,0.000000,0.000071
4,California,3803,1151,39538223,0.000096,0.000029

To export, want to make a slice excluding all DMV states -- Maryland, Virginia, DC

And then also PR because only looking at continental US

In [37]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]
df = df[df["state"] != "District of Columbia"]

Now need to reset the indexes again to make numbers consecutive now that I've removed ceratin rows.

In [38]:
df = df.reset_index(drop=True)

Now add in 2016 election winners for each state

First, read in file

In [39]:
df_2016_election_winners = pd.read_csv('pres-election-results-2016.csv')

type(df_2016_election_winners)

pandas.DataFrame

In [40]:
df['winning_party'] = df_2016_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2016_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,174,225,5024279,0.000035,0.000045,REPUBLICAN,0.620831
1,Alaska,0,213,733391,0.000000,0.000290,REPUBLICAN,0.512815
2,Arizona,204,220,7151502,0.000029,0.000031,REPUBLICAN,0.486716
3,Arkansas,0,213,3011524,0.000000,0.000071,REPUBLICAN,0.605741
4,California,3803,1151,39538223,0.000096,0.000029,DEMOCRAT,0.617264

In [41]:
df.index

RangeIndex(start=0, stop=48, step=1)

In [42]:
df_2016_election_winners.index

RangeIndex(start=0, stop=48, step=1)

Save as csv file

In [43]:
df.to_csv('DC-migration-2018.csv')