I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2014.xls')

In [3]:
df.shape

(85, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,315095393,26923,268147625,208630,37571394,185426,7334169,60012,111655,...,5146,United States2,2042205,32993,83844,8510,16858,3642,1941503,30408

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,315095393,26923,268147625,208630,37571394,185426,7334169,60012,111655,...,5146,United States2,2042205,32993,83844,8510,16858,3642,1941503,30408
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4791931,4065,4081522,22252,589211,18805,107919,8282,NaN,...,348,Alabama,13279,2672,320,319,46,79,12913,2648
11,Alaska,725206,1461,585916,7276,97358,6516,37842,4013,603,...,125,Alaska,4090,1210,118,73,0,145,3972,1205
12,Arizona,6651964,4638,5431241,29624,922129,25819,249730,12340,785,...,1801,Arizona,48864,5666,679,633,332,296,47853,5605
13,Arkansas,2931123,2667,2464189,16201,383087,15050,74741,6045,2145,...,64,Arkansas,9106,2535,148,173,241,249,8717,2536
14,California,38340324,10835,32849251,61601,4659084,58901,513968,18847,10439,...,705,California,318021,12211,4317,1748,1752,1097,311952,11956
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5293943,3847,4263998,25609,777699,21108,218728,12727,1004,...,1852,Colorado,33518,4790,342,385,765,864,32411,4654
17,Connecticut,3558915,2621,3111779,13932,334207,11288,82746,8190,275,...,197,Connecticut,30183,4320,4210,2202,82,121,25891,4203
18,Delaware,924770,1262,810905,7547,77246,6680,32166,3413,46,...,185,Delaware,4453,1284,272,306,0,185,4181,1250
19,District of Columbia,648586,1757,513634,7913,67286,5744,56234,4603,251,...,400,District of Columbia,11432,2238,39,66,148,152,11245,2226
20,Florida,19683763,7910,16504838,45685,2436619,41459,546501,21034,15731,...,354,Florida,195805,13262,27596,4710,4398,2127,163811,11519
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,9970167,6089,8406436,36778,1238139,35517,274095,15049,18778,...,481,Georgia,51497,5340,1315,843,227,283,49955,5363
23,Hawaii,1401004,1966,1198766,10297,131974,8488,58144,5069,510,...,61,Hawaii,12120,1939,262,269,971,508,10887,1843

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,315095393,26923,268147625,208630,37571394,185426,7334169,60012,111655,...,5146,United States2,2042205,32993,83844,8510,16858,3642,1941503,30408
10,Alabama,4791931,4065,4081522,22252,589211,18805,107919,8282,NaN,...,348,Alabama,13279,2672,320,319,46,79,12913,2648
11,Alaska,725206,1461,585916,7276,97358,6516,37842,4013,603,...,125,Alaska,4090,1210,118,73,0,145,3972,1205
12,Arizona,6651964,4638,5431241,29624,922129,25819,249730,12340,785,...,1801,Arizona,48864,5666,679,633,332,296,47853,5605
13,Arkansas,2931123,2667,2464189,16201,383087,15050,74741,6045,2145,...,64,Arkansas,9106,2535,148,173,241,249,8717,2536
14,California,38340324,10835,32849251,61601,4659084,58901,513968,18847,10439,...,705,California,318021,12211,4317,1748,1752,1097,311952,11956
16,Colorado,5293943,3847,4263998,25609,777699,21108,218728,12727,1004,...,1852,Colorado,33518,4790,342,385,765,864,32411,4654
17,Connecticut,3558915,2621,3111779,13932,334207,11288,82746,8190,275,...,197,Connecticut,30183,4320,4210,2202,82,121,25891,4203
18,Delaware,924770,1262,810905,7547,77246,6680,32166,3413,46,...,185,Delaware,4453,1284,272,306,0,185,4181,1250
19,District of Columbia,648586,1757,513634,7913,67286,5744,56234,4603,251,...,400,District of Columbia,11432,2238,39,66,148,152,11245,2226
20,Florida,19683763,7910,16504838,45685,2436619,41459,546501,21034,15731,...,354,Florida,195805,13262,27596,4710,4398,2127,163811,11519
22,Georgia,9970167,6089,8406436,36778,1238139,35517,274095,15049,18778,...,481,Georgia,51497,5340,1315,843,227,283,49955,5363
23,Hawaii,1401004,1966,1198766,10297,131974,8488,58144,5069,510,...,61,Hawaii,12120,1939,262,269,971,508,10887,1843
24,Idaho,1613068,2061,1335689,14615,207055,13624,64633,6253,166,...,871,Idaho,5691,1235,90,151,0,190,5601,1230
25,Illinois,12730206,5665,11021611,32616,1430902,30345,209536,11110,1566,...,202,Illinois,68157,6190,1185,586,435,365,66537,6184
26,Indiana,6516181,4079,5540754,26629,810518,23716,139846,8352,1229,...,757,Indiana,25063,3166,77,128,0,187,24986,3181
28,Iowa,3067872,2609,2594781,13916,379518,12526,79194,6405,641,...,274,Iowa,14379,3114,0,155,0,155,14379,3114

Rename columns to be clearer numbers

In [9]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '120', '121', '122', '123', '124', '125', '126', '127', '128', '129'],
      dtype='str', length=130)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [10]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

df

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,315095393,26923,268147625,208630,37571394,185426,7334169,60012,111655,...,33465,5146,2042205,32993,83844,8510,16858,3642,1941503,30408
10,Alabama,4791931,4065,4081522,22252,589211,18805,107919,8282,NaN,...,307,348,13279,2672,320,319,46,79,12913,2648
11,Alaska,725206,1461,585916,7276,97358,6516,37842,4013,603,...,107,125,4090,1210,118,73,0,145,3972,1205
12,Arizona,6651964,4638,5431241,29624,922129,25819,249730,12340,785,...,2670,1801,48864,5666,679,633,332,296,47853,5605
13,Arkansas,2931123,2667,2464189,16201,383087,15050,74741,6045,2145,...,34,64,9106,2535,148,173,241,249,8717,2536
14,California,38340324,10835,32849251,61601,4659084,58901,513968,18847,10439,...,1401,705,318021,12211,4317,1748,1752,1097,311952,11956
16,Colorado,5293943,3847,4263998,25609,777699,21108,218728,12727,1004,...,5426,1852,33518,4790,342,385,765,864,32411,4654
17,Connecticut,3558915,2621,3111779,13932,334207,11288,82746,8190,275,...,0,197,30183,4320,4210,2202,82,121,25891,4203
18,Delaware,924770,1262,810905,7547,77246,6680,32166,3413,46,...,0,185,4453,1284,272,306,0,185,4181,1250
19,District of Columbia,648586,1757,513634,7913,67286,5744,56234,4603,251,...,255,400,11432,2238,39,66,148,152,11245,2226
20,Florida,19683763,7910,16504838,45685,2436619,41459,546501,21034,15731,...,405,354,195805,13262,27596,4710,4398,2127,163811,11519
22,Georgia,9970167,6089,8406436,36778,1238139,35517,274095,15049,18778,...,360,481,51497,5340,1315,843,227,283,49955,5363
23,Hawaii,1401004,1966,1198766,10297,131974,8488,58144,5069,510,...,27,61,12120,1939,262,269,971,508,10887,1843
24,Idaho,1613068,2061,1335689,14615,207055,13624,64633,6253,166,...,1549,871,5691,1235,90,151,0,190,5601,1230
25,Illinois,12730206,5665,11021611,32616,1430902,30345,209536,11110,1566,...,190,202,68157,6190,1185,586,435,365,66537,6184
26,Indiana,6516181,4079,5540754,26629,810518,23716,139846,8352,1229,...,615,757,25063,3166,77,128,0,187,24986,3181
28,Iowa,3067872,2609,2594781,13916,379518,12526,79194,6405,641,...,298,274,14379,3114,0,155,0,155,14379,3114
29,Kansas,2866584,2600,2378716,16745,376239,15266,96467,7973,830,...,306,293,15162,2856,113,216,0,168,15049,2866
30,Kentucky,4357819,2944,3663490,18486,575429,18272,104975,7798,1409,...,291,290,13925,2546,84,155,0,185,13841,2544
31,Louisiana,4593505,3584,3970442,20735,511702,18953,97814,7800,4808,...,251,370,13547,2624,60,75,131,135,13356,2660
32,Maine,1317638,1582,1138397,9455,134611,8431,39065,4220,0,...,81,85,5565,1464,0,159,0,159,5565,1464
34,Maryland,5911235,3586,5091903,22914,615601,20033,156787,9338,770,...,219,205,46944,5391,1154,1192,51,87,45739,5219
35,Massachusetts,6674907,3547,5784744,21481,672510,19780,146622,7649,519,...,0,198,71031,6462,4441,1713,68,112,66522,6449
36,Michigan,9795659,4600,8336037,29138,1261495,26528,149991,9956,2362,...,117,135,48136,4766,717,800,232,178,47187,4630
37,Minnesota,5385219,3037,4612655,18403,635880,17046,106783,7233,392,...,42,42,29901,5398,189,257,103,175,29609,5400
38,Mississippi,2957658,3082,2554296,14497,321236,13038,73927,6852,6816,...,0,206,8199,1517,1343,682,0,206,6856,1259
40,Missouri,5992195,3743,5042396,23817,776519,20564,153320,9335,2807,...,709,618,19960,2263,776,783,47,110,19137,2314
41,Montana,1012169,1517,845142,8833,126508,7649,37561,4096,134,...,1552,1272,2958,813,14,26,0,161,2944,806
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
45,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1855356,2122,1541744,11830,252232,11543,52200,5289,510,...,1165,596,9180,1758,0,153,65,93,9115,1764
48,Nevada,2806170,2678,2235861,18271,426512,17873,130390,7549,475,...,359,241,13407,2515,97,158,70,116,13240,2527
49,New Hampshire,1314735,1334,1134514,10270,133298,9504,41393,3762,44,...,0,182,5530,2136,456,455,0,182,5074,2220
50,New Jersey,8840346,4188,7961796,23160,686056,20002,128911,9226,216,...,0,195,63583,4995,4180,1942,0,195,59403,5024
51,New Mexico,2060189,2902,1770053,12935,212456,11593,68917,6649,41,...,692,572,8763,1909,588,947,102,109,8073,1729
53,New York,19528220,5972,17418181,31878,1693064,29186,258571,11185,1662,...,320,240,158404,9997,4885,1746,349,265,153170,9670
54,North Carolina,9832152,5419,8332705,28703,1166928,27169,286533,13479,4264,...,675,644,45986,5223,1276,886,715,380,43995,5242
55,North Dakota,729874,1466,602508,6670,85084,4969,39059,4304,402,...,944,927,3223,1020,0,147,215,322,3008,951
56,Ohio,11464891,4533,9742065,34992,1484132,30668,196742,11827,1189,...,136,168,41952,4995,1874,937,0,185,40078,4626
57,Oklahoma,3827288,2471,3148699,16644,550149,14562,111346,8348,993,...,469,343,17094,2714,359,244,484,394,16251,2635
59,Oregon,3927857,2960,3196441,21251,571056,17936,137008,8735,156,...,1885,1147,23352,3468,78,132,196,161,23078,3418
60,Pennsylvania,12645888,4727,11103966,27311,1241534,22817,232889,11992,1535,...,143,161,67499,7151,7437,3100,50,91,60012,6595
61,Rhode Island,1045791,1336,906936,7854,98869,7579,32621,3400,347,...,0,203,7365,1794,914,829,0,203,6451,1684
62,South Carolina,4780659,3519,4046123,20327,542930,19804,171969,9132,3219,...,0,200,19637,3401,1325,895,253,177,18059,3645
63,South Dakota,842076,1090,701352,7865,109496,6804,28198,3741,0,...,2363,1637,3030,966,0,151,96,129,2934,927
65,Tennessee,6471445,3711,5465071,20831,796577,19366,182130,11634,9640,...,130,169,27667,3781,373,361,145,238,27149,3735
66,Texas,26588600,10391,22151594,60678,3681042,56949,538572,22996,6437,...,1647,860,217392,13621,6274,2310,2741,2063,208377,12926
67,Utah,2894001,2899,2407608,16818,374578,14902,90234,8541,365,...,3750,1552,21581,3132,280,212,0,184,21301,3098
68,Vermont,620898,883,536915,4667,59850,3939,22635,2419,0,...,29,49,1498,664,0,147,0,147,1498,664
69,Virginia,8224054,4721,6891144,29452,995822,26452,262477,12503,2654,...,147,179,74611,6633,1922,957,266,324,72423,6709
71,Washington,6979369,3884,5757065,26180,934922,23276,220259,13044,1640,...,1383,1026,67123,6824,728,547,1034,614,65361,6706
72,West Virginia,1831414,2060,1617510,10136,162340,9214,47957,4807,144,...,0,187,3607,1128,0,187,0,187,3607,1128
73,Wisconsin,5692727,3347,4868506,18280,688104,17604,117831,7616,452,...,16,24,18286,2702,937,749,48,79,17301,2549
74,Wyoming,577782,1222,475740,7103,74601,6250,25992,3696,254,...,NaN,NaN,1449,876,0,190,0,190,1449,876
76,Puerto Rico,3511186,3157,3251389,13399,237197,12111,19771,2798,50,...,0,220,2829,886,N/A3,N/A3,0,220,2829,886

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [11]:
df.iloc[3:] = df.iloc[3:].fillna('0')

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [15]:
#first, dealing with columns B-G/1-6)

column_1_name = f'{df.iloc[0, 1]} ({df.iloc[2, 1]})'
column_2_name = f'{df.iloc[0, 1]} ({df.iloc[2, 2]})'

column_3_name = f'{df.iloc[0, 3]} ({df.iloc[2, 3]})'
column_4_name = f'{df.iloc[0, 3]} ({df.iloc[2, 4]})'

column_5_name = f'{df.iloc[0, 5]} ({df.iloc[2, 5]})'
column_6_name = f'{df.iloc[0, 5]} ({df.iloc[2, 6]})'

df_clean = df.rename(columns ={
    '1': column_1_name,
    '2': column_2_name,
    '3': column_3_name,
    '4': column_4_name,
    '5': column_5_name,
    '6': column_6_name})

#next, for the rest of the columns:
#first, fill in blanks

df_filledin = df_clean.ffill(axis=1)

#then pull the info I need to name each column

for i in range(7, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [16]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Population 1 year and over (Estimate),Population 1 year and over (MOE),Same house 1 year ago (Estimate),Same house 1 year ago (MOE),Same state of residence 1 year ago (Estimate),Same state of residence 1 year ago (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (continued): Wyoming (Estimate),Different state of residence 1 year ago (continued): Wyoming (MOE),Abroad 1 year ago: Total (Estimate),Abroad 1 year ago: Total (MOE),Abroad 1 year ago: Puerto Rico (Estimate),Abroad 1 year ago: Puerto Rico (MOE),Abroad 1 year ago: U.S. Island Area (Estimate),Abroad 1 year ago: U.S. Island Area (MOE),Abroad 1 year ago: Foreign Country (Estimate),Abroad 1 year ago: Foreign Country (MOE)
53,New York,19528220,5972,17418181,31878,1693064,29186,258571,11185,1662,...,320,240,158404,9997,4885,1746,349,265,153170,9670
54,North Carolina,9832152,5419,8332705,28703,1166928,27169,286533,13479,4264,...,675,644,45986,5223,1276,886,715,380,43995,5242
55,North Dakota,729874,1466,602508,6670,85084,4969,39059,4304,402,...,944,927,3223,1020,0,147,215,322,3008,951
56,Ohio,11464891,4533,9742065,34992,1484132,30668,196742,11827,1189,...,136,168,41952,4995,1874,937,0,185,40078,4626
57,Oklahoma,3827288,2471,3148699,16644,550149,14562,111346,8348,993,...,469,343,17094,2714,359,244,484,394,16251,2635
59,Oregon,3927857,2960,3196441,21251,571056,17936,137008,8735,156,...,1885,1147,23352,3468,78,132,196,161,23078,3418
60,Pennsylvania,12645888,4727,11103966,27311,1241534,22817,232889,11992,1535,...,143,161,67499,7151,7437,3100,50,91,60012,6595
61,Rhode Island,1045791,1336,906936,7854,98869,7579,32621,3400,347,...,0,203,7365,1794,914,829,0,203,6451,1684
62,South Carolina,4780659,3519,4046123,20327,542930,19804,171969,9132,3219,...,0,200,19637,3401,1325,895,253,177,18059,3645
63,South Dakota,842076,1090,701352,7865,109496,6804,28198,3741,0,...,2363,1637,3030,966,0,151,96,129,2934,927
65,Tennessee,6471445,3711,5465071,20831,796577,19366,182130,11634,9640,...,130,169,27667,3781,373,361,145,238,27149,3735
66,Texas,26588600,10391,22151594,60678,3681042,56949,538572,22996,6437,...,1647,860,217392,13621,6274,2310,2741,2063,208377,12926
67,Utah,2894001,2899,2407608,16818,374578,14902,90234,8541,365,...,3750,1552,21581,3132,280,212,0,184,21301,3098
68,Vermont,620898,883,536915,4667,59850,3939,22635,2419,0,...,29,49,1498,664,0,147,0,147,1498,664
69,Virginia,8224054,4721,6891144,29452,995822,26452,262477,12503,2654,...,147,179,74611,6633,1922,957,266,324,72423,6709
71,Washington,6979369,3884,5757065,26180,934922,23276,220259,13044,1640,...,1383,1026,67123,6824,728,547,1034,614,65361,6706
72,West Virginia,1831414,2060,1617510,10136,162340,9214,47957,4807,144,...,0,187,3607,1128,0,187,0,187,3607,1128
73,Wisconsin,5692727,3347,4868506,18280,688104,17604,117831,7616,452,...,16,24,18286,2702,937,749,48,79,17301,2549
74,Wyoming,577782,1222,475740,7103,74601,6250,25992,3696,254,...,0,0,1449,876,0,190,0,190,1449,876
76,Puerto Rico,3511186,3157,3251389,13399,237197,12111,19771,2798,50,...,0,220,2829,886,N/A3,N/A3,0,220,2829,886


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [17]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),315095393,4791931,725206,6651964,2931123,38340324,5293943,3558915,924770,648586,...,6471445,26588600,2894001,620898,8224054,6979369,1831414,5692727,577782,3511186
Population 1 year and over (MOE),26923,4065,1461,4638,2667,10835,3847,2621,1262,1757,...,3711,10391,2899,883,4721,3884,2060,3347,1222,3157
Same house 1 year ago (Estimate),268147625,4081522,585916,5431241,2464189,32849251,4263998,3111779,810905,513634,...,5465071,22151594,2407608,536915,6891144,5757065,1617510,4868506,475740,3251389
Same house 1 year ago (MOE),208630,22252,7276,29624,16201,61601,25609,13932,7547,7913,...,20831,60678,16818,4667,29452,26180,10136,18280,7103,13399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago: Puerto Rico (MOE),8510,319,73,633,173,1748,385,2202,306,66,...,361,2310,212,147,957,547,187,749,190,N/A3
Abroad 1 year ago: U.S. Island Area (Estimate),16858,46,0,332,241,1752,765,82,0,148,...,145,2741,0,0,266,1034,0,48,0,0
Abroad 1 year ago: U.S. Island Area (MOE),3642,79,145,296,249,1097,864,121,185,152,...,238,2063,184,147,324,614,187,79,190,220
Abroad 1 year ago: Foreign Country (Estimate),1941503,12913,3972,47853,8717,311952,32411,25891,4181,11245,...,27149,208377,21301,1498,72423,65361,3607,17301,1449,2829
Abroad 1 year ago: Foreign Country (MOE),30408,2648,1205,5605,2536,11956,4654,4203,1250,2226,...,3735,12926,3098,664,6709,6706,1128,2549,876,886

In [18]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [19]:

df = df.iloc[1:]

df

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),315095393,4791931,725206,6651964,2931123,38340324,5293943,3558915,924770,648586,...,6471445,26588600,2894001,620898,8224054,6979369,1831414,5692727,577782,3511186
Population 1 year and over (MOE),26923,4065,1461,4638,2667,10835,3847,2621,1262,1757,...,3711,10391,2899,883,4721,3884,2060,3347,1222,3157
Same house 1 year ago (Estimate),268147625,4081522,585916,5431241,2464189,32849251,4263998,3111779,810905,513634,...,5465071,22151594,2407608,536915,6891144,5757065,1617510,4868506,475740,3251389
Same house 1 year ago (MOE),208630,22252,7276,29624,16201,61601,25609,13932,7547,7913,...,20831,60678,16818,4667,29452,26180,10136,18280,7103,13399
Same state of residence 1 year ago (Estimate),37571394,589211,97358,922129,383087,4659084,777699,334207,77246,67286,...,796577,3681042,374578,59850,995822,934922,162340,688104,74601,237197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago: Puerto Rico (MOE),8510,319,73,633,173,1748,385,2202,306,66,...,361,2310,212,147,957,547,187,749,190,N/A3
Abroad 1 year ago: U.S. Island Area (Estimate),16858,46,0,332,241,1752,765,82,0,148,...,145,2741,0,0,266,1034,0,48,0,0
Abroad 1 year ago: U.S. Island Area (MOE),3642,79,145,296,249,1097,864,121,185,152,...,238,2063,184,147,324,614,187,79,190,220
Abroad 1 year ago: Foreign Country (Estimate),1941503,12913,3972,47853,8717,311952,32411,25891,4181,11245,...,27149,208377,21301,1498,72423,65361,3607,17301,1449,2829
Abroad 1 year ago: Foreign Country (MOE),30408,2648,1205,5605,2536,11956,4654,4203,1250,2226,...,3735,12926,3098,664,6709,6706,1128,2549,876,886

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [20]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [21]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [22]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Population 1 year and over (Estimate)                             648586
Same house 1 year ago (Estimate)                                  513634
Same state of residence 1 year ago (Estimate)                      67286
Different state of residence 1 year ago: Total ...                 56234
Different state of residence 1 year ago: Alabam...                   251
Different state of residence 1 year ago (contin...                    92
Different state of residence 1 year ago (contin...                   186
Different state of residence 1 year ago (contin...                   106
Different state of residence 1 year ago (contin...                  5206
Different state of residence 1 year ago (contin...                   476
Different state of residence 1 year ago (contin...                  1336
Different state of residence 1 year ago (contin...                   290
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  1745
Different state of residence 1 year ago (contin...                   445
Different state of residence 1 year ago (contin...                   283
Different state of residence 1 year ago (contin...                   229
Different state of residence 1 year ago (contin...                  1768
Different state of residence 1 year ago (contin...                   525
Different state of residence 1 year ago (contin...                    96
Different state of residence 1 year ago (contin...                   133
Different state of residence 1 year ago (contin...                   375
Different state of residence 1 year ago (contin...                   689
Different state of residence 1 year ago (contin...                   167
Different state of residence 1 year ago (contin...                 13606
Different state of residence 1 year ago (contin...                  1575
Different state of residence 1 year ago (contin...                   334
Different state of residence 1 year ago (contin...                   414
Different state of residence 1 year ago (contin...                    71
Different state of residence 1 year ago (contin...                   195
Different state of residence 1 year ago (contin...                    84
Different state of residence 1 year ago (contin...                   111
Different state of residence 1 year ago (contin...                   593
Different state of residence 1 year ago (contin...                   154
Different state of residence 1 year ago (contin...                  2075
Different state of residence 1 year ago (contin...                    76
Different state of residence 1 year ago (contin...                  3562
Different state of residence 1 year ago (contin...                  1670
Different state of residence 1 year ago (contin...                    44
Different state of residence 1 year ago (contin...                   286
Different state of residence 1 year ago (contin...                    78
Different state of residence 1 year ago (contin...                   130
Different state of residence 1 year ago (contin...                  2311
Different state of residence 1 year ago (contin...                   125
Different state of residence 1 year ago (contin...                   389
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   429
Different state of residence 1 year ago (contin...                  1311
Different state of residence 1 year ago (contin...                   445
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  9920
Different state of residence 1 year ago (contin...                  1089
Different state of residence 1 year ago (contin...                   213
Different state of residence 1 year ago (contin...                   291
Different state of residence 1 year ago (contin...                   255
Abroad 1 year ago: Total (Estimate)                                11432
Abroad 1 year ago: Puerto Rico (Estimate)                             39
Abroad 1 year ago: U.S. Island Area (Estimate)                       148
Abroad 1 year ago: Foreign Country (Estimate)                      11245

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [23]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

Cut off the top columns that arent for specific states, as well as the last few that are for PR, US Islands, Foreign Country, and total

In [24]:
df

0                                              District of Columbia
Population 1 year and over (Estimate)                         648586
Population 1 year and over (MOE)                                1757
Same house 1 year ago (Estimate)                              513634
Same house 1 year ago (MOE)                                     7913
Same state of residence 1 year ago (Estimate)                  67286
...                                                              ...
Abroad 1 year ago: Puerto Rico (MOE)                              66
Abroad 1 year ago: U.S. Island Area (Estimate)                   148
Abroad 1 year ago: U.S. Island Area (MOE)                        152
Abroad 1 year ago: Foreign Country (Estimate)                  11245
Abroad 1 year ago: Foreign Country (MOE)                        2226

[118 rows x 1 columns]

In [25]:

df_estimates = df_estimates[4:-4]
df_moes = df_moes[4:-4]

In [27]:
df_moes.tail()

0             District of Columbia
0
Virginia                       1665
Washington                      826
West Virginia                   167
Wisconsin                       234
Wyoming                         400

In [23]:
df_estimates.head()

0          District of Columbia
0
Alabama                      316
Alaska                       579
Arizona                       79
Arkansas                       0
California                  2427

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [28]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

also need to drop the top row of pops df to get the dataframes to have the same row indices

In [30]:
df_pops = df_pops.drop('Label (Grouping)')

Now I'm adding a state polulation column to my newly formatted table

In [31]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [32]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

df.head()

0          pop_migrated MOE +/- state_population
0
Alabama             251     232        5,024,279
Alaska               92     110          733,391
Arizona             186     206        7,151,502
Arkansas            106     172        3,011,524
California         5206    1239       39,538,223

And strip commas in state_population column

In [33]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [34]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       251     232          5024279
Alaska                         92     110           733391
Arizona                       186     206          7151502
Arkansas                      106     172          3011524
California                   5206    1239         39538223
Colorado                      476     259          5773714
Connecticut                  1336     599          3605944
Delaware                      290     273           989948
District of Columbia            0       0           689545
Florida                      1745     681         21538187
Georgia                       445     285         10711908
Hawaii                        283     377          1455271
Idaho                         229     241          1839106
Illinois                     1768     846         12812508
Indiana                       525     343          6785528
Iowa                           96     153          3190369
Kansas                        133     145          2937880
Kentucky                      375     348          4505836
Louisiana                     689     493          4657757
Maine                         167     185          1362359
Maryland                    13606    2527          6177224
Massachusetts                1575     659          7029917
Michigan                      334     236         10077331
Minnesota                     414     283          5706494
Mississippi                    71     118          2961279
Missouri                      195     181          6154913
Montana                        84     137          1084225
Nebraska                      111      93          1961504
Nevada                        593     817          3104614
New Hampshire                 154     159          1377529
New Jersey                   2075     662          9288994
New Mexico                     76     104          2117522
New York                     3562    1035         20201249
North Carolina               1670     629         10439388
North Dakota                   44      73           779094
Ohio                          286     205         11799448
Oklahoma                       78     130          3959353
Oregon                        130     153          4237256
Pennsylvania                 2311     798         13002700
Rhode Island                  125     171          1097379
South Carolina                389     253          5118425
South Dakota                    0     198           886667
Tennessee                     429     307          6910840
Texas                        1311     609         29145505
Utah                          445     414          3271616
Vermont                         0     198           643077
Virginia                     9920    1665          8631393
Washington                   1089     826          7705281
West Virginia                 213     167          1793716
Wisconsin                     291     234          5893718
Wyoming                       255     400           576851

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [35]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [36]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [37]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,251,232,5024279,0.000050,0.000046
1,Alaska,92,110,733391,0.000125,0.000150
2,Arizona,186,206,7151502,0.000026,0.000029
3,Arkansas,106,172,3011524,0.000035,0.000057
4,California,5206,1239,39538223,0.000132,0.000031

Looking at states with most people coming to DC

In [38]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
20,Maryland,13606,2527,6177224,0.002203,0.000409
46,Virginia,9920,1665,8631393,0.001149,0.000193
50,Wyoming,255,400,576851,0.000442,0.000693
6,Connecticut,1336,599,3605944,0.000370,0.000166
7,Delaware,290,273,989948,0.000293,0.000276
21,Massachusetts,1575,659,7029917,0.000224,0.000094
30,New Jersey,2075,662,9288994,0.000223,0.000071
11,Hawaii,283,377,1455271,0.000194,0.000259
28,Nevada,593,817,3104614,0.000191,0.000263
38,Pennsylvania,2311,798,13002700,0.000178,0.000061

To export, want to make a slice excluding all DMV states -- Maryland, Virginia, DC

Also need to exclude PR because I'm just doing continental US

In [39]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]
df = df[df["state"] != "District of Columbia"]

Now need to reset the indexes again to make numbers consecutive now that I've removed ceratin rows.

In [40]:
df = df.reset_index(drop=True)

Now add in 2012 election winners for each state

First, read in file

In [41]:
df_2012_election_winners = pd.read_csv('pres-election-results-2012.csv')

type(df_2012_election_winners)

pandas.DataFrame

Next, add winning party and percent of votes columns

In [42]:
df_2012_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

df_2012_election_winners.head(20)

            state  year party_detailed  percent_total_votes
0         Alabama  2012     REPUBLICAN             0.605458
1          Alaska  2012     REPUBLICAN             0.548016
2         Arizona  2012     REPUBLICAN             0.536545
3        Arkansas  2012     REPUBLICAN             0.605669
4      California  2012       DEMOCRAT             0.602390
5        Colorado  2012       DEMOCRAT             0.514922
6     Connecticut  2012       DEMOCRAT             0.580850
7        Delaware  2012       DEMOCRAT             0.586107
8         Florida  2012       DEMOCRAT             0.500079
9         Georgia  2012     REPUBLICAN             0.533292
10         Hawaii  2012       DEMOCRAT             0.701479
11          Idaho  2012     REPUBLICAN             0.645298
12       Illinois  2012       DEMOCRAT             0.576021
13        Indiana  2012     REPUBLICAN             0.541255
14           Iowa  2012       DEMOCRAT             0.519880
15         Kansas  2012     REPUBLICAN             0.597113
16       Kentucky  2012     REPUBLICAN             0.604931
17      Louisiana  2012     REPUBLICAN             0.577846
18          Maine  2012       DEMOCRAT             0.553710
19  Massachusetts  2012       DEMOCRAT             0.603383

In [40]:
df['winning_party'] = df_2012_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2012_election_winners['percent_total_votes']

df.head(50)

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,316,217,5024279,6.289460e-05,0.000043,REPUBLICAN,0.605458
1,Alaska,579,658,733391,7.894834e-04,0.000897,REPUBLICAN,0.548016
2,Arizona,79,130,7151502,1.104663e-05,0.000018,REPUBLICAN,0.536545
3,Arkansas,0,192,3011524,0.000000e+00,0.000064,REPUBLICAN,0.605669
4,California,2427,847,39538223,6.138364e-05,0.000021,DEMOCRAT,0.602390
5,Colorado,337,242,5773714,5.836798e-05,0.000042,DEMOCRAT,0.514922
6,Connecticut,1597,631,3605944,4.428799e-04,0.000175,DEMOCRAT,0.580850
7,Delaware,336,254,989948,3.394118e-04,0.000257,DEMOCRAT,0.586107
8,Florida,1307,640,21538187,6.068292e-05,0.000030,DEMOCRAT,0.500079
9,Georgia,1497,599,10711908,1.397510e-04,0.000056,REPUBLICAN,0.533292
10,Hawaii,339,526,1455271,2.329463e-04,0.000361,DEMOCRAT,0.701479
11,Idaho,0,193,1839106,0.000000e+00,0.000105,REPUBLICAN,0.645298
12,Illinois,753,398,12812508,5.877070e-05,0.000031,DEMOCRAT,0.576021
13,Indiana,215,199,6785528,3.168508e-05,0.000029,REPUBLICAN,0.541255
14,Iowa,27,46,3190369,8.462971e-06,0.000014,DEMOCRAT,0.519880
15,Kansas,0,170,2937880,0.000000e+00,0.000058,REPUBLICAN,0.597113
16,Kentucky,46,71,4505836,1.020898e-05,0.000016,REPUBLICAN,0.604931
17,Louisiana,858,475,4657757,1.842088e-04,0.000102,REPUBLICAN,0.577846
18,Maine,0,165,1362359,0.000000e+00,0.000121,DEMOCRAT,0.553710
19,Massachusetts,1557,616,7029917,2.214820e-04,0.000088,DEMOCRAT,0.603383
20,Michigan,622,325,10077331,6.172269e-05,0.000032,DEMOCRAT,0.542082
21,Minnesota,0,145,5706494,0.000000e+00,0.000025,REPUBLICAN,0.449582
22,Mississippi,0,208,2961279,0.000000e+00,0.000070,REPUBLICAN,0.552858
23,Missouri,278,219,6154913,4.516717e-05,0.000036,REPUBLICAN,0.537637
24,Montana,44,75,1084225,4.058198e-05,0.000069,REPUBLICAN,0.553515
25,Nebraska,22,38,1961504,1.121588e-05,0.000019,REPUBLICAN,0.598032
26,Nevada,0,206,3104614,0.000000e+00,0.000066,DEMOCRAT,0.523562
27,New Hampshire,108,139,1377529,7.840125e-05,0.000101,DEMOCRAT,0.519797
28,New Jersey,2173,949,9288994,2.339328e-04,0.000102,DEMOCRAT,0.583424
29,New Mexico,411,481,2117522,1.940948e-04,0.000227,DEMOCRAT,0.529928
30,New York,4770,1660,20201249,2.361240e-04,0.000082,DEMOCRAT,0.607610
31,North Carolina,1253,452,10439388,1.200262e-04,0.000043,REPUBLICAN,0.503931
32,North Dakota,0,149,779094,0.000000e+00,0.000191,REPUBLICAN,0.583157
33,Ohio,315,262,11799448,2.669616e-05,0.000022,DEMOCRAT,0.506667
34,Oklahoma,155,193,3959353,3.914781e-05,0.000049,REPUBLICAN,0.667723
35,Oregon,194,259,4237256,4.578435e-05,0.000061,DEMOCRAT,0.542393
36,Pennsylvania,2177,791,13002700,1.674268e-04,0.000061,DEMOCRAT,0.520769
37,Rhode Island,1150,864,1097379,1.047952e-03,0.000787,DEMOCRAT,0.627010
38,South Carolina,506,316,5118425,9.885854e-05,0.000062,REPUBLICAN,0.545611
39,South Dakota,203,246,886667,2.289473e-04,0.000277,REPUBLICAN,0.578893
40,Tennessee,560,408,6910840,8.103212e-05,0.000059,REPUBLICAN,0.594787
41,Texas,1625,716,29145505,5.575474e-05,0.000025,REPUBLICAN,0.571670
42,Utah,126,158,3271616,3.851308e-05,0.000048,REPUBLICAN,0.727905
43,Vermont,0,151,643077,0.000000e+00,0.000235,DEMOCRAT,0.665706
44,Washington,159,152,7705281,2.063520e-05,0.000020,DEMOCRAT,0.561634
45,West Virginia,391,245,1793716,2.179832e-04,0.000137,REPUBLICAN,0.622958
46,Wisconsin,5,12,5893718,8.483609e-07,0.000002,DEMOCRAT,0.527762
47,Wyoming,3,9,576851,5.200650e-06,0.000016,REPUBLICAN,0.681936

Check that indexes match

In [43]:
df_2012_election_winners.reset_index(drop=True)

             state  year party_detailed  percent_total_votes
0          Alabama  2012     REPUBLICAN             0.605458
1           Alaska  2012     REPUBLICAN             0.548016
2          Arizona  2012     REPUBLICAN             0.536545
3         Arkansas  2012     REPUBLICAN             0.605669
4       California  2012       DEMOCRAT             0.602390
5         Colorado  2012       DEMOCRAT             0.514922
6      Connecticut  2012       DEMOCRAT             0.580850
7         Delaware  2012       DEMOCRAT             0.586107
8          Florida  2012       DEMOCRAT             0.500079
9          Georgia  2012     REPUBLICAN             0.533292
10          Hawaii  2012       DEMOCRAT             0.701479
11           Idaho  2012     REPUBLICAN             0.645298
12        Illinois  2012       DEMOCRAT             0.576021
13         Indiana  2012     REPUBLICAN             0.541255
14            Iowa  2012       DEMOCRAT             0.519880
15          Kansas  2012     REPUBLICAN             0.597113
16        Kentucky  2012     REPUBLICAN             0.604931
17       Louisiana  2012     REPUBLICAN             0.577846
18           Maine  2012       DEMOCRAT             0.553710
19   Massachusetts  2012       DEMOCRAT             0.603383
20        Michigan  2012       DEMOCRAT             0.542082
21       Minnesota  2012     REPUBLICAN             0.449582
22     Mississippi  2012     REPUBLICAN             0.552858
23        Missouri  2012     REPUBLICAN             0.537637
24         Montana  2012     REPUBLICAN             0.553515
25        Nebraska  2012     REPUBLICAN             0.598032
26          Nevada  2012       DEMOCRAT             0.523562
27   New Hampshire  2012       DEMOCRAT             0.519797
28      New Jersey  2012       DEMOCRAT             0.583424
29      New Mexico  2012       DEMOCRAT             0.529928
30        New York  2012       DEMOCRAT             0.607610
31  North Carolina  2012     REPUBLICAN             0.503931
32    North Dakota  2012     REPUBLICAN             0.583157
33            Ohio  2012       DEMOCRAT             0.506667
34        Oklahoma  2012     REPUBLICAN             0.667723
35          Oregon  2012       DEMOCRAT             0.542393
36    Pennsylvania  2012       DEMOCRAT             0.520769
37    Rhode Island  2012       DEMOCRAT             0.627010
38  South Carolina  2012     REPUBLICAN             0.545611
39    South Dakota  2012     REPUBLICAN             0.578893
40       Tennessee  2012     REPUBLICAN             0.594787
41           Texas  2012     REPUBLICAN             0.571670
42            Utah  2012     REPUBLICAN             0.727905
43         Vermont  2012       DEMOCRAT             0.665706
44      Washington  2012       DEMOCRAT             0.561634
45   West Virginia  2012     REPUBLICAN             0.622958
46       Wisconsin  2012       DEMOCRAT             0.527762
47         Wyoming  2012     REPUBLICAN             0.681936

In [44]:
df_2012_election_winners.index

RangeIndex(start=0, stop=48, step=1)

In [45]:
df.index

RangeIndex(start=0, stop=48, step=1)

Save as csv file

In [46]:
df.to_csv('DC-migration-2014.csv')