I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA State_to_State_Migrations_Table_2019.xls')

In [3]:
df.shape

(86, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.tail(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
57,Oklahoma,3907258,3062,3282746,16542,509137,16246,101844,8145,241,...,230,Oklahoma,13531,2029,741,622,0,165,12790,1977
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Oregon,4178578,4124,3527178,21443,501680,19322,129921,8055,162,...,794,Oregon,19799,3795,0,211,35,56,19764,3788
60,Pennsylvania,12670245,5785,11092255,37657,1259103,30402,267465,13835,1898,...,39,Pennsylvania,51422,5753,4028,1760,61,91,47333,5549
61,Rhode Island,1050602,1636,930406,10263,80686,8479,34984,4117,0,...,222,Rhode Island,4526,1436,113,144,150,153,4263,1433
62,South Carolina,5092727,4254,4414770,17856,478892,15019,176008,12536,873,...,218,South Carolina,23057,4477,1491,1150,319,297,21247,4160
63,South Dakota,872708,1720,739009,8766,102133,7228,26934,3576,339,...,288,South Dakota,4632,2854,682,735,0,167,3950,2747
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Tennessee,6754461,5775,5782145,24958,755183,25187,196765,12436,6294,...,60,Tennessee,20368,3408,24,33,255,285,20089,3434
66,Texas,28642658,11223,24347958,68604,3517954,58641,559661,22968,8791,...,975,Texas,217085,16079,9352,6440,371,400,207362,15174
67,Utah,3162102,3623,2661654,18895,389057,16224,95608,8887,1027,...,1009,Utah,15783,3314,96,162,107,151,15580,3310
68,Vermont,617560,1135,536752,5121,57776,5025,21212,2444,77,...,63,Vermont,1820,802,3,0,0,161,1817,802
69,Virginia,8439982,5417,7201805,28265,903735,27129,264855,11921,4028,...,233,Virginia,69587,8320,1896,1190,185,182,67506,8067
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Washington,7527366,5600,6253469,28478,977928,24801,231956,14786,1060,...,486,Washington,64013,6368,318,312,1465,950,62230,6446
72,West Virginia,1773280,1883,1563611,12229,164739,10870,39548,4719,245,...,207,West Virginia,5382,2146,606,528,0,207,4776,2098
73,Wisconsin,5760481,3237,5001140,19911,634732,17869,107973,7285,678,...,1826,Wisconsin,16636,3451,513,479,0,153,16123,3375
74,Wyoming,572884,1076,473128,8091,68127,6867,30247,4333,1227,...,NaN,Wyoming,1382,597,0,207,0,207,1382,597
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Puerto Rico,3175835,2114,2968876,10447,169733,8644,31144,5397,141,...,234,Puerto Rico,6082,1846,NaN,NaN,342,343,5740,1845

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,324665523,30094,280343146,195001,35013848,178044,7398337,64485,98704,...,4468,United States2,1910192,39481,66021,9911,15276,3033,1828895,40180
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4849509,3840,4197698,21706,534842,20556,104780,8007,NaN,...,206,Alabama,12189,2368,338,500,103,136,11748,2284
11,Alaska,722063,1360,609362,7734,74375,6681,34031,4202,260,...,196,Alaska,4295,1721,37,61,17,30,4241,1718
12,Arizona,7200620,6015,6038776,31879,861935,26584,253295,12249,1750,...,434,Arizona,46614,6437,970,909,152,167,45492,6240
13,Arkansas,2989054,2800,2559444,15248,361762,13847,59723,6369,636,...,1536,Arkansas,8125,2729,302,446,0,206,7823,2588
14,California,39084048,10760,34394220,68574,3943139,61711,480204,18764,3310,...,593,California,266485,12302,1780,1200,2887,1563,261818,11940
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5701658,4038,4695821,22285,736314,20685,240600,13693,3422,...,1317,Colorado,28923,4248,642,588,83,118,28198,4222
17,Connecticut,3531986,2674,3106754,20309,306070,16102,90044,7706,248,...,213,Connecticut,29118,5148,4280,2751,0,213,24838,4328
18,Delaware,964817,1555,843383,9324,79186,7262,38014,5368,0,...,203,Delaware,4234,1392,0,203,0,203,4234,1392
19,District of Columbia,697556,1657,563798,6607,64893,5923,58879,5115,462,...,218,District of Columbia,9986,2121,213,268,0,218,9773,2102
20,Florida,21269409,9193,18083185,55882,2381208,48207,601611,24764,15153,...,379,Florida,203405,12920,14657,3664,2422,1490,186326,12287
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,10499808,6442,9034705,37468,1130068,30378,284541,17311,14169,...,709,Georgia,50494,6109,1906,1008,359,322,48229,5897
23,Hawaii,1396819,2070,1215974,11310,116566,10726,49708,5198,502,...,195,Hawaii,14571,2803,204,215,442,331,13925,2764

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,324665523,30094,280343146,195001,35013848,178044,7398337,64485,98704,...,4468,United States2,1910192,39481,66021,9911,15276,3033,1828895,40180
10,Alabama,4849509,3840,4197698,21706,534842,20556,104780,8007,NaN,...,206,Alabama,12189,2368,338,500,103,136,11748,2284
11,Alaska,722063,1360,609362,7734,74375,6681,34031,4202,260,...,196,Alaska,4295,1721,37,61,17,30,4241,1718
12,Arizona,7200620,6015,6038776,31879,861935,26584,253295,12249,1750,...,434,Arizona,46614,6437,970,909,152,167,45492,6240
13,Arkansas,2989054,2800,2559444,15248,361762,13847,59723,6369,636,...,1536,Arkansas,8125,2729,302,446,0,206,7823,2588
14,California,39084048,10760,34394220,68574,3943139,61711,480204,18764,3310,...,593,California,266485,12302,1780,1200,2887,1563,261818,11940
16,Colorado,5701658,4038,4695821,22285,736314,20685,240600,13693,3422,...,1317,Colorado,28923,4248,642,588,83,118,28198,4222
17,Connecticut,3531986,2674,3106754,20309,306070,16102,90044,7706,248,...,213,Connecticut,29118,5148,4280,2751,0,213,24838,4328
18,Delaware,964817,1555,843383,9324,79186,7262,38014,5368,0,...,203,Delaware,4234,1392,0,203,0,203,4234,1392
19,District of Columbia,697556,1657,563798,6607,64893,5923,58879,5115,462,...,218,District of Columbia,9986,2121,213,268,0,218,9773,2102
20,Florida,21269409,9193,18083185,55882,2381208,48207,601611,24764,15153,...,379,Florida,203405,12920,14657,3664,2422,1490,186326,12287
22,Georgia,10499808,6442,9034705,37468,1130068,30378,284541,17311,14169,...,709,Georgia,50494,6109,1906,1008,359,322,48229,5897
23,Hawaii,1396819,2070,1215974,11310,116566,10726,49708,5198,502,...,195,Hawaii,14571,2803,204,215,442,331,13925,2764
24,Idaho,1764327,2658,1478739,13896,200377,10899,78730,8348,19,...,570,Idaho,6481,1992,0,204,0,204,6481,1992
25,Illinois,12536539,5997,11014059,33734,1274091,32339,190627,9364,1658,...,134,Illinois,57762,6136,714,417,263,268,56785,6138
26,Indiana,6656971,4247,5735703,24925,743092,21982,151443,10303,1481,...,187,Indiana,26733,4175,136,164,0,201,26597,4177
28,Iowa,3121385,2383,2686528,13620,348082,11253,72651,6363,70,...,398,Iowa,14124,3807,0,165,0,165,14124,3807

Rename columns to be clearer numbers

In [9]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '120', '121', '122', '123', '124', '125', '126', '127', '128', '129'],
      dtype='str', length=130)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [10]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

df

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,324665523,30094,280343146,195001,35013848,178044,7398337,64485,98704,...,23287,4468,1910192,39481,66021,9911,15276,3033,1828895,40180
10,Alabama,4849509,3840,4197698,21706,534842,20556,104780,8007,NaN,...,0,206,12189,2368,338,500,103,136,11748,2284
11,Alaska,722063,1360,609362,7734,74375,6681,34031,4202,260,...,242,196,4295,1721,37,61,17,30,4241,1718
12,Arizona,7200620,6015,6038776,31879,861935,26584,253295,12249,1750,...,664,434,46614,6437,970,909,152,167,45492,6240
13,Arkansas,2989054,2800,2559444,15248,361762,13847,59723,6369,636,...,1109,1536,8125,2729,302,446,0,206,7823,2588
14,California,39084048,10760,34394220,68574,3943139,61711,480204,18764,3310,...,1159,593,266485,12302,1780,1200,2887,1563,261818,11940
16,Colorado,5701658,4038,4695821,22285,736314,20685,240600,13693,3422,...,3860,1317,28923,4248,642,588,83,118,28198,4222
17,Connecticut,3531986,2674,3106754,20309,306070,16102,90044,7706,248,...,0,213,29118,5148,4280,2751,0,213,24838,4328
18,Delaware,964817,1555,843383,9324,79186,7262,38014,5368,0,...,0,203,4234,1392,0,203,0,203,4234,1392
19,District of Columbia,697556,1657,563798,6607,64893,5923,58879,5115,462,...,0,218,9986,2121,213,268,0,218,9773,2102
20,Florida,21269409,9193,18083185,55882,2381208,48207,601611,24764,15153,...,624,379,203405,12920,14657,3664,2422,1490,186326,12287
22,Georgia,10499808,6442,9034705,37468,1130068,30378,284541,17311,14169,...,968,709,50494,6109,1906,1008,359,322,48229,5897
23,Hawaii,1396819,2070,1215974,11310,116566,10726,49708,5198,502,...,0,195,14571,2803,204,215,442,331,13925,2764
24,Idaho,1764327,2658,1478739,13896,200377,10899,78730,8348,19,...,662,570,6481,1992,0,204,0,204,6481,1992
25,Illinois,12536539,5997,11014059,33734,1274091,32339,190627,9364,1658,...,109,134,57762,6136,714,417,263,268,56785,6138
26,Indiana,6656971,4247,5735703,24925,743092,21982,151443,10303,1481,...,118,187,26733,4175,136,164,0,201,26597,4177
28,Iowa,3121385,2383,2686528,13620,348082,11253,72651,6363,70,...,434,398,14124,3807,0,165,0,165,14124,3807
29,Kansas,2879518,2733,2426897,15581,345003,14805,94648,7695,1021,...,442,498,12970,2130,696,693,81,131,12193,2149
30,Kentucky,4421512,3469,3792437,21452,517128,18788,100057,10239,4390,...,0,201,11890,2192,92,124,0,201,11798,2195
31,Louisiana,4595111,4260,4018892,25759,491341,24641,67640,7320,2567,...,0,224,17238,3354,1165,1146,673,562,15400,3053
32,Maine,1331656,1983,1162558,8967,128105,8448,36129,3260,73,...,88,149,4864,1475,73,120,212,273,4579,1429
34,Maryland,5979602,4528,5224363,24311,569388,21673,141766,8795,1597,...,0,210,44085,5105,602,324,837,882,42646,5070
35,Massachusetts,6828110,4238,5975607,27342,644535,24113,144079,7664,1099,...,154,188,63889,7028,3043,1827,226,282,60620,6975
36,Michigan,9880758,5117,8606216,30908,1104190,27697,132008,7968,1997,...,139,139,38344,4270,990,557,80,89,37274,4259
37,Minnesota,5575235,3626,4836702,17149,606228,16532,106920,6956,433,...,207,252,25385,4728,29,47,330,296,25026,4714
38,Mississippi,2943737,2940,2583691,16717,291479,15906,61683,5919,3512,...,0,226,6884,1793,922,857,331,342,5631,1599
40,Missouri,6069697,3822,5200465,21972,694303,21399,152345,7192,2246,...,45,75,22584,3378,1109,677,593,681,20882,3115
41,Montana,1056994,1671,882156,9661,129779,8239,40862,4320,400,...,1662,795,4197,1406,11,20,0,177,4186,1405
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
45,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1910711,2177,1622237,11308,234322,10825,46064,5500,812,...,1000,602,8088,1897,122,156,0,165,7966,1851
48,Nevada,3048602,3454,2510591,20990,384676,17510,132950,9071,239,...,46,68,20385,5121,255,294,302,488,19828,5300
49,New Hampshire,1350155,1461,1173997,9472,119189,8363,50288,5067,379,...,0,195,6681,2263,475,529,0,195,6206,2118
50,New Jersey,8791672,5050,7888800,24045,689445,21026,149260,9572,357,...,0,213,64167,7967,3036,1978,305,315,60826,7820
51,New Mexico,2073628,2569,1816418,14704,189705,11524,55545,7590,751,...,1451,1198,11960,3086,217,378,0,210,11743,3102
53,New York,19240920,8850,17213380,32096,1638372,30677,254806,11785,851,...,72,88,134362,9596,1868,797,282,235,132212,9543
54,North Carolina,10371906,6477,8834381,37378,1170200,31849,315215,16391,4697,...,161,239,52110,6058,1986,1123,560,683,49564,5981
55,North Dakota,750501,1733,615450,9766,94413,7276,36668,5643,0,...,730,578,3970,1479,593,753,63,127,3314,1287
56,Ohio,11556037,5443,9891733,33048,1415185,32853,205542,11006,1203,...,492,512,43577,5314,2695,1439,725,1006,40157,4903
57,Oklahoma,3907258,3062,3282746,16542,509137,16246,101844,8145,241,...,326,230,13531,2029,741,622,0,165,12790,1977
59,Oregon,4178578,4124,3527178,21443,501680,19322,129921,8055,162,...,680,794,19799,3795,0,211,35,56,19764,3788
60,Pennsylvania,12670245,5785,11092255,37657,1259103,30402,267465,13835,1898,...,24,39,51422,5753,4028,1760,61,91,47333,5549
61,Rhode Island,1050602,1636,930406,10263,80686,8479,34984,4117,0,...,0,222,4526,1436,113,144,150,153,4263,1433
62,South Carolina,5092727,4254,4414770,17856,478892,15019,176008,12536,873,...,0,218,23057,4477,1491,1150,319,297,21247,4160
63,South Dakota,872708,1720,739009,8766,102133,7228,26934,3576,339,...,473,288,4632,2854,682,735,0,167,3950,2747
65,Tennessee,6754461,5775,5782145,24958,755183,25187,196765,12436,6294,...,46,60,20368,3408,24,33,255,285,20089,3434
66,Texas,28642658,11223,24347958,68604,3517954,58641,559661,22968,8791,...,1311,975,217085,16079,9352,6440,371,400,207362,15174
67,Utah,3162102,3623,2661654,18895,389057,16224,95608,8887,1027,...,1549,1009,15783,3314,96,162,107,151,15580,3310
68,Vermont,617560,1135,536752,5121,57776,5025,21212,2444,77,...,30,63,1820,802,3,0,0,161,1817,802
69,Virginia,8439982,5417,7201805,28265,903735,27129,264855,11921,4028,...,167,233,69587,8320,1896,1190,185,182,67506,8067
71,Washington,7527366,5600,6253469,28478,977928,24801,231956,14786,1060,...,626,486,64013,6368,318,312,1465,950,62230,6446
72,West Virginia,1773280,1883,1563611,12229,164739,10870,39548,4719,245,...,0,207,5382,2146,606,528,0,207,4776,2098
73,Wisconsin,5760481,3237,5001140,19911,634732,17869,107973,7285,678,...,1417,1826,16636,3451,513,479,0,153,16123,3375
74,Wyoming,572884,1076,473128,8091,68127,6867,30247,4333,1227,...,NaN,NaN,1382,597,0,207,0,207,1382,597
76,Puerto Rico,3175835,2114,2968876,10447,169733,8644,31144,5397,141,...,0,234,6082,1846,NaN,NaN,342,343,5740,1845

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [11]:
df.iloc[3:] = df.iloc[3:].fillna('0')

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#first, dealing with columns B-G/1-6)

column_1_name = f'{df.iloc[0, 1]} ({df.iloc[2, 1]})'
column_2_name = f'{df.iloc[0, 1]} ({df.iloc[2, 2]})'

column_3_name = f'{df.iloc[0, 3]} ({df.iloc[2, 3]})'
column_4_name = f'{df.iloc[0, 3]} ({df.iloc[2, 4]})'

column_5_name = f'{df.iloc[0, 5]} ({df.iloc[2, 5]})'
column_6_name = f'{df.iloc[0, 5]} ({df.iloc[2, 6]})'

df_clean = df.rename(columns ={
    '1': column_1_name,
    '2': column_2_name,
    '3': column_3_name,
    '4': column_4_name,
    '5': column_5_name,
    '6': column_6_name})

#next, for the rest of the columns:
#first, fill in blanks

df_filledin = df_clean.ffill(axis=1)

#then pull the info I need to name each column

for i in range(7, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [13]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Population 1 year and over (Estimate),Population 1 year and over (MOE),Same house 1 year ago (Estimate),Same house 1 year ago (MOE),Same state of residence 1 year ago (Estimate),Same state of residence 1 year ago (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (continued): Wyoming (Estimate),Different state of residence 1 year ago (continued): Wyoming (MOE),Abroad 1 year ago: Total (Estimate),Abroad 1 year ago: Total (MOE),Abroad 1 year ago: Puerto Rico (Estimate),Abroad 1 year ago: Puerto Rico (MOE),Abroad 1 year ago: U.S. Island Area (Estimate),Abroad 1 year ago: U.S. Island Area (MOE),Abroad 1 year ago: Foreign Country (Estimate),Abroad 1 year ago: Foreign Country (MOE)
53,New York,19240920,8850,17213380,32096,1638372,30677,254806,11785,851,...,72,88,134362,9596,1868,797,282,235,132212,9543
54,North Carolina,10371906,6477,8834381,37378,1170200,31849,315215,16391,4697,...,161,239,52110,6058,1986,1123,560,683,49564,5981
55,North Dakota,750501,1733,615450,9766,94413,7276,36668,5643,0,...,730,578,3970,1479,593,753,63,127,3314,1287
56,Ohio,11556037,5443,9891733,33048,1415185,32853,205542,11006,1203,...,492,512,43577,5314,2695,1439,725,1006,40157,4903
57,Oklahoma,3907258,3062,3282746,16542,509137,16246,101844,8145,241,...,326,230,13531,2029,741,622,0,165,12790,1977
59,Oregon,4178578,4124,3527178,21443,501680,19322,129921,8055,162,...,680,794,19799,3795,0,211,35,56,19764,3788
60,Pennsylvania,12670245,5785,11092255,37657,1259103,30402,267465,13835,1898,...,24,39,51422,5753,4028,1760,61,91,47333,5549
61,Rhode Island,1050602,1636,930406,10263,80686,8479,34984,4117,0,...,0,222,4526,1436,113,144,150,153,4263,1433
62,South Carolina,5092727,4254,4414770,17856,478892,15019,176008,12536,873,...,0,218,23057,4477,1491,1150,319,297,21247,4160
63,South Dakota,872708,1720,739009,8766,102133,7228,26934,3576,339,...,473,288,4632,2854,682,735,0,167,3950,2747
65,Tennessee,6754461,5775,5782145,24958,755183,25187,196765,12436,6294,...,46,60,20368,3408,24,33,255,285,20089,3434
66,Texas,28642658,11223,24347958,68604,3517954,58641,559661,22968,8791,...,1311,975,217085,16079,9352,6440,371,400,207362,15174
67,Utah,3162102,3623,2661654,18895,389057,16224,95608,8887,1027,...,1549,1009,15783,3314,96,162,107,151,15580,3310
68,Vermont,617560,1135,536752,5121,57776,5025,21212,2444,77,...,30,63,1820,802,3,0,0,161,1817,802
69,Virginia,8439982,5417,7201805,28265,903735,27129,264855,11921,4028,...,167,233,69587,8320,1896,1190,185,182,67506,8067
71,Washington,7527366,5600,6253469,28478,977928,24801,231956,14786,1060,...,626,486,64013,6368,318,312,1465,950,62230,6446
72,West Virginia,1773280,1883,1563611,12229,164739,10870,39548,4719,245,...,0,207,5382,2146,606,528,0,207,4776,2098
73,Wisconsin,5760481,3237,5001140,19911,634732,17869,107973,7285,678,...,1417,1826,16636,3451,513,479,0,153,16123,3375
74,Wyoming,572884,1076,473128,8091,68127,6867,30247,4333,1227,...,0,0,1382,597,0,207,0,207,1382,597
76,Puerto Rico,3175835,2114,2968876,10447,169733,8644,31144,5397,141,...,0,234,6082,1846,0,0,342,343,5740,1845


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [14]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),324665523,4849509,722063,7200620,2989054,39084048,5701658,3531986,964817,697556,...,6754461,28642658,3162102,617560,8439982,7527366,1773280,5760481,572884,3175835
Population 1 year and over (MOE),30094,3840,1360,6015,2800,10760,4038,2674,1555,1657,...,5775,11223,3623,1135,5417,5600,1883,3237,1076,2114
Same house 1 year ago (Estimate),280343146,4197698,609362,6038776,2559444,34394220,4695821,3106754,843383,563798,...,5782145,24347958,2661654,536752,7201805,6253469,1563611,5001140,473128,2968876
Same house 1 year ago (MOE),195001,21706,7734,31879,15248,68574,22285,20309,9324,6607,...,24958,68604,18895,5121,28265,28478,12229,19911,8091,10447
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago: Puerto Rico (MOE),9911,500,61,909,446,1200,588,2751,203,268,...,33,6440,162,0,1190,312,528,479,207,0
Abroad 1 year ago: U.S. Island Area (Estimate),15276,103,17,152,0,2887,83,0,0,0,...,255,371,107,0,185,1465,0,0,0,342
Abroad 1 year ago: U.S. Island Area (MOE),3033,136,30,167,206,1563,118,213,203,218,...,285,400,151,161,182,950,207,153,207,343
Abroad 1 year ago: Foreign Country (Estimate),1828895,11748,4241,45492,7823,261818,28198,24838,4234,9773,...,20089,207362,15580,1817,67506,62230,4776,16123,1382,5740
Abroad 1 year ago: Foreign Country (MOE),40180,2284,1718,6240,2588,11940,4222,4328,1392,2102,...,3434,15174,3310,802,8067,6446,2098,3375,597,1845

In [15]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [16]:

df = df.iloc[1:]

In [17]:
df

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),324665523,4849509,722063,7200620,2989054,39084048,5701658,3531986,964817,697556,...,6754461,28642658,3162102,617560,8439982,7527366,1773280,5760481,572884,3175835
Population 1 year and over (MOE),30094,3840,1360,6015,2800,10760,4038,2674,1555,1657,...,5775,11223,3623,1135,5417,5600,1883,3237,1076,2114
Same house 1 year ago (Estimate),280343146,4197698,609362,6038776,2559444,34394220,4695821,3106754,843383,563798,...,5782145,24347958,2661654,536752,7201805,6253469,1563611,5001140,473128,2968876
Same house 1 year ago (MOE),195001,21706,7734,31879,15248,68574,22285,20309,9324,6607,...,24958,68604,18895,5121,28265,28478,12229,19911,8091,10447
Same state of residence 1 year ago (Estimate),35013848,534842,74375,861935,361762,3943139,736314,306070,79186,64893,...,755183,3517954,389057,57776,903735,977928,164739,634732,68127,169733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago: Puerto Rico (MOE),9911,500,61,909,446,1200,588,2751,203,268,...,33,6440,162,0,1190,312,528,479,207,0
Abroad 1 year ago: U.S. Island Area (Estimate),15276,103,17,152,0,2887,83,0,0,0,...,255,371,107,0,185,1465,0,0,0,342
Abroad 1 year ago: U.S. Island Area (MOE),3033,136,30,167,206,1563,118,213,203,218,...,285,400,151,161,182,950,207,153,207,343
Abroad 1 year ago: Foreign Country (Estimate),1828895,11748,4241,45492,7823,261818,28198,24838,4234,9773,...,20089,207362,15580,1817,67506,62230,4776,16123,1382,5740
Abroad 1 year ago: Foreign Country (MOE),40180,2284,1718,6240,2588,11940,4222,4328,1392,2102,...,3434,15174,3310,802,8067,6446,2098,3375,597,1845

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [18]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [19]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [20]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Population 1 year and over (Estimate)                             697556
Same house 1 year ago (Estimate)                                  563798
Same state of residence 1 year ago (Estimate)                      64893
Different state of residence 1 year ago: Total ...                 58879
Different state of residence 1 year ago: Alabam...                   462
Different state of residence 1 year ago (contin...                   338
Different state of residence 1 year ago (contin...                   291
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  3437
Different state of residence 1 year ago (contin...                   870
Different state of residence 1 year ago (contin...                  1298
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  1496
Different state of residence 1 year ago (contin...                  1190
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                    28
Different state of residence 1 year ago (contin...                  1361
Different state of residence 1 year ago (contin...                   427
Different state of residence 1 year ago (contin...                    59
Different state of residence 1 year ago (contin...                    41
Different state of residence 1 year ago (contin...                   131
Different state of residence 1 year ago (contin...                   452
Different state of residence 1 year ago (contin...                   448
Different state of residence 1 year ago (contin...                 15499
Different state of residence 1 year ago (contin...                  2383
Different state of residence 1 year ago (contin...                   758
Different state of residence 1 year ago (contin...                   278
Different state of residence 1 year ago (contin...                   265
Different state of residence 1 year ago (contin...                   976
Different state of residence 1 year ago (contin...                     4
Different state of residence 1 year ago (contin...                    49
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                    49
Different state of residence 1 year ago (contin...                  2758
Different state of residence 1 year ago (contin...                   466
Different state of residence 1 year ago (contin...                  4314
Different state of residence 1 year ago (contin...                  1481
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   755
Different state of residence 1 year ago (contin...                   185
Different state of residence 1 year ago (contin...                   172
Different state of residence 1 year ago (contin...                  1718
Different state of residence 1 year ago (contin...                   138
Different state of residence 1 year ago (contin...                   568
Different state of residence 1 year ago (contin...                   250
Different state of residence 1 year ago (contin...                   991
Different state of residence 1 year ago (contin...                  2073
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                    54
Different state of residence 1 year ago (contin...                  8828
Different state of residence 1 year ago (contin...                   852
Different state of residence 1 year ago (contin...                   324
Different state of residence 1 year ago (contin...                   362
Different state of residence 1 year ago (contin...                     0
Abroad 1 year ago: Total (Estimate)                                 9986
Abroad 1 year ago: Puerto Rico (Estimate)                            213
Abroad 1 year ago: U.S. Island Area (Estimate)                         0
Abroad 1 year ago: Foreign Country (Estimate)                       9773

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [21]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

Cut off the top columns that arent for specific states

In [22]:

df_estimates = df_estimates[4:]
df_moes = df_moes[4:]

In [23]:
df_moes.head()

0          District of Columbia
0
Alabama                      448
Alaska                       584
Arizona                      306
Arkansas                     218
California                  1090

In [24]:
df_estimates.head()

0          District of Columbia
0
Alabama                      462
Alaska                       338
Arizona                      291
Arkansas                       0
California                  3437

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [25]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Also need to cut out one "total" column that is the total amount of "Abroad One Year Ago" incl PR, US Island Area, and Foreign Country

In [26]:
df = df.drop('Total')

df

0                    District of Columbia  MOE +/-
0
Alabama                                462     448
Alaska                                 338     584
Arizona                                291     306
Arkansas                                 0     218
California                            3437    1090
Colorado                               870     570
Connecticut                           1298     587
Delaware                                 0     218
District of Columbia                     0       0
Florida                               1496     680
Georgia                               1190     617
Hawaii                                   0     218
Idaho                                   28      41
Illinois                              1361     764
Indiana                                427     302
Iowa                                    59      68
Kansas                                  41      70
Kentucky                               131     135
Louisiana                              452     329
Maine                                  448     440
Maryland                             15499    3042
Massachusetts                         2383     750
Michigan                               758     430
Minnesota                              278     212
Mississippi                            265     277
Missouri                               976     588
Montana                                  4       9
Nebraska                                49     112
Nevada                                   0     218
New Hampshire                           49      81
New Jersey                            2758    1194
New Mexico                             466     736
New York                              4314    1272
North Carolina                        1481     798
North Dakota                             0     218
Ohio                                   755     491
Oklahoma                               185     194
Oregon                                 172     191
Pennsylvania                          1718     573
Rhode Island                           138     160
South Carolina                         568     373
South Dakota                           250     342
Tennessee                              991     540
Texas                                 2073    1067
Utah                                     0     218
Vermont                                 54     125
Virginia                              8828    1835
Washington                             852     601
West Virginia                          324     331
Wisconsin                              362     321
Wyoming                                  0     218
Puerto Rico                            213     268
U.S. Island Area                         0     218
Foreign Country                       9773    2102

also need to drop out the last two columns US Island Area and Foreign Country because those dont exist in the pop df and I don't need for this analysis

In [27]:
df = df.drop('U.S. Island Area')
df = df.drop('Foreign Country')

also need to drop the top row of pops df to get the dataframes to have the same row indices

In [28]:
df_pops = df_pops.drop('Label (Grouping)')

Now I'm adding a state polulation column to my newly formatted table

In [29]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [30]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [31]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [32]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       462     448          5024279
Alaska                        338     584           733391
Arizona                       291     306          7151502
Arkansas                        0     218          3011524
California                   3437    1090         39538223
Colorado                      870     570          5773714
Connecticut                  1298     587          3605944
Delaware                        0     218           989948
District of Columbia            0       0           689545
Florida                      1496     680         21538187
Georgia                      1190     617         10711908
Hawaii                          0     218          1455271
Idaho                          28      41          1839106
Illinois                     1361     764         12812508
Indiana                       427     302          6785528
Iowa                           59      68          3190369
Kansas                         41      70          2937880
Kentucky                      131     135          4505836
Louisiana                     452     329          4657757
Maine                         448     440          1362359
Maryland                    15499    3042          6177224
Massachusetts                2383     750          7029917
Michigan                      758     430         10077331
Minnesota                     278     212          5706494
Mississippi                   265     277          2961279
Missouri                      976     588          6154913
Montana                         4       9          1084225
Nebraska                       49     112          1961504
Nevada                          0     218          3104614
New Hampshire                  49      81          1377529
New Jersey                   2758    1194          9288994
New Mexico                    466     736          2117522
New York                     4314    1272         20201249
North Carolina               1481     798         10439388
North Dakota                    0     218           779094
Ohio                          755     491         11799448
Oklahoma                      185     194          3959353
Oregon                        172     191          4237256
Pennsylvania                 1718     573         13002700
Rhode Island                  138     160          1097379
South Carolina                568     373          5118425
South Dakota                  250     342           886667
Tennessee                     991     540          6910840
Texas                        2073    1067         29145505
Utah                            0     218          3271616
Vermont                        54     125           643077
Virginia                     8828    1835          8631393
Washington                    852     601          7705281
West Virginia                 324     331          1793716
Wisconsin                     362     321          5893718
Wyoming                         0     218           576851
Puerto Rico                   213     268          3285874

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [33]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [34]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Looking at states with most people coming to DC

In [35]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,,,,,
Maryland,15499,3042,6177224,0.002509,0.000492
Virginia,8828,1835,8631393,0.001023,0.000213
Alaska,338,584,733391,0.000461,0.000796
Connecticut,1298,587,3605944,0.000360,0.000163
Massachusetts,2383,750,7029917,0.000339,0.000107
Maine,448,440,1362359,0.000329,0.000323
New Jersey,2758,1194,9288994,0.000297,0.000129
South Dakota,250,342,886667,0.000282,0.000386
New Mexico,466,736,2117522,0.000220,0.000348
New York,4314,1272,20201249,0.000214,0.000063

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [36]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)

df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,462,448,5024279,0.000092,0.000089
1,Alaska,338,584,733391,0.000461,0.000796
2,Arizona,291,306,7151502,0.000041,0.000043
3,Arkansas,0,218,3011524,0.000000,0.000072
4,California,3437,1090,39538223,0.000087,0.000028

To export, want to make a slice excluding all DMV states -- Maryland, Virginia, DC

And then also PR because only looking at continental US

In [37]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]
df = df[df["state"] != "District of Columbia"]

Reset index so they match

In [38]:
df = df.reset_index(drop=True)

Now add in 2016 election winners for each state

First, read in file

In [39]:
df_2016_election_winners = pd.read_csv('pres-election-results-2016.csv')

type(df_2016_election_winners)

pandas.DataFrame

Next, add winning party and percent of votes columns

In [40]:
df_2016_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

df['winning_party'] = df_2016_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2016_election_winners['percent_total_votes']


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,462,448,5024279,0.000092,0.000089,REPUBLICAN,0.620831
1,Alaska,338,584,733391,0.000461,0.000796,REPUBLICAN,0.512815
2,Arizona,291,306,7151502,0.000041,0.000043,REPUBLICAN,0.486716
3,Arkansas,0,218,3011524,0.000000,0.000072,REPUBLICAN,0.605741
4,California,3437,1090,39538223,0.000087,0.000028,DEMOCRAT,0.617264

Save as csv file

In [41]:
df.to_csv('DC-migration-2019.csv')