I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2006.xls')

In [3]:
df.shape

(77, 115)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112',
       'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,593683,19539,392,299,1304,900,1811,1077,5984,...,757,1529,1033,154,168,Alabama,1501,1259,519,690

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112',
       'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,593683,19539,392,299,1304,900,1811,1077,5984,...,757,1529,1033,154,168,Alabama,1501,1259,519,690
9,Alaska,751,699,102086,7495,1190,711,503,723,3353,...,710,4850,1881,37,62,Alaska,845,756,334,374
10,Arizona,1805,1432,3715,1882,935748,26598,1163,690,85497,...,1869,11774,2709,52,85,Arizona,4367,1378,1442,1031
11,Arkansas,2678,1589,751,515,4212,1347,416998,16572,9141,...,888,1107,1021,739,1103,Arkansas,471,531,84,94
12,California,4133,1949,6376,2801,31915,4153,3709,1700,5173950,...,2772,34105,5293,530,460,California,10213,3168,1739,1141
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Colorado,1285,587,1821,890,13714,2911,893,526,34803,...,1264,5839,1909,155,179,Colorado,2303,916,6646,2289
15,Connecticut,496,468,0,269,262,211,0,269,2727,...,1204,593,564,76,123,Connecticut,160,185,0,269
16,Delaware,0,261,0,261,55,93,204,329,325,...,541,207,238,203,245,Delaware,0,261,0,261
17,District of Columbia,0,292,288,356,225,215,174,280,2672,...,1636,464,323,205,253,District of Columbia,266,256,0,292
18,Florida,13015,2462,4995,1648,6030,2457,3232,2024,27658,...,3250,5452,1717,3592,1478,Florida,9286,2607,389,310
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Georgia,14873,2233,2232,1068,5024,1491,2851,1332,24662,...,2636,3886,1559,3206,2275,Georgia,4028,2397,380,425
21,Hawaii,332,350,2906,1704,1718,830,0,267,14459,...,1434,3212,1603,0,267,Hawaii,257,321,101,169
22,Idaho,170,202,995,704,3178,1408,225,267,13537,...,687,12195,2712,70,131,Idaho,319,232,1047,674
23,Illinois,1286,571,1742,1211,5924,1472,2309,1434,15322,...,2306,5358,1794,637,359,Illinois,16802,2790,37,64

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
8,Alabama,593683,19539,392,299,1304,900,1811,1077,5984,...,757,1529,1033,154,168,Alabama,1501,1259,519,690
9,Alaska,751,699,102086,7495,1190,711,503,723,3353,...,710,4850,1881,37,62,Alaska,845,756,334,374
10,Arizona,1805,1432,3715,1882,935748,26598,1163,690,85497,...,1869,11774,2709,52,85,Arizona,4367,1378,1442,1031
11,Arkansas,2678,1589,751,515,4212,1347,416998,16572,9141,...,888,1107,1021,739,1103,Arkansas,471,531,84,94
12,California,4133,1949,6376,2801,31915,4153,3709,1700,5173950,...,2772,34105,5293,530,460,California,10213,3168,1739,1141
14,Colorado,1285,587,1821,890,13714,2911,893,526,34803,...,1264,5839,1909,155,179,Colorado,2303,916,6646,2289
15,Connecticut,496,468,0,269,262,211,0,269,2727,...,1204,593,564,76,123,Connecticut,160,185,0,269
16,Delaware,0,261,0,261,55,93,204,329,325,...,541,207,238,203,245,Delaware,0,261,0,261
17,District of Columbia,0,292,288,356,225,215,174,280,2672,...,1636,464,323,205,253,District of Columbia,266,256,0,292
18,Florida,13015,2462,4995,1648,6030,2457,3232,2024,27658,...,3250,5452,1717,3592,1478,Florida,9286,2607,389,310
20,Georgia,14873,2233,2232,1068,5024,1491,2851,1332,24662,...,2636,3886,1559,3206,2275,Georgia,4028,2397,380,425
21,Hawaii,332,350,2906,1704,1718,830,0,267,14459,...,1434,3212,1603,0,267,Hawaii,257,321,101,169
22,Idaho,170,202,995,704,3178,1408,225,267,13537,...,687,12195,2712,70,131,Idaho,319,232,1047,674
23,Illinois,1286,571,1742,1211,5924,1472,2309,1434,15322,...,2306,5358,1794,637,359,Illinois,16802,2790,37,64
24,Indiana,1551,1289,130,174,2434,1080,1201,780,7374,...,963,2066,1246,699,443,Indiana,4237,2133,62,102
26,Iowa,740,462,109,162,1702,746,675,573,6764,...,741,676,415,133,116,Iowa,3953,1113,502,400
27,Kansas,938,788,412,381,1695,842,2495,1456,8150,...,928,805,589,181,180,Kansas,493,305,374,377

Rename columns to be clearer, including manually renaming certain columns and stripping 'Unnamed: ' from the rest

In [9]:
print(df.columns.tolist())

['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114']

In [10]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.': '0'}, inplace=True)

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

print(df.columns.tolist())

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114']

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [11]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#For the rest of the columns:
#first, fill in blanks

df_filledin = df.ffill(axis=1)

df_filledin.head()

,0,1,2,3,4,5,6,7,8,9,...,104,105,106,107,108,109,111,112,113,114
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,593683,19539,392,299,1304,900,1811,1077,5984,...,2316,757,1529,1033,154,168,1501,1259,519,690
9,Alaska,751,699,102086,7495,1190,711,503,723,3353,...,1325,710,4850,1881,37,62,845,756,334,374

In [13]:
#then pull the info I need to name each column

for i in range(1, 105):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

In [14]:
df_filledin.head()

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,593683,19539,392,299,1304,900,1811,1077,5984,...,2316,757,1529,1033,154,168,1501,1259,519,690
9,Alaska,751,699,102086,7495,1190,711,503,723,3353,...,1325,710,4850,1881,37,62,845,756,334,374

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [15]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
54,Ohio,1834,864,745,480,4530,1638,1260,871,11098,...,3831,1355,1420,901,6837,1834,1184,677,115,139
55,Oklahoma,513,397,1304,966,4549,1777,7936,2569,8947,...,1679,888,2193,889,220,277,440,386,546,430
56,Oregon,42,68,1422,719,8078,2690,420,447,51295,...,798,485,24230,4096,577,919,1615,1317,753,775
57,Pennsylvania,1410,990,1501,923,2405,1254,1153,958,10789,...,11032,1843,2863,1523,2470,754,1524,707,0,240
58,Puerto Rico,0,275,0,275,38,64,0,275,1210,...,489,387,0,275,0,275,714,653,0,275
60,Rhode Island,98,185,106,127,844,769,0,281,1824,...,575,408,208,215,0,281,123,200,0,281
61,South Carolina,4779,2356,1317,967,2265,1111,229,193,4096,...,8560,2379,1282,723,1142,582,1690,1232,193,175
62,South Dakota,0,216,116,117,923,630,190,228,1536,...,17,31,785,492,0,216,224,149,544,419
63,Tennessee,7438,2465,445,481,3087,1408,3598,1606,10721,...,6028,1540,1920,941,667,603,1310,728,133,218
64,Texas,8736,2685,4910,1734,18641,3855,14725,3012,81572,...,16676,3088,10857,2391,1428,687,4121,1510,2700,1060
66,Utah,723,451,605,443,7495,2939,247,220,24994,...,1784,811,4221,1335,88,129,781,491,2446,1129
67,Vermont,17,28,0,205,455,470,66,113,554,...,1527,1429,252,257,0,205,248,351,51,68
68,Virginia,3379,1083,4116,1557,3286,1501,1061,667,18797,...,941937,23573,4712,1355,5119,1277,631,512,38,65
69,Washington,547,350,4161,1658,9879,2837,944,671,53034,...,6082,2225,1001766,22902,0,267,1275,915,515,356
70,West Virginia,993,783,817,603,16,27,30,52,1022,...,6846,1875,724,385,177710,9789,43,77,0,261
72,Wisconsin,1791,1731,406,498,2331,1003,2285,1580,4365,...,1413,720,1394,528,0,211,740600,17929,11,19
73,Wyoming,140,160,171,236,916,704,398,325,1200,...,127,140,892,670,0,259,935,946,67900,5757
74,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,...,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:
75,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...
76,"Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...",...,"Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm...","Source: U.S. Census Bureau, 2006 American Comm..."


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [16]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,MOE - Margin of error based on 90% confidence interval,"Source: U.S. Census Bureau, 2006 American Community Survey"
0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Alabama (Estimate),593683,751,1805,2678,4133,1285,496,0,0,13015,...,723,17,3379,547,993,1791,140,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Alabama (MOE),19539,699,1432,1589,1949,587,468,261,292,2462,...,451,28,1083,350,783,1731,160,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Alaska (Estimate),392,102086,3715,751,6376,1821,0,0,288,4995,...,605,0,4116,4161,817,406,171,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Alaska (MOE),299,7495,1882,515,2801,890,269,261,356,1648,...,443,205,1557,1658,603,498,236,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),168,62,85,1103,460,179,123,245,253,1478,...,129,205,1277,267,9789,211,259,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Wisconsin (Estimate),1501,845,4367,471,10213,2303,160,0,266,9286,...,781,248,631,1275,43,740600,935,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Wisconsin (MOE),1259,756,1378,531,3168,916,185,261,256,2607,...,491,351,512,915,77,17929,946,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Wyoming (Estimate),519,334,1442,84,1739,6646,0,0,0,389,...,2446,51,38,515,0,11,67900,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Wyoming (MOE),690,374,1031,94,1141,2289,269,261,292,310,...,1129,68,65,356,261,19,5757,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."

In [17]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [18]:

df = df.iloc[1:]

In [19]:
df

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,MOE - Margin of error based on 90% confidence interval,"Source: U.S. Census Bureau, 2006 American Community Survey"
Residence 1 year ago in --: Alabama (Estimate),593683,751,1805,2678,4133,1285,496,0,0,13015,...,723,17,3379,547,993,1791,140,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Alabama (MOE),19539,699,1432,1589,1949,587,468,261,292,2462,...,451,28,1083,350,783,1731,160,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Alaska (Estimate),392,102086,3715,751,6376,1821,0,0,288,4995,...,605,0,4116,4161,817,406,171,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Alaska (MOE),299,7495,1882,515,2801,890,269,261,356,1648,...,443,205,1557,1658,603,498,236,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Arizona (Estimate),1304,1190,935748,4212,31915,13714,262,55,225,6030,...,7495,455,3286,9879,16,2331,916,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),168,62,85,1103,460,179,123,245,253,1478,...,129,205,1277,267,9789,211,259,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Wisconsin (Estimate),1501,845,4367,471,10213,2303,160,0,266,9286,...,781,248,631,1275,43,740600,935,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Wisconsin (MOE),1259,756,1378,531,3168,916,185,261,256,2607,...,491,351,512,915,77,17929,946,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Wyoming (Estimate),519,334,1442,84,1739,6646,0,0,0,389,...,2446,51,38,515,0,11,67900,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."
Residence 1 year ago in --: Wyoming (MOE),690,374,1031,94,1141,2289,269,261,292,310,...,1129,68,65,356,261,19,5757,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2006 American Comm..."

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [20]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [21]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [22]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Residence 1 year ago in --: Alabama (Estimate)                         0
Residence 1 year ago in --: Alaska (Estimate)                        288
Residence 1 year ago in --: Arizona (Estimate)                       225
Residence 1 year ago in --: Arkansas (Estimate)                      174
Residence 1 year ago in --: California (Estimate)                   2672
Residence 1 year ago in --: Colorado (Estimate)                      135
Residence 1 year ago in --: Connecticut (Estimate)                  1033
Residence 1 year ago in --: Delaware (Estimate)                     2474
Residence 1 year ago in --: District of Columbi...                 58569
Residence 1 year ago in --: Florida (Estimate)                       892
Residence 1 year ago in --: Georgia (Estimate)                       921
Residence 1 year ago in --: Hawaii (Estimate)                        123
Residence 1 year ago in --: Idaho (Estimate)                         130
Residence 1 year ago in --: Illinois (Estimate)                     1796
Residence 1 year ago in --: Indiana (Estimate)                       627
Residence 1 year ago in --: Iowa (Estimate)                          117
Residence 1 year ago in --: Kansas (Estimate)                        359
Residence 1 year ago in --: Kentucky (Estimate)                      536
Residence 1 year ago in --: Louisiana (Estimate)                     274
Residence 1 year ago in --: Maine (Estimate)                         113
Residence 1 year ago in --: Maryland (Estimate)                    10842
Residence 1 year ago in --: Massachusetts (Esti...                   755
Residence 1 year ago in --: Michigan (Estimate)                      719
Residence 1 year ago in --: Minnesota (Estimate)                      68
Residence 1 year ago in --: Mississippi (Estimate)                   440
Residence 1 year ago in --: Missouri (Estimate)                      276
Residence 1 year ago in --: Montana (Estimate)                        27
Residence 1 year ago in --: Nebraska (Estimate)                        0
Residence 1 year ago in --: Nevada (Estimate)                         49
Residence 1 year ago in --: New Hampshire (Esti...                   265
Residence 1 year ago in --: New Jersey (Estimate)                    784
Residence 1 year ago in --: New Mexico (Estimate)                    181
Residence 1 year ago in --: New York (Estimate)                     4831
Residence 1 year ago in --: North Carolina (Est...                  1730
Residence 1 year ago in --: North Dakota (Estim...                     0
Residence 1 year ago in --: Ohio (Estimate)                         1169
Residence 1 year ago in --: Oklahoma (Estimate)                      154
Residence 1 year ago in --: Oregon (Estimate)                        154
Residence 1 year ago in --: Pennsylvania (Estim...                  2918
Residence 1 year ago in --: Puerto Rico (Estimate)                   100
Residence 1 year ago in --: Rhode Island (Estim...                   189
Residence 1 year ago in --: South Carolina (Est...                   502
Residence 1 year ago in --: South Dakota (Estim...                     0
Residence 1 year ago in --: Tennessee (Estimate)                      50
Residence 1 year ago in --: Texas (Estimate)                        2015
Residence 1 year ago in --: Utah (Estimate)                          201
Residence 1 year ago in --: Vermont (Estimate)                         0
Residence 1 year ago in --: Virginia (Estimate)                     6737
Residence 1 year ago in --: Washington (Estimate)                    464
Residence 1 year ago in --: West Virginia (Esti...                   205
Residence 1 year ago in --: Wisconsin (Estimate)                     266
Residence 1 year ago in --: Wyoming (Estimate)                         0

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [23]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

For 2021 and 2017, we needed to cut off the top columns that arent for specific states, but that's not relevent here because of different structure for 2009 and 2005

In [24]:

# df_estimates = df_estimates[4:]
# df_moes = df_moes[4:]

In [25]:
df_moes.head()

0          District of Columbia
0
Alabama                      292
Alaska                       356
Arizona                      215
Arkansas                     280
California                  1258

In [26]:
df_estimates.head()

0          District of Columbia
0
Alabama                        0
Alaska                       288
Arizona                      225
Arkansas                     174
California                  2672

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [27]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Now I'm adding a state polulation column to my newly formatted table

In [28]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [29]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [30]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [31]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                         0     292          5024279
Alaska                        288     356           733391
Arizona                       225     215          7151502
Arkansas                      174     280          3011524
California                   2672    1258         39538223
Colorado                      135     166          5773714
Connecticut                  1033     572          3605944
Delaware                     2474     475           989948
District of Columbia        58569    5619           689545
Florida                       892     524         21538187
Georgia                       921     710         10711908
Hawaii                        123     202          1455271
Idaho                         130     106          1839106
Illinois                     1796     694         12812508
Indiana                       627     758          6785528
Iowa                          117     193          3190369
Kansas                        359     359          2937880
Kentucky                      536     563          4505836
Louisiana                     274     316          4657757
Maine                         113     188          1362359
Maryland                    10842    2460          6177224
Massachusetts                 755     515          7029917
Michigan                      719     752         10077331
Minnesota                      68      79          5706494
Mississippi                   440     361          2961279
Missouri                      276     219          6154913
Montana                        27      46          1084225
Nebraska                        0     292          1961504
Nevada                         49      82          3104614
New Hampshire                 265     201          1377529
New Jersey                    784     370          9288994
New Mexico                    181     217          2117522
New York                     4831    1471         20201249
North Carolina               1730     916         10439388
North Dakota                    0     292           779094
Ohio                         1169     694         11799448
Oklahoma                      154     186          3959353
Oregon                        154     194          4237256
Pennsylvania                 2918    1152         13002700
Puerto Rico                   100     124          3285874
Rhode Island                  189     205          1097379
South Carolina                502     403          5118425
South Dakota                    0     292           886667
Tennessee                      50      84          6910840
Texas                        2015    1154         29145505
Utah                          201     201          3271616
Vermont                         0     292           643077
Virginia                     6737    1636          8631393
Washington                    464     323          7705281
West Virginia                 205     253          1793716
Wisconsin                     266     256          5893718
Wyoming                         0     292           576851

Adding columns representing the top and bottom of the margins of error

In [32]:
df['pop_migrated_upper'] = pd.to_numeric(df['pop_migrated']) + pd.to_numeric(df['MOE +/-']) 

df['pop_migrated_lower'] = pd.to_numeric(df['pop_migrated']) - pd.to_numeric(df['MOE +/-']) 

df

0,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower
0,,,,,
Alabama,0,292,5024279,292,-292
Alaska,288,356,733391,644,-68
Arizona,225,215,7151502,440,10
Arkansas,174,280,3011524,454,-106
California,2672,1258,39538223,3930,1414
Colorado,135,166,5773714,301,-31
Connecticut,1033,572,3605944,1605,461
Delaware,2474,475,989948,2949,1999
District of Columbia,58569,5619,689545,64188,52950
Florida,892,524,21538187,1416,368
Georgia,921,710,10711908,1631,211
Hawaii,123,202,1455271,325,-79
Idaho,130,106,1839106,236,24
Illinois,1796,694,12812508,2490,1102
Indiana,627,758,6785528,1385,-131
Iowa,117,193,3190369,310,-76
Kansas,359,359,2937880,718,0
Kentucky,536,563,4505836,1099,-27
Louisiana,274,316,4657757,590,-42
Maine,113,188,1362359,301,-75
Maryland,10842,2460,6177224,13302,8382
Massachusetts,755,515,7029917,1270,240
Michigan,719,752,10077331,1471,-33
Minnesota,68,79,5706494,147,-11
Mississippi,440,361,2961279,801,79
Missouri,276,219,6154913,495,57
Montana,27,46,1084225,73,-19
Nebraska,0,292,1961504,292,-292
Nevada,49,82,3104614,131,-33
New Hampshire,265,201,1377529,466,64
New Jersey,784,370,9288994,1154,414
New Mexico,181,217,2117522,398,-36
New York,4831,1471,20201249,6302,3360
North Carolina,1730,916,10439388,2646,814
North Dakota,0,292,779094,292,-292
Ohio,1169,694,11799448,1863,475
Oklahoma,154,186,3959353,340,-32
Oregon,154,194,4237256,348,-40
Pennsylvania,2918,1152,13002700,4070,1766
Puerto Rico,100,124,3285874,224,-24
Rhode Island,189,205,1097379,394,-16
South Carolina,502,403,5118425,905,99
South Dakota,0,292,886667,292,-292
Tennessee,50,84,6910840,134,-34
Texas,2015,1154,29145505,3169,861
Utah,201,201,3271616,402,0
Vermont,0,292,643077,292,-292
Virginia,6737,1636,8631393,8373,5101
Washington,464,323,7705281,787,141
West Virginia,205,253,1793716,458,-48
Wisconsin,266,256,5893718,522,10
Wyoming,0,292,576851,292,-292

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [33]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

df['migrated_adjusted_upper'] = (
    pd.to_numeric(df['pop_migrated_upper'])
    / pd.to_numeric(df['state_population'])

)

df['migrated_adjusted_lower'] = (
    pd.to_numeric(df['pop_migrated_lower'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [34]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Need to manually drop DC here because its input differently than in the other years -- here, the D.C. figure for folks that lived in D.C. both this year and last year is not n/a or 0, but rather a substantial number that represents the number of folks that did NOT move since last year's census

In [35]:
df = df.drop(['District of Columbia'])

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [36]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)

df.head()

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted
0,Alabama,0,292,5024279,292,-292,0.000000,0.000058,-0.000058,0.000058
1,Alaska,288,356,733391,644,-68,0.000393,0.000878,-0.000093,0.000485
2,Arizona,225,215,7151502,440,10,0.000031,0.000062,0.000001,0.000030
3,Arkansas,174,280,3011524,454,-106,0.000058,0.000151,-0.000035,0.000093
4,California,2672,1258,39538223,3930,1414,0.000068,0.000099,0.000036,0.000032

Looking at states with most people coming to DC

In [37]:

df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted
7,Delaware,2474,475,989948,2949,1999,0.002499,0.002979,0.002019,0.000480
19,Maryland,10842,2460,6177224,13302,8382,0.001755,0.002153,0.001357,0.000398
46,Virginia,6737,1636,8631393,8373,5101,0.000781,0.000970,0.000591,0.000190
1,Alaska,288,356,733391,644,-68,0.000393,0.000878,-0.000093,0.000485
6,Connecticut,1033,572,3605944,1605,461,0.000286,0.000445,0.000128,0.000159
31,New York,4831,1471,20201249,6302,3360,0.000239,0.000312,0.000166,0.000073
37,Pennsylvania,2918,1152,13002700,4070,1766,0.000224,0.000313,0.000136,0.000089
28,New Hampshire,265,201,1377529,466,64,0.000192,0.000338,0.000046,0.000146
39,Rhode Island,189,205,1097379,394,-16,0.000172,0.000359,-0.000015,0.000187
32,North Carolina,1730,916,10439388,2646,814,0.000166,0.000253,0.000078,0.000088

To export, want to make a slice excluding all DMV states -- Maryland, Virginia

In [38]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]

Now need to reset the index again to make numbers consecutive now that I've removed ceratin rows.

In [39]:
df = df.reset_index(drop=True)

Now add in 2004 election winners for each state

First, read in file

In [40]:
df_2004_election_winners = pd.read_csv('pres-election-results-2004.csv')

df_2004_election_winners.shape

(48, 5)

Next, add winning party and percent of votes columns

In [41]:
df_2004_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

Reset index to match the other df

In [42]:
df_2004_election_winners = df_2004_election_winners.reset_index(drop=True)

In [43]:
df_2004_election_winners.head()

df_2004_election_winners.index

RangeIndex(start=0, stop=48, step=1)

In [44]:

df['winning_party'] = df_2004_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2004_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,0,292,5024279,292,-292,0.000000,0.000058,-0.000058,0.000058,REPUBLICAN,0.624607
1,Alaska,288,356,733391,644,-68,0.000393,0.000878,-0.000093,0.000485,REPUBLICAN,0.610653
2,Arizona,225,215,7151502,440,10,0.000031,0.000062,0.000001,0.000030,REPUBLICAN,0.548694
3,Arkansas,174,280,3011524,454,-106,0.000058,0.000151,-0.000035,0.000093,REPUBLICAN,0.543060
4,California,2672,1258,39538223,3930,1414,0.000068,0.000099,0.000036,0.000032,DEMOCRAT,0.543056

Save as csv file

In [45]:
df.to_csv('DC-migration-2006.csv')