I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2010.xls')

In [3]:
df.shape

(84, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,NaN,...,52,Alabama,13166,2247,228,265,181,160,12757,2241
11,Alaska,702974,1600,565031,7596,95878,7984,36326,3708,477,...,131,Alaska,5739,1602,19,30,1374,1188,4346,1205
12,Arizona,6332786,4439,5069002,35057,1001991,32027,222725,11873,416,...,393,Arizona,39068,6046,599,771,223,286,38246,5951
13,Arkansas,2888304,2453,2387806,18627,412997,17485,79127,7901,1405,...,513,Arkansas,8374,2099,87,146,0,273,8287,2123
14,California,36907897,10889,30790221,71574,5413287,66460,444749,18415,3364,...,664,California,259640,13144,1223,1128,5123,2453,253294,13154
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,4988190,3936,4042039,25546,725413,23003,186366,9897,954,...,1439,Colorado,34372,4253,874,880,125,181,33373,4235
17,Connecticut,3541146,2779,3100742,16358,342904,15404,77333,6651,896,...,78,Connecticut,20167,2860,2027,1233,0,281,18140,2685
18,Delaware,889812,1573,764640,9145,90001,8498,30759,4030,128,...,265,Delaware,4412,1791,954,1095,431,400,3027,1274
19,District of Columbia,596747,1124,474676,8281,63766,6163,51244,4828,360,...,292,District of Columbia,7061,1472,0,292,62,103,6999,1448
20,Florida,18647600,7733,15554008,45602,2459530,38387,482889,22701,15830,...,258,Florida,151173,10799,12968,4149,1131,800,137074,9549
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,9587237,5924,8015409,37393,1278548,36794,249459,15858,13840,...,118,Georgia,43821,5631,1010,742,376,365,42435,5734
23,Hawaii,1346274,1690,1140572,10422,134315,9295,53581,6065,749,...,33,Hawaii,17806,4654,0,275,805,581,17001,4673

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,NaN,...,52,Alabama,13166,2247,228,265,181,160,12757,2241
11,Alaska,702974,1600,565031,7596,95878,7984,36326,3708,477,...,131,Alaska,5739,1602,19,30,1374,1188,4346,1205
12,Arizona,6332786,4439,5069002,35057,1001991,32027,222725,11873,416,...,393,Arizona,39068,6046,599,771,223,286,38246,5951
13,Arkansas,2888304,2453,2387806,18627,412997,17485,79127,7901,1405,...,513,Arkansas,8374,2099,87,146,0,273,8287,2123
14,California,36907897,10889,30790221,71574,5413287,66460,444749,18415,3364,...,664,California,259640,13144,1223,1128,5123,2453,253294,13154
16,Colorado,4988190,3936,4042039,25546,725413,23003,186366,9897,954,...,1439,Colorado,34372,4253,874,880,125,181,33373,4235
17,Connecticut,3541146,2779,3100742,16358,342904,15404,77333,6651,896,...,78,Connecticut,20167,2860,2027,1233,0,281,18140,2685
18,Delaware,889812,1573,764640,9145,90001,8498,30759,4030,128,...,265,Delaware,4412,1791,954,1095,431,400,3027,1274
19,District of Columbia,596747,1124,474676,8281,63766,6163,51244,4828,360,...,292,District of Columbia,7061,1472,0,292,62,103,6999,1448
20,Florida,18647600,7733,15554008,45602,2459530,38387,482889,22701,15830,...,258,Florida,151173,10799,12968,4149,1131,800,137074,9549
22,Georgia,9587237,5924,8015409,37393,1278548,36794,249459,15858,13840,...,118,Georgia,43821,5631,1010,742,376,365,42435,5734
23,Hawaii,1346274,1690,1140572,10422,134315,9295,53581,6065,749,...,33,Hawaii,17806,4654,0,275,805,581,17001,4673
24,Idaho,1550967,1954,1279856,12606,209272,10887,55638,6079,376,...,723,Idaho,6201,1618,233,374,36,62,5932,1578
25,Illinois,12680126,5467,11009852,32636,1404525,28126,203959,11573,1397,...,432,Illinois,61790,4951,2055,820,0,267,59735,4897
26,Indiana,6414862,4257,5431015,24897,833086,22796,127353,8463,1502,...,403,Indiana,23408,3198,572,457,75,124,22761,3113
28,Iowa,3013053,2381,2553210,15158,375650,12448,72557,5707,330,...,119,Iowa,11636,2469,149,176,0,228,11487,2434

Rename columns to be clearer, including manually renaming certain columns and stripping 'Unnamed: ' from the rest

In [9]:
print(df.columns.tolist())

['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129']

In [10]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns, just trimming:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

print(df.columns.tolist())

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129']

In [11]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [12]:
df.iloc[3:] = df.iloc[3:].fillna('0')

In [13]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,120,121,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,0,...,52,Alabama,13166,2247,228,265,181,160,12757,2241

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [14]:
#For the rest of the columns:
#first, fill in blanks

df_filledin = df.ffill(axis=1)

df_filledin.head()

,0,1,2,3,4,5,6,7,8,9,...,120,121,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,Population 1 year and over,Same house 1 year ago,Same house 1 year ago,Same state of residence 1 year ago,Same state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,...,Different state of residence 1 year ago (cont.),Current residence in --,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,Total,Alabama,...,Wyoming,Wyoming,Total,Total,Puerto Rico,Puerto Rico,U.S. Island Area,U.S. Island Area,Foreign Country,Foreign Country
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,0,...,52,Alabama,13166,2247,228,265,181,160,12757,2241

In [15]:
#then pull the info I need to name each column

for i in range(1, 120):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

In [16]:
df_filledin.head()

,0,Population 1 year and over: nan (Estimate),Population 1 year and over: nan (MOE),Same house 1 year ago: nan (Estimate),Same house 1 year ago: nan (MOE),Same state of residence 1 year ago: nan (Estimate),Same state of residence 1 year ago: nan (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (MOE),Current residence in --: Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
4,Current residence in --,Population 1 year and over,Population 1 year and over,Same house 1 year ago,Same house 1 year ago,Same state of residence 1 year ago,Same state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,...,Different state of residence 1 year ago (cont.),Current residence in --,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,Total,Alabama,...,Wyoming,Wyoming,Total,Total,Puerto Rico,Puerto Rico,U.S. Island Area,U.S. Island Area,Foreign Country,Foreign Country
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,305628607,29823,258552348,236128,38582885,213239,6743229,69387,99221,...,3185,United States1,1750145,36993,59885,6923,17167,3479,1673093,36130
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,0,...,52,Alabama,13166,2247,228,265,181,160,12757,2241

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [17]:
df = df_filledin.iloc[4:]

df.head(20)

,0,Population 1 year and over: nan (Estimate),Population 1 year and over: nan (MOE),Same house 1 year ago: nan (Estimate),Same house 1 year ago: nan (MOE),Same state of residence 1 year ago: nan (Estimate),Same state of residence 1 year ago: nan (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (MOE),Current residence in --: Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
10,Alabama,4729509,3716,3987155,21708,620465,21448,108723,8781,0,...,52,Alabama,13166,2247,228,265,181,160,12757,2241
11,Alaska,702974,1600,565031,7596,95878,7984,36326,3708,477,...,131,Alaska,5739,1602,19,30,1374,1188,4346,1205
12,Arizona,6332786,4439,5069002,35057,1001991,32027,222725,11873,416,...,393,Arizona,39068,6046,599,771,223,286,38246,5951
13,Arkansas,2888304,2453,2387806,18627,412997,17485,79127,7901,1405,...,513,Arkansas,8374,2099,87,146,0,273,8287,2123
14,California,36907897,10889,30790221,71574,5413287,66460,444749,18415,3364,...,664,California,259640,13144,1223,1128,5123,2453,253294,13154
16,Colorado,4988190,3936,4042039,25546,725413,23003,186366,9897,954,...,1439,Colorado,34372,4253,874,880,125,181,33373,4235
17,Connecticut,3541146,2779,3100742,16358,342904,15404,77333,6651,896,...,78,Connecticut,20167,2860,2027,1233,0,281,18140,2685
18,Delaware,889812,1573,764640,9145,90001,8498,30759,4030,128,...,265,Delaware,4412,1791,954,1095,431,400,3027,1274
19,District of Columbia,596747,1124,474676,8281,63766,6163,51244,4828,360,...,292,District of Columbia,7061,1472,0,292,62,103,6999,1448
20,Florida,18647600,7733,15554008,45602,2459530,38387,482889,22701,15830,...,258,Florida,151173,10799,12968,4149,1131,800,137074,9549
22,Georgia,9587237,5924,8015409,37393,1278548,36794,249459,15858,13840,...,118,Georgia,43821,5631,1010,742,376,365,42435,5734
23,Hawaii,1346274,1690,1140572,10422,134315,9295,53581,6065,749,...,33,Hawaii,17806,4654,0,275,805,581,17001,4673
24,Idaho,1550967,1954,1279856,12606,209272,10887,55638,6079,376,...,723,Idaho,6201,1618,233,374,36,62,5932,1578
25,Illinois,12680126,5467,11009852,32636,1404525,28126,203959,11573,1397,...,432,Illinois,61790,4951,2055,820,0,267,59735,4897
26,Indiana,6414862,4257,5431015,24897,833086,22796,127353,8463,1502,...,403,Indiana,23408,3198,572,457,75,124,22761,3113
28,Iowa,3013053,2381,2553210,15158,375650,12448,72557,5707,330,...,119,Iowa,11636,2469,149,176,0,228,11487,2434
29,Kansas,2820894,2731,2341401,17752,372161,15608,95059,7804,44,...,531,Kansas,12273,2344,68,88,90,105,12115,2355
30,Kentucky,4296639,3389,3638259,20337,519887,18955,118443,8947,2161,...,462,Kentucky,20050,4259,179,240,0,271,19871,4253
31,Louisiana,4483529,3720,3826390,25103,547291,22645,97889,8319,5740,...,67,Louisiana,11959,1983,402,285,116,136,11441,1979
32,Maine,1313902,1878,1136780,8034,146735,7677,27758,3059,402,...,766,Maine,2629,718,204,355,0,230,2425,669

Also need to drop totals columns at the start

In [18]:
df = df.drop(['Population 1 year and over: nan (Estimate)', 'Population 1 year and over: nan (MOE)', 'Same house 1 year ago: nan (Estimate)', 'Same house 1 year ago: nan (MOE)', 'Same state of residence 1 year ago: nan (Estimate)', 'Same state of residence 1 year ago: nan (MOE)', 'Different state of residence 1 year ago: Total (Estimate)', 'Different state of residence 1 year ago: Total (MOE)'], axis=1)


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [19]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Different state of residence 1 year ago: Alabama (Estimate),0,477,416,1405,3364,954,896,128,360,15830,...,8897,8636,93,0,2671,1322,41,552,172,629
Different state of residence 1 year ago: Alabama (MOE),0,790,305,1001,1977,803,891,211,418,3829,...,2131,2633,114,211,1201,1150,69,523,257,711
Different state of residence 1 year ago (cont.): Alaska (Estimate),3013,0,3109,934,9579,2225,0,68,591,5887,...,343,11613,1798,184,3296,5644,1326,798,0,156
Different state of residence 1 year ago (cont.): Alaska (MOE),1452,0,1297,798,2911,1220,281,111,529,2502,...,300,3256,1320,181,1952,2055,1210,549,269,259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),265,30,771,146,1128,880,1233,1095,292,4149,...,287,2074,446,211,872,277,232,478,269,N/A2
Abroad 1 year ago--: U.S. Island Area (Estimate),181,1374,223,0,5123,125,0,431,62,1131,...,0,843,108,0,217,2715,0,0,0,102
Abroad 1 year ago--: U.S. Island Area (MOE),160,1188,286,273,2453,181,281,400,103,800,...,287,622,129,211,207,1276,269,218,269,109
Abroad 1 year ago--: Foreign Country (Estimate),12757,4346,38246,8287,253294,33373,18140,3027,6999,137074,...,22077,166994,16747,2827,46942,54914,2451,13973,2039,4887
Abroad 1 year ago--: Foreign Country (MOE),2241,1205,5951,2123,13154,4235,2685,1274,1448,9549,...,2865,10904,3143,845,5312,5988,855,2235,774,1974

In [20]:
df_trans.index

Index(['0', 'Different state of residence 1 year ago: Alabama (Estimate)',
       'Different state of residence 1 year ago: Alabama (MOE)',
       'Different state of residence 1 year ago (cont.): Alaska (Estimate)',
       'Different state of residence 1 year ago (cont.): Alaska (MOE)',
       'Different state of residence 1 year ago (cont.): Arizona (Estimate)',
       'Different state of residence 1 year ago (cont.): Arizona (MOE)',
       'Different state of residence 1 year ago (cont.): Arkansas (Estimate)',
       'Different state of residence 1 year ago (cont.): Arkansas (MOE)',
       'Different state of residence 1 year ago (cont.): California (Estimate)',
       ...
       'Different state of residence 1 year ago (cont.): Wyoming (MOE)',
       'Current residence in --: Wyoming (MOE)',
       'Abroad 1 year ago--: Total (Estimate)',
       'Abroad 1 year ago--: Total (MOE)',
       'Abroad 1 year ago--: Puerto Rico (Estimate)',
       'Abroad 1 year ago--: Puerto Rico (MOE)',
       'Abroad 1 year ago--: U.S. Island Area (Estimate)',
       'Abroad 1 year ago--: U.S. Island Area (MOE)',
       'Abroad 1 year ago--: Foreign Country (Estimate)',
       'Abroad 1 year ago--: Foreign Country (MOE)'],
      dtype='str', length=112)

In [21]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [22]:

df = df.iloc[1:]

In [23]:
df

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Different state of residence 1 year ago: Alabama (Estimate),0,477,416,1405,3364,954,896,128,360,15830,...,8897,8636,93,0,2671,1322,41,552,172,629
Different state of residence 1 year ago: Alabama (MOE),0,790,305,1001,1977,803,891,211,418,3829,...,2131,2633,114,211,1201,1150,69,523,257,711
Different state of residence 1 year ago (cont.): Alaska (Estimate),3013,0,3109,934,9579,2225,0,68,591,5887,...,343,11613,1798,184,3296,5644,1326,798,0,156
Different state of residence 1 year ago (cont.): Alaska (MOE),1452,0,1297,798,2911,1220,281,111,529,2502,...,300,3256,1320,181,1952,2055,1210,549,269,259
Different state of residence 1 year ago (cont.): Arizona (Estimate),676,1354,0,777,33854,12287,664,60,662,3907,...,2291,16521,8147,65,3807,5971,0,1854,1511,288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),265,30,771,146,1128,880,1233,1095,292,4149,...,287,2074,446,211,872,277,232,478,269,N/A2
Abroad 1 year ago--: U.S. Island Area (Estimate),181,1374,223,0,5123,125,0,431,62,1131,...,0,843,108,0,217,2715,0,0,0,102
Abroad 1 year ago--: U.S. Island Area (MOE),160,1188,286,273,2453,181,281,400,103,800,...,287,622,129,211,207,1276,269,218,269,109
Abroad 1 year ago--: Foreign Country (Estimate),12757,4346,38246,8287,253294,33373,18140,3027,6999,137074,...,22077,166994,16747,2827,46942,54914,2451,13973,2039,4887
Abroad 1 year ago--: Foreign Country (MOE),2241,1205,5951,2123,13154,4235,2685,1274,1448,9549,...,2865,10904,3143,845,5312,5988,855,2235,774,1974

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [24]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

In [25]:
df.index

Index(['Different state of residence 1 year ago: Alabama (Estimate)',
       'Different state of residence 1 year ago: Alabama (MOE)',
       'Different state of residence 1 year ago (cont.): Alaska (Estimate)',
       'Different state of residence 1 year ago (cont.): Alaska (MOE)',
       'Different state of residence 1 year ago (cont.): Arizona (Estimate)',
       'Different state of residence 1 year ago (cont.): Arizona (MOE)',
       'Different state of residence 1 year ago (cont.): Arkansas (Estimate)',
       'Different state of residence 1 year ago (cont.): Arkansas (MOE)',
       'Different state of residence 1 year ago (cont.): California (Estimate)',
       'Different state of residence 1 year ago (cont.): California (MOE)',
       ...
       'Different state of residence 1 year ago (cont.): Wyoming (MOE)',
       'Current residence in --: Wyoming (MOE)',
       'Abroad 1 year ago--: Total (Estimate)',
       'Abroad 1 year ago--: Total (MOE)',
       'Abroad 1 year ago--: Puerto Rico (Estimate)',
       'Abroad 1 year ago--: Puerto Rico (MOE)',
       'Abroad 1 year ago--: U.S. Island Area (Estimate)',
       'Abroad 1 year ago--: U.S. Island Area (MOE)',
       'Abroad 1 year ago--: Foreign Country (Estimate)',
       'Abroad 1 year ago--: Foreign Country (MOE)'],
      dtype='str', length=111)

Delete rows that arent for specific states

In [26]:
df = df.iloc[:-9]

In [27]:
df

0                                                  District of Columbia
Different state of residence 1 year ago: Alabam...                   360
Different state of residence 1 year ago: Alabam...                   418
Different state of residence 1 year ago (cont.)...                   591
Different state of residence 1 year ago (cont.)...                   529
Different state of residence 1 year ago (cont.)...                   662
...                                                                  ...
Different state of residence 1 year ago (cont.)...                   754
Different state of residence 1 year ago (cont.)...                   391
Different state of residence 1 year ago (cont.)...                   325
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   292

[102 rows x 1 columns]

Import population maps in order to adjust each state per capita

In [28]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [29]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Different state of residence 1 year ago: Alabam...                   360
Different state of residence 1 year ago (cont.)...                   591
Different state of residence 1 year ago (cont.)...                   662
Different state of residence 1 year ago (cont.)...                   155
Different state of residence 1 year ago (cont.)...                  4205
Different state of residence 1 year ago (cont.)...                   656
Different state of residence 1 year ago (cont.)...                   926
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                  1100
Different state of residence 1 year ago (cont.)...                  1597
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   615
Different state of residence 1 year ago (cont.)...                   711
Different state of residence 1 year ago (cont.)...                   392
Different state of residence 1 year ago (cont.)...                    83
Different state of residence 1 year ago (cont.)...                    94
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                    76
Different state of residence 1 year ago (cont.)...                 13503
Different state of residence 1 year ago (cont.)...                  1376
Different state of residence 1 year ago (cont.)...                   126
Different state of residence 1 year ago (cont.)...                    87
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   272
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                    62
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   137
Different state of residence 1 year ago (cont.)...                  1924
Different state of residence 1 year ago (cont.)...                    61
Different state of residence 1 year ago (cont.)...                  3852
Different state of residence 1 year ago (cont.)...                  1897
Different state of residence 1 year ago (cont.)...                    98
Different state of residence 1 year ago (cont.)...                   598
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   601
Different state of residence 1 year ago (cont.)...                  2378
Different state of residence 1 year ago (cont.)...                   249
Different state of residence 1 year ago (cont.)...                   380
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   591
Different state of residence 1 year ago (cont.)...                  1180
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   199
Different state of residence 1 year ago (cont.)...                  7915
Different state of residence 1 year ago (cont.)...                   284
Different state of residence 1 year ago (cont.)...                   860
Different state of residence 1 year ago (cont.)...                   391
Different state of residence 1 year ago (cont.)...                     0

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [30]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

In [31]:
len(df_moes)

df_moes.index

Index(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia',
       'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
       'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype='str', name=0)

In [32]:
len(df_estimates)


df_estimates.index

Index(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia',
       'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
       'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype='str', name=0)

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [33]:
df_moes

0                    District of Columbia
0
Alabama                                418
Alaska                                 529
Arizona                                466
Arkansas                               195
California                            1255
Colorado                               637
Connecticut                            592
Delaware                               292
District of Columbia                     0
Florida                                609
Georgia                                795
Hawaii                                 292
Idaho                                  292
Illinois                               373
Indiana                                461
Iowa                                   377
Kansas                                 137
Kentucky                               155
Louisiana                              292
Maine                                  121
Maryland                              2647
Massachusetts                          540
Michigan                               153
Minnesota                              105
Mississippi                            292
Missouri                               371
Montana                                292
Nebraska                               103
Nevada                                 292
New Hampshire                          136
New Jersey                             694
New Mexico                             100
New York                              1325
North Carolina                        1089
North Dakota                           165
Ohio                                   359
Oklahoma                               292
Oregon                                 520
Pennsylvania                           771
Rhode Island                           206
South Carolina                         339
South Dakota                           292
Tennessee                              543
Texas                                  605
Utah                                   292
Vermont                                245
Virginia                              1638
Washington                             220
West Virginia                          754
Wisconsin                              325
Wyoming                                292

In [34]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Now I'm adding a state polulation column to my newly formatted table

In [35]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [36]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [37]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [38]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       360     418          5024279
Alaska                        591     529           733391
Arizona                       662     466          7151502
Arkansas                      155     195          3011524
California                   4205    1255         39538223
Colorado                      656     637          5773714
Connecticut                   926     592          3605944
Delaware                        0     292           989948
District of Columbia            0       0           689545
Florida                      1100     609         21538187
Georgia                      1597     795         10711908
Hawaii                          0     292          1455271
Idaho                           0     292          1839106
Illinois                      615     373         12812508
Indiana                       711     461          6785528
Iowa                          392     377          3190369
Kansas                         83     137          2937880
Kentucky                       94     155          4505836
Louisiana                       0     292          4657757
Maine                          76     121          1362359
Maryland                    13503    2647          6177224
Massachusetts                1376     540          7029917
Michigan                      126     153         10077331
Minnesota                      87     105          5706494
Mississippi                     0     292          2961279
Missouri                      272     371          6154913
Montana                         0     292          1084225
Nebraska                       62     103          1961504
Nevada                          0     292          3104614
New Hampshire                 137     136          1377529
New Jersey                   1924     694          9288994
New Mexico                     61     100          2117522
New York                     3852    1325         20201249
North Carolina               1897    1089         10439388
North Dakota                   98     165           779094
Ohio                          598     359         11799448
Oklahoma                        0     292          3959353
Oregon                        601     520          4237256
Pennsylvania                 2378     771         13002700
Rhode Island                  249     206          1097379
South Carolina                380     339          5118425
South Dakota                    0     292           886667
Tennessee                     591     543          6910840
Texas                        1180     605         29145505
Utah                            0     292          3271616
Vermont                       199     245           643077
Virginia                     7915    1638          8631393
Washington                    284     220          7705281
West Virginia                 860     754          1793716
Wisconsin                     391     325          5893718
Wyoming                         0     292           576851

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [39]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [40]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Need to manually drop DC here because its input differently than in the other years -- here, the D.C. figure for folks that lived in D.C. both this year and last year is not n/a or 0, but rather a substantial number that represents the number of folks that did NOT move since last year's census

In [41]:
df = df.drop(['District of Columbia'])

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [42]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,360,418,5024279,0.000072,0.000083
1,Alaska,591,529,733391,0.000806,0.000721
2,Arizona,662,466,7151502,0.000093,0.000065
3,Arkansas,155,195,3011524,0.000051,0.000065
4,California,4205,1255,39538223,0.000106,0.000032

Looking at states with most people coming to DC

In [43]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
19,Maryland,13503,2647,6177224,0.002186,0.000429
45,Virginia,7915,1638,8631393,0.000917,0.000190
1,Alaska,591,529,733391,0.000806,0.000721
47,West Virginia,860,754,1793716,0.000479,0.000420
44,Vermont,199,245,643077,0.000309,0.000381
6,Connecticut,926,592,3605944,0.000257,0.000164
38,Rhode Island,249,206,1097379,0.000227,0.000188
29,New Jersey,1924,694,9288994,0.000207,0.000075
20,Massachusetts,1376,540,7029917,0.000196,0.000077
31,New York,3852,1325,20201249,0.000191,0.000066

To export, want to make a slice excluding all DMV states -- Maryland, Virginia

In [44]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]

Now need to reset the index again to make numbers consecutive now that I've removed ceratin rows.

In [45]:
df = df.reset_index(drop=True)

Now add in 2008 election winners for each state

First, read in file

In [46]:
df_2008_election_winners = pd.read_csv('pres-election-results-2008.csv')

type(df_2008_election_winners)

pandas.DataFrame

In [47]:
df_2008_election_winners

    Unnamed: 0           state  year party_detailed  percent_total_votes
0           48         Alabama  2008     REPUBLICAN             0.603169
1           49          Alaska  2008     REPUBLICAN             0.594245
2           50         Arizona  2008     REPUBLICAN             0.536352
3           51        Arkansas  2008     REPUBLICAN             0.587159
4           52      California  2008       DEMOCRAT             0.610126
5           53        Colorado  2008       DEMOCRAT             0.536602
6           54     Connecticut  2008       DEMOCRAT             0.605888
7           55        Delaware  2008       DEMOCRAT             0.619427
8           56         Florida  2008       DEMOCRAT             0.510333
9           57         Georgia  2008     REPUBLICAN             0.522045
10          58          Hawaii  2008       DEMOCRAT             0.714529
11          59           Idaho  2008     REPUBLICAN             0.615171
12          60        Illinois  2008       DEMOCRAT             0.619181
13          61         Indiana  2008       DEMOCRAT             0.499459
14          62            Iowa  2008       DEMOCRAT             0.539280
15          63          Kansas  2008     REPUBLICAN             0.566123
16          64        Kentucky  2008     REPUBLICAN             0.573990
17          65       Louisiana  2008     REPUBLICAN             0.585627
18          66           Maine  2008       DEMOCRAT             0.577057
19          67   Massachusetts  2008       DEMOCRAT             0.613632
20          68        Michigan  2008       DEMOCRAT             0.574332
21          69       Minnesota  2008       DEMOCRAT             0.540603
22          70     Mississippi  2008     REPUBLICAN             0.561762
23          71        Missouri  2008     REPUBLICAN             0.494261
24          72         Montana  2008     REPUBLICAN             0.495325
25          73        Nebraska  2008     REPUBLICAN             0.565319
26          74          Nevada  2008       DEMOCRAT             0.551467
27          75   New Hampshire  2008       DEMOCRAT             0.541269
28          76      New Jersey  2008       DEMOCRAT             0.572721
29          77      New Mexico  2008       DEMOCRAT             0.569075
30          78        New York  2008       DEMOCRAT             0.601570
31          79  North Carolina  2008       DEMOCRAT             0.497037
32          80    North Dakota  2008     REPUBLICAN             0.532501
33          81            Ohio  2008       DEMOCRAT             0.515043
34          82        Oklahoma  2008     REPUBLICAN             0.656451
35          83          Oregon  2008       DEMOCRAT             0.567488
36          84    Pennsylvania  2008       DEMOCRAT             0.544855
37          85    Rhode Island  2008       DEMOCRAT             0.628640
38          86  South Carolina  2008     REPUBLICAN             0.538736
39          87    South Dakota  2008     REPUBLICAN             0.531590
40          88       Tennessee  2008     REPUBLICAN             0.568970
41          89           Texas  2008     REPUBLICAN             0.554524
42          90            Utah  2008     REPUBLICAN             0.625839
43          91         Vermont  2008       DEMOCRAT             0.674557
44          92      Washington  2008       DEMOCRAT             0.576529
45          93   West Virginia  2008     REPUBLICAN             0.557103
46          94       Wisconsin  2008       DEMOCRAT             0.562178
47          95         Wyoming  2008     REPUBLICAN             0.647138

Next, add winning party and percent of votes columns

In [48]:
df_2008_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

df_2008_election_winners.head()

        state  year party_detailed  percent_total_votes
0     Alabama  2008     REPUBLICAN             0.603169
1      Alaska  2008     REPUBLICAN             0.594245
2     Arizona  2008     REPUBLICAN             0.536352
3    Arkansas  2008     REPUBLICAN             0.587159
4  California  2008       DEMOCRAT             0.610126

In [49]:

df['winning_party'] = df_2008_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2008_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,360,418,5024279,0.000072,0.000083,REPUBLICAN,0.603169
1,Alaska,591,529,733391,0.000806,0.000721,REPUBLICAN,0.594245
2,Arizona,662,466,7151502,0.000093,0.000065,REPUBLICAN,0.536352
3,Arkansas,155,195,3011524,0.000051,0.000065,REPUBLICAN,0.587159
4,California,4205,1255,39538223,0.000106,0.000032,DEMOCRAT,0.610126

Check that indexes match

In [50]:
df.index

RangeIndex(start=0, stop=48, step=1)

In [51]:
df_2008_election_winners.index

RangeIndex(start=0, stop=48, step=1)

Save as csv file

In [52]:
df.to_csv('DC-migration-2010.csv')