I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2015.xls')

In [3]:
df.shape

(85, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,317635720,28922,270873397,189370,37146496,176254,7530129,67868,100809,...,4780,United States2,2085698,39419,89000,8853,20482,5276,1976216,37433

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,317635720,28922,270873397,189370,37146496,176254,7530129,67868,100809,...,4780,United States2,2085698,39419,89000,8853,20482,5276,1976216,37433
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4801599,3420,4113945,22379,561019,21500,114876,8513,NaN,...,266,Alabama,11759,2403,51,102,0,192,11708,2403
11,Alaska,727862,1356,582909,9527,105769,8533,34696,4503,279,...,422,Alaska,4488,1282,34,62,16,28,4438,1285
12,Arizona,6747595,4243,5536087,26178,910911,24238,253281,12395,607,...,1694,Arizona,47316,5688,1556,1296,105,121,45655,5434
13,Arkansas,2938341,3200,2440359,17443,407352,17073,81594,7126,956,...,251,Arkansas,9036,2094,0,190,0,190,9036,2094
14,California,38675135,11051,33446324,47467,4377667,41961,514477,19053,5273,...,666,California,336667,16275,1110,698,1518,915,334039,16226
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5393067,3719,4404058,21899,728077,17761,227445,12112,2392,...,1427,Colorado,33487,3701,126,209,325,326,33036,3694
17,Connecticut,3554844,3252,3109580,17815,340126,14637,76997,6705,163,...,198,Connecticut,28141,3996,3564,2602,15,31,24562,3181
18,Delaware,935813,1401,800701,9561,86009,7715,44495,5586,76,...,190,Delaware,4608,1492,236,271,0,190,4372,1467
19,District of Columbia,663006,1528,525024,7553,67188,5688,59905,4750,359,...,200,District of Columbia,10889,3045,18,41,0,200,10871,3037
20,Florida,20068392,6492,16832374,48927,2438828,43407,584938,21044,15449,...,867,Florida,212252,13881,28036,5779,910,577,183306,13613
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,10088525,6934,8489689,34028,1259007,33617,283325,17018,16372,...,1332,Georgia,56504,6654,2502,1267,1452,1262,52550,6538
23,Hawaii,1414355,1729,1206066,10201,136796,9374,53742,4403,240,...,182,Hawaii,17751,3472,115,112,1475,875,16161,3288

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,317635720,28922,270873397,189370,37146496,176254,7530129,67868,100809,...,4780,United States2,2085698,39419,89000,8853,20482,5276,1976216,37433
10,Alabama,4801599,3420,4113945,22379,561019,21500,114876,8513,NaN,...,266,Alabama,11759,2403,51,102,0,192,11708,2403
11,Alaska,727862,1356,582909,9527,105769,8533,34696,4503,279,...,422,Alaska,4488,1282,34,62,16,28,4438,1285
12,Arizona,6747595,4243,5536087,26178,910911,24238,253281,12395,607,...,1694,Arizona,47316,5688,1556,1296,105,121,45655,5434
13,Arkansas,2938341,3200,2440359,17443,407352,17073,81594,7126,956,...,251,Arkansas,9036,2094,0,190,0,190,9036,2094
14,California,38675135,11051,33446324,47467,4377667,41961,514477,19053,5273,...,666,California,336667,16275,1110,698,1518,915,334039,16226
16,Colorado,5393067,3719,4404058,21899,728077,17761,227445,12112,2392,...,1427,Colorado,33487,3701,126,209,325,326,33036,3694
17,Connecticut,3554844,3252,3109580,17815,340126,14637,76997,6705,163,...,198,Connecticut,28141,3996,3564,2602,15,31,24562,3181
18,Delaware,935813,1401,800701,9561,86009,7715,44495,5586,76,...,190,Delaware,4608,1492,236,271,0,190,4372,1467
19,District of Columbia,663006,1528,525024,7553,67188,5688,59905,4750,359,...,200,District of Columbia,10889,3045,18,41,0,200,10871,3037
20,Florida,20068392,6492,16832374,48927,2438828,43407,584938,21044,15449,...,867,Florida,212252,13881,28036,5779,910,577,183306,13613
22,Georgia,10088525,6934,8489689,34028,1259007,33617,283325,17018,16372,...,1332,Georgia,56504,6654,2502,1267,1452,1262,52550,6538
23,Hawaii,1414355,1729,1206066,10201,136796,9374,53742,4403,240,...,182,Hawaii,17751,3472,115,112,1475,875,16161,3288
24,Idaho,1635366,2042,1333758,15568,218791,12436,73809,7373,564,...,1169,Idaho,9008,2615,62,71,105,190,8841,2653
25,Illinois,12706393,5951,11029917,29927,1399829,28665,209828,10119,1853,...,322,Illinois,66819,5622,1655,715,268,305,64896,5755
26,Indiana,6540691,4312,5527512,24338,843210,22453,147529,10054,2130,...,247,Indiana,22440,3730,377,514,136,185,21927,3591
28,Iowa,3081446,2995,2598298,16346,386465,12421,85937,7418,285,...,180,Iowa,10746,2176,32,40,0,155,10714,2175

Rename columns to be clearer numbers

In [9]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '120', '121', '122', '123', '124', '125', '126', '127', '128', '129'],
      dtype='str', length=130)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [10]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

df

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,317635720,28922,270873397,189370,37146496,176254,7530129,67868,100809,...,31537,4780,2085698,39419,89000,8853,20482,5276,1976216,37433
10,Alabama,4801599,3420,4113945,22379,561019,21500,114876,8513,NaN,...,164,266,11759,2403,51,102,0,192,11708,2403
11,Alaska,727862,1356,582909,9527,105769,8533,34696,4503,279,...,414,422,4488,1282,34,62,16,28,4438,1285
12,Arizona,6747595,4243,5536087,26178,910911,24238,253281,12395,607,...,2473,1694,47316,5688,1556,1296,105,121,45655,5434
13,Arkansas,2938341,3200,2440359,17443,407352,17073,81594,7126,956,...,275,251,9036,2094,0,190,0,190,9036,2094
14,California,38675135,11051,33446324,47467,4377667,41961,514477,19053,5273,...,1672,666,336667,16275,1110,698,1518,915,334039,16226
16,Colorado,5393067,3719,4404058,21899,728077,17761,227445,12112,2392,...,3275,1427,33487,3701,126,209,325,326,33036,3694
17,Connecticut,3554844,3252,3109580,17815,340126,14637,76997,6705,163,...,0,198,28141,3996,3564,2602,15,31,24562,3181
18,Delaware,935813,1401,800701,9561,86009,7715,44495,5586,76,...,0,190,4608,1492,236,271,0,190,4372,1467
19,District of Columbia,663006,1528,525024,7553,67188,5688,59905,4750,359,...,0,200,10889,3045,18,41,0,200,10871,3037
20,Florida,20068392,6492,16832374,48927,2438828,43407,584938,21044,15449,...,924,867,212252,13881,28036,5779,910,577,183306,13613
22,Georgia,10088525,6934,8489689,34028,1259007,33617,283325,17018,16372,...,879,1332,56504,6654,2502,1267,1452,1262,52550,6538
23,Hawaii,1414355,1729,1206066,10201,136796,9374,53742,4403,240,...,0,182,17751,3472,115,112,1475,875,16161,3288
24,Idaho,1635366,2042,1333758,15568,218791,12436,73809,7373,564,...,2282,1169,9008,2615,62,71,105,190,8841,2653
25,Illinois,12706393,5951,11029917,29927,1399829,28665,209828,10119,1853,...,287,322,66819,5622,1655,715,268,305,64896,5755
26,Indiana,6540691,4312,5527512,24338,843210,22453,147529,10054,2130,...,172,247,22440,3730,377,514,136,185,21927,3591
28,Iowa,3081446,2995,2598298,16346,386465,12421,85937,7418,285,...,229,180,10746,2176,32,40,0,155,10714,2175
29,Kansas,2875640,2522,2405677,14673,360715,11629,91340,7226,717,...,393,365,17908,3502,17,31,0,168,17891,3509
30,Kentucky,4373403,3381,3706705,22052,543811,20127,106918,8171,1463,...,525,827,15969,3239,111,143,0,187,15858,3247
31,Louisiana,4612024,4460,4007364,20659,496223,18619,93321,7854,3318,...,26,60,15116,2842,1048,753,196,352,13872,2707
32,Maine,1317444,1397,1127394,9359,156271,8941,30123,2991,0,...,208,355,3656,990,0,163,0,163,3656,990
34,Maryland,5934005,4398,5076791,24604,638788,20920,168894,10301,1526,...,272,362,49532,4940,1627,1718,249,244,47656,4796
35,Massachusetts,6725678,3740,5893936,18618,634359,17901,132642,7404,269,...,0,200,64741,6266,4520,1813,1104,1033,59117,5679
36,Michigan,9811416,4125,8394658,25486,1229302,23453,142639,8234,1387,...,157,161,44817,5346,643,601,0,167,44174,5210
37,Minnesota,5419822,3620,4618325,19800,661383,18661,108476,7030,105,...,728,738,31638,4705,706,1023,186,154,30746,4553
38,Mississippi,2959289,2681,2554660,15529,327854,16330,69351,6816,6827,...,31,40,7424,1551,104,109,0,207,7320,1552
40,Missouri,6015580,3399,5056661,24391,777061,22731,159152,8254,1449,...,599,752,22706,2811,1323,1210,307,404,21076,2576
41,Montana,1019646,1426,855861,9601,118200,7821,42760,6511,0,...,2009,998,2825,986,0,165,41,67,2784,984
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
45,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1869217,1976,1570592,11472,236217,10096,52950,4461,32,...,746,388,9458,1447,389,388,0,155,9069,1434
48,Nevada,2859489,2806,2291842,18502,413831,17261,135999,9981,1830,...,543,362,17817,2686,339,322,219,260,17259,2679
49,New Hampshire,1318121,1867,1134482,9193,122442,7927,53446,5177,125,...,0,184,7751,1908,613,630,46,77,7092,1796
50,New Jersey,8854363,4962,7987859,26012,656570,22372,144074,8425,250,...,206,313,65860,6182,2780,1517,623,582,62457,5900
51,New Mexico,2060441,2662,1767704,12817,228103,11980,55753,5781,356,...,444,539,8881,1917,107,178,0,193,8774,1906
53,New York,19570171,7771,17506652,32943,1653268,29796,257611,10637,850,...,320,262,152640,10397,5522,1598,301,405,146817,10064
54,North Carolina,9927547,5134,8376304,32816,1194157,27794,310612,15103,3733,...,582,435,46474,4415,1125,756,472,455,44877,4316
55,North Dakota,745291,1249,608377,7924,90498,6644,42618,5171,0,...,234,250,3798,1097,0,151,0,151,3798,1097
56,Ohio,11482142,4883,9719944,31583,1508889,29950,203475,10154,2038,...,37,60,49834,5647,4311,1687,692,484,44831,5327
57,Oklahoma,3864908,2978,3202689,16599,532976,15499,110878,6734,957,...,150,214,18365,3244,303,245,164,268,17898,3232
59,Oregon,3985712,3006,3277453,19786,544776,18097,141162,7834,654,...,1021,704,22321,3833,58,104,1931,1621,20332,3467
60,Pennsylvania,12662192,5055,11109753,32343,1258572,26356,232683,11644,1663,...,674,949,61184,5651,7933,2098,438,264,52813,5106
61,Rhode Island,1045062,1593,901338,9189,97722,7798,38344,4294,39,...,0,206,7658,2447,1029,920,292,341,6337,2178
62,South Carolina,4839984,3503,4106166,20224,543488,17723,170366,10880,1854,...,0,203,19964,3530,1030,719,288,254,18646,3389
63,South Dakota,848285,1092,702122,7738,116343,6782,26962,3687,14,...,1426,827,2858,1416,9,15,0,151,2849,1416
65,Tennessee,6522259,4265,5535963,28320,766524,23974,195923,11637,10291,...,179,302,23849,3901,424,500,0,200,23425,3946
66,Texas,27092848,11293,22723345,58176,3594282,54950,553032,19120,7167,...,2743,1875,222189,13283,9707,3395,4696,3750,207786,12375
67,Utah,2947423,3093,2435722,19625,390649,17548,97361,7413,369,...,2609,1485,23691,2638,109,157,0,187,23582,2644
68,Vermont,619952,781,532319,5199,62067,4869,21232,2519,245,...,15,33,4334,1885,100,109,0,149,4234,1883
69,Virginia,8283737,4532,6952362,28986,983569,26232,277715,12444,2888,...,267,421,70091,6318,1945,737,1077,645,67069,6349
71,Washington,7089143,3701,5778806,28406,1017221,25445,230907,11515,580,...,755,562,62209,7091,683,523,672,426,60854,7056
72,West Virginia,1823753,2120,1610407,10957,167631,9128,42078,4511,240,...,0,189,3637,1269,565,562,0,189,3072,1120
73,Wisconsin,5708201,3093,4891636,19111,690306,17552,106511,8097,322,...,592,436,19748,3327,295,226,163,171,19290,3306
74,Wyoming,579102,1256,474927,7256,65384,6731,35947,4840,253,...,NaN,NaN,2844,1277,51,70,0,192,2793,1278
76,Puerto Rico,3443445,2859,3193423,14727,219833,13465,24762,3564,246,...,0,221,5427,1535,N/A3,N/A3,0,221,5427,1535

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [11]:
df.iloc[3:] = df.iloc[3:].fillna('0')

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#first, dealing with columns B-G/1-6)

column_1_name = f'{df.iloc[0, 1]} ({df.iloc[2, 1]})'
column_2_name = f'{df.iloc[0, 1]} ({df.iloc[2, 2]})'

column_3_name = f'{df.iloc[0, 3]} ({df.iloc[2, 3]})'
column_4_name = f'{df.iloc[0, 3]} ({df.iloc[2, 4]})'

column_5_name = f'{df.iloc[0, 5]} ({df.iloc[2, 5]})'
column_6_name = f'{df.iloc[0, 5]} ({df.iloc[2, 6]})'

df_clean = df.rename(columns ={
    '1': column_1_name,
    '2': column_2_name,
    '3': column_3_name,
    '4': column_4_name,
    '5': column_5_name,
    '6': column_6_name})

#next, for the rest of the columns:
#first, fill in blanks

df_filledin = df_clean.ffill(axis=1)

#then pull the info I need to name each column

for i in range(7, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [13]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Population 1 year and over (Estimate),Population 1 year and over (MOE),Same house 1 year ago (Estimate),Same house 1 year ago (MOE),Same state of residence 1 year ago (Estimate),Same state of residence 1 year ago (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (continued): Wyoming (Estimate),Different state of residence 1 year ago (continued): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
53,New York,19570171,7771,17506652,32943,1653268,29796,257611,10637,850,...,320,262,152640,10397,5522,1598,301,405,146817,10064
54,North Carolina,9927547,5134,8376304,32816,1194157,27794,310612,15103,3733,...,582,435,46474,4415,1125,756,472,455,44877,4316
55,North Dakota,745291,1249,608377,7924,90498,6644,42618,5171,0,...,234,250,3798,1097,0,151,0,151,3798,1097
56,Ohio,11482142,4883,9719944,31583,1508889,29950,203475,10154,2038,...,37,60,49834,5647,4311,1687,692,484,44831,5327
57,Oklahoma,3864908,2978,3202689,16599,532976,15499,110878,6734,957,...,150,214,18365,3244,303,245,164,268,17898,3232
59,Oregon,3985712,3006,3277453,19786,544776,18097,141162,7834,654,...,1021,704,22321,3833,58,104,1931,1621,20332,3467
60,Pennsylvania,12662192,5055,11109753,32343,1258572,26356,232683,11644,1663,...,674,949,61184,5651,7933,2098,438,264,52813,5106
61,Rhode Island,1045062,1593,901338,9189,97722,7798,38344,4294,39,...,0,206,7658,2447,1029,920,292,341,6337,2178
62,South Carolina,4839984,3503,4106166,20224,543488,17723,170366,10880,1854,...,0,203,19964,3530,1030,719,288,254,18646,3389
63,South Dakota,848285,1092,702122,7738,116343,6782,26962,3687,14,...,1426,827,2858,1416,9,15,0,151,2849,1416
65,Tennessee,6522259,4265,5535963,28320,766524,23974,195923,11637,10291,...,179,302,23849,3901,424,500,0,200,23425,3946
66,Texas,27092848,11293,22723345,58176,3594282,54950,553032,19120,7167,...,2743,1875,222189,13283,9707,3395,4696,3750,207786,12375
67,Utah,2947423,3093,2435722,19625,390649,17548,97361,7413,369,...,2609,1485,23691,2638,109,157,0,187,23582,2644
68,Vermont,619952,781,532319,5199,62067,4869,21232,2519,245,...,15,33,4334,1885,100,109,0,149,4234,1883
69,Virginia,8283737,4532,6952362,28986,983569,26232,277715,12444,2888,...,267,421,70091,6318,1945,737,1077,645,67069,6349
71,Washington,7089143,3701,5778806,28406,1017221,25445,230907,11515,580,...,755,562,62209,7091,683,523,672,426,60854,7056
72,West Virginia,1823753,2120,1610407,10957,167631,9128,42078,4511,240,...,0,189,3637,1269,565,562,0,189,3072,1120
73,Wisconsin,5708201,3093,4891636,19111,690306,17552,106511,8097,322,...,592,436,19748,3327,295,226,163,171,19290,3306
74,Wyoming,579102,1256,474927,7256,65384,6731,35947,4840,253,...,0,0,2844,1277,51,70,0,192,2793,1278
76,Puerto Rico,3443445,2859,3193423,14727,219833,13465,24762,3564,246,...,0,221,5427,1535,N/A3,N/A3,0,221,5427,1535


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [14]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),317635720,4801599,727862,6747595,2938341,38675135,5393067,3554844,935813,663006,...,6522259,27092848,2947423,619952,8283737,7089143,1823753,5708201,579102,3443445
Population 1 year and over (MOE),28922,3420,1356,4243,3200,11051,3719,3252,1401,1528,...,4265,11293,3093,781,4532,3701,2120,3093,1256,2859
Same house 1 year ago (Estimate),270873397,4113945,582909,5536087,2440359,33446324,4404058,3109580,800701,525024,...,5535963,22723345,2435722,532319,6952362,5778806,1610407,4891636,474927,3193423
Same house 1 year ago (MOE),189370,22379,9527,26178,17443,47467,21899,17815,9561,7553,...,28320,58176,19625,5199,28986,28406,10957,19111,7256,14727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),8853,102,62,1296,190,698,209,2602,271,41,...,500,3395,157,109,737,523,562,226,70,N/A3
Abroad 1 year ago--: U.S. Island Area (Estimate),20482,0,16,105,0,1518,325,15,0,0,...,0,4696,0,0,1077,672,0,163,0,0
Abroad 1 year ago--: U.S. Island Area (MOE),5276,192,28,121,190,915,326,31,190,200,...,200,3750,187,149,645,426,189,171,192,221
Abroad 1 year ago--: Foreign Country (Estimate),1976216,11708,4438,45655,9036,334039,33036,24562,4372,10871,...,23425,207786,23582,4234,67069,60854,3072,19290,2793,5427
Abroad 1 year ago--: Foreign Country (MOE),37433,2403,1285,5434,2094,16226,3694,3181,1467,3037,...,3946,12375,2644,1883,6349,7056,1120,3306,1278,1535

In [15]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [16]:

df = df.iloc[1:]

df

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),317635720,4801599,727862,6747595,2938341,38675135,5393067,3554844,935813,663006,...,6522259,27092848,2947423,619952,8283737,7089143,1823753,5708201,579102,3443445
Population 1 year and over (MOE),28922,3420,1356,4243,3200,11051,3719,3252,1401,1528,...,4265,11293,3093,781,4532,3701,2120,3093,1256,2859
Same house 1 year ago (Estimate),270873397,4113945,582909,5536087,2440359,33446324,4404058,3109580,800701,525024,...,5535963,22723345,2435722,532319,6952362,5778806,1610407,4891636,474927,3193423
Same house 1 year ago (MOE),189370,22379,9527,26178,17443,47467,21899,17815,9561,7553,...,28320,58176,19625,5199,28986,28406,10957,19111,7256,14727
Same state of residence 1 year ago (Estimate),37146496,561019,105769,910911,407352,4377667,728077,340126,86009,67188,...,766524,3594282,390649,62067,983569,1017221,167631,690306,65384,219833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),8853,102,62,1296,190,698,209,2602,271,41,...,500,3395,157,109,737,523,562,226,70,N/A3
Abroad 1 year ago--: U.S. Island Area (Estimate),20482,0,16,105,0,1518,325,15,0,0,...,0,4696,0,0,1077,672,0,163,0,0
Abroad 1 year ago--: U.S. Island Area (MOE),5276,192,28,121,190,915,326,31,190,200,...,200,3750,187,149,645,426,189,171,192,221
Abroad 1 year ago--: Foreign Country (Estimate),1976216,11708,4438,45655,9036,334039,33036,24562,4372,10871,...,23425,207786,23582,4234,67069,60854,3072,19290,2793,5427
Abroad 1 year ago--: Foreign Country (MOE),37433,2403,1285,5434,2094,16226,3694,3181,1467,3037,...,3946,12375,2644,1883,6349,7056,1120,3306,1278,1535

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [17]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [18]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [19]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Population 1 year and over (Estimate)                             663006
Same house 1 year ago (Estimate)                                  525024
Same state of residence 1 year ago (Estimate)                      67188
Different state of residence 1 year ago: Total ...                 59905
Different state of residence 1 year ago: Alabam...                   359
Different state of residence 1 year ago (contin...                   235
Different state of residence 1 year ago (contin...                   367
Different state of residence 1 year ago (contin...                   203
Different state of residence 1 year ago (contin...                  4119
Different state of residence 1 year ago (contin...                   433
Different state of residence 1 year ago (contin...                  1292
Different state of residence 1 year ago (contin...                   252
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  2731
Different state of residence 1 year ago (contin...                  1013
Different state of residence 1 year ago (contin...                    52
Different state of residence 1 year ago (contin...                     5
Different state of residence 1 year ago (contin...                   785
Different state of residence 1 year ago (contin...                   748
Different state of residence 1 year ago (contin...                   135
Different state of residence 1 year ago (contin...                    33
Different state of residence 1 year ago (contin...                   275
Different state of residence 1 year ago (contin...                   392
Different state of residence 1 year ago (contin...                   258
Different state of residence 1 year ago (contin...                 14726
Different state of residence 1 year ago (contin...                  2876
Different state of residence 1 year ago (contin...                  1308
Different state of residence 1 year ago (contin...                   545
Different state of residence 1 year ago (contin...                   338
Different state of residence 1 year ago (contin...                   141
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   674
Different state of residence 1 year ago (contin...                    68
Different state of residence 1 year ago (contin...                    47
Different state of residence 1 year ago (contin...                  1804
Different state of residence 1 year ago (contin...                    40
Different state of residence 1 year ago (contin...                  5133
Different state of residence 1 year ago (contin...                  1501
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  1027
Different state of residence 1 year ago (contin...                   150
Different state of residence 1 year ago (contin...                   157
Different state of residence 1 year ago (contin...                  1999
Different state of residence 1 year ago (contin...                   234
Different state of residence 1 year ago (contin...                  1806
Different state of residence 1 year ago (contin...                     9
Different state of residence 1 year ago (contin...                   873
Different state of residence 1 year ago (contin...                  1314
Different state of residence 1 year ago (contin...                   177
Different state of residence 1 year ago (contin...                   117
Different state of residence 1 year ago (contin...                  8028
Different state of residence 1 year ago (contin...                   134
Different state of residence 1 year ago (contin...                   478
Different state of residence 1 year ago (contin...                   514
Different state of residence 1 year ago (contin...                     0
Abroad 1 year ago--: Total (Estimate)                              10889
Abroad 1 year ago--: Puerto Rico (Estimate)                           18
Abroad 1 year ago--: U.S. Island Area (Estimate)                       0
Abroad 1 year ago--: Foreign Country (Estimate)                    10871

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [20]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

Cut off the top columns that arent for specific states

In [21]:

df_estimates = df_estimates[4:]
df_moes = df_moes[4:]

In [22]:
df_moes.head()

0          District of Columbia
0
Alabama                      302
Alaska                       257
Arizona                      293
Arkansas                     200
California                  1258

In [23]:
df_estimates.head()

0          District of Columbia
0
Alabama                      359
Alaska                       235
Arizona                      367
Arkansas                     203
California                  4119

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [24]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Also need to cut out one "total" column that is the total amount of "Abroad One Year Ago" incl PR, US Island Area, and Foreign Country

In [25]:
df = df.drop('Total')

df

0                    District of Columbia  MOE +/-
0
Alabama                                359     302
Alaska                                 235     257
Arizona                                367     293
Arkansas                               203     200
California                            4119    1258
Colorado                               433     360
Connecticut                           1292     648
Delaware                               252     251
District of Columbia                     0       0
Florida                               2731     936
Georgia                               1013     533
Hawaii                                  52     122
Idaho                                    5      11
Illinois                               785     357
Indiana                                748     460
Iowa                                   135     169
Kansas                                  33      77
Kentucky                               275     252
Louisiana                              392     388
Maine                                  258     208
Maryland                             14726    2234
Massachusetts                         2876    1070
Michigan                              1308     539
Minnesota                              545     495
Mississippi                            338     211
Missouri                               141     139
Montana                                  0     200
Nebraska                               674     423
Nevada                                  68      92
New Hampshire                           47      59
New Jersey                            1804     800
New Mexico                              40      68
New York                              5133    1205
North Carolina                        1501     695
North Dakota                             0     200
Ohio                                  1027     713
Oklahoma                               150     204
Oregon                                 157     211
Pennsylvania                          1999     637
Rhode Island                           234     208
South Carolina                        1806    1518
South Dakota                             9      21
Tennessee                              873     430
Texas                                 1314     584
Utah                                   177     187
Vermont                                117     143
Virginia                              8028    1715
Washington                             134     164
West Virginia                          478     432
Wisconsin                              514     421
Wyoming                                  0     200
Puerto Rico                             18      41
U.S. Island Area                         0     200
Foreign Country                      10871    3037

also need to drop out the last two columns US Island Area and Foreign Country because those dont exist in the pop df and I don't need for this analysis

In [26]:
df = df.drop('U.S. Island Area')
df = df.drop('Foreign Country')

also need to drop the top row of pops df to get the dataframes to have the same row indices

In [27]:
df_pops = df_pops.drop('Label (Grouping)')

Now I'm adding a state polulation column to my newly formatted table

In [28]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [29]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

df.head()

0          pop_migrated MOE +/- state_population
0
Alabama             359     302        5,024,279
Alaska              235     257          733,391
Arizona             367     293        7,151,502
Arkansas            203     200        3,011,524
California         4119    1258       39,538,223

And strip commas in state_population column

In [30]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [31]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       359     302          5024279
Alaska                        235     257           733391
Arizona                       367     293          7151502
Arkansas                      203     200          3011524
California                   4119    1258         39538223
Colorado                      433     360          5773714
Connecticut                  1292     648          3605944
Delaware                      252     251           989948
District of Columbia            0       0           689545
Florida                      2731     936         21538187
Georgia                      1013     533         10711908
Hawaii                         52     122          1455271
Idaho                           5      11          1839106
Illinois                      785     357         12812508
Indiana                       748     460          6785528
Iowa                          135     169          3190369
Kansas                         33      77          2937880
Kentucky                      275     252          4505836
Louisiana                     392     388          4657757
Maine                         258     208          1362359
Maryland                    14726    2234          6177224
Massachusetts                2876    1070          7029917
Michigan                     1308     539         10077331
Minnesota                     545     495          5706494
Mississippi                   338     211          2961279
Missouri                      141     139          6154913
Montana                         0     200          1084225
Nebraska                      674     423          1961504
Nevada                         68      92          3104614
New Hampshire                  47      59          1377529
New Jersey                   1804     800          9288994
New Mexico                     40      68          2117522
New York                     5133    1205         20201249
North Carolina               1501     695         10439388
North Dakota                    0     200           779094
Ohio                         1027     713         11799448
Oklahoma                      150     204          3959353
Oregon                        157     211          4237256
Pennsylvania                 1999     637         13002700
Rhode Island                  234     208          1097379
South Carolina               1806    1518          5118425
South Dakota                    9      21           886667
Tennessee                     873     430          6910840
Texas                        1314     584         29145505
Utah                          177     187          3271616
Vermont                       117     143           643077
Virginia                     8028    1715          8631393
Washington                    134     164          7705281
West Virginia                 478     432          1793716
Wisconsin                     514     421          5893718
Wyoming                         0     200           576851
Puerto Rico                    18      41          3285874

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [32]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [33]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [34]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,359,302,5024279,0.000071,0.000060
1,Alaska,235,257,733391,0.000320,0.000350
2,Arizona,367,293,7151502,0.000051,0.000041
3,Arkansas,203,200,3011524,0.000067,0.000066
4,California,4119,1258,39538223,0.000104,0.000032

Looking at states with most people coming to DC

In [35]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
20,Maryland,14726,2234,6177224,0.002384,0.000362
46,Virginia,8028,1715,8631393,0.000930,0.000199
21,Massachusetts,2876,1070,7029917,0.000409,0.000152
6,Connecticut,1292,648,3605944,0.000358,0.000180
40,South Carolina,1806,1518,5118425,0.000353,0.000297
27,Nebraska,674,423,1961504,0.000344,0.000216
1,Alaska,235,257,733391,0.000320,0.000350
48,West Virginia,478,432,1793716,0.000266,0.000241
7,Delaware,252,251,989948,0.000255,0.000254
32,New York,5133,1205,20201249,0.000254,0.000060

To export, want to make a slice excluding all DMV states -- Maryland, Virginia, DC

Also need to exclude PR because I'm just doing continental US

In [36]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]
df = df[df["state"] != "District of Columbia"]

Now need to reset the indexes again to make numbers consecutive now that I've removed ceratin rows.

In [37]:
df = df.reset_index(drop=True)

Add in 2012 election results

First read in file

In [38]:
df_2012_election_winners = pd.read_csv('pres-election-results-2012.csv')

type(df_2012_election_winners)

pandas.DataFrame

Next, add columns to dataframe w election results -- one for winning party and one for percent of votes that that party won by

In [39]:
df['winning_party'] = df_2012_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2012_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,359,302,5024279,0.000071,0.000060,REPUBLICAN,0.605458
1,Alaska,235,257,733391,0.000320,0.000350,REPUBLICAN,0.548016
2,Arizona,367,293,7151502,0.000051,0.000041,REPUBLICAN,0.536545
3,Arkansas,203,200,3011524,0.000067,0.000066,REPUBLICAN,0.605669
4,California,4119,1258,39538223,0.000104,0.000032,DEMOCRAT,0.602390

Save as csv file

In [40]:
df.to_csv('DC-migration-2015.csv')