This is a notebook to merge each year data from my other notebooks

In [1]:
import pandas as pd

Read in all the csv files that I cleaned up from each election year

In [2]:
df_2005 = pd.read_csv('DC-migration-2005.csv')
df_2009 = pd.read_csv('DC-migration-2009.csv')
df_2013 = pd.read_csv('DC-migration-2013.csv')
df_2017 = pd.read_csv('DC-migration-2017.csv')
df_2021 = pd.read_csv('DC-migration-2021.csv')

Starting the new dataframe w the 2005 data's migrated adjusted and moe adjusted rows.

In [3]:
df = df_2005[['0', 'migrated_adjusted', 'moe_adjusted']]

df.head()

            0  migrated_adjusted  moe_adjusted
0     Alabama           0.000000      0.000057
1      Alaska           0.000000      0.000390
2     Arizona           0.000069      0.000080
3    Arkansas           0.000000      0.000095
4  California           0.000059      0.000026

Renaming the states column to be titled 'state names'

In [4]:
df.rename(columns={'0':'state_names'}, inplace=True)

df.head()

  state_names  migrated_adjusted  moe_adjusted
0     Alabama           0.000000      0.000057
1      Alaska           0.000000      0.000390
2     Arizona           0.000069      0.000080
3    Arkansas           0.000000      0.000095
4  California           0.000059      0.000026

Rename the columns to be clear they are attatched to the 2005 data before adding in other years.

In [5]:
df.rename(columns={'migrated_adjusted':'migr_adj_2005'}, inplace=True)
df.rename(columns={'moe_adjusted':'moe_adj_2005'}, inplace=True)

Add 2009 migrated adjusted and moe adjusted rows.

In [6]:
df['migr_adj_2009'] = df_2009['migrated_adjusted']
df['moe_adj_2009'] = df_2009['moe_adjusted']

df.head()

  state_names  migr_adj_2005  moe_adj_2005  migr_adj_2009  moe_adj_2009
0     Alabama       0.000000      0.000057       0.000040      0.000033
1      Alaska       0.000000      0.000390       0.000327      0.000381
2     Arizona       0.000069      0.000080       0.000004      0.000008
3    Arkansas       0.000000      0.000095       0.000035      0.000042
4  California       0.000059      0.000026       0.000075      0.000023

Add 2013 migrated adjusted and moe adjusted rows.

In [7]:
df['migr_adj_2013'] = df_2013['migrated_adjusted']
df['moe_adj_2013'] = df_2013['moe_adjusted']

df.head()

,state_names,migr_adj_2005,moe_adj_2005,migr_adj_2009,moe_adj_2009,migr_adj_2013,moe_adj_2013
0,Alabama,0.000000,0.000057,0.000040,0.000033,0.000063,0.000043
1,Alaska,0.000000,0.000390,0.000327,0.000381,0.000789,0.000897
2,Arizona,0.000069,0.000080,0.000004,0.000008,0.000011,0.000018
3,Arkansas,0.000000,0.000095,0.000035,0.000042,0.000000,0.000064
4,California,0.000059,0.000026,0.000075,0.000023,0.000061,0.000021

Add 2017 migrated adjusted and moe adjusted rows.

In [8]:
df['migr_adj_2017'] = df_2017['migrated_adjusted']
df['moe_adj_2017'] = df_2017['moe_adjusted']

df.head()

,state_names,migr_adj_2005,moe_adj_2005,migr_adj_2009,moe_adj_2009,migr_adj_2013,moe_adj_2013,migr_adj_2017,moe_adj_2017
0,Alabama,0.000000,0.000057,0.000040,0.000033,0.000063,0.000043,0.000098,0.000083
1,Alaska,0.000000,0.000390,0.000327,0.000381,0.000789,0.000897,0.000000,0.000284
2,Arizona,0.000069,0.000080,0.000004,0.000008,0.000011,0.000018,0.000077,0.000093
3,Arkansas,0.000000,0.000095,0.000035,0.000042,0.000000,0.000064,0.000035,0.000048
4,California,0.000059,0.000026,0.000075,0.000023,0.000061,0.000021,0.000095,0.000026

Add 2021 migrated adjusted and moe adjusted rows.

In [9]:
df['migr_adj_2021'] = df_2021['migrated_adjusted']
df['moe_adj_2021'] = df_2021['moe_adjusted']

df.head()

,state_names,migr_adj_2005,moe_adj_2005,migr_adj_2009,moe_adj_2009,migr_adj_2013,moe_adj_2013,migr_adj_2017,moe_adj_2017,migr_adj_2021,moe_adj_2021
0,Alabama,0.000000,0.000057,0.000040,0.000033,0.000063,0.000043,0.000098,0.000083,0.000068,0.000073
1,Alaska,0.000000,0.000390,0.000327,0.000381,0.000789,0.000897,0.000000,0.000284,0.000267,0.000244
2,Arizona,0.000069,0.000080,0.000004,0.000008,0.000011,0.000018,0.000077,0.000093,0.000094,0.000088
3,Arkansas,0.000000,0.000095,0.000035,0.000042,0.000000,0.000064,0.000035,0.000048,0.000012,0.000025
4,California,0.000059,0.000026,0.000075,0.000023,0.000061,0.000021,0.000095,0.000026,0.000100,0.000033

In [10]:
df.to_csv('DC-migration-compiled-election-years.csv')