I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2011.xls')

In [3]:
df.shape

(84, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,307900319,29996,261087925,263315,37998701,233440,6987416,77858,106806,...,4631,United States1,1826277,39657,76218,8799,13131,3168,1736928,37914

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,307900319,29996,261087925,263315,37998701,233440,6987416,77858,106806,...,4631,United States1,1826277,39657,76218,8799,13131,3168,1736928,37914
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4745278,4078,4024442,22751,588293,20366,117726,9414,NaN,...,15,Alabama,14817,2811,569,601,0,190,14248,2893
11,Alaska,711962,1401,571857,8892,100280,8388,35084,4168,93,...,272,Alaska,4741,1264,1044,962,0,149,3697,901
12,Arizona,6402301,5660,5107496,39045,1028366,36556,222877,14358,833,...,1288,Arizona,43562,6373,871,639,122,135,42569,6259
13,Arkansas,2906632,2928,2421746,18606,405831,18050,69845,7292,691,...,399,Arkansas,9210,3170,529,507,46,81,8635,3062
14,California,37222678,9999,31213310,71183,5271168,68394,468428,17921,2087,...,1810,California,269772,16003,1344,635,2817,2043,265611,15898
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5048443,4037,4048042,22888,763233,18937,202124,11431,2340,...,923,Colorado,35044,5809,476,556,57,79,34511,5839
17,Connecticut,3548667,2644,3139496,16755,316883,15392,71502,6552,101,...,110,Connecticut,20786,4003,2105,1756,0,198,18681,3485
18,Delaware,897187,1369,775414,8584,83156,6851,33912,3955,81,...,527,Delaware,4705,1519,1008,971,0,192,3697,1338
19,District of Columbia,611608,1403,489659,6701,66519,6073,48066,4295,13,...,200,District of Columbia,7364,1786,0,200,0,200,7364,1786
20,Florida,18863948,8536,15742168,59355,2454255,53419,498597,22483,12635,...,725,Florida,168928,14572,21611,5621,2643,1361,144674,12266
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,9699859,5580,8095407,40769,1289450,37444,271077,15123,18799,...,775,Georgia,43925,5368,1635,841,992,1218,41298,5237
23,Hawaii,1357806,1803,1160948,10743,122727,8676,57542,5083,1268,...,23,Hawaii,16589,3678,238,398,114,133,16237,3632

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,307900319,29996,261087925,263315,37998701,233440,6987416,77858,106806,...,4631,United States1,1826277,39657,76218,8799,13131,3168,1736928,37914
10,Alabama,4745278,4078,4024442,22751,588293,20366,117726,9414,NaN,...,15,Alabama,14817,2811,569,601,0,190,14248,2893
11,Alaska,711962,1401,571857,8892,100280,8388,35084,4168,93,...,272,Alaska,4741,1264,1044,962,0,149,3697,901
12,Arizona,6402301,5660,5107496,39045,1028366,36556,222877,14358,833,...,1288,Arizona,43562,6373,871,639,122,135,42569,6259
13,Arkansas,2906632,2928,2421746,18606,405831,18050,69845,7292,691,...,399,Arkansas,9210,3170,529,507,46,81,8635,3062
14,California,37222678,9999,31213310,71183,5271168,68394,468428,17921,2087,...,1810,California,269772,16003,1344,635,2817,2043,265611,15898
16,Colorado,5048443,4037,4048042,22888,763233,18937,202124,11431,2340,...,923,Colorado,35044,5809,476,556,57,79,34511,5839
17,Connecticut,3548667,2644,3139496,16755,316883,15392,71502,6552,101,...,110,Connecticut,20786,4003,2105,1756,0,198,18681,3485
18,Delaware,897187,1369,775414,8584,83156,6851,33912,3955,81,...,527,Delaware,4705,1519,1008,971,0,192,3697,1338
19,District of Columbia,611608,1403,489659,6701,66519,6073,48066,4295,13,...,200,District of Columbia,7364,1786,0,200,0,200,7364,1786
20,Florida,18863948,8536,15742168,59355,2454255,53419,498597,22483,12635,...,725,Florida,168928,14572,21611,5621,2643,1361,144674,12266
22,Georgia,9699859,5580,8095407,40769,1289450,37444,271077,15123,18799,...,775,Georgia,43925,5368,1635,841,992,1218,41298,5237
23,Hawaii,1357806,1803,1160948,10743,122727,8676,57542,5083,1268,...,23,Hawaii,16589,3678,238,398,114,133,16237,3632
24,Idaho,1559637,2674,1284530,13188,208434,13285,60336,6293,263,...,340,Idaho,6337,1846,249,412,34,53,6054,1758
25,Illinois,12718402,5792,11076528,31383,1353853,28856,216204,11862,2823,...,76,Illinois,71817,6607,2387,715,76,79,69354,6616
26,Indiana,6437155,3841,5478683,24180,809158,21392,127874,8918,1562,...,170,Indiana,21440,4553,132,220,121,141,21187,4544
28,Iowa,3027718,2514,2573313,16682,370554,15638,70405,5539,207,...,117,Iowa,13446,2997,57,115,44,68,13345,2986

Rename columns to be clearer, including manually renaming certain columns and stripping 'Unnamed: ' from the rest

In [9]:
print(df.columns.tolist())

['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129']

In [10]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns, just trimming:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)


print(df.columns.tolist())

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129']

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [11]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [12]:
df.iloc[3:] = df.iloc[3:].fillna('0')

In [13]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,307900319,29996,261087925,263315,37998701,233440,6987416,77858,106806,...,31991,4631,1826277,39657,76218,8799,13131,3168,1736928,37914
10,Alabama,4745278,4078,4024442,22751,588293,20366,117726,9414,0,...,9,15,14817,2811,569,601,0,190,14248,2893

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [14]:
#For the rest of the columns:
#first, fill in blanks

df_filledin = df.ffill(axis=1)

df_filledin.head()

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,Population 1 year and over,Same house 1 year ago,Same house 1 year ago,Same state of residence 1 year ago,Same state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,...,Different state of residence 1 year ago (cont.),Different state of residence 1 year ago (cont.),Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,Total,Alabama,...,Wyoming,Wyoming,Total,Total,Puerto Rico,Puerto Rico,U.S. Island Area,U.S. Island Area,Foreign Country,Foreign Country
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,307900319,29996,261087925,263315,37998701,233440,6987416,77858,106806,...,31991,4631,1826277,39657,76218,8799,13131,3168,1736928,37914
10,Alabama,4745278,4078,4024442,22751,588293,20366,117726,9414,0,...,9,15,14817,2811,569,601,0,190,14248,2893

In [15]:
#then pull the info I need to name each column

for i in range(1, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

In [16]:
df_filledin.head()

,0,Population 1 year and over: nan (Estimate),Population 1 year and over: nan (MOE),Same house 1 year ago: nan (Estimate),Same house 1 year ago: nan (MOE),Same state of residence 1 year ago: nan (Estimate),Same state of residence 1 year ago: nan (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (Estimate),Different state of residence 1 year ago (cont.): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
4,Current residence in --,Population 1 year and over,Population 1 year and over,Same house 1 year ago,Same house 1 year ago,Same state of residence 1 year ago,Same state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,...,Different state of residence 1 year ago (cont.),Different state of residence 1 year ago (cont.),Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,Total,Alabama,...,Wyoming,Wyoming,Total,Total,Puerto Rico,Puerto Rico,U.S. Island Area,U.S. Island Area,Foreign Country,Foreign Country
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,307900319,29996,261087925,263315,37998701,233440,6987416,77858,106806,...,31991,4631,1826277,39657,76218,8799,13131,3168,1736928,37914
10,Alabama,4745278,4078,4024442,22751,588293,20366,117726,9414,0,...,9,15,14817,2811,569,601,0,190,14248,2893

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [17]:
df = df_filledin.iloc[4:]

In [18]:
df

,0,Population 1 year and over: nan (Estimate),Population 1 year and over: nan (MOE),Same house 1 year ago: nan (Estimate),Same house 1 year ago: nan (MOE),Same state of residence 1 year ago: nan (Estimate),Same state of residence 1 year ago: nan (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (Estimate),Different state of residence 1 year ago (cont.): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
10,Alabama,4745278,4078,4024442,22751,588293,20366,117726,9414,0,...,9,15,14817,2811,569,601,0,190,14248,2893
11,Alaska,711962,1401,571857,8892,100280,8388,35084,4168,93,...,246,272,4741,1264,1044,962,0,149,3697,901
12,Arizona,6402301,5660,5107496,39045,1028366,36556,222877,14358,833,...,2510,1288,43562,6373,871,639,122,135,42569,6259
13,Arkansas,2906632,2928,2421746,18606,405831,18050,69845,7292,691,...,252,399,9210,3170,529,507,46,81,8635,3062
14,California,37222678,9999,31213310,71183,5271168,68394,468428,17921,2087,...,2047,1810,269772,16003,1344,635,2817,2043,265611,15898
16,Colorado,5048443,4037,4048042,22888,763233,18937,202124,11431,2340,...,2942,923,35044,5809,476,556,57,79,34511,5839
17,Connecticut,3548667,2644,3139496,16755,316883,15392,71502,6552,101,...,65,110,20786,4003,2105,1756,0,198,18681,3485
18,Delaware,897187,1369,775414,8584,83156,6851,33912,3955,81,...,463,527,4705,1519,1008,971,0,192,3697,1338
19,District of Columbia,611608,1403,489659,6701,66519,6073,48066,4295,13,...,0,200,7364,1786,0,200,0,200,7364,1786
20,Florida,18863948,8536,15742168,59355,2454255,53419,498597,22483,12635,...,846,725,168928,14572,21611,5621,2643,1361,144674,12266
22,Georgia,9699859,5580,8095407,40769,1289450,37444,271077,15123,18799,...,504,775,43925,5368,1635,841,992,1218,41298,5237
23,Hawaii,1357806,1803,1160948,10743,122727,8676,57542,5083,1268,...,14,23,16589,3678,238,398,114,133,16237,3632
24,Idaho,1559637,2674,1284530,13188,208434,13285,60336,6293,263,...,487,340,6337,1846,249,412,34,53,6054,1758
25,Illinois,12718402,5792,11076528,31383,1353853,28856,216204,11862,2823,...,58,76,71817,6607,2387,715,76,79,69354,6616
26,Indiana,6437155,3841,5478683,24180,809158,21392,127874,8918,1562,...,117,170,21440,4553,132,220,121,141,21187,4544
28,Iowa,3027718,2514,2573313,16682,370554,15638,70405,5539,207,...,140,117,13446,2997,57,115,44,68,13345,2986
29,Kansas,2833584,2851,2372033,15236,362782,14847,83640,7144,434,...,1285,791,15129,2288,775,1013,253,396,14101,2164
30,Kentucky,4316297,3382,3686232,19523,505741,18525,110031,9177,925,...,57,93,14293,2809,192,262,0,189,14101,2765
31,Louisiana,4518629,3250,3865118,18789,538691,17818,99138,7082,3065,...,357,541,15682,2868,393,384,32,64,15257,2813
32,Maine,1315833,1456,1120364,10400,157102,9401,33818,4248,634,...,21,37,4549,1726,65,64,0,157,4484,1731
34,Maryland,5759087,4326,5008452,20478,553895,18323,153979,9033,228,...,80,132,42761,5926,779,654,133,158,41849,5966
35,Massachusetts,6515057,3680,5658768,20357,656441,18778,139830,8282,1201,...,0,204,60018,5394,4413,1542,294,364,55311,5211
36,Michigan,9766574,4376,8340767,29076,1242917,25401,139158,8465,3527,...,841,655,43732,5321,908,857,478,572,42346,4976
37,Minnesota,5277329,3380,4505462,20788,646176,19647,101029,7052,123,...,224,178,24662,3040,54,91,35,45,24573,3040
38,Mississippi,2943021,3088,2534036,16620,332934,15960,68511,5606,8922,...,0,206,7540,2070,318,411,87,110,7135,1978
40,Missouri,5937896,4110,4963040,26160,801046,25054,149439,9288,1395,...,1120,900,24371,3772,709,463,222,216,23440,3736
41,Montana,987076,1359,828254,8593,122210,8386,33553,4015,449,...,2413,1709,3059,1062,353,522,0,165,2706,801
44,0,0,0,0,0,0,0,Total,0,Alabama,...,Wyoming,0,Total,0,Puerto Rico,0,U.S. Island Area,0,Foreign Country,0
45,0,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1817126,2304,1505191,11978,253269,10841,52070,5507,169,...,965,421,6596,1476,0,155,11,19,6585,1478
48,Nevada,2688336,3578,2084668,23272,480317,23514,110345,9419,280,...,933,702,13006,2756,153,258,127,149,12726,2687
49,New Hampshire,1305678,2046,1141236,9064,122129,8186,37000,3717,193,...,162,218,5313,1388,0,184,0,184,5313,1388
50,New Jersey,8719952,4595,7825661,21158,693380,21063,140194,8607,189,...,15,29,60717,5750,4312,1535,73,103,56332,5497
51,New Mexico,2055293,2718,1753413,15690,228218,13801,62130,7330,410,...,283,313,11532,2620,99,158,0,198,11433,2625
53,New York,19248685,7023,17055260,37016,1756105,32216,282209,11956,1812,...,688,645,155111,10586,10582,3796,254,305,144275,9818
54,North Carolina,9539412,5364,8070238,36924,1160510,33476,265291,16660,5420,...,153,228,43373,5356,844,447,582,474,41947,5419
55,North Dakota,675161,1047,559906,6503,79837,6140,32510,3641,97,...,139,102,2908,1066,76,110,0,143,2832,1056
56,Ohio,11418944,4418,9764366,32087,1425709,29701,191778,11799,1567,...,1280,793,37091,4223,1607,1062,458,536,35026,4118
57,Oklahoma,3742698,2585,3089041,15209,528498,15584,108878,7998,591,...,1763,1572,16281,3206,105,139,47,48,16129,3205
59,Oregon,3828714,3857,3128121,20096,549332,19087,127906,9071,758,...,914,880,23355,4384,4,8,549,523,22802,4332
60,Pennsylvania,12610486,5092,11099077,27780,1224564,25195,234291,11246,1332,...,195,237,52554,5764,2723,1294,166,243,49665,5697
61,Rhode Island,1040022,1440,903786,8645,101689,7813,26769,2836,0,...,23,47,7778,1837,293,292,249,353,7236,1796
62,South Carolina,4624180,3871,3899705,25459,546666,21151,157644,12647,2999,...,632,647,20165,6013,2166,1534,203,195,17796,5881
63,South Dakota,814175,1297,688436,7824,94655,6542,27506,3893,0,...,1310,880,3578,1550,0,155,0,155,3578,1550
65,Tennessee,6333466,4450,5342978,29750,794556,26578,170969,13046,9326,...,131,214,24963,4567,1083,1191,59,100,23821,4238
66,Texas,25327104,10987,20984855,65490,3648260,63784,514726,23860,8747,...,2500,1485,179263,13868,5225,2173,710,778,173328,13486
67,Utah,2769627,2949,2295961,19215,373984,17246,85217,7587,486,...,1058,609,14465,2475,0,192,0,192,14465,2475
68,Vermont,621354,940,537304,5021,60719,4634,20463,1946,0,...,38,62,2868,803,19,45,0,145,2849,800
69,Virginia,7996552,5256,6789620,30962,889751,30111,257130,14025,4930,...,190,274,60051,6990,1222,779,124,201,58705,6768
71,Washington,6748474,4248,5565069,27197,919925,27221,208507,13639,1821,...,1507,870,54973,5730,1083,1061,362,321,53528,5625
72,West Virginia,1836614,1681,1609110,9854,172262,8430,50068,4934,221,...,0,184,5174,1423,680,450,557,556,3937,1154
73,Wisconsin,5647213,2653,4846550,18735,675623,19411,109439,8715,708,...,14,23,15601,2441,728,715,0,151,14873,2450
74,Wyoming,561389,1021,462808,7194,66648,5771,30651,4428,51,...,0,0,1282,1155,0,189,0,189,1282,1155
76,Puerto Rico,3669195,3034,3403602,12450,238263,11889,22649,3662,35,...,0,210,4681,2095,N/A2,N/A2,0,210,4681,2095

And can also delete excess title columns at the start

In [19]:
df = df.drop(columns = 
    ['Population 1 year and over: nan (Estimate)',
    'Population 1 year and over: nan (MOE)',
    'Same house 1 year ago: nan (Estimate)',
    'Same house 1 year ago: nan (MOE)',
    'Same state of residence 1 year ago: nan (Estimate)',
    'Same state of residence 1 year ago: nan (MOE)',
    'Different state of residence 1 year ago: Total (Estimate)',
    'Different state of residence 1 year ago: Total (MOE)'])

df.head()

,0,Different state of residence 1 year ago: Alabama (Estimate),Different state of residence 1 year ago: Alabama (MOE),Different state of residence 1 year ago (cont.): Alaska (Estimate),Different state of residence 1 year ago (cont.): Alaska (MOE),Different state of residence 1 year ago (cont.): Arizona (Estimate),Different state of residence 1 year ago (cont.): Arizona (MOE),Different state of residence 1 year ago (cont.): Arkansas (Estimate),Different state of residence 1 year ago (cont.): Arkansas (MOE),Different state of residence 1 year ago (cont.): California (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (Estimate),Different state of residence 1 year ago (cont.): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
10,Alabama,0,0,1771,1098,1677,1060,1642,1063,3389,...,9,15,14817,2811,569,601,0,190,14248,2893
11,Alaska,93,113,0,0,2467,1902,190,258,3098,...,246,272,4741,1264,1044,962,0,149,3697,901
12,Arizona,833,587,5001,2214,0,0,1066,740,49635,...,2510,1288,43562,6373,871,639,122,135,42569,6259
13,Arkansas,691,573,560,669,439,381,0,0,4077,...,252,399,9210,3170,529,507,46,81,8635,3062
14,California,2087,927,7358,2501,35650,4362,2648,1019,0,...,2047,1810,269772,16003,1344,635,2817,2043,265611,15898

In [20]:
df

,0,Different state of residence 1 year ago: Alabama (Estimate),Different state of residence 1 year ago: Alabama (MOE),Different state of residence 1 year ago (cont.): Alaska (Estimate),Different state of residence 1 year ago (cont.): Alaska (MOE),Different state of residence 1 year ago (cont.): Arizona (Estimate),Different state of residence 1 year ago (cont.): Arizona (MOE),Different state of residence 1 year ago (cont.): Arkansas (Estimate),Different state of residence 1 year ago (cont.): Arkansas (MOE),Different state of residence 1 year ago (cont.): California (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (Estimate),Different state of residence 1 year ago (cont.): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
10,Alabama,0,0,1771,1098,1677,1060,1642,1063,3389,...,9,15,14817,2811,569,601,0,190,14248,2893
11,Alaska,93,113,0,0,2467,1902,190,258,3098,...,246,272,4741,1264,1044,962,0,149,3697,901
12,Arizona,833,587,5001,2214,0,0,1066,740,49635,...,2510,1288,43562,6373,871,639,122,135,42569,6259
13,Arkansas,691,573,560,669,439,381,0,0,4077,...,252,399,9210,3170,529,507,46,81,8635,3062
14,California,2087,927,7358,2501,35650,4362,2648,1019,0,...,2047,1810,269772,16003,1344,635,2817,2043,265611,15898
16,Colorado,2340,1681,3191,1622,12338,3704,1615,1191,23234,...,2942,923,35044,5809,476,556,57,79,34511,5839
17,Connecticut,101,120,180,299,1387,939,84,178,3699,...,65,110,20786,4003,2105,1756,0,198,18681,3485
18,Delaware,81,135,329,544,541,728,0,192,699,...,463,527,4705,1519,1008,971,0,192,3697,1338
19,District of Columbia,13,29,135,217,43,71,81,93,3797,...,0,200,7364,1786,0,200,0,200,7364,1786
20,Florida,12635,3566,7405,3412,8451,3258,3025,1241,22420,...,846,725,168928,14572,21611,5621,2643,1361,144674,12266
22,Georgia,18799,5015,1079,765,4292,1849,2112,1366,14949,...,504,775,43925,5368,1635,841,992,1218,41298,5237
23,Hawaii,1268,846,844,670,2900,1208,242,260,10173,...,14,23,16589,3678,238,398,114,133,16237,3632
24,Idaho,263,259,4510,2938,3543,1771,224,188,9021,...,487,340,6337,1846,249,412,34,53,6054,1758
25,Illinois,2823,1526,4119,3153,7657,1987,3185,1513,13930,...,58,76,71817,6607,2387,715,76,79,69354,6616
26,Indiana,1562,1293,371,324,3975,1427,2016,1321,7649,...,117,170,21440,4553,132,220,121,141,21187,4544
28,Iowa,207,259,967,651,1411,726,433,317,3297,...,140,117,13446,2997,57,115,44,68,13345,2986
29,Kansas,434,310,108,84,2028,858,998,697,4743,...,1285,791,15129,2288,775,1013,253,396,14101,2164
30,Kentucky,925,441,0,189,1818,916,1058,778,2130,...,57,93,14293,2809,192,262,0,189,14101,2765
31,Louisiana,3065,1401,288,266,2010,1529,2774,1144,3957,...,357,541,15682,2868,393,384,32,64,15257,2813
32,Maine,634,541,37,43,325,301,38,67,829,...,21,37,4549,1726,65,64,0,157,4484,1731
34,Maryland,228,128,671,493,945,604,423,528,8595,...,80,132,42761,5926,779,654,133,158,41849,5966
35,Massachusetts,1201,1083,225,345,1017,518,167,201,11556,...,0,204,60018,5394,4413,1542,294,364,55311,5211
36,Michigan,3527,2060,3456,1793,3840,1382,2054,1024,7793,...,841,655,43732,5321,908,857,478,572,42346,4976
37,Minnesota,123,150,893,619,2314,1071,951,599,6638,...,224,178,24662,3040,54,91,35,45,24573,3040
38,Mississippi,8922,2639,117,102,556,405,2315,1360,4723,...,0,206,7540,2070,318,411,87,110,7135,1978
40,Missouri,1395,654,2043,2471,2356,1028,6168,1528,8386,...,1120,900,24371,3772,709,463,222,216,23440,3736
41,Montana,449,318,1118,921,1971,1358,49,70,3033,...,2413,1709,3059,1062,353,522,0,165,2706,801
44,0,Alabama,0,Alaska,0,Arizona,0,Arkansas,0,California,...,Wyoming,0,Total,0,Puerto Rico,0,U.S. Island Area,0,Foreign Country,0
45,0,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,169,271,721,785,1646,898,161,146,5124,...,965,421,6596,1476,0,155,11,19,6585,1478
48,Nevada,280,330,597,525,10142,4338,310,358,40114,...,933,702,13006,2756,153,258,127,149,12726,2687
49,New Hampshire,193,237,0,184,246,210,22,37,547,...,162,218,5313,1388,0,184,0,184,5313,1388
50,New Jersey,189,209,1198,790,3784,2287,57,97,5986,...,15,29,60717,5750,4312,1535,73,103,56332,5497
51,New Mexico,410,494,416,446,7444,3409,682,607,7066,...,283,313,11532,2620,99,158,0,198,11433,2625
53,New York,1812,1002,6124,2270,2821,1100,1041,734,25761,...,688,645,155111,10586,10582,3796,254,305,144275,9818
54,North Carolina,5420,2338,3991,2185,4286,2860,327,322,15373,...,153,228,43373,5356,844,447,582,474,41947,5419
55,North Dakota,97,125,393,365,1313,613,249,293,1356,...,139,102,2908,1066,76,110,0,143,2832,1056
56,Ohio,1567,705,1637,1579,6763,3193,1952,1128,9032,...,1280,793,37091,4223,1607,1062,458,536,35026,4118
57,Oklahoma,591,368,1137,857,3770,1522,6894,2060,8233,...,1763,1572,16281,3206,105,139,47,48,16129,3205
59,Oregon,758,1071,1935,1062,7911,3054,988,1155,34214,...,914,880,23355,4384,4,8,549,523,22802,4332
60,Pennsylvania,1332,684,759,664,2278,917,582,601,10672,...,195,237,52554,5764,2723,1294,166,243,49665,5697
61,Rhode Island,0,207,0,207,214,348,0,207,1949,...,23,47,7778,1837,293,292,249,353,7236,1796
62,South Carolina,2999,1543,2421,1281,1971,1391,1333,1301,6592,...,632,647,20165,6013,2166,1534,203,195,17796,5881
63,South Dakota,0,155,554,492,1422,1445,659,778,1286,...,1310,880,3578,1550,0,155,0,155,3578,1550
65,Tennessee,9326,2717,531,465,1346,1176,7393,3038,7130,...,131,214,24963,4567,1083,1191,59,100,23821,4238
66,Texas,8747,2609,6670,2828,20073,5295,16461,3965,58992,...,2500,1485,179263,13868,5225,2173,710,778,173328,13486
67,Utah,486,558,2151,1259,6585,2560,422,455,18237,...,1058,609,14465,2475,0,192,0,192,14465,2475
68,Vermont,0,145,580,441,310,325,0,145,819,...,38,62,2868,803,19,45,0,145,2849,800
69,Virginia,4930,2057,3202,1687,4679,2151,645,606,19371,...,190,274,60051,6990,1222,779,124,201,58705,6768
71,Washington,1821,1049,5266,2233,12397,3133,756,565,38421,...,1507,870,54973,5730,1083,1061,362,321,53528,5625
72,West Virginia,221,228,598,566,50,95,225,361,1442,...,0,184,5174,1423,680,450,557,556,3937,1154
73,Wisconsin,708,761,432,323,4045,1532,335,285,6637,...,14,23,15601,2441,728,715,0,151,14873,2450
74,Wyoming,51,62,761,597,369,276,174,191,2539,...,0,0,1282,1155,0,189,0,189,1282,1155
76,Puerto Rico,35,59,378,457,229,363,0,210,207,...,0,210,4681,2095,N/A2,N/A2,0,210,4681,2095


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [21]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Different state of residence 1 year ago: Alabama (Estimate),0,93,833,691,2087,2340,101,81,13,12635,...,9326,8747,486,0,4930,1821,221,708,51,35
Different state of residence 1 year ago: Alabama (MOE),0,113,587,573,927,1681,120,135,29,3566,...,2717,2609,558,145,2057,1049,228,761,62,59
Different state of residence 1 year ago (cont.): Alaska (Estimate),1771,0,5001,560,7358,3191,180,329,135,7405,...,531,6670,2151,580,3202,5266,598,432,761,378
Different state of residence 1 year ago (cont.): Alaska (MOE),1098,0,2214,669,2501,1622,299,544,217,3412,...,465,2828,1259,441,1687,2233,566,323,597,457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),601,962,639,507,635,556,1756,971,200,5621,...,1191,2173,192,45,779,1061,450,715,189,N/A2
Abroad 1 year ago--: U.S. Island Area (Estimate),0,0,122,46,2817,57,0,0,0,2643,...,59,710,0,0,124,362,557,0,0,0
Abroad 1 year ago--: U.S. Island Area (MOE),190,149,135,81,2043,79,198,192,200,1361,...,100,778,192,145,201,321,556,151,189,210
Abroad 1 year ago--: Foreign Country (Estimate),14248,3697,42569,8635,265611,34511,18681,3697,7364,144674,...,23821,173328,14465,2849,58705,53528,3937,14873,1282,4681
Abroad 1 year ago--: Foreign Country (MOE),2893,901,6259,3062,15898,5839,3485,1338,1786,12266,...,4238,13486,2475,800,6768,5625,1154,2450,1155,2095

In [22]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [23]:

df = df.iloc[1:]

And drop the final four rows (arent states)

In [28]:
df = df.iloc[:-8]

And drop columns with 0 as title (represnt the header that was in the middle of the original excel sheet)

In [29]:

df.drop(columns=['0'], inplace=True)

df.columns

Index(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District of Columbia ', 'Florida',
       'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia',
       'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico'],
      dtype='object', name='0')

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [30]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [31]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops = df_pops[1:]

df_pops

                               0
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [32]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Different state of residence 1 year ago: Alabam...                    13
Different state of residence 1 year ago (cont.)...                   135
Different state of residence 1 year ago (cont.)...                    43
Different state of residence 1 year ago (cont.)...                    81
Different state of residence 1 year ago (cont.)...                  3797
Different state of residence 1 year ago (cont.)...                   452
Different state of residence 1 year ago (cont.)...                   981
Different state of residence 1 year ago (cont.)...                   128
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                  1254
Different state of residence 1 year ago (cont.)...                   937
Different state of residence 1 year ago (cont.)...                   372
Different state of residence 1 year ago (cont.)...                    68
Different state of residence 1 year ago (cont.)...                  1397
Different state of residence 1 year ago (cont.)...                   128
Different state of residence 1 year ago (cont.)...                   241
Different state of residence 1 year ago (cont.)...                     6
Different state of residence 1 year ago (cont.)...                   297
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                 14129
Different state of residence 1 year ago (cont.)...                  2048
Different state of residence 1 year ago (cont.)...                  1108
Different state of residence 1 year ago (cont.)...                   409
Different state of residence 1 year ago (cont.)...                    83
Different state of residence 1 year ago (cont.)...                   112
Different state of residence 1 year ago (cont.)...                    38
Different state of residence 1 year ago (cont.)...                    79
Different state of residence 1 year ago (cont.)...                   238
Different state of residence 1 year ago (cont.)...                   145
Different state of residence 1 year ago (cont.)...                  1035
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                  2313
Different state of residence 1 year ago (cont.)...                  1716
Different state of residence 1 year ago (cont.)...                   285
Different state of residence 1 year ago (cont.)...                   306
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                    51
Different state of residence 1 year ago (cont.)...                  1589
Different state of residence 1 year ago (cont.)...                    50
Different state of residence 1 year ago (cont.)...                   357
Different state of residence 1 year ago (cont.)...                   104
Different state of residence 1 year ago (cont.)...                   421
Different state of residence 1 year ago (cont.)...                  1083
Different state of residence 1 year ago (cont.)...                    75
Different state of residence 1 year ago (cont.)...                   445
Different state of residence 1 year ago (cont.)...                  7975
Different state of residence 1 year ago (cont.)...                   476
Different state of residence 1 year ago (cont.)...                   120
Different state of residence 1 year ago (cont.)...                   946
Different state of residence 1 year ago (cont.)...                     0

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [33]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

For 2021 and 2017, we needed to cut off the top columns that arent for specific states, but that's not relevent here because of different structure for 2009 and 2005

In [ ]:

# df_estimates = df_estimates[4:]
# df_moes = df_moes[4:]

In [34]:
df_moes.head()

0          District of Columbia
0
Alabama                       29
Alaska                       217
Arizona                       71
Arkansas                      93
California                  1233

In [35]:
df_estimates.head()

0          District of Columbia
0
Alabama                       13
Alaska                       135
Arizona                       43
Arkansas                      81
California                  3797

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [36]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Now I'm adding a state polulation column to my newly formatted table

In [37]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [38]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [39]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [40]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                        13      29          5024279
Alaska                        135     217           733391
Arizona                        43      71          7151502
Arkansas                       81      93          3011524
California                   3797    1233         39538223
Colorado                      452     321          5773714
Connecticut                   981     472          3605944
Delaware                      128     125           989948
District of Columbia            0       0           689545
Florida                      1254     651         21538187
Georgia                       937     572         10711908
Hawaii                        372     396          1455271
Idaho                          68     113          1839106
Illinois                     1397     814         12812508
Indiana                       128     147          6785528
Iowa                          241     284          3190369
Kansas                          6      19          2937880
Kentucky                      297     260          4505836
Louisiana                       0     200          4657757
Maine                           0     200          1362359
Maryland                    14129    2971          6177224
Massachusetts                2048     789          7029917
Michigan                     1108     554         10077331
Minnesota                     409     457          5706494
Mississippi                    83      99          2961279
Missouri                      112     184          6154913
Montana                        38      64          1084225
Nebraska                       79     110          1961504
Nevada                        238     282          3104614
New Hampshire                 145     139          1377529
New Jersey                   1035     605          9288994
New Mexico                      0     200          2117522
New York                     2313     697         20201249
North Carolina               1716     760         10439388
North Dakota                  285     360           779094
Ohio                          306     224         11799448
Oklahoma                        0     200          3959353
Oregon                         51      64          4237256
Pennsylvania                 1589     757         13002700
Rhode Island                   50      63          1097379
South Carolina                357     329          5118425
South Dakota                  104     129           886667
Tennessee                     421     358          6910840
Texas                        1083     491         29145505
Utah                           75     118          3271616
Vermont                       445     489           643077
Virginia                     7975    1285          8631393
Washington                    476     300          7705281
West Virginia                 120     138          1793716
Wisconsin                     946     668          5893718
Wyoming                         0     200           576851

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [41]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [42]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Need to manually drop DC here because its input differently than in the other years -- here, the D.C. figure for folks that lived in D.C. both this year and last year is not n/a or 0, but rather a substantial number that represents the number of folks that did NOT move since last year's census

In [43]:
df = df.drop(['District of Columbia'])

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [44]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,13,29,5024279,0.000003,0.000006
1,Alaska,135,217,733391,0.000184,0.000296
2,Arizona,43,71,7151502,0.000006,0.000010
3,Arkansas,81,93,3011524,0.000027,0.000031
4,California,3797,1233,39538223,0.000096,0.000031

Looking at states with most people coming to DC

In [45]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
19,Maryland,14129,2971,6177224,0.002287,0.000481
45,Virginia,7975,1285,8631393,0.000924,0.000149
44,Vermont,445,489,643077,0.000692,0.000760
33,North Dakota,285,360,779094,0.000366,0.000462
20,Massachusetts,2048,789,7029917,0.000291,0.000112
6,Connecticut,981,472,3605944,0.000272,0.000131
10,Hawaii,372,396,1455271,0.000256,0.000272
1,Alaska,135,217,733391,0.000184,0.000296
32,North Carolina,1716,760,10439388,0.000164,0.000073
48,Wisconsin,946,668,5893718,0.000161,0.000113

To export, want to make a slice excluding all DMV states -- Maryland, Virginia

In [46]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]

Now need to reset the index again to make numbers consecutive now that I've removed ceratin rows.

In [47]:
df = df.reset_index(drop=True)

Now add in 2008 election winners for each state

First, read in file

In [48]:
df_2008_election_winners = pd.read_csv('pres-election-results-2008.csv')

type(df_2008_election_winners)

pandas.DataFrame

Next, add winning party and percent of votes columns

In [49]:
df_2008_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

df_2008_election_winners.head()

        state  year party_detailed  percent_total_votes
0     Alabama  2008     REPUBLICAN             0.603169
1      Alaska  2008     REPUBLICAN             0.594245
2     Arizona  2008     REPUBLICAN             0.536352
3    Arkansas  2008     REPUBLICAN             0.587159
4  California  2008       DEMOCRAT             0.610126

In [50]:

df['winning_party'] = df_2008_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2008_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,13,29,5024279,0.000003,0.000006,REPUBLICAN,0.603169
1,Alaska,135,217,733391,0.000184,0.000296,REPUBLICAN,0.594245
2,Arizona,43,71,7151502,0.000006,0.000010,REPUBLICAN,0.536352
3,Arkansas,81,93,3011524,0.000027,0.000031,REPUBLICAN,0.587159
4,California,3797,1233,39538223,0.000096,0.000031,DEMOCRAT,0.610126

Check that indexes match

In [51]:
df.index

RangeIndex(start=0, stop=48, step=1)

In [52]:
df_2008_election_winners.index

RangeIndex(start=0, stop=48, step=1)

Save as csv file

In [53]:
df.to_csv('DC-migration-2011.csv')