I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2016.xls')

In [3]:
df.shape

(85, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,319361956,30974,272660098,208903,36952658,198593,7552536,73712,99892,...,3871,United States2,2196664,37386,88676,7958,16060,2338,2091928,36976

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,319361956,30974,272660098,208903,36952658,198593,7552536,73712,99892,...,3871,United States2,2196664,37386,88676,7958,16060,2338,2091928,36976
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4810126,3913,4141850,18249,529994,17409,122220,9811,NaN,...,691,Alabama,16062,2720,335,214,608,479,15119,2741
11,Alaska,731760,1282,593897,7921,100004,6403,31300,3641,423,...,242,Alaska,6559,1959,848,1059,350,448,5361,1639
12,Arizona,6851836,4173,5586753,30225,938077,26500,273257,14805,894,...,683,Arizona,53749,6106,1462,917,151,253,52136,6088
13,Arkansas,2949650,3135,2484705,17957,384811,15832,71083,6657,2057,...,290,Arkansas,9051,1843,857,794,0,197,8194,1794
14,California,38783436,10247,33594813,62303,4337251,59356,514758,19678,3045,...,1596,California,336614,13654,1102,682,3315,1372,332197,13552
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5476928,3255,4466067,27786,754712,24804,223260,12315,2328,...,1297,Colorado,32889,4669,751,643,614,891,31524,4521
17,Connecticut,3541758,2975,3116440,16535,323316,14648,75586,6930,1102,...,200,Connecticut,26416,3933,3066,1260,602,845,22748,3861
18,Delaware,942073,1325,817779,9121,85147,8425,33400,3275,148,...,193,Delaware,5747,1837,666,944,0,193,5081,1628
19,District of Columbia,672022,1765,538547,7335,64166,6120,58154,4335,140,...,203,District of Columbia,11155,1804,351,287,136,171,10668,1773
20,Florida,20401575,7828,17176492,49542,2387227,43437,605018,21606,11353,...,351,Florida,232838,15743,24132,4560,1117,686,207589,13902
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,10179860,6234,8514847,32855,1290632,29551,305040,15456,18276,...,37,Georgia,69341,8196,2626,1216,445,286,66270,7937
23,Hawaii,1410258,1894,1217704,11310,117894,10811,57229,6791,1182,...,185,Hawaii,17431,3746,0,185,1076,597,16355,3651

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,319361956,30974,272660098,208903,36952658,198593,7552536,73712,99892,...,3871,United States2,2196664,37386,88676,7958,16060,2338,2091928,36976
10,Alabama,4810126,3913,4141850,18249,529994,17409,122220,9811,NaN,...,691,Alabama,16062,2720,335,214,608,479,15119,2741
11,Alaska,731760,1282,593897,7921,100004,6403,31300,3641,423,...,242,Alaska,6559,1959,848,1059,350,448,5361,1639
12,Arizona,6851836,4173,5586753,30225,938077,26500,273257,14805,894,...,683,Arizona,53749,6106,1462,917,151,253,52136,6088
13,Arkansas,2949650,3135,2484705,17957,384811,15832,71083,6657,2057,...,290,Arkansas,9051,1843,857,794,0,197,8194,1794
14,California,38783436,10247,33594813,62303,4337251,59356,514758,19678,3045,...,1596,California,336614,13654,1102,682,3315,1372,332197,13552
16,Colorado,5476928,3255,4466067,27786,754712,24804,223260,12315,2328,...,1297,Colorado,32889,4669,751,643,614,891,31524,4521
17,Connecticut,3541758,2975,3116440,16535,323316,14648,75586,6930,1102,...,200,Connecticut,26416,3933,3066,1260,602,845,22748,3861
18,Delaware,942073,1325,817779,9121,85147,8425,33400,3275,148,...,193,Delaware,5747,1837,666,944,0,193,5081,1628
19,District of Columbia,672022,1765,538547,7335,64166,6120,58154,4335,140,...,203,District of Columbia,11155,1804,351,287,136,171,10668,1773
20,Florida,20401575,7828,17176492,49542,2387227,43437,605018,21606,11353,...,351,Florida,232838,15743,24132,4560,1117,686,207589,13902
22,Georgia,10179860,6234,8514847,32855,1290632,29551,305040,15456,18276,...,37,Georgia,69341,8196,2626,1216,445,286,66270,7937
23,Hawaii,1410258,1894,1217704,11310,117894,10811,57229,6791,1182,...,185,Hawaii,17431,3746,0,185,1076,597,16355,3651
24,Idaho,1663756,2007,1369449,15368,214222,12941,71556,7065,0,...,1721,Idaho,8529,2249,0,198,74,79,8455,2250
25,Illinois,12654142,5822,10996695,35598,1387848,31048,203713,9123,2022,...,303,Illinois,65886,5219,1793,821,0,185,64093,4955
26,Indiana,6554084,4241,5580090,26152,801425,26459,145782,9568,1133,...,192,Indiana,26787,3487,34,57,0,192,26753,3482
28,Iowa,3097283,2760,2622577,14595,383520,13922,78263,5607,395,...,185,Iowa,12923,1927,12,24,84,118,12827,1904

Rename columns to be clearer numbers

In [9]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '120', '121', '122', '123', '124', '125', '126', '127', '128', '129'],
      dtype='str', length=130)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [10]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

df

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,319361956,30974,272660098,208903,36952658,198593,7552536,73712,99892,...,27184,3871,2196664,37386,88676,7958,16060,2338,2091928,36976
10,Alabama,4810126,3913,4141850,18249,529994,17409,122220,9811,NaN,...,539,691,16062,2720,335,214,608,479,15119,2741
11,Alaska,731760,1282,593897,7921,100004,6403,31300,3641,423,...,291,242,6559,1959,848,1059,350,448,5361,1639
12,Arizona,6851836,4173,5586753,30225,938077,26500,273257,14805,894,...,925,683,53749,6106,1462,917,151,253,52136,6088
13,Arkansas,2949650,3135,2484705,17957,384811,15832,71083,6657,2057,...,178,290,9051,1843,857,794,0,197,8194,1794
14,California,38783436,10247,33594813,62303,4337251,59356,514758,19678,3045,...,2674,1596,336614,13654,1102,682,3315,1372,332197,13552
16,Colorado,5476928,3255,4466067,27786,754712,24804,223260,12315,2328,...,3657,1297,32889,4669,751,643,614,891,31524,4521
17,Connecticut,3541758,2975,3116440,16535,323316,14648,75586,6930,1102,...,0,200,26416,3933,3066,1260,602,845,22748,3861
18,Delaware,942073,1325,817779,9121,85147,8425,33400,3275,148,...,0,193,5747,1837,666,944,0,193,5081,1628
19,District of Columbia,672022,1765,538547,7335,64166,6120,58154,4335,140,...,0,203,11155,1804,351,287,136,171,10668,1773
20,Florida,20401575,7828,17176492,49542,2387227,43437,605018,21606,11353,...,454,351,232838,15743,24132,4560,1117,686,207589,13902
22,Georgia,10179860,6234,8514847,32855,1290632,29551,305040,15456,18276,...,22,37,69341,8196,2626,1216,445,286,66270,7937
23,Hawaii,1410258,1894,1217704,11310,117894,10811,57229,6791,1182,...,0,185,17431,3746,0,185,1076,597,16355,3651
24,Idaho,1663756,2007,1369449,15368,214222,12941,71556,7065,0,...,3030,1721,8529,2249,0,198,74,79,8455,2250
25,Illinois,12654142,5822,10996695,35598,1387848,31048,203713,9123,2022,...,271,303,65886,5219,1793,821,0,185,64093,4955
26,Indiana,6554084,4241,5580090,26152,801425,26459,145782,9568,1133,...,0,192,26787,3487,34,57,0,192,26753,3482
28,Iowa,3097283,2760,2622577,14595,383520,13922,78263,5607,395,...,171,185,12923,1927,12,24,84,118,12827,1904
29,Kansas,2870529,2533,2394351,14952,369971,12594,88830,6459,879,...,79,93,17377,3891,308,313,190,189,16879,3881
30,Kentucky,4385213,2955,3698797,19715,553718,18441,113238,7668,2272,...,0,190,19460,3797,2194,1437,0,190,17266,3285
31,Louisiana,4622042,3291,3994321,24494,526380,22229,85371,7322,5658,...,162,168,15970,2946,186,165,299,288,15485,2971
32,Maine,1319292,1668,1146220,8252,129892,6745,38590,4947,471,...,0,172,4590,1692,0,172,0,172,4590,1692
34,Maryland,5949566,4278,5140378,24631,606423,22556,158647,9687,1241,...,0,198,44118,5584,1214,773,487,387,42417,5555
35,Massachusetts,6745441,3674,5866016,20917,657022,16439,149408,9363,681,...,166,255,72995,6553,4448,1716,147,143,68400,6110
36,Michigan,9813772,4749,8362412,27022,1240633,24949,155874,9738,2287,...,1380,716,54853,5486,1030,828,290,211,53533,5438
37,Minnesota,5455904,2872,4669227,18130,645164,16382,111307,7183,115,...,846,697,30206,4357,60,76,289,444,29857,4349
38,Mississippi,2951081,3274,2556013,17776,324577,14529,64639,6777,5125,...,0,213,5852,1388,910,1170,0,213,4942,1201
40,Missouri,6022165,4040,5078669,22798,758791,18896,162809,8925,2283,...,540,449,21896,3392,684,515,376,320,20836,3307
41,Montana,1032794,1223,863174,7519,128300,7323,37775,4095,296,...,1434,692,3545,882,0,168,54,95,3491,870
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
45,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1882987,1995,1573126,12455,248118,11217,51448,5875,227,...,1281,872,10295,2972,0,159,29,62,10266,2971
48,Nevada,2907243,2819,2400809,18901,374058,17993,117899,7370,394,...,1686,1713,14477,2780,399,473,362,327,13716,2679
49,New Hampshire,1322101,1298,1122068,9993,140603,8528,52457,5343,174,...,0,187,6973,1948,202,377,0,187,6771,1918
50,New Jersey,8852286,5371,7934689,25558,703637,23786,144359,9330,48,...,0,200,69601,6999,3694,2207,208,242,65699,6722
51,New Mexico,2057857,2689,1768040,12935,214411,11952,64802,5735,732,...,198,185,10604,2846,92,114,53,99,10459,2856
53,New York,19526443,6611,17465164,35945,1634487,32252,260723,11746,402,...,83,103,166069,11119,7385,2081,467,501,158217,10372
54,North Carolina,10032407,5350,8460264,33199,1190972,27274,330896,14462,3491,...,145,175,50275,5579,1631,942,47,102,48597,5493
55,North Dakota,746271,1202,620891,7724,91010,6382,29655,3868,193,...,342,234,4715,1828,1049,1257,0,155,3666,1401
56,Ohio,11481752,4551,9755589,33208,1482286,29906,195396,9185,3101,...,179,228,48481,5348,3059,1218,0,189,45422,5307
57,Oklahoma,3873232,2534,3225478,15384,530770,13855,102000,7094,176,...,299,306,14984,2936,272,182,484,543,14228,2840
59,Oregon,4052221,3173,3307805,19198,577950,19092,139334,9092,167,...,563,341,27132,4466,0,201,95,155,27037,4445
60,Pennsylvania,12645493,5619,11016361,36704,1308271,34321,252060,10750,1978,...,188,211,68801,6719,7005,2340,332,323,61464,5997
61,Rhode Island,1045691,1810,898574,10119,106725,9017,32800,4037,53,...,0,208,7592,2436,40,68,0,208,7552,2437
62,South Carolina,4903788,3376,4176954,27733,542415,22405,165230,10983,2823,...,508,704,19189,3143,595,720,254,284,18340,3004
63,South Dakota,853832,1413,720262,7279,97747,6762,31789,3927,0,...,2047,1065,4034,1732,0,157,0,157,4034,1732
65,Tennessee,6580953,4457,5644022,24352,742615,23525,170867,10319,7683,...,25,48,23449,3653,667,719,361,406,22421,3508
66,Texas,27472626,10409,23105984,50841,3599897,48634,531996,20183,6915,...,732,486,234749,13127,9246,2823,590,649,224913,12929
67,Utah,3002244,3318,2474308,19586,396018,17139,107083,9315,125,...,755,590,24835,4628,59,93,143,143,24633,4637
68,Vermont,619387,803,535268,5519,60744,4942,21262,2769,0,...,0,151,2113,643,0,151,146,148,1967,598
69,Virginia,8312297,5430,7008805,27572,961003,22934,264164,11923,2424,...,48,62,78325,6303,2001,1202,559,555,75765,6271
71,Washington,7202119,4069,5924723,30369,958326,27224,257728,13383,1465,...,866,517,61342,6594,480,782,893,514,59969,6397
72,West Virginia,1810709,2337,1582818,10978,176953,9202,47196,5756,284,...,0,193,3742,1099,112,120,0,193,3630,1109
73,Wisconsin,5712104,3128,4876817,20516,696530,19673,118814,6959,966,...,420,259,19943,2704,1619,1003,160,203,18164,2517
74,Wyoming,577567,1366,472996,8803,75995,6553,26471,4106,265,...,NaN,NaN,2105,1017,0,197,173,181,1932,997
76,Puerto Rico,3384760,2761,3143116,12230,216969,11523,21196,3444,49,...,0,222,3479,1053,NaN,NaN,0,222,3479,1053

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [11]:
df.iloc[3:] = df.iloc[3:].fillna('0')

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#first, dealing with columns B-G/1-6)

column_1_name = f'{df.iloc[0, 1]} ({df.iloc[2, 1]})'
column_2_name = f'{df.iloc[0, 1]} ({df.iloc[2, 2]})'

column_3_name = f'{df.iloc[0, 3]} ({df.iloc[2, 3]})'
column_4_name = f'{df.iloc[0, 3]} ({df.iloc[2, 4]})'

column_5_name = f'{df.iloc[0, 5]} ({df.iloc[2, 5]})'
column_6_name = f'{df.iloc[0, 5]} ({df.iloc[2, 6]})'

df_clean = df.rename(columns ={
    '1': column_1_name,
    '2': column_2_name,
    '3': column_3_name,
    '4': column_4_name,
    '5': column_5_name,
    '6': column_6_name})

#next, for the rest of the columns:
#first, fill in blanks

df_filledin = df_clean.ffill(axis=1)

#then pull the info I need to name each column

for i in range(7, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [13]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Population 1 year and over (Estimate),Population 1 year and over (MOE),Same house 1 year ago (Estimate),Same house 1 year ago (MOE),Same state of residence 1 year ago (Estimate),Same state of residence 1 year ago (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (continued): Wyoming (Estimate),Different state of residence 1 year ago (continued): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
53,New York,19526443,6611,17465164,35945,1634487,32252,260723,11746,402,...,83,103,166069,11119,7385,2081,467,501,158217,10372
54,North Carolina,10032407,5350,8460264,33199,1190972,27274,330896,14462,3491,...,145,175,50275,5579,1631,942,47,102,48597,5493
55,North Dakota,746271,1202,620891,7724,91010,6382,29655,3868,193,...,342,234,4715,1828,1049,1257,0,155,3666,1401
56,Ohio,11481752,4551,9755589,33208,1482286,29906,195396,9185,3101,...,179,228,48481,5348,3059,1218,0,189,45422,5307
57,Oklahoma,3873232,2534,3225478,15384,530770,13855,102000,7094,176,...,299,306,14984,2936,272,182,484,543,14228,2840
59,Oregon,4052221,3173,3307805,19198,577950,19092,139334,9092,167,...,563,341,27132,4466,0,201,95,155,27037,4445
60,Pennsylvania,12645493,5619,11016361,36704,1308271,34321,252060,10750,1978,...,188,211,68801,6719,7005,2340,332,323,61464,5997
61,Rhode Island,1045691,1810,898574,10119,106725,9017,32800,4037,53,...,0,208,7592,2436,40,68,0,208,7552,2437
62,South Carolina,4903788,3376,4176954,27733,542415,22405,165230,10983,2823,...,508,704,19189,3143,595,720,254,284,18340,3004
63,South Dakota,853832,1413,720262,7279,97747,6762,31789,3927,0,...,2047,1065,4034,1732,0,157,0,157,4034,1732
65,Tennessee,6580953,4457,5644022,24352,742615,23525,170867,10319,7683,...,25,48,23449,3653,667,719,361,406,22421,3508
66,Texas,27472626,10409,23105984,50841,3599897,48634,531996,20183,6915,...,732,486,234749,13127,9246,2823,590,649,224913,12929
67,Utah,3002244,3318,2474308,19586,396018,17139,107083,9315,125,...,755,590,24835,4628,59,93,143,143,24633,4637
68,Vermont,619387,803,535268,5519,60744,4942,21262,2769,0,...,0,151,2113,643,0,151,146,148,1967,598
69,Virginia,8312297,5430,7008805,27572,961003,22934,264164,11923,2424,...,48,62,78325,6303,2001,1202,559,555,75765,6271
71,Washington,7202119,4069,5924723,30369,958326,27224,257728,13383,1465,...,866,517,61342,6594,480,782,893,514,59969,6397
72,West Virginia,1810709,2337,1582818,10978,176953,9202,47196,5756,284,...,0,193,3742,1099,112,120,0,193,3630,1109
73,Wisconsin,5712104,3128,4876817,20516,696530,19673,118814,6959,966,...,420,259,19943,2704,1619,1003,160,203,18164,2517
74,Wyoming,577567,1366,472996,8803,75995,6553,26471,4106,265,...,0,0,2105,1017,0,197,173,181,1932,997
76,Puerto Rico,3384760,2761,3143116,12230,216969,11523,21196,3444,49,...,0,222,3479,1053,0,0,0,222,3479,1053


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [14]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),319361956,4810126,731760,6851836,2949650,38783436,5476928,3541758,942073,672022,...,6580953,27472626,3002244,619387,8312297,7202119,1810709,5712104,577567,3384760
Population 1 year and over (MOE),30974,3913,1282,4173,3135,10247,3255,2975,1325,1765,...,4457,10409,3318,803,5430,4069,2337,3128,1366,2761
Same house 1 year ago (Estimate),272660098,4141850,593897,5586753,2484705,33594813,4466067,3116440,817779,538547,...,5644022,23105984,2474308,535268,7008805,5924723,1582818,4876817,472996,3143116
Same house 1 year ago (MOE),208903,18249,7921,30225,17957,62303,27786,16535,9121,7335,...,24352,50841,19586,5519,27572,30369,10978,20516,8803,12230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),7958,214,1059,917,794,682,643,1260,944,287,...,719,2823,93,151,1202,782,120,1003,197,0
Abroad 1 year ago--: U.S. Island Area (Estimate),16060,608,350,151,0,3315,614,602,0,136,...,361,590,143,146,559,893,0,160,173,0
Abroad 1 year ago--: U.S. Island Area (MOE),2338,479,448,253,197,1372,891,845,193,171,...,406,649,143,148,555,514,193,203,181,222
Abroad 1 year ago--: Foreign Country (Estimate),2091928,15119,5361,52136,8194,332197,31524,22748,5081,10668,...,22421,224913,24633,1967,75765,59969,3630,18164,1932,3479
Abroad 1 year ago--: Foreign Country (MOE),36976,2741,1639,6088,1794,13552,4521,3861,1628,1773,...,3508,12929,4637,598,6271,6397,1109,2517,997,1053

In [15]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [16]:

df = df.iloc[1:]

df

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),319361956,4810126,731760,6851836,2949650,38783436,5476928,3541758,942073,672022,...,6580953,27472626,3002244,619387,8312297,7202119,1810709,5712104,577567,3384760
Population 1 year and over (MOE),30974,3913,1282,4173,3135,10247,3255,2975,1325,1765,...,4457,10409,3318,803,5430,4069,2337,3128,1366,2761
Same house 1 year ago (Estimate),272660098,4141850,593897,5586753,2484705,33594813,4466067,3116440,817779,538547,...,5644022,23105984,2474308,535268,7008805,5924723,1582818,4876817,472996,3143116
Same house 1 year ago (MOE),208903,18249,7921,30225,17957,62303,27786,16535,9121,7335,...,24352,50841,19586,5519,27572,30369,10978,20516,8803,12230
Same state of residence 1 year ago (Estimate),36952658,529994,100004,938077,384811,4337251,754712,323316,85147,64166,...,742615,3599897,396018,60744,961003,958326,176953,696530,75995,216969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),7958,214,1059,917,794,682,643,1260,944,287,...,719,2823,93,151,1202,782,120,1003,197,0
Abroad 1 year ago--: U.S. Island Area (Estimate),16060,608,350,151,0,3315,614,602,0,136,...,361,590,143,146,559,893,0,160,173,0
Abroad 1 year ago--: U.S. Island Area (MOE),2338,479,448,253,197,1372,891,845,193,171,...,406,649,143,148,555,514,193,203,181,222
Abroad 1 year ago--: Foreign Country (Estimate),2091928,15119,5361,52136,8194,332197,31524,22748,5081,10668,...,22421,224913,24633,1967,75765,59969,3630,18164,1932,3479
Abroad 1 year ago--: Foreign Country (MOE),36976,2741,1639,6088,1794,13552,4521,3861,1628,1773,...,3508,12929,4637,598,6271,6397,1109,2517,997,1053

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [17]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [18]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [19]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Population 1 year and over (Estimate)                             672022
Same house 1 year ago (Estimate)                                  538547
Same state of residence 1 year ago (Estimate)                      64166
Different state of residence 1 year ago: Total ...                 58154
Different state of residence 1 year ago: Alabam...                   140
Different state of residence 1 year ago (contin...                    77
Different state of residence 1 year ago (contin...                   744
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  3908
Different state of residence 1 year ago (contin...                   531
Different state of residence 1 year ago (contin...                  1225
Different state of residence 1 year ago (contin...                   278
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  2717
Different state of residence 1 year ago (contin...                  1105
Different state of residence 1 year ago (contin...                   103
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  2418
Different state of residence 1 year ago (contin...                   957
Different state of residence 1 year ago (contin...                   218
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   233
Different state of residence 1 year ago (contin...                   197
Different state of residence 1 year ago (contin...                   118
Different state of residence 1 year ago (contin...                 12778
Different state of residence 1 year ago (contin...                  1974
Different state of residence 1 year ago (contin...                   922
Different state of residence 1 year ago (contin...                   542
Different state of residence 1 year ago (contin...                   224
Different state of residence 1 year ago (contin...                   566
Different state of residence 1 year ago (contin...                    17
Different state of residence 1 year ago (contin...                   190
Different state of residence 1 year ago (contin...                   356
Different state of residence 1 year ago (contin...                   168
Different state of residence 1 year ago (contin...                  1494
Different state of residence 1 year ago (contin...                     1
Different state of residence 1 year ago (contin...                  4762
Different state of residence 1 year ago (contin...                  1367
Different state of residence 1 year ago (contin...                    83
Different state of residence 1 year ago (contin...                   659
Different state of residence 1 year ago (contin...                   122
Different state of residence 1 year ago (contin...                   125
Different state of residence 1 year ago (contin...                  2468
Different state of residence 1 year ago (contin...                   268
Different state of residence 1 year ago (contin...                   382
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   452
Different state of residence 1 year ago (contin...                  2213
Different state of residence 1 year ago (contin...                   249
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  9847
Different state of residence 1 year ago (contin...                   418
Different state of residence 1 year ago (contin...                   296
Different state of residence 1 year ago (contin...                   242
Different state of residence 1 year ago (contin...                     0
Abroad 1 year ago--: Total (Estimate)                              11155
Abroad 1 year ago--: Puerto Rico (Estimate)                          351
Abroad 1 year ago--: U.S. Island Area (Estimate)                     136
Abroad 1 year ago--: Foreign Country (Estimate)                    10668

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [20]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

Cut off the top columns that arent for specific states

In [21]:

df_estimates = df_estimates[4:]
df_moes = df_moes[4:]

In [22]:
df_moes.head()

0          District of Columbia
0
Alabama                      161
Alaska                       130
Arizona                      505
Arkansas                     203
California                   974

In [23]:
df_estimates.head()

0          District of Columbia
0
Alabama                      140
Alaska                        77
Arizona                      744
Arkansas                       0
California                  3908

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [24]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Also need to cut out one "total" column that is the total amount of "Abroad One Year Ago" incl PR, US Island Area, and Foreign Country

In [25]:
df = df.drop('Total')

df

0                    District of Columbia  MOE +/-
0
Alabama                                140     161
Alaska                                  77     130
Arizona                                744     505
Arkansas                                 0     203
California                            3908     974
Colorado                               531     459
Connecticut                           1225     594
Delaware                               278     287
District of Columbia                     0       0
Florida                               2717    1021
Georgia                               1105     607
Hawaii                                 103     122
Idaho                                    0     203
Illinois                              2418     990
Indiana                                957     826
Iowa                                   218     208
Kansas                                   0     203
Kentucky                               233     280
Louisiana                              197     163
Maine                                  118     144
Maryland                             12778    2313
Massachusetts                         1974     731
Michigan                               922     395
Minnesota                              542     341
Mississippi                            224     218
Missouri                               566     456
Montana                                 17      30
Nebraska                               190     266
Nevada                                 356     402
New Hampshire                          168     268
New Jersey                            1494     756
New Mexico                               1       3
New York                              4762    1210
North Carolina                        1367     621
North Dakota                            83      84
Ohio                                   659     362
Oklahoma                               122     205
Oregon                                 125     140
Pennsylvania                          2468     848
Rhode Island                           268     224
South Carolina                         382     291
South Dakota                             0     203
Tennessee                              452     330
Texas                                 2213     909
Utah                                   249     292
Vermont                                  0     203
Virginia                              9847    2343
Washington                             418     337
West Virginia                          296     337
Wisconsin                              242     222
Wyoming                                  0     203
Puerto Rico                            351     287
U.S. Island Area                       136     171
Foreign Country                      10668    1773

also need to drop out the last two columns US Island Area and Foreign Country because those dont exist in the pop df and I don't need for this analysis

In [26]:
df = df.drop('U.S. Island Area')
df = df.drop('Foreign Country')

also need to drop the top row of pops df to get the dataframes to have the same row indices

In [27]:
df_pops = df_pops.drop('Label (Grouping)')

Now I'm adding a state polulation column to my newly formatted table

In [28]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [29]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

df.head()

0          pop_migrated MOE +/- state_population
0
Alabama             140     161        5,024,279
Alaska               77     130          733,391
Arizona             744     505        7,151,502
Arkansas              0     203        3,011,524
California         3908     974       39,538,223

And strip commas in state_population column

In [30]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [31]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       140     161          5024279
Alaska                         77     130           733391
Arizona                       744     505          7151502
Arkansas                        0     203          3011524
California                   3908     974         39538223
Colorado                      531     459          5773714
Connecticut                  1225     594          3605944
Delaware                      278     287           989948
District of Columbia            0       0           689545
Florida                      2717    1021         21538187
Georgia                      1105     607         10711908
Hawaii                        103     122          1455271
Idaho                           0     203          1839106
Illinois                     2418     990         12812508
Indiana                       957     826          6785528
Iowa                          218     208          3190369
Kansas                          0     203          2937880
Kentucky                      233     280          4505836
Louisiana                     197     163          4657757
Maine                         118     144          1362359
Maryland                    12778    2313          6177224
Massachusetts                1974     731          7029917
Michigan                      922     395         10077331
Minnesota                     542     341          5706494
Mississippi                   224     218          2961279
Missouri                      566     456          6154913
Montana                        17      30          1084225
Nebraska                      190     266          1961504
Nevada                        356     402          3104614
New Hampshire                 168     268          1377529
New Jersey                   1494     756          9288994
New Mexico                      1       3          2117522
New York                     4762    1210         20201249
North Carolina               1367     621         10439388
North Dakota                   83      84           779094
Ohio                          659     362         11799448
Oklahoma                      122     205          3959353
Oregon                        125     140          4237256
Pennsylvania                 2468     848         13002700
Rhode Island                  268     224          1097379
South Carolina                382     291          5118425
South Dakota                    0     203           886667
Tennessee                     452     330          6910840
Texas                        2213     909         29145505
Utah                          249     292          3271616
Vermont                         0     203           643077
Virginia                     9847    2343          8631393
Washington                    418     337          7705281
West Virginia                 296     337          1793716
Wisconsin                     242     222          5893718
Wyoming                         0     203           576851
Puerto Rico                   351     287          3285874

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [32]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [33]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [34]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,140,161,5024279,0.000028,0.000032
1,Alaska,77,130,733391,0.000105,0.000177
2,Arizona,744,505,7151502,0.000104,0.000071
3,Arkansas,0,203,3011524,0.000000,0.000067
4,California,3908,974,39538223,0.000099,0.000025

Looking at states with most people coming to DC

In [35]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
20,Maryland,12778,2313,6177224,0.002069,0.000374
46,Virginia,9847,2343,8631393,0.001141,0.000271
6,Connecticut,1225,594,3605944,0.000340,0.000165
7,Delaware,278,287,989948,0.000281,0.000290
21,Massachusetts,1974,731,7029917,0.000281,0.000104
39,Rhode Island,268,224,1097379,0.000244,0.000204
32,New York,4762,1210,20201249,0.000236,0.000060
38,Pennsylvania,2468,848,13002700,0.000190,0.000065
13,Illinois,2418,990,12812508,0.000189,0.000077
48,West Virginia,296,337,1793716,0.000165,0.000188

To export, want to make a slice excluding all DMV states -- Maryland, Virginia, DC

Also need to exclude PR because I'm just doing continental US

In [36]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]
df = df[df["state"] != "District of Columbia"]

Now need to reset the indexes again to make numbers consecutive now that I've removed ceratin rows.

In [37]:
df = df.reset_index(drop=True)

Now add in 2012 election winners for each state

First, read in file

In [38]:
df_2012_election_winners = pd.read_csv('pres-election-results-2012.csv')

type(df_2012_election_winners)

pandas.DataFrame

Next, add columns to dataframe w election results -- one for winning party and one for percent of votes that that party won by

In [39]:
df['winning_party'] = df_2012_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2012_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,140,161,5024279,0.000028,0.000032,REPUBLICAN,0.605458
1,Alaska,77,130,733391,0.000105,0.000177,REPUBLICAN,0.548016
2,Arizona,744,505,7151502,0.000104,0.000071,REPUBLICAN,0.536545
3,Arkansas,0,203,3011524,0.000000,0.000067,REPUBLICAN,0.605669
4,California,3908,974,39538223,0.000099,0.000025,DEMOCRAT,0.602390

Save as csv file

In [40]:
df.to_csv('DC-migration-2016.csv')