I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [53]:
import pandas as pd
import numpy as np

Read in the file

In [54]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2012.xls')

In [55]:
df.shape

(84, 130)

In [56]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [57]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same residence 1 year ago,NaN,"Different residence, same state 1 year ago",NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,310212755,25814,263612596,229733,37696597,211307,7070345,58599,109210,...,5150,United States1,1833217,32633,74500,8156,15876,3083,1742841,31206

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [58]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [59]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same residence 1 year ago,NaN,"Different residence, same state 1 year ago",NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States1,310212755,25814,263612596,229733,37696597,211307,7070345,58599,109210,...,5150,United States1,1833217,32633,74500,8156,15876,3083,1742841,31206
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4764428,3589,4054260,21464,590326,19701,104600,8482,NaN,...,107,Alabama,15242,2994,619,551,0,184,14623,2857
11,Alaska,721186,1290,592551,8741,90613,7239,33415,4385,1097,...,217,Alaska,4607,1235,25,43,272,312,4310,1199
12,Arizona,6468907,3874,5242674,32185,953789,28803,232457,14183,1331,...,1401,Arizona,39987,4295,1791,1662,447,401,37749,4037
13,Arkansas,2912680,2753,2453347,16841,373046,14543,76948,7223,374,...,2098,Arkansas,9339,1679,0,184,4,7,9335,1680
14,California,37572738,10274,31777868,67939,5046618,65422,493641,19652,2509,...,1117,California,254611,13204,2323,1076,1483,859,250805,13066
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5123944,2939,4131357,21752,751921,19587,205060,11855,3108,...,2808,Colorado,35606,4299,1144,903,387,327,34075,4250
17,Connecticut,3555319,2447,3114940,16188,334918,14546,80311,6574,46,...,120,Connecticut,25150,4381,3228,1540,213,179,21709,3926
18,Delaware,906576,1624,782216,9177,86003,7626,34757,4691,119,...,182,Delaware,3600,1007,56,90,0,182,3544,991
19,District of Columbia,624847,948,500267,6225,61992,5668,53830,5001,79,...,303,District of Columbia,8758,1942,0,197,0,197,8758,1942
20,Florida,19114620,6877,16032617,49245,2380288,44658,537148,19784,18599,...,567,Florida,164567,10910,21638,4641,2328,1213,140601,9386
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,9796547,5863,8231384,34188,1236302,31155,277466,14075,13864,...,154,Georgia,51395,6804,1730,1190,853,507,48812,6838
23,Hawaii,1374852,1662,1164145,10466,134827,9196,55145,5749,608,...,66,Hawaii,20735,2663,336,436,631,383,19768,2685

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [60]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same residence 1 year ago,NaN,"Different residence, same state 1 year ago",NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,310212755,25814,263612596,229733,37696597,211307,7070345,58599,109210,...,5150,United States1,1833217,32633,74500,8156,15876,3083,1742841,31206
10,Alabama,4764428,3589,4054260,21464,590326,19701,104600,8482,NaN,...,107,Alabama,15242,2994,619,551,0,184,14623,2857
11,Alaska,721186,1290,592551,8741,90613,7239,33415,4385,1097,...,217,Alaska,4607,1235,25,43,272,312,4310,1199
12,Arizona,6468907,3874,5242674,32185,953789,28803,232457,14183,1331,...,1401,Arizona,39987,4295,1791,1662,447,401,37749,4037
13,Arkansas,2912680,2753,2453347,16841,373046,14543,76948,7223,374,...,2098,Arkansas,9339,1679,0,184,4,7,9335,1680
14,California,37572738,10274,31777868,67939,5046618,65422,493641,19652,2509,...,1117,California,254611,13204,2323,1076,1483,859,250805,13066
16,Colorado,5123944,2939,4131357,21752,751921,19587,205060,11855,3108,...,2808,Colorado,35606,4299,1144,903,387,327,34075,4250
17,Connecticut,3555319,2447,3114940,16188,334918,14546,80311,6574,46,...,120,Connecticut,25150,4381,3228,1540,213,179,21709,3926
18,Delaware,906576,1624,782216,9177,86003,7626,34757,4691,119,...,182,Delaware,3600,1007,56,90,0,182,3544,991
19,District of Columbia,624847,948,500267,6225,61992,5668,53830,5001,79,...,303,District of Columbia,8758,1942,0,197,0,197,8758,1942
20,Florida,19114620,6877,16032617,49245,2380288,44658,537148,19784,18599,...,567,Florida,164567,10910,21638,4641,2328,1213,140601,9386
22,Georgia,9796547,5863,8231384,34188,1236302,31155,277466,14075,13864,...,154,Georgia,51395,6804,1730,1190,853,507,48812,6838
23,Hawaii,1374852,1662,1164145,10466,134827,9196,55145,5749,608,...,66,Hawaii,20735,2663,336,436,631,383,19768,2685
24,Idaho,1573036,2184,1296975,12998,210151,11483,59283,6040,575,...,406,Idaho,6627,1610,136,228,303,317,6188,1617
25,Illinois,12725119,5939,11009321,31714,1441191,27618,208755,10844,883,...,309,Illinois,65852,6243,2049,1480,149,177,63654,6337
26,Indiana,6457067,4184,5493090,26865,805228,22224,134137,9664,1625,...,2023,Indiana,24612,3645,136,194,0,184,24476,3650
28,Iowa,3035469,2721,2585979,14093,362938,11238,75760,5982,503,...,316,Iowa,10792,1952,786,1190,0,151,10006,1402

Rename columns to be clearer, including manually renaming certain columns and stripping 'Unnamed: ' from the rest

In [61]:
print(df.columns.tolist())

['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129']

In [62]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns, just trimming:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)


print(df.columns.tolist())

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129']

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [63]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [64]:
df.iloc[3:] = df.iloc[3:].fillna('0')

In [65]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,NaN,Same residence 1 year ago,NaN,"Different residence, same state 1 year ago",NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,310212755,25814,263612596,229733,37696597,211307,7070345,58599,109210,...,32228,5150,1833217,32633,74500,8156,15876,3083,1742841,31206
10,Alabama,4764428,3589,4054260,21464,590326,19701,104600,8482,0,...,88,107,15242,2994,619,551,0,184,14623,2857

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [66]:
#For the rest of the columns:
#first, fill in blanks

df_filledin = df.ffill(axis=1)

df_filledin.head()

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,Population 1 year and over,Same residence 1 year ago,Same residence 1 year ago,"Different residence, same state 1 year ago","Different residence, same state 1 year ago",Different state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,...,Different state of residence 1 year ago (cont.),Different state of residence 1 year ago (cont.),Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,Total,Alabama,...,Wyoming,Wyoming,Total,Total,Puerto Rico,Puerto Rico,U.S. Island Area,U.S. Island Area,Foreign Country,Foreign Country
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,310212755,25814,263612596,229733,37696597,211307,7070345,58599,109210,...,32228,5150,1833217,32633,74500,8156,15876,3083,1742841,31206
10,Alabama,4764428,3589,4054260,21464,590326,19701,104600,8482,0,...,88,107,15242,2994,619,551,0,184,14623,2857

In [67]:
#then pull the info I need to name each column

for i in range(1, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

In [68]:
df_filledin.head()

,0,Population 1 year and over: nan (Estimate),Population 1 year and over: nan (MOE),Same residence 1 year ago: nan (Estimate),Same residence 1 year ago: nan (MOE),"Different residence, same state 1 year ago: nan (Estimate)","Different residence, same state 1 year ago: nan (MOE)",Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (Estimate),Different state of residence 1 year ago (cont.): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
4,Current residence in --,Population 1 year and over,Population 1 year and over,Same residence 1 year ago,Same residence 1 year ago,"Different residence, same state 1 year ago","Different residence, same state 1 year ago",Different state of residence 1 year ago,Different state of residence 1 year ago,Different state of residence 1 year ago,...,Different state of residence 1 year ago (cont.),Different state of residence 1 year ago (cont.),Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--,Abroad 1 year ago--
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,Total,Alabama,...,Wyoming,Wyoming,Total,Total,Puerto Rico,Puerto Rico,U.S. Island Area,U.S. Island Area,Foreign Country,Foreign Country
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States1,310212755,25814,263612596,229733,37696597,211307,7070345,58599,109210,...,32228,5150,1833217,32633,74500,8156,15876,3083,1742841,31206
10,Alabama,4764428,3589,4054260,21464,590326,19701,104600,8482,0,...,88,107,15242,2994,619,551,0,184,14623,2857

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [69]:
df = df_filledin.iloc[4:]

In [70]:
df

,0,Population 1 year and over: nan (Estimate),Population 1 year and over: nan (MOE),Same residence 1 year ago: nan (Estimate),Same residence 1 year ago: nan (MOE),"Different residence, same state 1 year ago: nan (Estimate)","Different residence, same state 1 year ago: nan (MOE)",Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (Estimate),Different state of residence 1 year ago (cont.): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
10,Alabama,4764428,3589,4054260,21464,590326,19701,104600,8482,0,...,88,107,15242,2994,619,551,0,184,14623,2857
11,Alaska,721186,1290,592551,8741,90613,7239,33415,4385,1097,...,136,217,4607,1235,25,43,272,312,4310,1199
12,Arizona,6468907,3874,5242674,32185,953789,28803,232457,14183,1331,...,2786,1401,39987,4295,1791,1662,447,401,37749,4037
13,Arkansas,2912680,2753,2453347,16841,373046,14543,76948,7223,374,...,1498,2098,9339,1679,0,184,4,7,9335,1680
14,California,37572738,10274,31777868,67939,5046618,65422,493641,19652,2509,...,1886,1117,254611,13204,2323,1076,1483,859,250805,13066
16,Colorado,5123944,2939,4131357,21752,751921,19587,205060,11855,3108,...,5602,2808,35606,4299,1144,903,387,327,34075,4250
17,Connecticut,3555319,2447,3114940,16188,334918,14546,80311,6574,46,...,104,120,25150,4381,3228,1540,213,179,21709,3926
18,Delaware,906576,1624,782216,9177,86003,7626,34757,4691,119,...,0,182,3600,1007,56,90,0,182,3544,991
19,District of Columbia,624847,948,500267,6225,61992,5668,53830,5001,79,...,215,303,8758,1942,0,197,0,197,8758,1942
20,Florida,19114620,6877,16032617,49245,2380288,44658,537148,19784,18599,...,773,567,164567,10910,21638,4641,2328,1213,140601,9386
22,Georgia,9796547,5863,8231384,34188,1236302,31155,277466,14075,13864,...,106,154,51395,6804,1730,1190,853,507,48812,6838
23,Hawaii,1374852,1662,1164145,10466,134827,9196,55145,5749,608,...,50,66,20735,2663,336,436,631,383,19768,2685
24,Idaho,1573036,2184,1296975,12998,210151,11483,59283,6040,575,...,677,406,6627,1610,136,228,303,317,6188,1617
25,Illinois,12725119,5939,11009321,31714,1441191,27618,208755,10844,883,...,302,309,65852,6243,2049,1480,149,177,63654,6337
26,Indiana,6457067,4184,5493090,26865,805228,22224,134137,9664,1625,...,1681,2023,24612,3645,136,194,0,184,24476,3650
28,Iowa,3035469,2721,2585979,14093,362938,11238,75760,5982,503,...,392,316,10792,1952,786,1190,0,151,10006,1402
29,Kansas,2848708,2507,2361899,16878,381695,15902,88284,7145,853,...,278,239,16830,2856,82,147,605,417,16143,2808
30,Kentucky,4328626,2851,3676472,15304,521511,14825,112787,7854,4137,...,0,181,17856,3275,170,197,0,181,17686,3277
31,Louisiana,4545914,4612,3912023,21791,528406,20131,91215,6941,2329,...,146,216,14270,2470,655,507,267,239,13348,2481
32,Maine,1315586,1384,1132344,9895,151438,9223,27523,3132,129,...,59,81,4281,1182,38,69,0,155,4243,1173
34,Maryland,5816472,3717,5068457,21604,549973,20595,154983,8958,1261,...,0,190,43059,4885,294,249,116,142,42649,4886
35,Massachusetts,6580641,3587,5752166,19793,626380,17354,142577,7863,636,...,264,404,59518,6623,4056,1883,121,156,55341,6212
36,Michigan,9778980,4263,8330990,24803,1268105,23226,133981,8566,2341,...,1277,862,45904,4348,782,797,422,306,44700,4217
37,Minnesota,5315228,2787,4536303,18312,653012,17074,101042,6534,1299,...,213,213,24871,3235,134,136,234,283,24503,3179
38,Mississippi,2947696,2744,2529377,17940,339807,16126,73500,7080,5141,...,307,287,5012,1277,81,108,59,100,4872,1263
40,Missouri,5951913,3866,4965459,21306,801093,19635,162930,8034,1333,...,810,452,22431,3287,826,958,308,399,21297,2935
41,Montana,995544,947,829489,8669,126463,7466,37690,4305,31,...,934,387,1902,524,0,157,64,109,1838,493
44,0,0,0,0,0,0,0,Total,0,Alabama,...,Wyoming,0,Total,0,Puerto Rico,0,U.S. Island Area,0,Foreign Country,0
45,0,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1829420,2101,1540361,9074,237937,9736,43266,4512,245,...,917,371,7856,1718,0,149,0,149,7856,1718
48,Nevada,2725280,3005,2105070,21984,481496,19389,124285,9956,761,...,766,706,14429,2285,237,356,412,524,13780,2094
49,New Hampshire,1309203,1504,1127376,9730,125118,9101,50484,5282,0,...,71,120,6225,1675,75,123,18,30,6132,1663
50,New Jersey,8772744,4541,7929570,23298,655465,21808,130223,7649,779,...,23,30,57486,5907,2574,1462,38,65,54874,5533
51,New Mexico,2060595,2119,1769341,11461,226243,12069,54693,5877,787,...,95,100,10318,2657,429,466,159,154,9730,2561
53,New York,19352153,6112,17202134,34343,1723117,30910,270053,11861,1364,...,396,370,156849,9211,7321,1791,814,592,148714,9149
54,North Carolina,9640490,5097,8167830,27074,1149080,24801,273149,13136,4329,...,604,687,50431,5085,2025,1218,674,289,47732,4741
55,North Dakota,689838,1379,563978,6361,84294,5380,38213,3616,83,...,365,269,3353,1114,0,141,28,44,3325,1114
56,Ohio,11414635,5725,9735390,29715,1440815,28423,196391,9611,3705,...,202,210,42039,4968,1403,910,0,182,40636,4982
57,Oklahoma,3762311,2764,3107367,14635,531347,12812,108972,6570,1030,...,45,68,14625,2231,0,149,257,198,14368,2262
59,Oregon,3857465,2984,3158450,19251,560673,17729,118925,7769,373,...,765,664,19417,3339,152,177,477,546,18788,3285
60,Pennsylvania,12630082,4558,11107110,28998,1252378,26347,215500,8872,1926,...,434,439,55094,5215,7847,2646,224,169,47023,4578
61,Rhode Island,1040527,1533,899551,9890,101165,8498,33446,3551,20,...,21,32,6365,1629,116,186,0,200,6249,1646
62,South Carolina,4668886,3434,3929626,20572,564350,20053,156705,9611,1665,...,0,197,18205,4182,1070,890,0,197,17135,4064
63,South Dakota,821669,1036,676014,7752,115606,7423,26051,2891,0,...,979,735,3998,1116,134,235,0,147,3864,1076
65,Tennessee,6378278,4412,5396833,24470,783077,21860,177098,10625,12116,...,358,382,21270,3181,717,499,28,55,20525,3115
66,Texas,25711791,10124,21354247,60947,3656070,53747,507752,20202,9993,...,2472,1676,193722,10277,4435,1611,1455,1027,187832,10482
67,Utah,2805440,2571,2324019,16852,373980,16586,87870,7490,126,...,2216,715,19571,2661,239,190,0,181,19332,2630
68,Vermont,620224,821,532237,5326,61242,5294,24431,2713,16,...,96,102,2314,691,0,143,45,73,2269,683
69,Virginia,8085389,4754,6857430,25550,915242,24032,250653,11997,2515,...,143,166,62064,6250,516,466,899,726,60649,6138
71,Washington,6815763,3864,5648199,25225,904695,24285,215494,12552,1507,...,394,495,47375,5674,1025,878,1044,528,45306,5353
72,West Virginia,1837518,2090,1613322,11785,174112,11396,47125,4317,477,...,252,395,2959,985,79,123,0,182,2880,983
73,Wisconsin,5660677,3351,4849945,15530,693737,15440,99192,6959,323,...,30,46,17803,2571,975,943,38,63,16790,2572
74,Wyoming,569734,1083,459226,7512,77324,6960,31149,3430,260,...,0,0,2035,973,16,27,0,185,2019,976
76,Puerto Rico,3628402,2934,3366593,12125,238042,11523,20044,2902,8,...,0,214,3723,1074,N/A2,N/A2,0,214,3723,1074

And can also delete excess title columns at the start

In [71]:
df.drop(columns = 
    ['Population 1 year and over: nan (Estimate)',
     'Population 1 year and over: nan (MOE)',
     'Same residence 1 year ago: nan (Estimate)',
     'Same residence 1 year ago: nan (MOE)',
     'Different residence, same state 1 year ago: nan (Estimate)',
     'Different residence, same state 1 year ago: nan (MOE)',
     'Different state of residence 1 year ago: Total (Estimate)',
     'Different state of residence 1 year ago: Total (MOE)']
, inplace=True)

In [72]:
df

,0,Different state of residence 1 year ago: Alabama (Estimate),Different state of residence 1 year ago: Alabama (MOE),Different state of residence 1 year ago (cont.): Alaska (Estimate),Different state of residence 1 year ago (cont.): Alaska (MOE),Different state of residence 1 year ago (cont.): Arizona (Estimate),Different state of residence 1 year ago (cont.): Arizona (MOE),Different state of residence 1 year ago (cont.): Arkansas (Estimate),Different state of residence 1 year ago (cont.): Arkansas (MOE),Different state of residence 1 year ago (cont.): California (Estimate),...,Different state of residence 1 year ago (cont.): Wyoming (Estimate),Different state of residence 1 year ago (cont.): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country (Estimate),Abroad 1 year ago--: Foreign Country (MOE)
10,Alabama,0,0,1004,829,962,583,660,382,3077,...,88,107,15242,2994,619,551,0,184,14623,2857
11,Alaska,1097,825,0,0,1520,1441,196,202,3494,...,136,217,4607,1235,25,43,272,312,4310,1199
12,Arizona,1331,1286,3717,1505,0,0,1214,659,44889,...,2786,1401,39987,4295,1791,1662,447,401,37749,4037
13,Arkansas,374,293,855,906,1677,954,0,0,3525,...,1498,2098,9339,1679,0,184,4,7,9335,1680
14,California,2509,983,6995,1948,38916,5726,3472,1354,0,...,1886,1117,254611,13204,2323,1076,1483,859,250805,13066
16,Colorado,3108,1610,3457,1695,10589,2218,1043,580,22152,...,5602,2808,35606,4299,1144,903,387,327,34075,4250
17,Connecticut,46,103,439,511,3167,3028,200,228,3161,...,104,120,25150,4381,3228,1540,213,179,21709,3926
18,Delaware,119,164,692,920,188,227,0,182,2221,...,0,182,3600,1007,56,90,0,182,3544,991
19,District of Columbia,79,138,1247,715,902,646,35,59,4999,...,215,303,8758,1942,0,197,0,197,8758,1942
20,Florida,18599,4762,10704,4327,6473,1865,3321,1136,20386,...,773,567,164567,10910,21638,4641,2328,1213,140601,9386
22,Georgia,13864,2903,2654,1444,6657,2675,1041,519,14174,...,106,154,51395,6804,1730,1190,853,507,48812,6838
23,Hawaii,608,479,1417,869,1865,695,24,54,9756,...,50,66,20735,2663,336,436,631,383,19768,2685
24,Idaho,575,838,1198,790,2424,1307,291,268,10280,...,677,406,6627,1610,136,228,303,317,6188,1617
25,Illinois,883,478,2250,1511,7139,2314,1587,643,14940,...,302,309,65852,6243,2049,1480,149,177,63654,6337
26,Indiana,1625,788,479,429,2763,1095,564,753,6033,...,1681,2023,24612,3645,136,194,0,184,24476,3650
28,Iowa,503,400,951,814,1590,803,451,237,3268,...,392,316,10792,1952,786,1190,0,151,10006,1402
29,Kansas,853,609,333,407,3094,1630,2158,890,5411,...,278,239,16830,2856,82,147,605,417,16143,2808
30,Kentucky,4137,1628,304,370,1103,715,518,299,3415,...,0,181,17856,3275,170,197,0,181,17686,3277
31,Louisiana,2329,1114,403,467,2021,1191,3645,2324,5139,...,146,216,14270,2470,655,507,267,239,13348,2481
32,Maine,129,172,38,48,230,170,0,155,1610,...,59,81,4281,1182,38,69,0,155,4243,1173
34,Maryland,1261,713,1947,1123,760,359,136,159,8614,...,0,190,43059,4885,294,249,116,142,42649,4886
35,Massachusetts,636,622,890,600,1972,979,394,340,12770,...,264,404,59518,6623,4056,1883,121,156,55341,6212
36,Michigan,2341,1013,1152,685,7168,3100,906,559,8085,...,1277,862,45904,4348,782,797,422,306,44700,4217
37,Minnesota,1299,919,523,312,3065,861,375,222,8086,...,213,213,24871,3235,134,136,234,283,24503,3179
38,Mississippi,5141,1870,0,198,710,509,2680,1447,4371,...,307,287,5012,1277,81,108,59,100,4872,1263
40,Missouri,1333,768,2186,1289,2297,741,9434,2224,10717,...,810,452,22431,3287,826,958,308,399,21297,2935
41,Montana,31,55,726,442,1548,938,63,102,5428,...,934,387,1902,524,0,157,64,109,1838,493
44,0,Alabama,0,Alaska,0,Arizona,0,Arkansas,0,California,...,Wyoming,0,Total,0,Puerto Rico,0,U.S. Island Area,0,Foreign Country,0
45,0,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,245,275,626,531,2406,1120,363,317,3438,...,917,371,7856,1718,0,149,0,149,7856,1718
48,Nevada,761,724,2161,1047,8748,2540,353,404,49978,...,766,706,14429,2285,237,356,412,524,13780,2094
49,New Hampshire,0,181,437,378,440,413,0,181,1514,...,71,120,6225,1675,75,123,18,30,6132,1663
50,New Jersey,779,509,359,437,1328,704,57,70,4330,...,23,30,57486,5907,2574,1462,38,65,54874,5533
51,New Mexico,787,509,320,264,6391,1673,410,286,4536,...,95,100,10318,2657,429,466,159,154,9730,2561
53,New York,1364,864,4002,2016,4146,2468,247,203,24623,...,396,370,156849,9211,7321,1791,814,592,148714,9149
54,North Carolina,4329,1544,1458,925,3493,1189,861,649,13883,...,604,687,50431,5085,2025,1218,674,289,47732,4741
55,North Dakota,83,142,70,105,1571,788,0,141,999,...,365,269,3353,1114,0,141,28,44,3325,1114
56,Ohio,3705,2297,2207,1757,4929,1912,884,604,8995,...,202,210,42039,4968,1403,910,0,182,40636,4982
57,Oklahoma,1030,467,1279,600,2974,1435,5777,1187,8950,...,45,68,14625,2231,0,149,257,198,14368,2262
59,Oregon,373,425,2513,953,7954,2060,165,158,31862,...,765,664,19417,3339,152,177,477,546,18788,3285
60,Pennsylvania,1926,1318,1658,857,3529,1256,573,315,7772,...,434,439,55094,5215,7847,2646,224,169,47023,4578
61,Rhode Island,20,44,0,200,93,151,0,200,2146,...,21,32,6365,1629,116,186,0,200,6249,1646
62,South Carolina,1665,635,1244,1016,2222,1160,839,526,5979,...,0,197,18205,4182,1070,890,0,197,17135,4064
63,South Dakota,0,147,855,1127,435,333,227,354,1494,...,979,735,3998,1116,134,235,0,147,3864,1076
65,Tennessee,12116,3309,1281,847,2250,907,3306,1731,8396,...,358,382,21270,3181,717,499,28,55,20525,3115
66,Texas,9993,3132,6759,2614,18908,3870,13781,3771,62702,...,2472,1676,193722,10277,4435,1611,1455,1027,187832,10482
67,Utah,126,171,2819,1292,7966,2419,361,402,15286,...,2216,715,19571,2661,239,190,0,181,19332,2630
68,Vermont,16,23,93,153,127,165,0,143,1112,...,96,102,2314,691,0,143,45,73,2269,683
69,Virginia,2515,990,1906,1287,2420,1030,445,319,14780,...,143,166,62064,6250,516,466,899,726,60649,6138
71,Washington,1507,730,4328,1682,8362,2641,1413,1121,45597,...,394,495,47375,5674,1025,878,1044,528,45306,5353
72,West Virginia,477,339,306,455,79,129,0,182,1231,...,252,395,2959,985,79,123,0,182,2880,983
73,Wisconsin,323,262,236,193,3257,1696,253,216,5347,...,30,46,17803,2571,975,943,38,63,16790,2572
74,Wyoming,260,284,590,661,2014,1234,244,405,2035,...,0,0,2035,973,16,27,0,185,2019,976
76,Puerto Rico,8,15,57,94,54,90,93,158,519,...,0,214,3723,1074,N/A2,N/A2,0,214,3723,1074


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [73]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Different state of residence 1 year ago: Alabama (Estimate),0,1097,1331,374,2509,3108,46,119,79,18599,...,12116,9993,126,16,2515,1507,477,323,260,8
Different state of residence 1 year ago: Alabama (MOE),0,825,1286,293,983,1610,103,164,138,4762,...,3309,3132,171,23,990,730,339,262,284,15
Different state of residence 1 year ago (cont.): Alaska (Estimate),1004,0,3717,855,6995,3457,439,692,1247,10704,...,1281,6759,2819,93,1906,4328,306,236,590,57
Different state of residence 1 year ago (cont.): Alaska (MOE),829,0,1505,906,1948,1695,511,920,715,4327,...,847,2614,1292,153,1287,1682,455,193,661,94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),551,43,1662,184,1076,903,1540,90,197,4641,...,499,1611,190,143,466,878,123,943,27,N/A2
Abroad 1 year ago--: U.S. Island Area (Estimate),0,272,447,4,1483,387,213,0,0,2328,...,28,1455,0,45,899,1044,0,38,0,0
Abroad 1 year ago--: U.S. Island Area (MOE),184,312,401,7,859,327,179,182,197,1213,...,55,1027,181,73,726,528,182,63,185,214
Abroad 1 year ago--: Foreign Country (Estimate),14623,4310,37749,9335,250805,34075,21709,3544,8758,140601,...,20525,187832,19332,2269,60649,45306,2880,16790,2019,3723
Abroad 1 year ago--: Foreign Country (MOE),2857,1199,4037,1680,13066,4250,3926,991,1942,9386,...,3115,10482,2630,683,6138,5353,983,2572,976,1074

In [74]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [75]:

df = df.iloc[1:]

And drop the final four rows (arent states)

In [76]:
df = df.iloc[:-8]

And drop columns with 0 as title (represnt the header that was in the middle of the original excel sheet)

In [77]:

df.drop(columns=['0'], inplace=True)

df.columns

Index(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District of Columbia ', 'Florida',
       'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia',
       'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico'],
      dtype='object', name='0')

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [78]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita; remove Puerto Rico from the end

In [79]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops = df_pops[1:-1]

df_pops

                               0
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [80]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Different state of residence 1 year ago: Alabam...                    79
Different state of residence 1 year ago (cont.)...                  1247
Different state of residence 1 year ago (cont.)...                   902
Different state of residence 1 year ago (cont.)...                    35
Different state of residence 1 year ago (cont.)...                  4999
Different state of residence 1 year ago (cont.)...                   677
Different state of residence 1 year ago (cont.)...                   618
Different state of residence 1 year ago (cont.)...                    78
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                  1705
Different state of residence 1 year ago (cont.)...                  1079
Different state of residence 1 year ago (cont.)...                    38
Different state of residence 1 year ago (cont.)...                    46
Different state of residence 1 year ago (cont.)...                   795
Different state of residence 1 year ago (cont.)...                   469
Different state of residence 1 year ago (cont.)...                   133
Different state of residence 1 year ago (cont.)...                   164
Different state of residence 1 year ago (cont.)...                   112
Different state of residence 1 year ago (cont.)...                   283
Different state of residence 1 year ago (cont.)...                   194
Different state of residence 1 year ago (cont.)...                 14120
Different state of residence 1 year ago (cont.)...                  1524
Different state of residence 1 year ago (cont.)...                   944
Different state of residence 1 year ago (cont.)...                   393
Different state of residence 1 year ago (cont.)...                    44
Different state of residence 1 year ago (cont.)...                   337
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   172
Different state of residence 1 year ago (cont.)...                    42
Different state of residence 1 year ago (cont.)...                   197
Different state of residence 1 year ago (cont.)...                  1451
Different state of residence 1 year ago (cont.)...                   116
Different state of residence 1 year ago (cont.)...                  3085
Different state of residence 1 year ago (cont.)...                   985
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   651
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   157
Different state of residence 1 year ago (cont.)...                  1494
Different state of residence 1 year ago (cont.)...                   635
Different state of residence 1 year ago (cont.)...                   150
Different state of residence 1 year ago (cont.)...                     0
Different state of residence 1 year ago (cont.)...                   577
Different state of residence 1 year ago (cont.)...                  1473
Different state of residence 1 year ago (cont.)...                   116
Different state of residence 1 year ago (cont.)...                   267
Different state of residence 1 year ago (cont.)...                  9537
Different state of residence 1 year ago (cont.)...                   481
Different state of residence 1 year ago (cont.)...                   293
Different state of residence 1 year ago (cont.)...                   721
Different state of residence 1 year ago (cont.)...                   215

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [81]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

For 2021 and 2017, we needed to cut off the top columns that arent for specific states, but that's not relevent here because of different structure for 2009 and 2005

In [ ]:

# df_estimates = df_estimates[4:]
# df_moes = df_moes[4:]

In [82]:
df_moes.head()

0          District of Columbia
0
Alabama                      138
Alaska                       715
Arizona                      646
Arkansas                      59
California                  2108

In [83]:
df_estimates.head()

0          District of Columbia
0
Alabama                       79
Alaska                      1247
Arizona                      902
Arkansas                      35
California                  4999

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [84]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Now I'm adding a state polulation column to my newly formatted table

In [85]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [86]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [87]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [88]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                        79     138          5024279
Alaska                       1247     715           733391
Arizona                       902     646          7151502
Arkansas                       35      59          3011524
California                   4999    2108         39538223
Colorado                      677     546          5773714
Connecticut                   618     439          3605944
Delaware                       78     127           989948
District of Columbia            0       0           689545
Florida                      1705     661         21538187
Georgia                      1079     470         10711908
Hawaii                         38      87          1455271
Idaho                          46      75          1839106
Illinois                      795     446         12812508
Indiana                       469     379          6785528
Iowa                          133     221          3190369
Kansas                        164     267          2937880
Kentucky                      112     136          4505836
Louisiana                     283     295          4657757
Maine                         194     244          1362359
Maryland                    14120    2487          6177224
Massachusetts                1524     717          7029917
Michigan                      944     670         10077331
Minnesota                     393     240          5706494
Mississippi                    44      74          2961279
Missouri                      337     354          6154913
Montana                         0     197          1084225
Nebraska                      172     182          1961504
Nevada                         42      69          3104614
New Hampshire                 197     183          1377529
New Jersey                   1451     792          9288994
New Mexico                    116     139          2117522
New York                     3085     851         20201249
North Carolina                985     503         10439388
North Dakota                    0     197           779094
Ohio                          651     429         11799448
Oklahoma                        0     197          3959353
Oregon                        157     182          4237256
Pennsylvania                 1494     608         13002700
Rhode Island                  635     596          1097379
South Carolina                150     140          5118425
South Dakota                    0     197           886667
Tennessee                     577     478          6910840
Texas                        1473     826         29145505
Utah                          116     145          3271616
Vermont                       267     250           643077
Virginia                     9537    1762          8631393
Washington                    481     358          7705281
West Virginia                 293     219          1793716
Wisconsin                     721     420          5893718
Wyoming                       215     303           576851

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [89]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [90]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Need to manually drop DC here because its input differently than in the other years -- here, the D.C. figure for folks that lived in D.C. both this year and last year is not n/a or 0, but rather a substantial number that represents the number of folks that did NOT move since last year's census

In [91]:
df = df.drop(['District of Columbia'])

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [92]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,79,138,5024279,0.000016,0.000027
1,Alaska,1247,715,733391,0.001700,0.000975
2,Arizona,902,646,7151502,0.000126,0.000090
3,Arkansas,35,59,3011524,0.000012,0.000020
4,California,4999,2108,39538223,0.000126,0.000053

Looking at states with most people coming to DC

In [93]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
19,Maryland,14120,2487,6177224,0.002286,0.000403
1,Alaska,1247,715,733391,0.001700,0.000975
45,Virginia,9537,1762,8631393,0.001105,0.000204
38,Rhode Island,635,596,1097379,0.000579,0.000543
44,Vermont,267,250,643077,0.000415,0.000389
49,Wyoming,215,303,576851,0.000373,0.000525
20,Massachusetts,1524,717,7029917,0.000217,0.000102
6,Connecticut,618,439,3605944,0.000171,0.000122
47,West Virginia,293,219,1793716,0.000163,0.000122
29,New Jersey,1451,792,9288994,0.000156,0.000085

To export, want to make a slice excluding all DMV states -- Maryland, Virginia

In [94]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]

Now need to reset the index again to make numbers consecutive now that I've removed ceratin rows.

In [95]:
df = df.reset_index(drop=True)

Now add in 2008 election winners for each state

First, read in file

In [96]:
df_2008_election_winners = pd.read_csv('pres-election-results-2008.csv')

type(df_2008_election_winners)

pandas.DataFrame

Next, add winning party and percent of votes columns

In [97]:
df_2008_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

df_2008_election_winners.head()

        state  year party_detailed  percent_total_votes
0     Alabama  2008     REPUBLICAN             0.603169
1      Alaska  2008     REPUBLICAN             0.594245
2     Arizona  2008     REPUBLICAN             0.536352
3    Arkansas  2008     REPUBLICAN             0.587159
4  California  2008       DEMOCRAT             0.610126

In [ ]:

df['winning_party'] = df_2008_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2008_election_winners['percent_total_votes']

df.head()

Check that indexes match

In [ ]:
df.index

In [ ]:
df_2008_election_winners.index

Save as csv file

In [ ]:
df.to_csv('DC-migration-2012.csv')