I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA State_to_State_Migrations_Table_2017.xls')

In [3]:
df.shape

(86, 130)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.tail(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
57,Oklahoma,3875922,2998,3216306,16831,542724,15629,101961,5461,1133,...,206,Oklahoma,14931,3150,386,248,96,136,14449,3144
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Oregon,4102048,2613,3405784,21975,520747,20098,149513,8993,179,...,231,Oregon,26004,3616,0,207,220,258,25784,3592
60,Pennsylvania,12674642,5854,11072942,30451,1292389,28379,250120,12213,1416,...,179,Pennsylvania,59191,6605,7783,2488,378,332,51030,5652
61,Rhode Island,1048549,1369,922210,8302,83440,7010,36850,4029,135,...,217,Rhode Island,6049,1755,306,397,0,217,5743,1692
62,South Carolina,4966211,3526,4248517,21416,531315,19807,166573,9580,2133,...,211,South Carolina,19806,3181,1506,980,197,166,18103,3014
63,South Dakota,856726,1949,723740,7648,99781,5584,26106,3529,144,...,464,South Dakota,7099,2487,358,306,58,100,6683,2468
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Tennessee,6642072,5023,5675990,26239,748912,22417,191909,10150,9523,...,504,Tennessee,25261,3848,979,1104,773,392,23509,3768
66,Texas,27924632,9989,23534387,67754,3643333,65150,524511,22790,10235,...,588,Texas,222401,14550,5105,1755,1714,677,215582,14375
67,Utah,3056193,3007,2532858,16462,398606,14353,99584,7531,644,...,997,Utah,25145,4357,0,192,502,512,24643,4436
68,Vermont,619089,948,536390,5931,57588,4891,21868,3314,0,...,653,Vermont,3243,1880,125,174,0,157,3118,1879
69,Virginia,8372522,4750,7089782,25415,958267,22292,250490,10432,2341,...,503,Virginia,73983,7003,1318,703,850,515,71815,6872
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Washington,7318811,4011,6016482,24671,978057,22670,260787,14178,1605,...,412,Washington,63485,6684,88,106,1992,1214,61405,6551
72,West Virginia,1798306,1891,1589833,9253,165375,8367,40007,4327,239,...,200,West Virginia,3091,912,103,129,0,200,2988,874
73,Wisconsin,5731549,3294,4908638,17520,687285,16914,112519,6909,757,...,250,Wisconsin,23107,3476,2541,1331,74,120,20492,3238
74,Wyoming,573483,1042,481231,7380,71338,6817,18511,2739,264,...,NaN,Wyoming,2403,1038,0,201,0,201,2403,1038
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Puerto Rico,3313519,3560,3101332,13351,189034,12193,20167,4285,888,...,262,Puerto Rico,2986,1148,NaN,NaN,97,161,2889,1152

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123',
       'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126', 'Unnamed: 127',
       'Unnamed: 128', 'Unnamed: 129'],
      dtype='str', length=130)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country4,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,United States2,321994428,33543,275921008,183767,36468599,171943,7471493,70316,101466,...,4190,United States2,2133328,38070,97488,9821,18321,3416,2017519,36251
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alabama,4819343,3710,4158224,20321,535649,18004,111803,8786,NaN,...,193,Alabama,13667,2273,476,469,0,200,13191,2200
11,Alaska,730874,1438,595804,9147,98168,8242,30199,4584,942,...,13,Alaska,6703,2197,0,153,965,797,5738,2168
12,Arizona,6935358,3888,5717189,24333,911120,22690,261727,11986,1337,...,910,Arizona,45322,5364,438,358,91,106,44793,5315
13,Arkansas,2968395,3103,2509717,16654,370309,15515,79411,7492,574,...,25,Arkansas,8958,2034,573,602,0,201,8385,1955
14,California,39085984,10045,34009331,68358,4234770,58169,523131,20053,3715,...,994,California,318752,16837,1864,876,842,422,316046,16679
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Colorado,5542282,3414,4546729,22932,734182,22118,226933,11475,3120,...,1877,Colorado,34438,5150,828,652,568,382,33042,4876
17,Connecticut,3556297,2701,3136666,16246,311726,14866,83325,6561,206,...,265,Connecticut,24580,4479,3780,2431,0,207,20800,3534
18,Delaware,952449,1698,830905,8792,78998,7077,38532,4552,506,...,198,Delaware,4014,1272,260,241,66,110,3688,1174
19,District of Columbia,684810,1664,554225,7670,64013,6510,56231,4393,494,...,208,District of Columbia,10341,2210,356,325,78,130,9907,2249
20,Florida,20772371,8045,17554348,46036,2402381,46730,566476,18973,9389,...,384,Florida,249166,15822,28538,6571,2847,2026,217781,13578
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Georgia,10299497,6400,8760762,36118,1202587,29374,278889,16483,15270,...,652,Georgia,57259,6329,3345,1584,306,294,53608,6052
23,Hawaii,1410750,1722,1231340,10978,115683,10053,46457,5358,844,...,165,Hawaii,17270,3559,11,18,1572,1101,15687,3219

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in --,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country4,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,321994428,33543,275921008,183767,36468599,171943,7471493,70316,101466,...,4190,United States2,2133328,38070,97488,9821,18321,3416,2017519,36251
10,Alabama,4819343,3710,4158224,20321,535649,18004,111803,8786,NaN,...,193,Alabama,13667,2273,476,469,0,200,13191,2200
11,Alaska,730874,1438,595804,9147,98168,8242,30199,4584,942,...,13,Alaska,6703,2197,0,153,965,797,5738,2168
12,Arizona,6935358,3888,5717189,24333,911120,22690,261727,11986,1337,...,910,Arizona,45322,5364,438,358,91,106,44793,5315
13,Arkansas,2968395,3103,2509717,16654,370309,15515,79411,7492,574,...,25,Arkansas,8958,2034,573,602,0,201,8385,1955
14,California,39085984,10045,34009331,68358,4234770,58169,523131,20053,3715,...,994,California,318752,16837,1864,876,842,422,316046,16679
16,Colorado,5542282,3414,4546729,22932,734182,22118,226933,11475,3120,...,1877,Colorado,34438,5150,828,652,568,382,33042,4876
17,Connecticut,3556297,2701,3136666,16246,311726,14866,83325,6561,206,...,265,Connecticut,24580,4479,3780,2431,0,207,20800,3534
18,Delaware,952449,1698,830905,8792,78998,7077,38532,4552,506,...,198,Delaware,4014,1272,260,241,66,110,3688,1174
19,District of Columbia,684810,1664,554225,7670,64013,6510,56231,4393,494,...,208,District of Columbia,10341,2210,356,325,78,130,9907,2249
20,Florida,20772371,8045,17554348,46036,2402381,46730,566476,18973,9389,...,384,Florida,249166,15822,28538,6571,2847,2026,217781,13578
22,Georgia,10299497,6400,8760762,36118,1202587,29374,278889,16483,15270,...,652,Georgia,57259,6329,3345,1584,306,294,53608,6052
23,Hawaii,1410750,1722,1231340,10978,115683,10053,46457,5358,844,...,165,Hawaii,17270,3559,11,18,1572,1101,15687,3219
24,Idaho,1694182,2325,1405344,15502,210310,14673,71899,7189,58,...,1076,Idaho,6629,2456,67,117,0,201,6562,2447
25,Illinois,12659328,5300,11026895,37393,1365922,33966,195092,11000,1682,...,569,Illinois,71419,5809,1829,1082,0,190,69590,5780
26,Indiana,6591598,4170,5633171,21965,792487,21997,142290,8504,1216,...,197,Indiana,23650,3542,144,155,93,126,23413,3546
28,Iowa,3106880,2770,2654666,12669,362905,12692,77072,4978,817,...,65,Iowa,12237,2764,67,115,0,163,12170,2750

Rename columns to be clearer numbers

In [9]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '120', '121', '122', '123', '124', '125', '126', '127', '128', '129'],
      dtype='str', length=130)

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [10]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110', '121']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

df

,0,1,2,3,4,5,6,7,8,9,...,119,120,122,123,124,125,126,127,128,129
4,Current residence in --,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,NaN,Abroad 1 year ago--,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country4,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,321994428,33543,275921008,183767,36468599,171943,7471493,70316,101466,...,25954,4190,2133328,38070,97488,9821,18321,3416,2017519,36251
10,Alabama,4819343,3710,4158224,20321,535649,18004,111803,8786,NaN,...,104,193,13667,2273,476,469,0,200,13191,2200
11,Alaska,730874,1438,595804,9147,98168,8242,30199,4584,942,...,6,13,6703,2197,0,153,965,797,5738,2168
12,Arizona,6935358,3888,5717189,24333,911120,22690,261727,11986,1337,...,997,910,45322,5364,438,358,91,106,44793,5315
13,Arkansas,2968395,3103,2509717,16654,370309,15515,79411,7492,574,...,12,25,8958,2034,573,602,0,201,8385,1955
14,California,39085984,10045,34009331,68358,4234770,58169,523131,20053,3715,...,1395,994,318752,16837,1864,876,842,422,316046,16679
16,Colorado,5542282,3414,4546729,22932,734182,22118,226933,11475,3120,...,5135,1877,34438,5150,828,652,568,382,33042,4876
17,Connecticut,3556297,2701,3136666,16246,311726,14866,83325,6561,206,...,257,265,24580,4479,3780,2431,0,207,20800,3534
18,Delaware,952449,1698,830905,8792,78998,7077,38532,4552,506,...,0,198,4014,1272,260,241,66,110,3688,1174
19,District of Columbia,684810,1664,554225,7670,64013,6510,56231,4393,494,...,0,208,10341,2210,356,325,78,130,9907,2249
20,Florida,20772371,8045,17554348,46036,2402381,46730,566476,18973,9389,...,396,384,249166,15822,28538,6571,2847,2026,217781,13578
22,Georgia,10299497,6400,8760762,36118,1202587,29374,278889,16483,15270,...,630,652,57259,6329,3345,1584,306,294,53608,6052
23,Hawaii,1410750,1722,1231340,10978,115683,10053,46457,5358,844,...,96,165,17270,3559,11,18,1572,1101,15687,3219
24,Idaho,1694182,2325,1405344,15502,210310,14673,71899,7189,58,...,1747,1076,6629,2456,67,117,0,201,6562,2447
25,Illinois,12659328,5300,11026895,37393,1365922,33966,195092,11000,1682,...,414,569,71419,5809,1829,1082,0,190,69590,5780
26,Indiana,6591598,4170,5633171,21965,792487,21997,142290,8504,1216,...,0,197,23650,3542,144,155,93,126,23413,3546
28,Iowa,3106880,2770,2654666,12669,362905,12692,77072,4978,817,...,54,65,12237,2764,67,115,0,163,12170,2750
29,Kansas,2876925,2252,2413141,16713,366147,14775,86154,6863,276,...,123,214,11483,2776,347,480,0,177,11136,2612
30,Kentucky,4404279,3412,3721100,18613,563721,16774,103985,7510,2851,...,266,435,15473,2667,1402,974,0,195,14071,2643
31,Louisiana,4629962,4671,4030674,23379,513676,21398,72836,6749,2830,...,195,313,12776,2507,455,352,0,214,12321,2434
32,Maine,1322591,1567,1140136,8998,144186,7584,34252,3384,246,...,0,175,4017,1191,12,23,0,175,4005,1193
34,Maryland,5988007,3186,5168350,22507,605885,19283,165654,9442,644,...,44,73,48118,5690,1808,1419,488,421,45822,5774
35,Massachusetts,6789798,4401,5888011,21681,677835,20305,146299,9016,212,...,0,210,77653,7313,6748,2338,273,208,70632,6322
36,Michigan,9851330,4904,8450559,29643,1203536,27635,148787,8966,3669,...,635,605,48448,4526,2621,1909,29,48,45798,4373
37,Minnesota,5510902,3342,4728748,17295,643272,15812,115623,6938,491,...,213,198,23259,3670,503,491,0,153,22756,3633
38,Mississippi,2946971,3473,2553271,15365,313673,14480,73549,6399,5936,...,212,344,6478,1463,281,335,31,55,6166,1449
40,Missouri,6039877,3888,5108238,22203,742205,20941,164957,10094,2518,...,529,404,24477,3896,943,579,180,299,23354,3826
41,Montana,1039170,1406,883342,6867,116400,6019,35456,3743,301,...,4072,2136,3972,1508,151,194,0,174,3821,1457
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,Wyoming,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
45,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
47,Nebraska,1894217,1845,1586729,11557,243792,10896,52507,4964,420,...,572,361,11189,2380,436,561,115,165,10638,2326
48,Nevada,2963456,3069,2430163,15771,383067,15449,133074,9455,191,...,143,174,17152,3228,384,416,783,719,15985,3252
49,New Hampshire,1330742,1551,1134244,9693,137212,7357,52893,5645,109,...,0,192,6393,1992,547,698,90,153,5756,1854
50,New Jersey,8910191,5107,7968039,30575,710807,24385,152106,10356,169,...,110,146,79239,8423,4195,1915,73,90,74971,8335
51,New Mexico,2062628,2509,1801560,14081,193225,12238,57255,6560,770,...,267,231,10588,2699,131,158,0,201,10457,2701
53,New York,19638923,8149,17553033,35651,1655152,34038,285252,11214,1849,...,54,65,145486,8190,5910,1731,1325,1355,138251,7633
54,North Carolina,10158556,5686,8649400,35788,1139260,29207,313834,13762,4526,...,159,212,56062,6184,3011,1506,385,526,52666,6001
55,North Dakota,744641,1446,609017,7590,92436,6922,37315,3906,53,...,829,544,5873,1643,664,704,0,161,5209,1631
56,Ohio,11520109,5548,9822847,30854,1452745,28255,198929,10839,2487,...,248,236,45588,5474,3765,1698,267,321,41556,5129
57,Oklahoma,3875922,2998,3216306,16831,542724,15629,101961,5461,1133,...,251,206,14931,3150,386,248,96,136,14449,3144
59,Oregon,4102048,2613,3405784,21975,520747,20098,149513,8993,179,...,227,231,26004,3616,0,207,220,258,25784,3592
60,Pennsylvania,12674642,5854,11072942,30451,1292389,28379,250120,12213,1416,...,0,179,59191,6605,7783,2488,378,332,51030,5652
61,Rhode Island,1048549,1369,922210,8302,83440,7010,36850,4029,135,...,0,217,6049,1755,306,397,0,217,5743,1692
62,South Carolina,4966211,3526,4248517,21416,531315,19807,166573,9580,2133,...,0,211,19806,3181,1506,980,197,166,18103,3014
63,South Dakota,856726,1949,723740,7648,99781,5584,26106,3529,144,...,728,464,7099,2487,358,306,58,100,6683,2468
65,Tennessee,6642072,5023,5675990,26239,748912,22417,191909,10150,9523,...,362,504,25261,3848,979,1104,773,392,23509,3768
66,Texas,27924632,9989,23534387,67754,3643333,65150,524511,22790,10235,...,948,588,222401,14550,5105,1755,1714,677,215582,14375
67,Utah,3056193,3007,2532858,16462,398606,14353,99584,7531,644,...,1722,997,25145,4357,0,192,502,512,24643,4436
68,Vermont,619089,948,536390,5931,57588,4891,21868,3314,0,...,643,653,3243,1880,125,174,0,157,3118,1879
69,Virginia,8372522,4750,7089782,25415,958267,22292,250490,10432,2341,...,305,503,73983,7003,1318,703,850,515,71815,6872
71,Washington,7318811,4011,6016482,24671,978057,22670,260787,14178,1605,...,581,412,63485,6684,88,106,1992,1214,61405,6551
72,West Virginia,1798306,1891,1589833,9253,165375,8367,40007,4327,239,...,0,200,3091,912,103,129,0,200,2988,874
73,Wisconsin,5731549,3294,4908638,17520,687285,16914,112519,6909,757,...,273,250,23107,3476,2541,1331,74,120,20492,3238
74,Wyoming,573483,1042,481231,7380,71338,6817,18511,2739,264,...,NaN,NaN,2403,1038,0,201,0,201,2403,1038
76,Puerto Rico,3313519,3560,3101332,13351,189034,12193,20167,4285,888,...,0,262,2986,1148,NaN,NaN,97,161,2889,1152

Before I forward fill into the null values, I want to make sure to preserve any values that were listed as N/A in the original dataset.

There is one set for each of the states. Specifically, for those people that had a different state of residence last year than this year, the cells in the excel sheet where the row state (currently reside in) and the column state (lived last year) are the same are filled in as N/A.

Here, it makes sense to replace them with zero, because no people who had a different state of residence last year than this year lived in a given state both last year and this year.

In [11]:
df.iloc[3:] = df.iloc[3:].fillna('0')

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#first, dealing with columns B-G/1-6)

column_1_name = f'{df.iloc[0, 1]} ({df.iloc[2, 1]})'
column_2_name = f'{df.iloc[0, 1]} ({df.iloc[2, 2]})'

column_3_name = f'{df.iloc[0, 3]} ({df.iloc[2, 3]})'
column_4_name = f'{df.iloc[0, 3]} ({df.iloc[2, 4]})'

column_5_name = f'{df.iloc[0, 5]} ({df.iloc[2, 5]})'
column_6_name = f'{df.iloc[0, 5]} ({df.iloc[2, 6]})'

df_clean = df.rename(columns ={
    '1': column_1_name,
    '2': column_2_name,
    '3': column_3_name,
    '4': column_4_name,
    '5': column_5_name,
    '6': column_6_name})

#next, for the rest of the columns:
#first, fill in blanks

df_filledin = df_clean.ffill(axis=1)

#then pull the info I need to name each column

for i in range(7, 119):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [13]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Population 1 year and over (Estimate),Population 1 year and over (MOE),Same house 1 year ago (Estimate),Same house 1 year ago (MOE),Same state of residence 1 year ago (Estimate),Same state of residence 1 year ago (MOE),Different state of residence 1 year ago: Total (Estimate),Different state of residence 1 year ago: Total (MOE),Different state of residence 1 year ago: Alabama (Estimate),...,Different state of residence 1 year ago (continued): Wyoming (Estimate),Different state of residence 1 year ago (continued): Wyoming (MOE),Abroad 1 year ago--: Total (Estimate),Abroad 1 year ago--: Total (MOE),Abroad 1 year ago--: Puerto Rico (Estimate),Abroad 1 year ago--: Puerto Rico (MOE),Abroad 1 year ago--: U.S. Island Area (Estimate),Abroad 1 year ago--: U.S. Island Area (MOE),Abroad 1 year ago--: Foreign Country4 (Estimate),Abroad 1 year ago--: Foreign Country4 (MOE)
53,New York,19638923,8149,17553033,35651,1655152,34038,285252,11214,1849,...,54,65,145486,8190,5910,1731,1325,1355,138251,7633
54,North Carolina,10158556,5686,8649400,35788,1139260,29207,313834,13762,4526,...,159,212,56062,6184,3011,1506,385,526,52666,6001
55,North Dakota,744641,1446,609017,7590,92436,6922,37315,3906,53,...,829,544,5873,1643,664,704,0,161,5209,1631
56,Ohio,11520109,5548,9822847,30854,1452745,28255,198929,10839,2487,...,248,236,45588,5474,3765,1698,267,321,41556,5129
57,Oklahoma,3875922,2998,3216306,16831,542724,15629,101961,5461,1133,...,251,206,14931,3150,386,248,96,136,14449,3144
59,Oregon,4102048,2613,3405784,21975,520747,20098,149513,8993,179,...,227,231,26004,3616,0,207,220,258,25784,3592
60,Pennsylvania,12674642,5854,11072942,30451,1292389,28379,250120,12213,1416,...,0,179,59191,6605,7783,2488,378,332,51030,5652
61,Rhode Island,1048549,1369,922210,8302,83440,7010,36850,4029,135,...,0,217,6049,1755,306,397,0,217,5743,1692
62,South Carolina,4966211,3526,4248517,21416,531315,19807,166573,9580,2133,...,0,211,19806,3181,1506,980,197,166,18103,3014
63,South Dakota,856726,1949,723740,7648,99781,5584,26106,3529,144,...,728,464,7099,2487,358,306,58,100,6683,2468
65,Tennessee,6642072,5023,5675990,26239,748912,22417,191909,10150,9523,...,362,504,25261,3848,979,1104,773,392,23509,3768
66,Texas,27924632,9989,23534387,67754,3643333,65150,524511,22790,10235,...,948,588,222401,14550,5105,1755,1714,677,215582,14375
67,Utah,3056193,3007,2532858,16462,398606,14353,99584,7531,644,...,1722,997,25145,4357,0,192,502,512,24643,4436
68,Vermont,619089,948,536390,5931,57588,4891,21868,3314,0,...,643,653,3243,1880,125,174,0,157,3118,1879
69,Virginia,8372522,4750,7089782,25415,958267,22292,250490,10432,2341,...,305,503,73983,7003,1318,703,850,515,71815,6872
71,Washington,7318811,4011,6016482,24671,978057,22670,260787,14178,1605,...,581,412,63485,6684,88,106,1992,1214,61405,6551
72,West Virginia,1798306,1891,1589833,9253,165375,8367,40007,4327,239,...,0,200,3091,912,103,129,0,200,2988,874
73,Wisconsin,5731549,3294,4908638,17520,687285,16914,112519,6909,757,...,273,250,23107,3476,2541,1331,74,120,20492,3238
74,Wyoming,573483,1042,481231,7380,71338,6817,18511,2739,264,...,0,0,2403,1038,0,201,0,201,2403,1038
76,Puerto Rico,3313519,3560,3101332,13351,189034,12193,20167,4285,888,...,0,262,2986,1148,0,0,97,161,2889,1152


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [14]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),321994428,4819343,730874,6935358,2968395,39085984,5542282,3556297,952449,684810,...,6642072,27924632,3056193,619089,8372522,7318811,1798306,5731549,573483,3313519
Population 1 year and over (MOE),33543,3710,1438,3888,3103,10045,3414,2701,1698,1664,...,5023,9989,3007,948,4750,4011,1891,3294,1042,3560
Same house 1 year ago (Estimate),275921008,4158224,595804,5717189,2509717,34009331,4546729,3136666,830905,554225,...,5675990,23534387,2532858,536390,7089782,6016482,1589833,4908638,481231,3101332
Same house 1 year ago (MOE),183767,20321,9147,24333,16654,68358,22932,16246,8792,7670,...,26239,67754,16462,5931,25415,24671,9253,17520,7380,13351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),9821,469,153,358,602,876,652,2431,241,325,...,1104,1755,192,174,703,106,129,1331,201,0
Abroad 1 year ago--: U.S. Island Area (Estimate),18321,0,965,91,0,842,568,0,66,78,...,773,1714,502,0,850,1992,0,74,0,97
Abroad 1 year ago--: U.S. Island Area (MOE),3416,200,797,106,201,422,382,207,110,130,...,392,677,512,157,515,1214,200,120,201,161
Abroad 1 year ago--: Foreign Country4 (Estimate),2017519,13191,5738,44793,8385,316046,33042,20800,3688,9907,...,23509,215582,24643,3118,71815,61405,2988,20492,2403,2889
Abroad 1 year ago--: Foreign Country4 (MOE),36251,2200,2168,5315,1955,16679,4876,3534,1174,2249,...,3768,14375,4436,1879,6872,6551,874,3238,1038,1152

In [15]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [16]:

df = df.iloc[1:]

In [17]:
df

0,United States2,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
Population 1 year and over (Estimate),321994428,4819343,730874,6935358,2968395,39085984,5542282,3556297,952449,684810,...,6642072,27924632,3056193,619089,8372522,7318811,1798306,5731549,573483,3313519
Population 1 year and over (MOE),33543,3710,1438,3888,3103,10045,3414,2701,1698,1664,...,5023,9989,3007,948,4750,4011,1891,3294,1042,3560
Same house 1 year ago (Estimate),275921008,4158224,595804,5717189,2509717,34009331,4546729,3136666,830905,554225,...,5675990,23534387,2532858,536390,7089782,6016482,1589833,4908638,481231,3101332
Same house 1 year ago (MOE),183767,20321,9147,24333,16654,68358,22932,16246,8792,7670,...,26239,67754,16462,5931,25415,24671,9253,17520,7380,13351
Same state of residence 1 year ago (Estimate),36468599,535649,98168,911120,370309,4234770,734182,311726,78998,64013,...,748912,3643333,398606,57588,958267,978057,165375,687285,71338,189034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Abroad 1 year ago--: Puerto Rico (MOE),9821,469,153,358,602,876,652,2431,241,325,...,1104,1755,192,174,703,106,129,1331,201,0
Abroad 1 year ago--: U.S. Island Area (Estimate),18321,0,965,91,0,842,568,0,66,78,...,773,1714,502,0,850,1992,0,74,0,97
Abroad 1 year ago--: U.S. Island Area (MOE),3416,200,797,106,201,422,382,207,110,130,...,392,677,512,157,515,1214,200,120,201,161
Abroad 1 year ago--: Foreign Country4 (Estimate),2017519,13191,5738,44793,8385,316046,33042,20800,3688,9907,...,23509,215582,24643,3118,71815,61405,2988,20492,2403,2889
Abroad 1 year ago--: Foreign Country4 (MOE),36251,2200,2168,5315,1955,16679,4876,3534,1174,2249,...,3768,14375,4436,1879,6872,6551,874,3238,1038,1152

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [18]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [19]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [20]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Population 1 year and over (Estimate)                             684810
Same house 1 year ago (Estimate)                                  554225
Same state of residence 1 year ago (Estimate)                      64013
Different state of residence 1 year ago: Total ...                 56231
Different state of residence 1 year ago: Alabam...                   494
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   549
Different state of residence 1 year ago (contin...                   105
Different state of residence 1 year ago (contin...                  3763
Different state of residence 1 year ago (contin...                  1109
Different state of residence 1 year ago (contin...                  1149
Different state of residence 1 year ago (contin...                   375
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  1182
Different state of residence 1 year ago (contin...                  1507
Different state of residence 1 year ago (contin...                    29
Different state of residence 1 year ago (contin...                   161
Different state of residence 1 year ago (contin...                  2726
Different state of residence 1 year ago (contin...                   710
Different state of residence 1 year ago (contin...                    17
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   285
Different state of residence 1 year ago (contin...                   461
Different state of residence 1 year ago (contin...                   122
Different state of residence 1 year ago (contin...                 10835
Different state of residence 1 year ago (contin...                  2669
Different state of residence 1 year ago (contin...                   808
Different state of residence 1 year ago (contin...                   436
Different state of residence 1 year ago (contin...                   157
Different state of residence 1 year ago (contin...                   466
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   128
Different state of residence 1 year ago (contin...                    88
Different state of residence 1 year ago (contin...                  2590
Different state of residence 1 year ago (contin...                   206
Different state of residence 1 year ago (contin...                  5238
Different state of residence 1 year ago (contin...                  1867
Different state of residence 1 year ago (contin...                     5
Different state of residence 1 year ago (contin...                  1026
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                    37
Different state of residence 1 year ago (contin...                  1824
Different state of residence 1 year ago (contin...                   296
Different state of residence 1 year ago (contin...                   235
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                  1057
Different state of residence 1 year ago (contin...                  2858
Different state of residence 1 year ago (contin...                   384
Different state of residence 1 year ago (contin...                   447
Different state of residence 1 year ago (contin...                  7509
Different state of residence 1 year ago (contin...                   206
Different state of residence 1 year ago (contin...                     0
Different state of residence 1 year ago (contin...                   115
Different state of residence 1 year ago (contin...                     0
Abroad 1 year ago--: Total (Estimate)                              10341
Abroad 1 year ago--: Puerto Rico (Estimate)                          356
Abroad 1 year ago--: U.S. Island Area (Estimate)                      78
Abroad 1 year ago--: Foreign Country4 (Estimate)                    9907

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [21]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

Cut off the top columns that arent for specific states

In [22]:

df_estimates = df_estimates[4:]
df_moes = df_moes[4:]

In [23]:
df_moes.head()

0          District of Columbia
0
Alabama                      417
Alaska                       208
Arizona                      667
Arkansas                     146
California                  1034

In [24]:
df_estimates.head()

0          District of Columbia
0
Alabama                      494
Alaska                         0
Arizona                      549
Arkansas                     105
California                  3763

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [25]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Also need to cut out one "total" column that is the total amount of "Abroad One Year Ago" incl PR, US Island Area, and Foreign Country

In [26]:
df = df.drop('Total')

df

0                    District of Columbia  MOE +/-
0
Alabama                                494     417
Alaska                                   0     208
Arizona                                549     667
Arkansas                               105     146
California                            3763    1034
Colorado                              1109     667
Connecticut                           1149     624
Delaware                               375     336
District of Columbia                     0       0
Florida                               1182     530
Georgia                               1507     643
Hawaii                                  29      47
Idaho                                  161     184
Illinois                              2726     945
Indiana                                710     574
Iowa                                    17      29
Kansas                                   0     208
Kentucky                               285     452
Louisiana                              461     452
Maine                                  122     126
Maryland                             10835    1863
Massachusetts                         2669     723
Michigan                               808     396
Minnesota                              436     391
Mississippi                            157     182
Missouri                               466     319
Montana                                  0     208
Nebraska                                 0     208
Nevada                                 128     141
New Hampshire                           88     141
New Jersey                            2590    1443
New Mexico                             206     353
New York                              5238    1495
North Carolina                        1867     893
North Dakota                             5      13
Ohio                                  1026     500
Oklahoma                                 0     208
Oregon                                  37      62
Pennsylvania                          1824     640
Rhode Island                           296     336
South Carolina                         235     214
South Dakota                             0     208
Tennessee                             1057     609
Texas                                 2858    1430
Utah                                   384     360
Vermont                                447     456
Virginia                              7509    1565
Washington                             206     231
West Virginia                            0     208
Wisconsin                              115     145
Wyoming                                  0     208
Puerto Rico                            356     325
U.S. Island Area                        78     130
Foreign Country4                      9907    2249

also need to drop out the last two columns US Island Area and Foreign Country because those dont exist in the pop df and I don't need for this analysis

In [27]:
df = df.drop('U.S. Island Area')
df = df.drop('Foreign Country4')

also need to drop the top row of pops df to get the dataframes to have the same row indices

In [28]:
df_pops = df_pops.drop('Label (Grouping)')

Now I'm adding a state polulation column to my newly formatted table

In [29]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [30]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [31]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [32]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       494     417          5024279
Alaska                          0     208           733391
Arizona                       549     667          7151502
Arkansas                      105     146          3011524
California                   3763    1034         39538223
Colorado                     1109     667          5773714
Connecticut                  1149     624          3605944
Delaware                      375     336           989948
District of Columbia            0       0           689545
Florida                      1182     530         21538187
Georgia                      1507     643         10711908
Hawaii                         29      47          1455271
Idaho                         161     184          1839106
Illinois                     2726     945         12812508
Indiana                       710     574          6785528
Iowa                           17      29          3190369
Kansas                          0     208          2937880
Kentucky                      285     452          4505836
Louisiana                     461     452          4657757
Maine                         122     126          1362359
Maryland                    10835    1863          6177224
Massachusetts                2669     723          7029917
Michigan                      808     396         10077331
Minnesota                     436     391          5706494
Mississippi                   157     182          2961279
Missouri                      466     319          6154913
Montana                         0     208          1084225
Nebraska                        0     208          1961504
Nevada                        128     141          3104614
New Hampshire                  88     141          1377529
New Jersey                   2590    1443          9288994
New Mexico                    206     353          2117522
New York                     5238    1495         20201249
North Carolina               1867     893         10439388
North Dakota                    5      13           779094
Ohio                         1026     500         11799448
Oklahoma                        0     208          3959353
Oregon                         37      62          4237256
Pennsylvania                 1824     640         13002700
Rhode Island                  296     336          1097379
South Carolina                235     214          5118425
South Dakota                    0     208           886667
Tennessee                    1057     609          6910840
Texas                        2858    1430         29145505
Utah                          384     360          3271616
Vermont                       447     456           643077
Virginia                     7509    1565          8631393
Washington                    206     231          7705281
West Virginia                   0     208          1793716
Wisconsin                     115     145          5893718
Wyoming                         0     208           576851
Puerto Rico                   356     325          3285874

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [33]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [34]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Looking at states with most people coming to DC

In [35]:
df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,,,,,
Maryland,10835,1863,6177224,0.001754,0.000302
Virginia,7509,1565,8631393,0.000870,0.000181
Vermont,447,456,643077,0.000695,0.000709
Massachusetts,2669,723,7029917,0.000380,0.000103
Delaware,375,336,989948,0.000379,0.000339
Connecticut,1149,624,3605944,0.000319,0.000173
New Jersey,2590,1443,9288994,0.000279,0.000155
Rhode Island,296,336,1097379,0.000270,0.000306
New York,5238,1495,20201249,0.000259,0.000074
Illinois,2726,945,12812508,0.000213,0.000074

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [36]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)


df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted
0,Alabama,494,417,5024279,0.000098,0.000083
1,Alaska,0,208,733391,0.000000,0.000284
2,Arizona,549,667,7151502,0.000077,0.000093
3,Arkansas,105,146,3011524,0.000035,0.000048
4,California,3763,1034,39538223,0.000095,0.000026

To export, want to make a slice excluding all DMV states -- Maryland, Virginia, DC

And then also PR because only looking at continental US

In [37]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]
df = df[df["state"] != "District of Columbia"]

Now need to reset the indexes again to make numbers consecutive now that I've removed ceratin rows.

In [38]:
df = df.reset_index(drop=True)

Now add in 2016 election winners for each state

First, read in file

In [39]:
df_2016_election_winners = pd.read_csv('pres-election-results-2016.csv')

type(df_2016_election_winners)

pandas.DataFrame

In [40]:
df['winning_party'] = df_2016_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2016_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,migrated_adjusted,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,494,417,5024279,0.000098,0.000083,REPUBLICAN,0.620831
1,Alaska,0,208,733391,0.000000,0.000284,REPUBLICAN,0.512815
2,Arizona,549,667,7151502,0.000077,0.000093,REPUBLICAN,0.486716
3,Arkansas,105,146,3011524,0.000035,0.000048,REPUBLICAN,0.605741
4,California,3763,1034,39538223,0.000095,0.000026,DEMOCRAT,0.617264

In [41]:
df.index

RangeIndex(start=0, stop=48, step=1)

In [42]:
df_2016_election_winners.index

RangeIndex(start=0, stop=48, step=1)

Save as csv file

In [43]:
df.to_csv('DC-migration-2017.csv')