I'm interested to see where people move to DC from.

I'd like to group the DMV -- DC, Maryland and Virginia -- together for this.

Relatedly, I'm currious whether in election years, the influx comes from redder/bluer states depending on election results.

In [1]:
import pandas as pd
import numpy as np

Read in the file

In [2]:
df = pd.read_excel('ORIGINAL DATA state_to_state_migrations_table_2007.xls')

In [3]:
df.shape

(77, 115)

In [4]:
df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112',
       'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

Need to drop the notes in the excel doc that come before and after the actual chart.
I am also dropping the middle repeated headers columns 45-47 in the doc

In [5]:

df = df.iloc[np.r_[4:43, 44:77]]
                   
df.head()

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,604287,20130,1253,1131,1005,610,1580,795,4643,...,1563,1023,1120,361,348,Alabama,590,483,294,292

It looks like pandas has already automatically unmerged the header columns that in the .xls cover more than one column, so now I'm just going to forward fill the headers to avoid null values.

In [6]:

#checking the columns, can see that this still needs work

df.columns

Index(['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108',
       'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112',
       'Unnamed: 113', 'Unnamed: 114'],
      dtype='str', length=115)

In [7]:
df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alabama,604287,20130,1253,1131,1005,610,1580,795,4643,...,1563,1023,1120,361,348,Alabama,590,483,294,292
9,Alaska,1151,972,98512,8275,2320,1271,386,412,3985,...,939,3368,1456,0,237,Alaska,586,548,0,237
10,Arizona,1678,1346,1994,908,929396,27779,1432,811,65684,...,1714,9194,2213,759,562,Arizona,4049,1888,1219,943
11,Arkansas,2065,1351,410,506,930,637,425248,16470,7139,...,496,1908,1424,222,330,Arkansas,1599,1164,498,559
12,California,2527,1264,5508,1924,33629,6142,4098,1260,4819935,...,3603,24449,3719,265,262,California,5551,1496,1388,996
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Colorado,1958,1499,1905,1238,10752,2778,2261,1145,29278,...,1652,3639,1089,369,456,Colorado,3007,1521,2446,870
15,Connecticut,205,250,244,304,701,361,219,218,4376,...,555,761,686,46,76,Connecticut,207,166,0,273
16,Delaware,185,225,60,101,324,386,0,261,214,...,578,21,39,100,144,Delaware,0,261,50,82
17,District of Columbia,453,492,0,300,296,308,574,706,4178,...,1650,586,512,163,168,District of Columbia,204,178,0,300
18,Florida,13391,3414,6221,2565,3872,1260,1883,1215,20661,...,4054,7426,2861,2778,1219,Florida,6744,2088,795,496
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Georgia,17724,2931,2063,1774,4385,1703,2285,1195,21454,...,2642,1735,917,1861,1279,Georgia,2300,1201,420,318
21,Hawaii,1223,1534,588,591,2125,1429,5,10,11560,...,1718,3327,1447,25,41,Hawaii,563,525,0,271
22,Idaho,67,94,693,549,4701,2049,0,257,10146,...,301,11271,2469,238,298,Idaho,627,527,1578,800
23,Illinois,2554,911,938,1136,5847,2155,4378,1739,14173,...,1808,3362,1343,496,557,Illinois,20647,3865,65,108

Drop rows that appear to be for readability of the .xls by dropping all rows that are NaN across the board.

In [8]:
df = df.dropna(how="all")

df.head(20)

,"Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
4,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Current residence in --,Residence 1 year ago in --,NaN,NaN,NaN
5,NaN,Alabama,NaN,Alaska,NaN,Arizona,NaN,Arkansas,NaN,California,...,NaN,Washington,NaN,West Virginia,NaN,NaN,Wisconsin,NaN,Wyoming,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,Estimate,MOE,Estimate,MOE,NaN,Estimate,MOE,Estimate,MOE
8,Alabama,604287,20130,1253,1131,1005,610,1580,795,4643,...,1563,1023,1120,361,348,Alabama,590,483,294,292
9,Alaska,1151,972,98512,8275,2320,1271,386,412,3985,...,939,3368,1456,0,237,Alaska,586,548,0,237
10,Arizona,1678,1346,1994,908,929396,27779,1432,811,65684,...,1714,9194,2213,759,562,Arizona,4049,1888,1219,943
11,Arkansas,2065,1351,410,506,930,637,425248,16470,7139,...,496,1908,1424,222,330,Arkansas,1599,1164,498,559
12,California,2527,1264,5508,1924,33629,6142,4098,1260,4819935,...,3603,24449,3719,265,262,California,5551,1496,1388,996
14,Colorado,1958,1499,1905,1238,10752,2778,2261,1145,29278,...,1652,3639,1089,369,456,Colorado,3007,1521,2446,870
15,Connecticut,205,250,244,304,701,361,219,218,4376,...,555,761,686,46,76,Connecticut,207,166,0,273
16,Delaware,185,225,60,101,324,386,0,261,214,...,578,21,39,100,144,Delaware,0,261,50,82
17,District of Columbia,453,492,0,300,296,308,574,706,4178,...,1650,586,512,163,168,District of Columbia,204,178,0,300
18,Florida,13391,3414,6221,2565,3872,1260,1883,1215,20661,...,4054,7426,2861,2778,1219,Florida,6744,2088,795,496
20,Georgia,17724,2931,2063,1774,4385,1703,2285,1195,21454,...,2642,1735,917,1861,1279,Georgia,2300,1201,420,318
21,Hawaii,1223,1534,588,591,2125,1429,5,10,11560,...,1718,3327,1447,25,41,Hawaii,563,525,0,271
22,Idaho,67,94,693,549,4701,2049,0,257,10146,...,301,11271,2469,238,298,Idaho,627,527,1578,800
23,Illinois,2554,911,938,1136,5847,2155,4378,1739,14173,...,1808,3362,1343,496,557,Illinois,20647,3865,65,108
24,Indiana,1317,804,148,179,3301,1323,567,303,7380,...,1458,2075,1395,726,623,Indiana,4356,1780,818,933
26,Iowa,511,534,507,466,2699,908,707,632,4489,...,591,966,595,528,532,Iowa,5704,1885,191,179
27,Kansas,971,754,418,405,1914,982,2595,1406,5735,...,1110,1454,928,118,207,Kansas,399,308,888,661

Rename columns to be clearer, including manually renaming certain columns and stripping 'Unnamed: ' from the rest

In [9]:
print(df.columns.tolist())

['Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114']

In [10]:
#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 46 through 48.': '0'}, inplace=True)

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

print(df.columns.tolist())

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114']

Drop the repeated "Current Residence In" columns that are there for readability (identical to the state titles in column A, they repeat in A, L, W, AH, AS, BD, BO, BZ, CK, CV, DG, DR)

In [11]:
columns_to_drop =  ['11', '22', '33', '44', '55', '66', '77', '88', '99', '110']

for column in columns_to_drop:
    df.drop(columns = [column], inplace = True)

Rename columns by forwards filling some of what, in the original excel sheet, was merged column titles spanning more than one column

In [12]:
#For the rest of the columns:
#first, fill in blanks

df_filledin = df.ffill(axis=1)

df_filledin.head()

,0,1,2,3,4,5,6,7,8,9,...,104,105,106,107,108,109,111,112,113,114
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,604287,20130,1253,1131,1005,610,1580,795,4643,...,4390,1563,1023,1120,361,348,590,483,294,292
9,Alaska,1151,972,98512,8275,2320,1271,386,412,3985,...,1028,939,3368,1456,0,237,586,548,0,237

In [13]:
#then pull the info I need to name each column

for i in range(1, 105):
    new_column_name = f'{df_filledin.iloc[0, i]}: {df_filledin.iloc[1, i]} ({df_filledin.iloc[2, i]})'
    current_column_name = df_filledin.columns[i]
    df_filledin = df_filledin.rename(columns = {current_column_name: new_column_name})

In [14]:
df_filledin.head()

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
4,Current residence in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,...,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --,Residence 1 year ago in --
5,NaN,Alabama,Alabama,Alaska,Alaska,Arizona,Arizona,Arkansas,Arkansas,California,...,Virginia,Virginia,Washington,Washington,West Virginia,West Virginia,Wisconsin,Wisconsin,Wyoming,Wyoming
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,Alabama,604287,20130,1253,1131,1005,610,1580,795,4643,...,4390,1563,1023,1120,361,348,590,483,294,292
9,Alaska,1151,972,98512,8275,2320,1271,386,412,3985,...,1028,939,3368,1456,0,237,586,548,0,237

Now that everything is properly renamed (ie the various titles and subtitles are brought into the title of the actual column), we can delete the subtitle rows

In [15]:
df = df_filledin.iloc[3:]

df.tail(20)

,0,Residence 1 year ago in --: Alabama (Estimate),Residence 1 year ago in --: Alabama (MOE),Residence 1 year ago in --: Alaska (Estimate),Residence 1 year ago in --: Alaska (MOE),Residence 1 year ago in --: Arizona (Estimate),Residence 1 year ago in --: Arizona (MOE),Residence 1 year ago in --: Arkansas (Estimate),Residence 1 year ago in --: Arkansas (MOE),Residence 1 year ago in --: California (Estimate),...,Residence 1 year ago in --: Virginia (Estimate),Residence 1 year ago in --: Virginia (MOE),Residence 1 year ago in --: Washington (Estimate),Residence 1 year ago in --: Washington (MOE),Residence 1 year ago in --: West Virginia (Estimate),Residence 1 year ago in --: West Virginia (MOE),Residence 1 year ago in --: Wisconsin (Estimate),Residence 1 year ago in --: Wisconsin (MOE),Residence 1 year ago in --: Wyoming (Estimate),Residence 1 year ago in --: Wyoming (MOE)
54,Ohio,1544,819,1100,1183,3007,1211,435,515,12056,...,5506,1505,1410,678,7241,2113,2415,1157,637,599
55,Oklahoma,744,703,1496,1020,4193,1503,7690,1710,15936,...,1877,886,2285,1276,260,228,772,502,211,206
56,Oregon,889,674,3029,1278,7024,2055,425,396,35942,...,3051,1595,23144,2923,0,273,317,273,850,571
57,Pennsylvania,861,718,1063,847,4251,1413,2428,1834,11173,...,12913,2770,2257,898,3918,1806,1768,962,545,504
58,Puerto Rico,121,141,0,283,27,45,0,283,1459,...,171,209,205,336,0,283,274,337,0,283
60,Rhode Island,0,285,158,258,137,168,0,285,1243,...,490,334,300,303,32,54,0,285,0,285
61,South Carolina,2337,689,507,404,1090,462,741,503,7583,...,8131,2538,829,635,1869,1114,917,561,232,337
62,South Dakota,135,238,86,96,1037,680,246,265,1529,...,180,168,910,1009,0,221,732,555,1029,817
63,Tennessee,11797,2448,557,485,2918,1681,3667,1370,11389,...,5630,1599,2147,1238,829,424,3658,1746,112,187
64,Texas,8086,2987,7239,3024,16002,4140,16860,3839,78310,...,14537,3689,10670,3529,1044,650,8128,2843,2789,1352
66,Utah,877,908,1106,647,7588,2682,0,261,22204,...,1393,1065,6777,2540,670,900,1900,1680,1195,571
67,Vermont,122,198,36,59,128,176,110,183,1558,...,465,259,323,280,138,148,56,69,84,122
68,Virginia,4288,1449,2684,1549,3605,1480,1658,1319,17437,...,915263,24627,3736,1101,5484,2284,997,548,687,632
69,Washington,489,444,5941,1866,7581,1859,1017,741,43361,...,4346,1519,921085,23229,123,176,3043,1381,571,378
70,West Virginia,315,442,507,457,309,271,0,265,986,...,7378,1707,445,163,178896,9646,80,67,0,265
72,Wisconsin,302,262,158,124,2572,1374,516,304,5063,...,2745,902,593,469,59,104,723651,21577,793,598
73,Wyoming,29,49,47,83,2223,1236,165,294,3185,...,203,263,1402,1256,0,259,150,108,74171,6158
74,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,...,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:,Footnotes:
75,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...,MOE - Margin of error based on 90% confidence ...
76,"Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...",...,"Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm...","Source: U.S. Census Bureau, 2007 American Comm..."


Transposing for further cleaning

Using "set_index" to tell it to use the column titled 0 as the new column titles.

In [16]:
df.columns

df_trans = df.set_index(df['0']).transpose()

df_trans

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,MOE - Margin of error based on 90% confidence interval,"Source: U.S. Census Bureau, 2007 American Community Survey"
0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Alabama (Estimate),604287,1151,1678,2065,2527,1958,205,185,453,13391,...,877,122,4288,489,315,302,29,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Alabama (MOE),20130,972,1346,1351,1264,1499,250,225,492,3414,...,908,198,1449,444,442,262,49,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Alaska (Estimate),1253,98512,1994,410,5508,1905,244,60,0,6221,...,1106,36,2684,5941,507,158,47,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Alaska (MOE),1131,8275,908,506,1924,1238,304,101,300,2565,...,647,59,1549,1866,457,124,83,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),348,237,562,330,262,456,76,144,168,1219,...,900,148,2284,176,9646,104,259,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Wisconsin (Estimate),590,586,4049,1599,5551,3007,207,0,204,6744,...,1900,56,997,3043,80,723651,150,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Wisconsin (MOE),483,548,1888,1164,1496,1521,166,261,178,2088,...,1680,69,548,1381,67,21577,108,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Wyoming (Estimate),294,0,1219,498,1388,2446,0,50,0,795,...,1195,84,687,571,0,793,74171,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Wyoming (MOE),292,237,943,559,996,870,273,82,300,496,...,571,122,632,378,265,598,6158,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."

In [17]:
df = df_trans

Now that its transposed, I just need to drop the first row that is now already in the names of the columns.

In [18]:

df = df.iloc[1:]

In [19]:
df

0,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,Florida,...,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Footnotes:,MOE - Margin of error based on 90% confidence interval,"Source: U.S. Census Bureau, 2007 American Community Survey"
Residence 1 year ago in --: Alabama (Estimate),604287,1151,1678,2065,2527,1958,205,185,453,13391,...,877,122,4288,489,315,302,29,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Alabama (MOE),20130,972,1346,1351,1264,1499,250,225,492,3414,...,908,198,1449,444,442,262,49,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Alaska (Estimate),1253,98512,1994,410,5508,1905,244,60,0,6221,...,1106,36,2684,5941,507,158,47,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Alaska (MOE),1131,8275,908,506,1924,1238,304,101,300,2565,...,647,59,1549,1866,457,124,83,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Arizona (Estimate),1005,2320,929396,930,33629,10752,701,324,296,3872,...,7588,128,3605,7581,309,2572,2223,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Residence 1 year ago in --: West Virginia (MOE),348,237,562,330,262,456,76,144,168,1219,...,900,148,2284,176,9646,104,259,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Wisconsin (Estimate),590,586,4049,1599,5551,3007,207,0,204,6744,...,1900,56,997,3043,80,723651,150,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Wisconsin (MOE),483,548,1888,1164,1496,1521,166,261,178,2088,...,1680,69,548,1381,67,21577,108,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Wyoming (Estimate),294,0,1219,498,1388,2446,0,50,0,795,...,1195,84,687,571,0,793,74171,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."
Residence 1 year ago in --: Wyoming (MOE),292,237,943,559,996,870,273,82,300,496,...,571,122,632,378,265,598,6158,Footnotes:,MOE - Margin of error based on 90% confidence ...,"Source: U.S. Census Bureau, 2007 American Comm..."

Wooohooo now this finally looks good.

Now we can analyze some stuff.

First up, find DC info:

In [20]:
df = df[['District of Columbia ']]
# indices = df.index.tolist
# indices

Import population maps in order to adjust each state per capita

In [21]:
df_pops = pd.read_csv('State populations 2020 from census.csv')

df_pops = df_pops.transpose()
df_pops

                               0
Label (Grouping)           Total
Alabama                5,024,279
Alaska                   733,391
Arizona                7,151,502
Arkansas               3,011,524
California            39,538,223
Colorado               5,773,714
Connecticut            3,605,944
Delaware                 989,948
District of Columbia     689,545
Florida               21,538,187
Georgia               10,711,908
Hawaii                 1,455,271
Idaho                  1,839,106
Illinois              12,812,508
Indiana                6,785,528
Iowa                   3,190,369
Kansas                 2,937,880
Kentucky               4,505,836
Louisiana              4,657,757
Maine                  1,362,359
Maryland               6,177,224
Massachusetts          7,029,917
Michigan              10,077,331
Minnesota              5,706,494
Mississippi            2,961,279
Missouri               6,154,913
Montana                1,084,225
Nebraska               1,961,504
Nevada                 3,104,614
New Hampshire          1,377,529
New Jersey             9,288,994
New Mexico             2,117,522
New York              20,201,249
North Carolina        10,439,388
North Dakota             779,094
Ohio                  11,799,448
Oklahoma               3,959,353
Oregon                 4,237,256
Pennsylvania          13,002,700
Rhode Island           1,097,379
South Carolina         5,118,425
South Dakota             886,667
Tennessee              6,910,840
Texas                 29,145,505
Utah                   3,271,616
Vermont                  643,077
Virginia               8,631,393
Washington             7,705,281
West Virginia          1,793,716
Wisconsin              5,893,718
Wyoming                  576,851
Puerto Rico            3,285,874

Strip out all columns except those representing the number estimate for inmigration from each state.

I'm doing this by saving the NaNs out for now, though, as I want to bring them back.

In [22]:
df_estimates = df[df.index.astype(str).str.contains('Estimate', case=False, na=False)]

df_moes = df[df.index.astype(str).str.contains('MOE', case=False, na=False)]

df_estimates

0                                                  District of Columbia
Residence 1 year ago in --: Alabama (Estimate)                       453
Residence 1 year ago in --: Alaska (Estimate)                          0
Residence 1 year ago in --: Arizona (Estimate)                       296
Residence 1 year ago in --: Arkansas (Estimate)                      574
Residence 1 year ago in --: California (Estimate)                   4178
Residence 1 year ago in --: Colorado (Estimate)                      489
Residence 1 year ago in --: Connecticut (Estimate)                  1438
Residence 1 year ago in --: Delaware (Estimate)                      471
Residence 1 year ago in --: District of Columbi...                 58181
Residence 1 year ago in --: Florida (Estimate)                      2307
Residence 1 year ago in --: Georgia (Estimate)                       501
Residence 1 year ago in --: Hawaii (Estimate)                        252
Residence 1 year ago in --: Idaho (Estimate)                          47
Residence 1 year ago in --: Illinois (Estimate)                     1239
Residence 1 year ago in --: Indiana (Estimate)                       124
Residence 1 year ago in --: Iowa (Estimate)                          111
Residence 1 year ago in --: Kansas (Estimate)                          0
Residence 1 year ago in --: Kentucky (Estimate)                      202
Residence 1 year ago in --: Louisiana (Estimate)                      96
Residence 1 year ago in --: Maine (Estimate)                          53
Residence 1 year ago in --: Maryland (Estimate)                    14647
Residence 1 year ago in --: Massachusetts (Esti...                  1659
Residence 1 year ago in --: Michigan (Estimate)                      419
Residence 1 year ago in --: Minnesota (Estimate)                       0
Residence 1 year ago in --: Mississippi (Estimate)                     0
Residence 1 year ago in --: Missouri (Estimate)                      355
Residence 1 year ago in --: Montana (Estimate)                       119
Residence 1 year ago in --: Nebraska (Estimate)                      102
Residence 1 year ago in --: Nevada (Estimate)                         53
Residence 1 year ago in --: New Hampshire (Esti...                   108
Residence 1 year ago in --: New Jersey (Estimate)                    778
Residence 1 year ago in --: New Mexico (Estimate)                    107
Residence 1 year ago in --: New York (Estimate)                     3751
Residence 1 year ago in --: North Carolina (Est...                   534
Residence 1 year ago in --: North Dakota (Estim...                     0
Residence 1 year ago in --: Ohio (Estimate)                         1232
Residence 1 year ago in --: Oklahoma (Estimate)                        0
Residence 1 year ago in --: Oregon (Estimate)                        400
Residence 1 year ago in --: Pennsylvania (Estim...                  1406
Residence 1 year ago in --: Puerto Rico (Estimate)                     0
Residence 1 year ago in --: Rhode Island (Estim...                   415
Residence 1 year ago in --: South Carolina (Est...                   103
Residence 1 year ago in --: South Dakota (Estim...                    53
Residence 1 year ago in --: Tennessee (Estimate)                     124
Residence 1 year ago in --: Texas (Estimate)                         968
Residence 1 year ago in --: Utah (Estimate)                            0
Residence 1 year ago in --: Vermont (Estimate)                       172
Residence 1 year ago in --: Virginia (Estimate)                     6365
Residence 1 year ago in --: Washington (Estimate)                    586
Residence 1 year ago in --: West Virginia (Esti...                   163
Residence 1 year ago in --: Wisconsin (Estimate)                     204
Residence 1 year ago in --: Wyoming (Estimate)                         0

Renaming all the indexes to just be the state names in both estimates and moes data frames so that I can then merge them.

In [23]:
df_estimates.index = df_estimates.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

df_moes.index = df_moes.index.to_series().astype(str).str.extract(r':\s*(.*?)\s*\(')[0]

For 2021 and 2017, we needed to cut off the top columns that arent for specific states, but that's not relevent here because of different structure for 2009 and 2005

In [24]:

# df_estimates = df_estimates[4:]
# df_moes = df_moes[4:]

In [25]:
df_moes.head()

0          District of Columbia
0
Alabama                      492
Alaska                       300
Arizona                      308
Arkansas                     706
California                  1801

In [26]:
df_estimates.head()

0          District of Columbia
0
Alabama                      453
Alaska                         0
Arizona                      296
Arkansas                     574
California                  4178

Add the moes information (currently its own dataframe) as a column into the estimates dataframe

In [27]:
df_estimates['MOE +/-'] = df_moes['District of Columbia ']

df = df_estimates

Now I'm adding a state polulation column to my newly formatted table

In [28]:
df['state_population'] = df_pops[0]

Rename the columns to make more sense

In [29]:
df.rename(columns={'District of Columbia ':'pop_migrated'}, inplace=True)

And strip commas in state_population column

In [30]:
df['state_population'] = df['state_population'].str.replace(',', '')

Checking progress

In [31]:
df

0                    pop_migrated MOE +/- state_population
0
Alabama                       453     492          5024279
Alaska                          0     300           733391
Arizona                       296     308          7151502
Arkansas                      574     706          3011524
California                   4178    1801         39538223
Colorado                      489     382          5773714
Connecticut                  1438     776          3605944
Delaware                      471     284           989948
District of Columbia        58181    6847           689545
Florida                      2307     985         21538187
Georgia                       501     348         10711908
Hawaii                        252     260          1455271
Idaho                          47      77          1839106
Illinois                     1239     518         12812508
Indiana                       124     163          6785528
Iowa                          111     184          3190369
Kansas                          0     300          2937880
Kentucky                      202     218          4505836
Louisiana                      96     158          4657757
Maine                          53      89          1362359
Maryland                    14647    2724          6177224
Massachusetts                1659     714          7029917
Michigan                      419     268         10077331
Minnesota                       0     300          5706494
Mississippi                     0     300          2961279
Missouri                      355     336          6154913
Montana                       119     197          1084225
Nebraska                      102     175          1961504
Nevada                         53      89          3104614
New Hampshire                 108     112          1377529
New Jersey                    778     362          9288994
New Mexico                    107     194          2117522
New York                     3751     957         20201249
North Carolina                534     323         10439388
North Dakota                    0     300           779094
Ohio                         1232     709         11799448
Oklahoma                        0     300          3959353
Oregon                        400     374          4237256
Pennsylvania                 1406     567         13002700
Puerto Rico                     0     300          3285874
Rhode Island                  415     235          1097379
South Carolina                103     171          5118425
South Dakota                   53      90           886667
Tennessee                     124     143          6910840
Texas                         968     441         29145505
Utah                            0     300          3271616
Vermont                       172     202           643077
Virginia                     6365    1650          8631393
Washington                    586     512          7705281
West Virginia                 163     168          1793716
Wisconsin                     204     178          5893718
Wyoming                         0     300           576851

Adding columns representing the top and bottom of the margins of error

In [32]:
df['pop_migrated_upper'] = pd.to_numeric(df['pop_migrated']) + pd.to_numeric(df['MOE +/-']) 

df['pop_migrated_lower'] = pd.to_numeric(df['pop_migrated']) - pd.to_numeric(df['MOE +/-']) 

df

0,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower
0,,,,,
Alabama,453,492,5024279,945,-39
Alaska,0,300,733391,300,-300
Arizona,296,308,7151502,604,-12
Arkansas,574,706,3011524,1280,-132
California,4178,1801,39538223,5979,2377
Colorado,489,382,5773714,871,107
Connecticut,1438,776,3605944,2214,662
Delaware,471,284,989948,755,187
District of Columbia,58181,6847,689545,65028,51334
Florida,2307,985,21538187,3292,1322
Georgia,501,348,10711908,849,153
Hawaii,252,260,1455271,512,-8
Idaho,47,77,1839106,124,-30
Illinois,1239,518,12812508,1757,721
Indiana,124,163,6785528,287,-39
Iowa,111,184,3190369,295,-73
Kansas,0,300,2937880,300,-300
Kentucky,202,218,4505836,420,-16
Louisiana,96,158,4657757,254,-62
Maine,53,89,1362359,142,-36
Maryland,14647,2724,6177224,17371,11923
Massachusetts,1659,714,7029917,2373,945
Michigan,419,268,10077331,687,151
Minnesota,0,300,5706494,300,-300
Mississippi,0,300,2961279,300,-300
Missouri,355,336,6154913,691,19
Montana,119,197,1084225,316,-78
Nebraska,102,175,1961504,277,-73
Nevada,53,89,3104614,142,-36
New Hampshire,108,112,1377529,220,-4
New Jersey,778,362,9288994,1140,416
New Mexico,107,194,2117522,301,-87
New York,3751,957,20201249,4708,2794
North Carolina,534,323,10439388,857,211
North Dakota,0,300,779094,300,-300
Ohio,1232,709,11799448,1941,523
Oklahoma,0,300,3959353,300,-300
Oregon,400,374,4237256,774,26
Pennsylvania,1406,567,13002700,1973,839
Puerto Rico,0,300,3285874,300,-300
Rhode Island,415,235,1097379,650,180
South Carolina,103,171,5118425,274,-68
South Dakota,53,90,886667,143,-37
Tennessee,124,143,6910840,267,-19
Texas,968,441,29145505,1409,527
Utah,0,300,3271616,300,-300
Vermont,172,202,643077,374,-30
Virginia,6365,1650,8631393,8015,4715
Washington,586,512,7705281,1098,74
West Virginia,163,168,1793716,331,-5
Wisconsin,204,178,5893718,382,26
Wyoming,0,300,576851,300,-300

Add a row with the proportion of state residents counted in the census that moved to DC (ie divide each state's immigration to DC number by the total pop of the state sending those people to DC)

In [33]:
df['migrated_adjusted'] = (
    pd.to_numeric(df['pop_migrated'])
    / pd.to_numeric(df['state_population'])

)

df['migrated_adjusted_upper'] = (
    pd.to_numeric(df['pop_migrated_upper'])
    / pd.to_numeric(df['state_population'])

)

df['migrated_adjusted_lower'] = (
    pd.to_numeric(df['pop_migrated_lower'])
    / pd.to_numeric(df['state_population'])

)

Add a row with the adjusted MOE

In [34]:
df['moe_adjusted'] = (
    pd.to_numeric(df['MOE +/-'])
    / pd.to_numeric(df['state_population'])

)

Need to manually drop DC here because its input differently than in the other years -- here, the D.C. figure for folks that lived in D.C. both this year and last year is not n/a or 0, but rather a substantial number that represents the number of folks that did NOT move since last year's census

In [35]:
df = df.drop(['District of Columbia'])

Add a column with the state names so the states arent just in an index, and reset the index to numbers

In [36]:
df.insert(0, "state", df.index)

df = df.reset_index(drop=True)

df.head()

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted
0,Alabama,453,492,5024279,945,-39,0.000090,0.000188,-0.000008,0.000098
1,Alaska,0,300,733391,300,-300,0.000000,0.000409,-0.000409,0.000409
2,Arizona,296,308,7151502,604,-12,0.000041,0.000084,-0.000002,0.000043
3,Arkansas,574,706,3011524,1280,-132,0.000191,0.000425,-0.000044,0.000234
4,California,4178,1801,39538223,5979,2377,0.000106,0.000151,0.000060,0.000046

Looking at states with most people coming to DC

In [37]:

df.sort_values(by='migrated_adjusted', ascending=False).head(10)

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted
19,Maryland,14647,2724,6177224,17371,11923,0.002371,0.002812,0.001930,0.000441
46,Virginia,6365,1650,8631393,8015,4715,0.000737,0.000929,0.000546,0.000191
7,Delaware,471,284,989948,755,187,0.000476,0.000763,0.000189,0.000287
6,Connecticut,1438,776,3605944,2214,662,0.000399,0.000614,0.000184,0.000215
39,Rhode Island,415,235,1097379,650,180,0.000378,0.000592,0.000164,0.000214
45,Vermont,172,202,643077,374,-30,0.000267,0.000582,-0.000047,0.000314
20,Massachusetts,1659,714,7029917,2373,945,0.000236,0.000338,0.000134,0.000102
3,Arkansas,574,706,3011524,1280,-132,0.000191,0.000425,-0.000044,0.000234
31,New York,3751,957,20201249,4708,2794,0.000186,0.000233,0.000138,0.000047
10,Hawaii,252,260,1455271,512,-8,0.000173,0.000352,-0.000005,0.000179

To export, want to make a slice excluding all DMV states -- Maryland, Virginia

In [38]:
df = df[df["state"] != "Maryland"]
df = df[df["state"] != "Virginia"]
df = df[df["state"] != "Puerto Rico"]

Now need to reset the index again to make numbers consecutive now that I've removed ceratin rows.

In [39]:
df = df.reset_index(drop=True)

Now add in 2004 election winners for each state

First, read in file

In [40]:
df_2004_election_winners = pd.read_csv('pres-election-results-2004.csv')

df_2004_election_winners.shape

(48, 5)

Next, add winning party and percent of votes columns

In [41]:
df_2004_election_winners.drop(columns = ['Unnamed: 0'], inplace = True)

Reset index to match the other df

In [42]:
df_2004_election_winners = df_2004_election_winners.reset_index(drop=True)

In [43]:
df_2004_election_winners.head()

df_2004_election_winners.index

RangeIndex(start=0, stop=48, step=1)

In [44]:

df['winning_party'] = df_2004_election_winners['party_detailed']
df['winner_percent_of_votes'] = df_2004_election_winners['percent_total_votes']

df.head()

0,state,pop_migrated,MOE +/-,state_population,pop_migrated_upper,pop_migrated_lower,migrated_adjusted,migrated_adjusted_upper,migrated_adjusted_lower,moe_adjusted,winning_party,winner_percent_of_votes
0,Alabama,453,492,5024279,945,-39,0.000090,0.000188,-0.000008,0.000098,REPUBLICAN,0.624607
1,Alaska,0,300,733391,300,-300,0.000000,0.000409,-0.000409,0.000409,REPUBLICAN,0.610653
2,Arizona,296,308,7151502,604,-12,0.000041,0.000084,-0.000002,0.000043,REPUBLICAN,0.548694
3,Arkansas,574,706,3011524,1280,-132,0.000191,0.000425,-0.000044,0.000234,REPUBLICAN,0.543060
4,California,4178,1801,39538223,5979,2377,0.000106,0.000151,0.000060,0.000046,DEMOCRAT,0.543056

Save as csv file

In [45]:
df.to_csv('DC-migration-2007.csv')